### ISSUE TITLE
Language Level Migration, :: class can be used, UI glitch

### ISSUE THREAD

**Issue by craiglondon** [kalessil/phpinspectionsea#1001]
First, thank you for reporting a bug or making a request. That takes time and we appreciate that!

Let's start with common details:
 
| Subject    | Details                                                  |
| :--------- | :------------------------------------------------------- |
| Issue type | Bug    |
| IDE        | PhpStorm 2018.2.2 Build #PS-182.4129.45, built on August 22, 2018                       |
| Plugin     | Php Inspections (EA Extended) (3.0.5.1) |

Scenario: The results of an inspect say there are 11 items that can be replaced by "Use ::class instead", when I click the button for one "Use ::class instead" the results for the other 10 go away, and I have to run the inspection again to see the other 10 again.

Before
![image](https://user-images.githubusercontent.com/3833140/44732300-f9675700-aab2-11e8-9b18-dd9cdcda2df5.png)

After clicking the button "Use ::class instead"
![image](https://user-images.githubusercontent.com/3833140/44732346-1439cb80-aab3-11e8-874a-cf9b4c3c00c0.png)

After rerunning the inspection
![image](https://user-images.githubusercontent.com/3833140/44732380-26b40500-aab3-11e8-9d5a-f722455ecdb6.png)

**Comment by kalessil** [comment]
Thank you for reporting @craiglondon. Unfortunately, this seems to be IDE related.
