### ISSUE TITLE
[WIP, false-positive] on security advisories for Composer packages

### ISSUE THREAD

**Issue by sciamannikoo** [kalessil/phpinspectionsea#101]
I'm getting this warning: "Please add roave/security-advisories:dev-master as a firewall for vulnerable components."

![image](https://cloud.githubusercontent.com/assets/181780/21797592/386dd2e4-d710-11e6-965c-5834563c2c3a.png)

As you can see, the library is there.

**Comment by kalessil** [comment]
Thank you for reporting @sciamannikoo, if it possible would you please send me the composer.json for analysis?

**Comment by sciamannikoo** [comment]
Sure, it's a really simple composer.json:

```
{
  "name": "wpml-shared/wpml-lib-dependencies",
  "keywords": ["wpml", "dependencies"],
  "homepage": "https://git.onthegosystems.com/wpml-shared/wpml-lib-cache",
  "type": "library",
  "license": "GPL-2.0",
  "authors": [
    {
      "name": "Andrea Sciamanna",
      "email": "andrea.s@icanlocalize.com",
      "homepage": "http://wpml.org"
    }
  ],
  "require": {
    "php": ">=5.2.0",
    "twig/twig": "~1.0",
    "roave/security-advisories": "dev-master"
  },
  "autoload": {
    "classmap": ["src/"]
  }
}
```

The same object in a scratch JSON file does not show the warning.

Also, removing the "twig/twig" library, the warning disappear, which probably makes sense, since there are no other libraries, expect for "php".

**Comment by kalessil** [comment]
Yep, when no 3rd party used the plugin stays silent - this was added in the last release.
