### ISSUE TITLE
Suppress for statement disappears

### ISSUE THREAD

**Issue by iakoder** [kalessil/phpinspectionsea#1011]
| Subject    | Details                                                  |
| :--------- | :------------------------------------------------------- |
| Issue type | Bug     |
| IDE        | PhpStorm 2018.2.3 EAP                          |
| Plugin     | Php Inspections (EA Extended),  3.0.6 |

PhpStorm or plugin bug?

- Run inspection by name: Parameter/variable is not used
- Inspection finds 1700+ issues across many, many files
- Select first issue and choose "Suppress for statement"
- @noinspection added
- Select next issue and "Suppress for statement is not available.

Attached is a screen recording showing the issue

[SuppressForStatementDisappears.zip](https://github.com/kalessil/phpinspectionsea/files/2350548/SuppressForStatementDisappears.zip)

**Comment by kalessil** [comment]
I suspecting IDE. If there are no exceptions by the plugin in IDE log, then it's guarantied to be IDE.
