### ISSUE TITLE
No progress bar for batch supression

### ISSUE THREAD

**Issue by iakoder** [kalessil/phpinspectionsea#1012]
| Subject    | Details                                                  |
| :--------- | :------------------------------------------------------- |
| Issue type | Bug     |
| IDE        | PhpStorm 2018.2.3 EAP                          |
| Plugin     | Php Inspections (EA Extended), 3.0.6 |

PhpStorm or plugin issue?
[NoProgress.zip](https://github.com/kalessil/phpinspectionsea/files/2350567/NoProgress.zip)

- Run inspection by name: parameter/variable is not used
- Find 1700+ issues across many, many files
- Click on top line, outer group, in the results list
- Choose Suppress for statement

Result: Progress dialog appears with no status updates for about three minutes then goes away after updating 89 files and fixing all the issues.

PhpStorm 2018.2.3 EAP
Build #PS-182.4323.23, built on August 29, 2018
Licensed to Intacct / Dan Wilks
Subscription is active until June 23, 2019
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by kalessil** [comment]
Also handled by IDE. Off-topic: didn't run into the issues, perhaps IDE log has exceptions logged?
