### ISSUE TITLE
Inconsistent Suppress formatting

### ISSUE THREAD

**Issue by iakoder** [kalessil/phpinspectionsea#1013]
| Subject    | Details                                                  |
| :--------- | :------------------------------------------------------- |
| Issue type | Bug     |
| IDE        | PhpStorm 2018.2.3 EAP                          |
| Plugin     | Php Inspections (EA Extended) 3.0.6 |

- Run inspection by name: Parameter/variable is not used
- Find 1 700+ issues across 89 files
- Suppress for statement for all of them (at the top-level of the results list)

Sometime the suppression is on its own line, sometimes the suppression is on the same line.  I'd always like the @noinspection on the line above where possible.

PhpStorm or plugin issue?

PhpStorm 2018.2.3 EAP
Build #PS-182.4323.23, built on August 29, 2018
Licensed to Intacct / Dan Wilks
Subscription is active until June 23, 2019
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

![screen shot 2018-09-04 at 4 17 36 pm](https://user-images.githubusercontent.com/13456541/45062695-fb0abf00-b05e-11e8-8c0b-205953ab2323.png)
![screen shot 2018-09-04 at 4 18 04 pm](https://user-images.githubusercontent.com/13456541/45062696-fb0abf00-b05e-11e8-8711-5ade1b3239e6.png)

**Comment by funivan** [comment]
I think this issue is relevant to the PhpStorm platform and not to the PhpInspections. PhpInspections does not handle `noispection` tag.

**Comment by kalessil** [comment]
Correct, suppressions are 100% handled by IDE (we can not even disable suppressing if needed).
