### ISSUE TITLE
Inconsistent behavior of @noinspection on a block of code with issues on each line

### ISSUE THREAD

**Issue by iakoder** [kalessil/phpinspectionsea#1015]
| Subject    | Details                                                  |
| :--------- | :------------------------------------------------------- |
| Issue type | Bug or Feature request - it depends     |
| IDE        | PhpStorm 2018.2.3 EAP                          |
| Plugin     | Php Inspections (EA Extended) 3.0.6 |

Some arrays only need a single @noinspect to suppress them for a block and others need an @noinspect on every line of a block

I removed the @noinspect above the last write to $dummyarr in this block to verify that it was needed

![screen shot 2018-09-04 at 4 41 05 pm](https://user-images.githubusercontent.com/13456541/45063202-a61c7800-b061-11e8-8144-c52581f8f56d.png)

Compared to this screenshot where only the first entry in the block needs to have the @noinspection.  The array is used in an @include not shown in the screenshot.  I like this behavior much better.

![screen shot 2018-09-04 at 4 44 27 pm](https://user-images.githubusercontent.com/13456541/45063244-d82dda00-b061-11e8-985d-cbc79ab8a3da.png)

PhpStorm 2018.2.3 EAP
Build #PS-182.4323.23, built on August 29, 2018
Licensed to Intacct / Dan Wilks
Subscription is active until June 23, 2019
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by kalessil** [comment]
@iakoder: this can be and inspection bug. Would you please post a simplified examples (with 2 assignments max in one block)?

**Comment by kalessil** [comment]
ping @iakoder

**Comment by iakoder** [comment]
Sorry, was on vacation.  What, exactly are you looking for?

**Comment by kalessil** [comment]
Oh, hope the vacation was great =) I was looking for a simplified example (minimalistic one).

**Comment by iakoder** [comment]
```
<?php

function foo() {

    $deptArray = [];

    $dummyarr = array();
    foreach ( $deptArray as $deptDet) {
        /** @noinspection OnlyWritesOnParameterInspection */
        $dummyarr['id'] = $deptDet['ELEMENTID'];
        // Parameter/variable is overridden, but is never used or appears outside of the scope
        $dummyarr['name'] = $deptDet['NAME'];
    }
}

/**
 * @param string $supplier
 */
function bar($supplier)
{
    $PrintOffsets = array();
    switch($supplier){
        case 'Smart source' :
            /** @noinspection OnlyWritesOnParameterInspection */
            $PrintOffsets['PAYERSADD']['TOP'] = "0.10in"; //0 - 15
            // Pretty much the same code but no inspection issue
            $PrintOffsets['PAYERSADD']['LEFT'] = "0.075in"; //5 - 10
            break;
    }

}
```

Repros in PhpStorm 2018.2.3 and 2018.3 EAP 183.3283.10 with PHP Inspection (EA Extended 3.0.6).

**Comment by kalessil** [comment]
Well, this is very specific for this inspection, confirming to be a bug. Based on the provided samples, I prepared a test case for the correct behaviour (which is not a case yet):
```php
function suppression_cases_holder(array $source, array $destination) {
    /* the very first suppression suppose to disable reporting all statements */
    
    foreach ($source as $item) {
        /** @noinspection OnlyWritesOnParameterInspection */
        $destination['...'][] = '...';
        $destination['...'][] = '...';
    }

    if (!empty($source)) {
        $destination['...'][] = '...';
        $destination['...'][] = '...';
    }
    
    $destination['...'][] = '...';
    $destination['...'][] = '...';

    switch ($source) {
        case 'source' :
            $destination['...'][] = '...';
            $destination['...'][] = '...';
            break;
    }
}
```

**Comment by kalessil** [comment]
Fixed!
