### ISSUE TITLE
False warning of "strpos can be used instead"

### ISSUE THREAD

**Issue by Frederick888** [kalessil/phpinspectionsea#1016]
First, thank you for reporting a bug or making a request. That takes time and we appreciate that!

Let's start with common details:
 
| Subject    | Details                                                  |
| :--------- | :------------------------------------------------------- |
| Issue type | Bug/False-Positive    |
| IDE        | IDEA 2018.2.3                          |
| Plugin     | Php Inspections (EA Extended), 3.0.6 |

Description or screenshot:
--
    public function test_test_test()
    {
        $arrayOfArrays = [
            ['*', 'hello', 'world'],
            ['+', 'foo', 'bar'],
        ];
        foreach ($arrayOfArrays as $array) {
            if ($array[0] === '*') {
                echo 'Yes';
            }
        }
    }

False warning `strpos($array, '*') === 0 can be used instead` for the code above.

Environment details
---
IntelliJ IDEA 2018.2.3 (Ultimate Edition)
Build #IU-182.4323.46, built on September 4, 2018
JRE: 1.8.0_152-release-1248-b3 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by kalessil** [comment]
Thank you for reporting @Frederick888, I'll take care about the issue.

**Comment by kalessil** [comment]
Fixed!
