### ISSUE TITLE
NestedPositiveIfStatementsInspection, Undefined variable when one is an assignment

### ISSUE THREAD

**Issue by puggan** [kalessil/phpinspectionsea#1017]
Issue type: Bug/False-Positive
IDE: PhpStorm 2018.2.3 EAP (Build #PS-182.4323.23, built on August 29, 2018)
Plugin: Ext 3.0.5.1 & Ult 2.0.7
Description or screenshot:
![screenshot from 2018-09-05 13-09-37](https://user-images.githubusercontent.com/866668/45089613-061c2880-b10d-11e8-91b5-2b5ee099e644.png)

	if($a = 7) if(in_array($a, [0, 7])) echo 1;

**Comment by puggan** [comment]
ah, its an "Operator Precedence" problem, then thus may be problems to:

	if(true ?: false) if(false) echo 1;
	if(true ?? false) if(false) echo 1;
	if(true AND true) if(false) echo 1;

not that I can image a case where the 3th matters, for most cases
`(A AND B) && C` and `A AND (B && C)` are equal.

**Comment by kalessil** [comment]
Correct =)

**Comment by kalessil** [comment]
Fixed!
