### ISSUE TITLE
Not enough checks for NPE

### ISSUE THREAD

**Issue by Koc** [kalessil/phpinspectionsea#1020]
| Subject    | Details                                                  |
| :--------- | :------------------------------------------------------- |
| Issue type | Bug    |
| IDE        | PhpStorm 2017.3.6                     |
| Plugin     | EA Extended Version: 3.0.6 |

```php
foreach ($citiesWithoutAssociation as $directoryCity) {
    $directoryRegionId = $directoryCity->getRegion()->getId();
    $region = $this->meestExpressRegionRepository->findRegionByDirectoryId($directoryRegionId);

    if (!$region) { // this empty if suppress npe $region->getId() but shouldn't
    }

    $meestExpressCities = $this->meestExpressCityRepository
        ->findPreferredCitiesForAssociation($directoryCity->getNameUa(), $region->getId());
    }
```

Expecteg get NPE warning but empty if has suppressed it.

**Comment by kalessil** [comment]
That's an expected behavior - we don't process workflow, but the fact that variables were checked at all.
