### ISSUE TITLE
Ternary mixed with spaceships confuses the "suspicious ternary" inspection

### ISSUE THREAD

**Issue by Bilge** [kalessil/phpinspectionsea#1021]
The following code raises the *suspicious ternary operator* warning.

>$b['foo'] <=> $a['bar'] ?: $a['baz'] <=> $b['bat'];

This is a common and elegant way to express both a primary and secondary sort order. However, the inspection thinks this will not work as expected; yet it does work.

**Comment by kalessil** [comment]
Thank you for reporting @Bilge, confirmed.

**Comment by kalessil** [comment]
Fixed!
