### ISSUE TITLE
wrong refactor suggestion for call_user_func_array([$this, 'test'], []);

### ISSUE THREAD

**Issue by kaznovac** [kalessil/phpinspectionsea#1022]
| Subject    | Details                                                  |
| :--------- | :------------------------------------------------------- |
| Issue type | Bug |
| IDE        | PhpStorm, 2018.2 .2 |
| Plugin     | Php Inspections (EA Extended), 3.0.6 |

Description or screenshot:
plugins suggest to refactor `call_user_func_array([$this, 'test'], []);` to `call_user_func([$this, 'test'], );` notice the missing second parameter

Environment details
---
PhpStorm 2018.2.2
Build #PS-182.4129.45, built on August 22, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by kalessil** [comment]
Confirmed, thank you for reporting @kaznovac !

**Comment by kalessil** [comment]
Fixed!
