### ISSUE TITLE
No inspection for array_map to array_column

### ISSUE THREAD

**Issue by vladyslavstartsev** [kalessil/phpinspectionsea#1024]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     |  Feature request                          |
| Plugin         | Php Inspections (EA Extended), 3.0.6 |
| Language level | PHP 7.2  |

Current behaviour (description/screenshot:)
--
I've found it only in Doctrine Repositories, when you want to get only one column, but I think it can be found in other places.

no inspection for this
![image](https://user-images.githubusercontent.com/17382248/45253941-af665700-b377-11e8-804b-4a107e736288.png)

Expected behaviour
--
The upper image should be converted to this
![image](https://user-images.githubusercontent.com/17382248/45253961-09ffb300-b378-11e8-9a46-c318c865d33d.png)

Environment details
---
Information from Help -> About dialog (contains IDE and it's version details).
PhpStorm 2018.2.2
Build #PS-182.4129.45, built on August 22, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.8.0-53-generic

Inspired by this answer on SO https://stackoverflow.com/questions/11657835/how-to-get-a-one-dimensional-scalar-array-as-a-doctrine-dql-query-result/22424012#22424012

**Comment by kalessil** [comment]
Available in Php Inspections (EA Ultimate) - added in one of previous releases.
