### ISSUE TITLE
Unassigned return values

### ISSUE THREAD

**Issue by pretzlaw** [kalessil/phpinspectionsea#1026]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | Feature request,                          |
| Plugin         | both |
| Language level | any                        |

Current behaviour (description/screenshot:)
--

I write something like 

    str_replace( '[:toc:]', generateTocFromMarkdown( $markdown ), $markdown );
    $object->transpose($table);

Expected behaviour
--

As the first ones return is not assigned to a variable, it makes no sense to have this line at all.
But the second one is some custom thing so guessing there is hard.
PHP EA could nag about things like:

preg_replace not assigned, trim, array_map, ...

**Comment by kalessil** [comment]
Implemented!
