### ISSUE TITLE
"Type compability > 'in_array(...)', 'array_search(...)' type unsafe usage" inspection removes backslash

### ISSUE THREAD

**Issue by Koopzington** [kalessil/phpinspectionsea#1029]
| Subject|Details|
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | Bug/False-Positive|
| Plugin         | Php Inspections (EA Extended) 3.0.6|

Current behaviour
---
The autofix replaces `\in_array($foo, $bar);` with `in_array($foo, $bar, true);`

Expected behaviour
---
This inspection (and maybe others which are related to functions that can be prefixed with a backslash) should keep the backslash when fixing the issue.
Obviously this is only a quality-of-life improvement because it saves you another `Alt + Return`...

**Comment by kalessil** [comment]
Confirmed, thank you for reporting @Koopzington.

**Comment by kalessil** [comment]
Fixed.
