### ISSUE TITLE
Ensure strict_types location on auto-fix

### ISSUE THREAD

**Issue by azdanov** [kalessil/phpinspectionsea#1030]
When using `Use ::class instead` auto-fix, the generated _use_ statement is appended right after `<?php` block which works fine. But when `declare(strict_types=1);` is already defined the _use_ statement is added before the _declare_ statement which makes the file invalid, in my case using Laravel.

> As directives are handled as the file is being compiled, only literals may be given as directive values. Variables and constants cannot be used.
https://secure.php.net/manual/en/control-structures.declare.php

<img width="719" alt="screen shot 2018-09-11 at 11 38 17" src="https://user-images.githubusercontent.com/6123841/45349157-38200580-b5b9-11e8-9316-bc7845117368.png">

**Comment by kalessil** [comment]
Fixed!
