### ISSUE TITLE
[Feature Request] Cognitive Complexity

### ISSUE THREAD

**Issue by azdanov** [kalessil/phpinspectionsea#1037]
I've looked in already implemented inspections, but couldn't find anything similar.

> [...] the cognitive complexity is how difficult is to understand a function and all its possible paths.

Instead of trying to explain the inspection, here is a good article: https://www.tomasvotruba.cz/blog/2018/05/21/is-your-code-readable-by-humans-cognitive-complexity-tells-you/.

**Comment by kalessil** [comment]
Let me evaluate in our projects, to get fa eeling how does it fit daily development and existing toolchain (phpmd, infection and Php Inspections (EA Extended) of course).
Examples look good so far, thank you for sharing!

**Comment by kalessil** [comment]
Re-opening
