### ISSUE TITLE
"Extension is missing in composer.json" uses wrong composer.json

### ISSUE THREAD

**Issue by DCoderLT** [kalessil/phpinspectionsea#1038]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | Bug/False-Positive                          |
| Plugin         | Php Inspections (EA Extended) 3.0.6.1 |
| Language level | PHP 7.1                        |

Current behaviour (description/screenshot:)
--
I have a project with multiple components with their own composer.json files.
- `Admin/backend/composer.json`
- `Tests/composer.json`

The "extension is missing in composer.json" inspection/quick fix both seem to use the second file even when the inspected code is inside `Admin/backend` directory.
I'm not sure if it's relevant, but the `Admin` folder is also set up as a separate IDEA module (File → Project Structure → Modules).

Expected behaviour
--
Code inspection should reference the closest ancestor `composer.json`.

Environment details
---
IntelliJ IDEA 2018.2.4 (Ultimate Edition)
Build #IU-182.4505.22, built on September 18, 2018
JRE: 1.8.0_152-release-927-b1 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by kalessil** [comment]
Thank you for reporting @DCoderLT, unfortunately the missing extension inspection is coming from PhpStorm team.
