### ISSUE TITLE
Written value is the same as default one

### ISSUE THREAD

**Issue by webimpress** [kalessil/phpinspectionsea#1039]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | Bug/False-Positive
| Plugin         | Php Inspections (EA Extended) 3.0.6.1 |
| Language level | e.g. PHP 7.1    |

Current behaviour (description/screenshot:)
--

1. PR with the code: https://github.com/doctrine/DoctrineModule/pull/644
2. Check class DoctrineModule\Stdlib\Hydrator\DoctrineObject and properties there.
3. Those have different values than in parent class but PHPStorm thinks that those are the same.

Expected behaviour
--
Values shouldn't be marked grey as these values are different than in parent class.
PHPStrom thinks that these values are exactly the same.

Environment details
---
PHPStorm 2018.2.3

Reported firstly as bug in PHPStorm, but the problem is in the plugin:
- https://youtrack.jetbrains.com/issue/WI-43079

Notes
---
- Bugs fixed with the highest priority, so features might be postponed. But it shouldn't stop you, right?
- The project support is powered by community funding via [Patreon](https://www.patreon.com/kalessil)

**Comment by kalessil** [comment]
Thank you for reporting @webimpress, this might be the same as #958 (class constant references are the same name, but resolved to different classes).

**Comment by kalessil** [comment]
Fixed!
