### ISSUE TITLE
Feature: Method can be made static

### ISSUE THREAD

**Issue by puggan** [kalessil/phpinspectionsea#1041]
Issue type: Feature request
Plugin: Php Inspections (EA Extended) or Php Inspections (EA Ultimate)

Current behaviour (description/screenshot:)
![screenshot from 2018-09-25 18-48-22](https://user-images.githubusercontent.com/866668/46029398-9c7fb080-c0f3-11e8-8487-c405961f7ef2.png)

```
<?php
class a
{
    // Example b, recommends use 'self::'
    public function b()
    {
        return $this->a();
    }

    // Example c with self::, could now note that this function can be made static
    public function c()
    {
        return self::a();
    }

    // the static function
    public static function a()
    {
        return 'a';
    }
}
```

Expected behaviour
After handeling the `$this->` to `self::`, the function no longer have any references to $this,
and can therefor be made static.
It whould be nice if the plugin could tell me that.

**Comment by kalessil** [comment]
Duplicates #204 (which didn't happen and has many possible side-effects). But there is also #1043 (static anonymous functions) which will happen.
