### ISSUE TITLE
FP, Unnecessary semicolon, laravl/blade @endphp

### ISSUE THREAD

**Issue by puggan** [kalessil/phpinspectionsea#1045]
Issue type: False-Positive
Php Inspections (EA Ultimate): v2.0.8
PHP "v5.6.30" in composer.json

Current behaviour
![screenshot from 2018-09-26 17-17-31](https://user-images.githubusercontent.com/866668/46090039-1f664100-c1b0-11e8-80a5-6530e694b3ac.png)

Expected behaviour
as `@endphp` is expanded to ` ?>`,
and running the inspection on the generated cache-file
dosn't give this warning,
I expected to not get it in the blade-file.

Environment details
attaching the output of `composer show | sed -e "s/\([0-9]\.[0-9]\+\)\s.*/\1/"`
[compoer_versions.txt](https://github.com/kalessil/phpinspectionsea/files/2420432/compoer_versions.txt)

To add `@php` and `@endphp` in older version of Blade, i used:

            \Illuminate\Support\Facades\Blade::directive('php', function () {return "<?php ";});
            \Illuminate\Support\Facades\Blade::directive('endphp', function () {return ' ?>';});

---
Information from Help -> About dialog (contains IDE and it's version details).
PhpStorm 2018.3 EAP
Build #PS-183.2407.8, built on September 12, 2018
PhpStorm EAP User
Expiration date: October 12, 2018
JRE: 1.8.0_152-release-1293-b10 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-34-generic

**Comment by kalessil** [comment]
Thank you for reporting @puggan. Looks like a bug, I'll make sure the inspection does not process blade-files.

**Comment by kalessil** [comment]
Fixed.
