### ISSUE TITLE
False-Positive for "Makes no sense, because this type is not defined in annotations."

### ISSUE THREAD

**Issue by voku** [kalessil/phpinspectionsea#1046]
| Subject        | Details                                                                       | 
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | False-Positive                          |
| Plugin         | Php Inspections (EA Ultimate) v2.0.8 |
| Language level | e.g. PHP 7.0                       |

Current behaviour (description/screenshot:)
--
![bildschirmfoto vom 2018-09-27 02-04-19](https://user-images.githubusercontent.com/264695/46115933-b4d9f300-c1f9-11e8-9d3d-fb641fa7561a.png)

Expected behaviour
--
if "is_subclass_of()" is used for strings, then it's ok if the parameter was a string ...

Environment details
---
PhpStorm 2018.3 EAP
Build #PS-183.2635.12, built on September 19, 2018
PhpStorm EAP User
Expiration date: October 19, 2018
JRE: 1.8.0_152-release-1293-b10 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-134-generic

**Comment by kalessil** [comment]
Fixed!
