### ISSUE TITLE
Ultimate - Issue with indirectly required packages (Transitive)

### ISSUE THREAD

**Issue by sanderha** [kalessil/phpinspectionsea#1047]
First, thank you for reporting a bug or making a request. That takes time and we appreciate that!

Let's start with common details:
 
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | Support Request                          |
| Plugin         | Php Inspections (EA Ultimate), 2.0.8 |
| Language level | PHP 7.1                       |

Current behaviour (description/screenshot:)
--
All classes not directly required via the project composer.json are highlighted. On mouseover I get this message: "_This class belongs to a package which is not directly required in your composer.json_"
![image](https://user-images.githubusercontent.com/6941043/46127864-3a799500-c232-11e8-9342-eb8c131ddd65.png)

Expected behaviour
--
Dont highlight these classes?

Environment details
---
PhpStorm 2017.1.5
Build #PS-171.4694.83, built on March 7, 2018
Licensed to xx
You have a perpetual fallback license for this version
Subscription is active until June 27, 2019
JRE: 1.8.0_112-release-736-b22 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.4

**Comment by kalessil** [comment]
There are at least 3 options:
- Disable the inspection in the project
- Update composer.json to list transitive dependencies as well
- In inspections settings add '<vendor>/*' into exclusions list

What will work at best for you?

**Comment by sanderha** [comment]
Ah I see. Is it generally recommended by the community to list transitive dependencies in the composer.json?

**Comment by kalessil** [comment]
There is no agreed strategy in the community on this. I'd recommend to discuss this with the team.
My hints would be following:
- disable the inspection in monolithic projects
- list transitive dependencies in composer.json for micro-services and cloud applications.
