### ISSUE TITLE
PhpStorm works really slow with this extension on Magento 2.2.5 projects

### ISSUE THREAD

**Issue by ihor-sviziev** [kalessil/phpinspectionsea#1052]
Current behavior (description/screenshot:)
--
PhpStorm indexation is starting to be really slow, when you're changing between 2 different projects - it all the time tries to reindex everything again and again.

Expected behavior
--
Indexation should happening only at the same time as plugin is not installed, speed of navigation between files and indexation process should be ~ the same.

Environment details
---
Two Magento 2 projects, installed via composer

PhpStorm 2018.2.4
Build #PS-182.4505.42, built on September 27, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-34-generic

Notes
---
Unfortunately it's hard to define what actually slow, but just opening project, removing vendor directory and run composer install leads to really slow phpstorm.
After uninstalling this plugin - everything starting good again.

**Comment by kalessil** [comment]
Hi @ihor-sviziev, please use "Help -> Diagnostic -> Profile indexing" tool and share the generated artifact for further analysis. Hopefully it'll be something we can fix on our end.

**Comment by kalessil** [comment]
ping @ihor-sviziev

**Comment by ihor-sviziev** [comment]
Hi @kalessil,

Now I can't provide you this info. Will close this issue for now
