### ISSUE TITLE
Missing Array and string offset validity for types containing mixed

### ISSUE THREAD

**Issue by b1rdex** [kalessil/phpinspectionsea#1054]
In the following code only second and third example usages are correctly identifyed and reported as `may not support offset operations`.
I think that's because `MixedReturn::get()` is union `array|stdClass[]` internally and `array` type is collection of `mixed` type items, so `$item` is `mixed|stdClass` internally?
Would be nice to detect first example as probable error too.

```php
class MixedReturn
{
    /**
     * @return \stdClass[]
     */
    public function get(): array
    {
    }
}

$list = (new MixedReturn())->get();
foreach ($list as $item) {
    echo $item['test'];
}

/** @var \stdClass[] $list2 */
$list2 = $list;
foreach ($list2 as $item2) {
    echo $item2['test'];
}

foreach ($list as $item3) {
    /** @var \stdClass $item3 */
    echo $item3['test'];
}
```

**Comment by kalessil** [comment]
@b1rdex, could not reproduce (PhpStorm 2018.2.3), what;s you PhpStorm version?

![image](https://user-images.githubusercontent.com/1577185/46518965-f5c7ac80-c876-11e8-8f38-8cae38ed7574.png)

**Comment by b1rdex** [comment]
Originally reported from previous EAP. Now #PS-183.3283.10, built on October 3, 2018, still reproducible.

**Comment by kalessil** [comment]
Ok, I'll add a new test case and let see how many build on stable version going to fail ;)

**Comment by kalessil** [comment]
@b1rdex: checked (can not reproduce still), see here: https://travis-ci.org/kalessil/phpinspectionsea/builds/437515864

Can be the an EAP issue or caused by a third-party plugin as well.
