### ISSUE TITLE
FP TransitiveDependenciesUsageInspection

### ISSUE THREAD

**Issue by puggan** [kalessil/phpinspectionsea#1056]
Issue type: False-Positive
Plugin: EAU v2.0.8
Language level: 7.2

Current behaviour (description/screenshot:)
--
The class belongs to a package which is not directly required in your composer.json. Please add the package into your composer.json
![screenshot from 2018-10-04 12-04-16](https://user-images.githubusercontent.com/866668/46467297-ac6f5280-c7cd-11e8-9d97-7b12a9a3afc6.png)
![screenshot from 2018-10-04 12-04-22](https://user-images.githubusercontent.com/866668/46467306-aed1ac80-c7cd-11e8-89a1-2cd99429d9ee.png)
[TransitiveDependenciesUsageInspection.zip](https://github.com/kalessil/phpinspectionsea/files/2445874/TransitiveDependenciesUsageInspection.zip)

Expected behaviour
--
No warning, as "\Illuminate\Database\Schema\Blueprint" 
comes from "vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php"
that is part of "laravel/framework",
that is the only required package in "composer.json".

Environment details
---
PhpStorm 2018.3 EAP
Build #PS-183.2940.15, built on September 26, 2018
PhpStorm EAP User
Expiration date: October 26, 2018
JRE: 1.8.0_152-release-1293-b14 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-34-generic

**Comment by puggan** [comment]
May have something to do with the "replace" part of the composoer.json in laravel/framework:
https://github.com/laravel/framework/blob/5.7/composer.json

**Comment by kalessil** [comment]
@puggan: proposal with `replace` sounds good, I'll make adjustments.
@CZechBoY: the inspection heavily depends on composer auto-loading, alternatives are not supported ATM.

**Comment by CZechBoY** [comment]
@kalessil What about classmap?

**Comment by puggan** [comment]
"the inspection heavily depends on composer auto-loading"
according to composer autoloding, the Blueprint belongs to '/laravel/framework',

all 3 files say the same:

in vendor/composer/autoload_static.php:
```
'Illuminate\\Database\\Schema\\Blueprint' => __DIR__ . '/..' . '/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php'
```

in vendor/composer/autoload_classmap.php:
```
'Illuminate\\Database\\Schema\\Blueprint' => $vendorDir . '/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php',
```

in vendor/composer/autoload_psr4.php:
```
'Illuminate\\' => array($vendorDir . '/laravel/framework/src/Illuminate'),
```

or where is your inspection getting its intel from?

**Comment by kalessil** [comment]
@puggan: plugin indexes all composer.json files for getting packages information.

**Comment by kalessil** [comment]
Done!
