### ISSUE TITLE
Wrong refactoring suggested for call_user_func_array with key => value array

### ISSUE THREAD

**Issue by andreasschroth** [kalessil/phpinspectionsea#1058]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | Bug                          |
| Plugin         | Php Inspections (EA Extended), 3.0.6.1 |
| Language level | PHP 7.2                        |

Current behaviour:
---

Suggested refactoring is from

`call_user_func_array($callback, ['key1' => $value1, 'key2' => $value2]);`

to

`call_user_func($callback, 'key1', 'key2');`

Expected behaviour:
---

Correct call would be:

`call_user_func($callback, $value1, $value2);`

Because the values of the arrays are passed to the function, not the keys.

Environment details:
---

Latest version of PhpStorm stable.

**Comment by kalessil** [comment]
Thank you for reporting @andreasschroth, I'll take care about the issue.

**Comment by kalessil** [comment]
Fixed!
