### ISSUE TITLE
[Bug] Suggested fix in "General '\Exception' is thrown" is wrong if Exception is imported via namespace

### ISSUE THREAD

**Issue by andreasschroth** [kalessil/phpinspectionsea#1062]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | Bug                          |
| Plugin         | Php Inspections (EA Extended), 3.0.6.1 |
| Language level | PHP 7.2                        |

Current behaviour:
---

Here is some example code:

```php
namespace Demo\Test;

use Exception;

class Demo
{
    public function illustrateBugReport()
    {
        throw new Exception('Invalid context specified.');
    }
}
```

When using the suggested fix from the "General '\Exception' is thrown" inspection, the line that throws the exception gets replaced by this:

```php
throw new RuntimeException('Invalid context specified.');
```

But obviously this will break the code, as `Demo\Test\RuntimeException` does not exist (class with a name in that namespace).

Expected behaviour:
---

The correct fix would be to either use the fully qualified name for `RuntimeException` here, that would be:

```php
throw new \RuntimeException('Invalid context specified.');
```

OR alternatively import `RuntimeException` as well. Like this:

```php
namespace Demo\Test;

use RuntimeException;

class Demo
{
    public function illustrateBugReport()
    {
        throw new RuntimeException('Invalid context specified.');
    }
}
```

**Comment by kalessil** [comment]
Confirmed, the easiest way will be to follow `throw new \RuntimeException(...);` approach. Thank you for reporting @andreasschroth.

**Comment by kalessil** [comment]
Fixed!
