### ISSUE TITLE
[FP] substr() used as index-based access (on int)

### ISSUE THREAD

**Issue by puggan** [kalessil/phpinspectionsea#1074]
Issue type: False-Positive
Plugin: Ultimate v2.0.9

Current behaviour:
![screenshot from 2018-10-22 10-08-22](https://user-images.githubusercontent.com/866668/47283350-5549ea00-d5e3-11e8-985d-e539ece23d73.png)

Expected behaviour:
quiet, or something that converts it to string before using index-based access.

Environment details:
PhpStorm 2018.2.5
Build #PS-182.4892.16, built on October 11, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-36-generic

**Comment by kalessil** [comment]
Thank you for reporting @puggan, that's a good catch. I'll fix the code generation for this case.

**Comment by kalessil** [comment]
Fixed!
