### ISSUE TITLE
RealpathInSteamContextInspection inspection has a typo

### ISSUE THREAD

**Issue by SkylerLS** [kalessil/phpinspectionsea#1080]
First, thank you for reporting a bug or making a request. That takes time and we appreciate that!

Let's start with common details:
 
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | Typo                          |
| Plugin         | Php Inspections (EA Extended) |
| Language level | 7.2.7                         |

Current behaviour (description/screenshot:)
--
Use `\realpath` function somewhere in the code add an @noinspection tag.
Currently The tag is named `@noinspection RealpathInSteamContextInspection`

Expected behaviour
--
The tag is named `@noinspection RealpathInStreamContextInspection`

Environment details
---
PhpStorm 2018.2.5
Build #PS-182.4892.16, built on October 11, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by kalessil** [comment]
Thank you for reporting @SkylerLS, I'll take care of fixing this bug.

**Comment by kalessil** [comment]
Fixed!
