### ISSUE TITLE
[FP] Loop which does not loop, blade

### ISSUE THREAD

**Issue by puggan** [kalessil/phpinspectionsea#1082]
Issue type: Bug/False-Positive
Plugin: Ultimate 2.0.9
Language level: php 5.6, blade, laravel/framework v5.1.46 

        @foreach ($payments as $payment)
            <tr>
                <td>Inbetalningar - {{ $payment->tr_type }}</td>
                <td align="right" title="{{ Currency::formatNumber($payment->pos) }}, {{ Currency::formatNumber($payment->neg) }}">{{ Currency::formatNumber($payment->pos + $payment->neg) }}</td>
                <td>&nbsp;</td>
            </tr>
        @endforeach

Current behaviour (description/screenshot:)
The loop above triggers the inspection "Loop which does not loop"

Expected behaviour:
Not triggered

Environment details:
PhpStorm 2018.3 EAP
Build #PS-183.3975.17, built on October 24, 2018
PhpStorm EAP User
Expiration date: November 23, 2018
JRE: 1.8.0_152-release-1343-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.0-10-generic

**Comment by puggan** [comment]
Blade parsing seam of in general, as all lopp dosn't loop warnings, and all ifs says Statement has empty block.

**Comment by kalessil** [comment]
Fixed! We'll skip processing blade files, as they are not php code.
