### ISSUE TITLE
False-positive if "possible Null-pointer exception" when variable has been checked with ternary that uses brackets

### ISSUE THREAD

**Issue by windaishi** [kalessil/phpinspectionsea#1086]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | Bug/False-Positive                          |
| Plugin         | EA extended 3.0.7  |
| Language level | PHP 5.6                        |

Current behaviour (description/screenshot:)
--
"Null pointer exception may occur here" is triggered when a ternary operator with brackets is used to check the variable to be not null:

![image](https://user-images.githubusercontent.com/6232639/47784018-abfea480-dd04-11e8-859d-2498f58ea381.png)

If you remove the brackets in that case, the inspection is not triggered.

Expected behaviour
--
The inspection should not be triggered

Environment details
---
![image](https://user-images.githubusercontent.com/6232639/47784304-74442c80-dd05-11e8-8532-111530dbcf55.png)

**Comment by kalessil** [comment]
Thank you for reporting @windaishi, I'll take care of fixing the issue.

**Comment by kalessil** [comment]
Fixed!
