### ISSUE TITLE
The call to count() should not be seen as inefficient.

### ISSUE THREAD

**Issue by windaishi** [kalessil/phpinspectionsea#1088]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | Feature request |
| Plugin         | Php Inspections (EA Extended) |
| Language level | PHP 5.6                      |

Current behaviour (description/screenshot:)
--
The sniff "Callable calls in loops termination condition" reports a call of `count()` as having "weak performance"

![image](https://user-images.githubusercontent.com/6232639/47853909-965ead00-dde0-11e8-9751-b57957ab25e2.png)

Expected behaviour
--
The sniff should not report a call of `count()` in loops as "weak performance".

Maybe a white-list solves the problem.

Environment details
---
![image](https://user-images.githubusercontent.com/6232639/47784304-74442c80-dd05-11e8-8532-111530dbcf55.png)

**Comment by kalessil** [comment]
It's the root cause of this inspection - a pattern-troublemaker in high load projects. I'd encourage to follow its recommendations (Quick-Fix) or disable the inspection if it doesn't fit the project.

**Comment by rentalhost** [comment]
By PHP 7.2.2, I got **17%+** performance when `count()` is not used on looping conditional (eg. `for ($i = 0, $j = count(...); $i < $j; ...)`). So I think that this inspection is valid at moment.

**Comment by windaishi** [comment]
Hey guys. Thanks for clarification.

Am Do., 1. Nov. 2018, 16:22 hat David Rodrigues <notifications@github.com>
geschrieben:
