### ISSUE TITLE
Variable variables incorrectly evaluated as suspicious assignment.

### ISSUE THREAD

**Issue by WiXSL** [kalessil/phpinspectionsea#1091]
First, thank you for reporting a bug or making a request. That takes time and we appreciate that!

Let's start with common details:
 
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | Bug/False-Positive                          |
| Plugin         | Php Inspections (EA Extended) v3.0.7 |
| Language level | PHP 7.2 

Current behaviour (description/screenshot:)
![captura](https://user-images.githubusercontent.com/8268610/48000523-7bdc4a80-e0e4-11e8-8f2b-daa112d7285f.GIF)

Environment details
PhpStorm 2018.3 EAP
Build #PS-183.4139.30, built on October 31, 2018
PhpStorm EAP User
Expiration date: November 30, 2018
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by kalessil** [comment]
Fixed!
