### ISSUE TITLE
New value type (static) is not in annotated types

### ISSUE THREAD

**Issue by puggan** [kalessil/phpinspectionsea#1092]
Is #439 back?

Issue type: Bug/False-Positive
Plugin: EA Ultimate 2.0.9
Language level: php 5.6

Current behaviour:
![screenshot from 2018-11-05 15-28-37](https://user-images.githubusercontent.com/866668/48003906-11410400-e110-11e8-8f0a-07a69e72db05.png)

Expected behaviour:
static shold be converted to Carbon, and Carbon is in @param, so no warning.

Environment details:
PhpStorm 2018.3 EAP
Build #PS-183.3975.17, built on October 24, 2018
PhpStorm EAP User
Expiration date: November 23, 2018
JRE: 1.8.0_152-release-1343-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.0-10-generic

**Comment by kalessil** [comment]
@puggan, is it possible to provide a simplified code fragment?

**Comment by puggan** [comment]
@kalessil use the one in 439, it also fails.

![screenshot from 2018-11-06 15-37-06](https://user-images.githubusercontent.com/866668/48071141-d905f800-e1d9-11e8-9575-d5215dab36d4.png)

**Comment by kalessil** [comment]
Great, will check today.

**Comment by kalessil** [comment]
Reproduced, will take care of fixing the issue.

**Comment by kalessil** [comment]
Fixed!
