### ISSUE TITLE
Feature request - need inspection to validate names of function/method parameters same as now for function names

### ISSUE THREAD

**Issue by fux666** [kalessil/phpinspectionsea#1094]
Hi!

I would like to kindly ask to add to EA Extended a possibility to check the naming of function / method parameter names. I have currently method to validate other constructs as constants, classes, methods, etc. But surprisingly the parameters naming validation seems to be missing.

Please help to add such inspection to allow to more completely fit the organizations coding / naming standards.

thanks so much - Mark

Current behavior (description/screenshot:)
--
It is not possible to validate the parameter names for functions and methods

Expected behavior
--
New inspection is added that regexp allows definition of the expected naming format for function parameters.

**Comment by kalessil** [comment]
Mark, this seems similar to #1096, or? Did you try also "Naming conventions" inspections coming with IDE itself (the are disabled by default)?

**Comment by fux666** [comment]
Actually I did for all other objects, and they are working beautifully. The issue is that this is missing for Parameters, we currently have in newest version: PHP -> Naming Conventions -> Class, Constant, Function, Method, Property and Variable. However.... parameter (of functions and methods) are not here - why?!

The issue #1096 is different, while the Naming Conventions works perfectly to establish generic naming rules, in my case variable having the "v" prefix always, the issue 1096 tries to extend such validation to also validate the type of variable, which naming conventions are unable to do. So we have 2 distinct... challenges: 

1. **enable validation of parameter names** (this issue)
2. **extend all validations to be type aware (issue #1096)** possibly in some other tool, as long it reports to inspection window to have this consistent with Inspections, EA extended and Sonar Lint.

**Comment by kalessil** [comment]
Understood. In order to keep focus, I think we shouldn't expand the plugin functionality in this direction. Perhaps someone from the community wants to create a new plugin (sharing the link in my Twitter).
