### ISSUE TITLE
Feature Request - validation of the missing parametr types definitions

### ISSUE THREAD

**Issue by fux666** [kalessil/phpinspectionsea#1095]
Hi!

We discovered that we need to have inspection where the code audit shows us all the instances where the parameter type if not defined, right now we do not seem to have a way to easily tell which parameters are missing type definitions. We would like to use fully typed model for 95% of our functions in the code base. For this reason the inspection that will show us all instances where such definitions are missing would be extremely helpful to accomplish that task.              |

Current behavior (description/screenshot:)
--
It is not possible to determine if there are some function / method parameters that do not have type specified.

Expected behavior
--
New inspection that would list all instances where type is not defined, furthermore a way should be present to allow disabling this inspections (by annotation?) for the functions where the type is not desired (e.g. mixed type accepting sometimes a string but also a number).

**Comment by funivan** [comment]
Implemented this feature: 
https://github.com/funivan/PhpClean#missingparametertypedeclaration
https://plugins.jetbrains.com/plugin/11272-phpclean

**Comment by fux666** [comment]
Thanks a million, I will check it out tomorrow :)
