### ISSUE TITLE
Support Request -  Define the inspection (Structural Search?) requiring all int parameters have name starting with "int" prefix

### ISSUE THREAD

**Issue by fux666** [kalessil/phpinspectionsea#1096]
Hi!

Our coding standards require that all int parameters should have name starting with "int" prefix, We need to set-up the inspection that would find all occurrences where type is defined but the name prefix does not match this requirement and list it for respective corrections or silencing this error (e.g. for legacy class or function).

As per our best knowledge the "Structural Search" functionality may possibly offer such functionality. Never the less we were unsuccessful for several weeks of experiments to set it up correctly. I would like to kindly ask for advise if such inspection is possible either in EA Extended or in "Structural Search" and how to set it up. Thanks in advance for your help!

 Current behavior (description/screenshot:)
--
No way to find all instances where variable is defined as integer e.g. function myFunction(int $param) which name is not starting with "int" prefix. Actual name required would be myFunction(int $intParam) to meet the coding standards. Name should be possible to be defined as regexp for example "i", "int","integer", "parInt", etc...

Expected behavior
--
A way to set up the inspection to catch all occurrences where the parameter name is not meeting the coding standards. For particular occurrence it should be possible to disable the warning (e.g. with annotation).

**Comment by kalessil** [comment]
SSR never worked for me as well, and it still mystery for me why PhpStorm invests time into it.
But getting back to the topic, so far I didn't see similar functionality in PhpStorm or 3rd party tools. The easiest way (taking in account this project history and scope) would be to implement a custom PHP CodeSniffer rules for that (I didn't dig too much there, but it possible to hook a custom AST node visitor like function or method and check if naming rules are violated).

**Comment by funivan** [comment]
Hello @fux666, I can help you with this rule. You can contact me via email: alotofall [at] gmail.com

@kalessil Structural search helped me several times. But I totally agree - SSR is crap)
