### ISSUE TITLE
False positive: Unnecessary parentheses

### ISSUE THREAD

**Issue by foobar13372** [kalessil/phpinspectionsea#1098]
Using short ternaries to decide for an array and directly accessing these arrays results in a warning about missing paranetheses:

` ($concreteArray ?? $defaultArray)['key'];`

(also for `?:`)

Basically the same as #205 just for arrays.

**Comment by kalessil** [comment]
Thank you for reporting @foobar13372, I'll take care of fixing the issue.

**Comment by kalessil** [comment]
Fixed!
