### ISSUE TITLE
[new, security] security issues for mcrypt

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#11]
https://paragonie.com/blog/2015/05/if-you-re-typing-word-mcrypt-into-your-code-you-re-doing-it-wrong
- mcrypt_encrypt() - block zero-padded, if mcrypt_get_block_size() not in the scope and below PHP 5.6
- mcrypt_encrypt() - require 5th parameter when 4th is MCRYPT_MODE_(CBC|CFB|OFB)
- 3 more items has been released in v2.2.0

**Comment by kalessil** [comment]
Partially done:

- mcrypt_encrypt() - MCRYPT_RIJNDAEL_192 is less studied, use MCRYPT_RIJNDAEL_128 (AES) instead
- mcrypt_encrypt() - MCRYPT_RIJNDAEL_256 is not AES-256, use MCRYPT_RIJNDAEL_128 + 256 bit key
- mcrypt_create_iv() - use random_bytes() in PHP7+

**Comment by rentalhost** [comment]
Instead of create small "patches" on `mcrypt`, why just not consider that "insecure" and suggests to use OpenSSL?

**Comment by kalessil** [comment]
PHP 7.2 deprecated mcrypt, so PS will do this soon, but some frameworks has graceful fallback from openssl to mcrypt - so still makes sense.

**Comment by rentalhost** [comment]
I guess that this inspection should consider the general public. Fallbacks cases should not be reported. Don't you think?

**Comment by kalessil** [comment]
2.3.11
- mcrypt_encrypt() - RSA+CBC case got reported now
- mcrypt_encrypt() - require 5th parameter when 4th is MCRYPT_MODE_(CBC|CFB|OFB) - SKIPPED (ext is dead)
