### ISSUE TITLE
Do not suggest return type for interface implementations

### ISSUE THREAD

**Issue by antiphp** [kalessil/phpinspectionsea#1100]
Hey,

**Implementing an interface** - especially a native interface - **should not lead to inspection issues** regarding suggested return types or similar.

Expected behaviour:
=> Ignore it, since it's an interface defintion. **Complain at the interface, not the implementation**.

Environment details:
=> Php Inpsections: 3.0.8.1
=> PhpStorm: 2018.3 EAP
=> PHP: 7.2.10

Example:

    class FooSet implements \ArrayAccess, \IteratorAggregate
    {
        // ...
       
        // ":bool" can be declared as return type" ...
        /**
         * @inheritdoc
         */
        public function offsetExists($offset)
        {
            return isset($this->set[(string)$offset]);
        }

        // ...
    }

Notes: 
Language level migration / Return type hint can be used

Cheers

**Comment by kalessil** [comment]
Thank you for reporting @antiphp, will do.

**Comment by kalessil** [comment]
@antiphp, looking deeper into the issue and questions are coming: 
- what is the problem exactly (I can see this case has no side-effects when hints are getting applied: https://3v4l.org/tpbkP)?
- what's is the typical workflow for this issue types and why it can not be applied in this case?

**Comment by antiphp** [comment]
Well it looks like the return type can be any value. I just replaced ":bool" with ":\DateTime" and it does not raise an error.

But my point was more like, when an interface defines an expectation, the implementation must follow that definition. So inspections should not complain for things like that, because that piece of code is right, it just follows the interface definition. But that's just an opinion. What do you think?

**Comment by kalessil** [comment]
@antiphp  if I understand correctly, the point is to follow one-to-one the interface/parent method definition (even if we can declare return type there). That's opposite to the inspection intentions, probably it should be disabled in the project context at all (probably as I\m not aware of the project specific and team level).

**Comment by antiphp** [comment]
I thought it is not allowed to specify a return type in the class when the interface does not. Well but with fact my report does not make any sense, sorry guys! Thanks for pointing that out.

**Comment by kalessil** [comment]
Ah, ok =)
