### ISSUE TITLE
I love new patterns but...

### ISSUE THREAD

**Issue by iakoder** [kalessil/phpinspectionsea#1101]
First, thank you for reporting a bug or making a request. That takes time and we appreciate that!

Let's start with common details:
 
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Feature request     |Feature request                          |
| Plugin         | Php Inspections (EA Extended), 3.0.8.1 |
| Language level | PHP 7.0                        |

I like new patterns, I really do.  They can sometimes be problematic.  We have PhpStorm inspections hooked into Jenkins and when tests fail we block future commits.  We also tell all our developers, run inspections and make sure they're clean before you commit.

In order to keep things sane we have a known, shared configuration and we disable new inspections by default so that new versions of PhpStorm shouldn't break our inspections.  Over time we enable new inspections, clean up the issues and then add those inspections to the global configuration.

The new null coalescing operator can be used inspection patterns just uncovered 183 opportunities for us to improve our codebase but I have to tell our developers that they cannot upgrade to this version until we go through and address these issues.

I would much prefer that new patterns come as new options in the inspection.  In this particular case an option like "Consider if statements."  Which wouldn't be checked by default because of our PhpStorm setting.

**Comment by kalessil** [comment]
Great writing @iakoder, thank you fior the feedback. This is clearly a problem and the setting is needed without much discussion ;) In future poke me directly via e-mail for when situation repeated - shorter and less tolerant forms will work ;)

And, I'll add a setting shortly. Question on my end: should I make 3.0.8.2 with it or you've already take care of the reported cases?

**Comment by kalessil** [comment]
Added new settings!

**Comment by iakoder** [comment]
@kalessil, thanks!  As you could guess from the other issues I reported I've taken a pass at cleaning up all these issues.  When I'll get approval to commit them is another story.  The only inspection I can't get rid of is  https://github.com/kalessil/phpinspectionsea/issues/1105
