### ISSUE TITLE
Fix for null coalesce operator ate my braces

### ISSUE THREAD

**Issue by iakoder** [kalessil/phpinspectionsea#1102]
First, thank you for reporting a bug or making a request. That takes time and we appreciate that!

Let's start with common details:
 
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | Bug                          |
| Plugin         | Php Inspections (EA Extended), 3.0.8.1 |
| Language level | PHP 7.0                      |

See https://youtrack.jetbrains.com/issue/WI-44203

After fixing a null coalesce operator turned

```
        } else if (isset($selectedAmtMap[$vendorID][$billRecNo])) { 
            $selectedAmount = $selectedAmtMap[$vendorID][$billRecNo]; 
        } else {
            $selectedAmount = $billData['TOTALDUE']; 
        }
```

into

```
 } else $selectedAmount = $selectedAmtMap[$vendorID][$billRecNo] ?? $billData['TOTALDUE'];
```

instead of

```
        } else {
            $selectedAmount = $selectedAmtMap[$vendorID][$billRecNo] ?? $billData['TOTALDUE'];
        }
```

PhpStorm 2018.3 EAP
Build #PS-183.4284.100, built on November 14, 2018
PhpStorm EAP User
Expiration date: December 14, 2018
JRE: 1.8.0_152-release-1343-b15 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1

**Comment by kalessil** [comment]
Fixed!
