### ISSUE TITLE
@param self

### ISSUE THREAD

**Issue by ockstadt** [kalessil/phpinspectionsea#1116]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | Bug/False-Positive                          |
| Plugin         | Php Inspections (EA Extended) |
| Language level | e.g. PHP 7.2              |

Current behaviour (description/screenshot:)
![grafik](https://user-images.githubusercontent.com/36147797/48937458-70738680-ef0e-11e8-8787-837d4fe630a8.png)

When changing type hinting from classname to "self" we get a false-positive.

"@param self $phpInspectionIssue" is underlined.

![grafik](https://user-images.githubusercontent.com/36147797/48937964-0956d180-ef10-11e8-9e97-82b61625f0b5.png)

Expected behaviour
No issue to be shown anymore. "@param self $phpInspectionIssue" should not be underlined.

**Comment by kalessil** [comment]
Thank you for reporting @ockstadt, unfortunatelly that seem to be an inspection by PhpStorm itself. Please report to JetBrains team ([here](tbrains.com/issues/WI)).
