### ISSUE TITLE
[critical] [performance-problem]  ReferenceMismatchInspector produce tree materialization

### ISSUE THREAD

**Issue by MaXal** [kalessil/phpinspectionsea#1120]
According to our performance test runs of batch inspection, the method `ReferenceMismatchInspector::checkReferenceReturnedByCallable` is the main culprit in performance degradation. It introduces significant hit and in some cases (drupal8 batch inspection) leads to total freeze because of constant GC. GC happens because a lot of files should be materialized. 

As you may see the method does `OpenapiResolveUtil.resolveReference(reference);` and starts to traverse the tree instead of using stub information.

**Comment by wbars** [comment]
@kalessil Despite the fact that we don't yet keep information about returning by reference in stubs you still can index your own information via implementing file based index (e.g. `com.intellij.util.indexing.FileBasedIndexExtension`. Is this extensions you can keep boolean value for each function/method FQN whether it returned by reference and use this index in your inspection. This expected to be significantly faster than old approach.

**Comment by kalessil** [comment]
Done! Dropping it completely.
