### ISSUE TITLE
[performance-problem] AutoloadingIssuesInspector traverse the whole tree to the bottom

### ISSUE THREAD

**Issue by MaXal** [kalessil/phpinspectionsea#1123]
In the class `AutoloadingIssuesInspector` on the line:
`final List<PhpClass> classes = PsiTreeUtil.findChildrenOfType(file, PhpClass.class).stream()
                            .filter(c -> !c.isAnonymous()).collect(Collectors.toList());`
the whole tree is traversed to the bottom to find classes.
It's better to use: `com.jetbrains.php.lang.psi.PhpFile#getTopLevelDefs`.

**Comment by kalessil** [comment]
Fixed!
