### ISSUE TITLE
[performance-problem] ClassConstantUsageCorrectnessInspector traverse the whole tree looking for trait usages

### ISSUE THREAD

**Issue by MaXal** [kalessil/phpinspectionsea#1124]
In class `ClassConstantUsageCorrectnessInspector` the code `for (final PhpUse use : PsiTreeUtil.findChildrenOfType(current, PhpUse.class)) {` traverse the whole class in attempt to find use statements. 

Probably `com.jetbrains.php.lang.psi.stubs.PhpClassStub#getTraits` should be used instead.

**Comment by kalessil** [comment]
Fixed!

**Comment by MaXal** [comment]
@kalessil Thank you a lot for the fixes! It was really fast!

**Comment by kalessil** [comment]
You are welcome @MaXal =)
