### ISSUE TITLE
[FP] "Null pointer exception may occur here" inside isset()

### ISSUE THREAD

**Issue by puggan** [kalessil/phpinspectionsea#1130]
Issue type: Bug/False-Positive
Plugin: Php Inspections (EA Ultimate) v2.0.10
Language level: PHP 5.6

Current behaviour (description/screenshot:)
--
![screenshot from 2018-12-03 15-55-19](https://user-images.githubusercontent.com/866668/49381319-e8faf400-f713-11e8-8cf2-e347d75acae3.png)

"Null pointer exception may occur here" warning, inside the isset().
The content of the var is from a function that may return null.

Expected behaviour
--
No warning, as isset() just returns false, if the variable is null.

Environment details
---
PhpStorm 2018.3
Build #PS-183.4284.150, built on November 21, 2018
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.0-11-generic

Tested:
---
https://3v4l.org/ZjAve

**Comment by kalessil** [comment]
Oh, interesting why I didn't handle this.

**Comment by kalessil** [comment]
Fixed!
