### ISSUE TITLE
[Feature request] Non-optimal regular expression, PCRE_UNGREEDY

### ISSUE THREAD

**Issue by puggan** [kalessil/phpinspectionsea#1133]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type | Feature request |
| Plugin | Php Inspections (EA Ultimate) v2.0.11 |
| Language level | PHP 5.6 |

Current behaviour (description/screenshot:)
--
The project had the code `preg_replace("/[^0-9]/isU",`,
The plugin complained alot about it, after fixing all sugestions i was left with:
`/\D/U`, so I just had to lookup U and see what it was.
U or PCRE_UNGREEDY make all `*` behave like `*?`, and `+` like `+?`.
As the rexexp have neither * or +, it seams verry irelevant / ambiguous.

Expected behaviour
--
It should have said that all i, s & U was ambiguous.

Environment details
---
PhpStorm 2018.3
Build #PS-183.4284.150, built on November 21, 2018
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.0-12-generic

**Comment by puggan** [comment]
Tested, and U also makes `?` act as `??`

https://3v4l.org/PYRBN

**Comment by funivan** [comment]
Hello @puggan. Thanks for the report.
But in the original preg_match you already have `U` modifier`"/[^0-9]/isU"`. 
If you remove it - what plugin will suggest to you?

**Comment by puggan** [comment]
If you use the U modifer, without any of the `?`, `*` or `+`,
I expext the plugin to say its ambiguous,
as it do if i or s is used when not needed.

So the `/[^0-9]/isU` should be minimized to just `/\D/`.

**Comment by kalessil** [comment]
Oh, looks like a great addition to the inspection, thank you @puggan for making the research!

**Comment by funivan** [comment]
I think this should be splited to 2 workflows:
1. replace `[^0-9]` to  `\D`
2. remove unnecessary `U` modifier

**Comment by kalessil** [comment]
Implemented!
