### ISSUE TITLE
[performance-problem] ArgumentEqualsDefaultValueInspector produces tree materialization

### ISSUE THREAD

**Issue by MaXal** [kalessil/phpinspectionsea#1134]
In the inspection the following code:
```
final PsiElement resolved = OpenapiResolveUtil.resolveReference(reference);
...
final Parameter[] parameters = ((Function) resolved).getParameters();
...
final PsiElement value = parameters[index].getDefaultValue();
```
produces tree materialization since `Parameter#getDefaultValue` is not backed by stubs.

You may use `Parameter#getDefaultValuePresentation` which is available since PhpStorm 2018.2 instead.

**Comment by kalessil** [comment]
Fixed! Has do introduce a new index in order to keep compatibility with PS 2016.
