### ISSUE TITLE
"argument unpacking" can be used -> is not working with root-namespace hint "\"

### ISSUE THREAD

**Issue by voku** [kalessil/phpinspectionsea#1137]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | Bug                          |
| Plugin         | Php Inspections (EA Ultimate), v2.0.11 |
| Language level | e.g. PHP 7.0                       |

Current behaviour (description:)
--
does not show the hint for "argument unpacking"

Expected behaviour
--
show the hint for "argument unpacking"

Environment details
---
PhpStorm 2018.3.1
Build #PS-183.4588.67, built on December 5, 2018
Licensed to Portable UTF-8 /  
Subscription is active until April 5, 2019
For non-commercial open source development only.
JRE: 1.8.0_152-release-1343-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-139-generic

Example
---
```php
$list = \call_user_func_array('array_merge', $list);
```

**Comment by kalessil** [comment]
Added new test cases, probably php version in the project settings is not set to 7.0.
