### ISSUE TITLE
[Feature Request] new inspection: unecessary call via parent::

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1138]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | Feature request                   |
| Plugin         | Php Inspections (EA Extended)  |

Expected behaviour :
--
If there is a class who call a method via parent:: and neither the class itself nor its childrens have this method, suggest to replace parent:: with $this->

After a lot of refactoring, we ended up with a generic functionnality in a parent method (let's say A) and the old deprecated functionnality in the child method A. While we migrated, we replaced calls from $this->A() to parent::A(). We now have finished the migration and we have deleted every child method. Now we end up with a lot of parent::A() who refers in fact to $this->A(). This is not very easy to spot and an inspection could help with cases like this. 

Notes
--
- It must not be in a static method
- The class must have no childrens or they must not redeclare the called method
- It may not work if the called method is magic ? (__call mumbo jumbo?)
- Maybe there are other cases in which parent:: can't be replaced by $this:: ?

**Comment by kalessil** [comment]
Looks like a code style issue to me, I'll implement with the intention to the original use-case and ignoring magic.

**Comment by kalessil** [comment]
Implemented!

**Comment by orklah** [comment]
Wow! Thanks!

**Comment by kalessil** [comment]
You are welcome =)
