### ISSUE TITLE
False positive "This makes no sense or enforces the operation result"

### ISSUE THREAD

**Issue by Sorcy** [kalessil/phpinspectionsea#1140]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | False-Positive                          |
| Plugin         | Php Inspections (EA Extended) V3.0.9.1 |
| Language level | PHP 7.1                         |

Current behaviour (description/screenshot:)

A colleague of mine likes to write symfony collection filters like this:

        $allImages = $object->getImages()
            ->filter(function (Image $image) use ($maxAge, $includeUnrated, $now) {
                return true
                    && ($image->getCreated() <= $now)
                    && ($now <= $image->getDeleted())
                    && ($image->getAge() <= $maxAge)
                    && ((Audit::STATE_ACCEPTED === $image->getState()) || $includeUnrated)
                    && (Audit::STATE_REJECTED !== $image->getState())
                    ;
            });

While I would agree that the "true" in the begginning of the return is a weird way to handle the filter, he absolutely wants it this way and PHP Inspections marks the "true" as "This makes no sense or enforces the operation result" error, which of course is not true.

Expected behaviour

Do not mark the true as making no sense, even so it's pretty ugly.

Environment details

PhpStorm 2018.3.1
Build #PS-183.4588.67, built on December 5, 2018
Licensed to <redacted>
Subscription is active until April 25, 2019
JRE: 1.8.0_152-release-1343-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by orklah** [comment]
Well, this is specifically the case I want to be warned about when I use this inspection.

If it was ruled as a false positive(because how it is indented?), it would be a bug for others.

Did you consider suppressing the inspection for this statement? You can do it with this tag:
/** @noinspection SuspiciousBinaryOperationInspection */

**Comment by kalessil** [comment]
Technically, `true && ...` and `false || ` are false positives. So I have to skip them in this specific inspection.

But code style is questionable, so I'll introduce a new code style inspection marking those hardcoded booleans as dead code.

**Comment by orklah** [comment]
Oh, I thought this was the "This makes no sense" part of the inspection, the other part being the opposite "enforces the operation result". I misinterpreted the message of the inspection

**Comment by kalessil** [comment]
Fixed! I re-worked reporting, so the `true && ...` and `false || ...` are decorated as unused code when reported. When this is out, I'll need feedback ;)
