### ISSUE TITLE
SenselessTernaryOperatorInspection not shown on ultimate

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1147]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | Bug                     |
| Plugin         |  Php Inspections (EA Ultimate) 2.0.11 |

I just installed the 14 days trial for EA Ultimate and I'm surprised that the SenselessTernaryOperatorInspection is not shown anymore. It seems to be the only inspection on Extended not included in Ultimate. Was this inspection replaced by something else in the Ultimate version?

Thanks

**Comment by kalessil** [comment]
Awesome, the Ultimate really great =)
I'll hardly remember all changes, but yes the inspection was replaced with one called "Illusion of choice".
