### ISSUE TITLE
[Feature Request] extend `'in_array(...)' misused` and `Non-optimal if conditions`

### ISSUE THREAD

**Issue by vladyslavstartsev** [kalessil/phpinspectionsea#1148]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | Feature request                          |
| Plugin         | Php Inspections (EA Extended), v3.0.9.1 |
| Language level |  PHP 7.2                        |

This code (that is marked as `This call is duplicated in conditions set.`)

```php
if (
    \Route::currentRouteName() !== 'bar' &&
    \Route::currentRouteName() !== 'baz'
) {
    //do something
}
```

can be converted into this

```php
if (\in_array(\Route::currentRouteName(), [
    'bar',
    'baz'
],true)) {
    //do something
}
```

**Comment by kalessil** [comment]
Marking as implemented, still, need to add tests, run QA and Performance tests.
