### ISSUE TITLE
[FP] ClassExistenceCheckInspector with is_subclass_of

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1151]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | False-Positive                         |
| Plugin         | Php Inspections (EA Ultimate)|

Current behaviour (description/screenshot:)
--
When using is_a with a string, the ClassExistenceCheckInspector inspection suggest to use the third parameter to allow using string. This makes perfect sense given the default value of the argument is false.

However, with is_subclass_of, we also have the same inspection. This doesn't make sense because the default value of the third parameter is true. Which means the string usage is allowed by default. It feels weird to add the boolean to its default value to resolve the inspection for a code who is working as expected

**Comment by kalessil** [comment]
Sound reasonable (I also didn't notice that defaults differs there). Fixed!
