### ISSUE TITLE
nested if removes comments

### ISSUE THREAD

**Issue by puggan** [kalessil/phpinspectionsea#1162]
| Subject        | Details 
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | Bug |
| Plugin         | Php Inspections (EA Ultimate) v2.0.11 |
| Language level | PHP 7.3 |

Current behaviour (description/screenshot:)
--
```php
<?php

function a() {return true;}
function b() {return true;}
function c() {echo 'hello';}

// Before

if(a()) {
    // also check b
    if(b()) {
        c();
    }
}

// After

if(a() && b()) {
    c();
}
```

Expected behaviour
--
```php
// also check b
if(a() && b()) {
    c();
}
```

Environment details
---
PhpStorm 2018.3.2
Build #PS-183.4886.22, built on December 12, 2018
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.0-13-generic

**Comment by kalessil** [comment]
Fixed!
