### ISSUE TITLE
IV correctness: when the single variant is a method, check if it abstracts bytes generation

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#1164]

**Comment by bcremer** [comment]
Relates to https://github.com/shopware/shopware/pull/1970#issuecomment-453447722.

![image](https://user-images.githubusercontent.com/55820/51031365-a9d68300-159c-11e9-947c-d95fad571a0a.png)

**Comment by kalessil** [comment]
Fixed!
