### ISSUE TITLE
Severity of some inspections cannot be changed

### ISSUE THREAD

**Issue by julienfalque** [kalessil/phpinspectionsea#118]
For some inspections, changing the severity has no effect and the default severity is always used. I have this issue with at least two for now, but there may be more:
- Compatibility > Binary-unsafe 'fopen(...)' usage;
- Probable bugs > Array and string offset validity.

I have set their severity to _Warning_ but they still appear as _Error_.

**Comment by funivan** [comment]
What is your version of the phpstorm ?

**Comment by julienfalque** [comment]
2016.3.2

**Comment by funivan** [comment]
@kalessil confirm this bug
Phpstorm version: 2017.1 EAP  #PS-171.2455.9
Plugin version: 2.3.1.1

**Comment by kalessil** [comment]
@julienfalque : the severity is related to grouping of inspection results, not highlighting in the source code.

I totally agree to make fopen() reports warnings instead of errors.
Can you elaborate a little bit more which offsets messages you want to make less visible (it's 3 different cases which can be reported)?

**Comment by julienfalque** [comment]
> @julienfalque : the severity is related to grouping of inspection results, not highlighting in the source code.

I'm sorry but I don't understand what you mean. Usually when I change the severity of inspections, it does change the way they are reported in the editor.

If I set the severity of _PHP > Code Style > Traditional syntax array literal detected_ to _Error_, using `array()` instead of `[]` in my code will appear with a scary red underlining in the editor, but setting it to _Weak warning_ will make the editor report it in a much less agressive way.

This is what I expect when changing the severity of the inspections I mentioned earlier.

> Can you elaborate a little bit more which offsets messages you want to make less visible (it's 3 different cases which can be reported)?

In my case, the reported error is _Resolved index type ([string]) is incompatible with possible [int]. Probably just proper type hinting needed_.

By the way, I do think some inspections should default to _Warning_  severity instead of _Error_, but the issue here is that the default cannot be changed by the user.

**Comment by kalessil** [comment]
The bug label makes sense, I have an idea why severity changes worked for the [], but not for the reported inspections.

Would you please provide an extended list of inspections you are trying to turn into warning instead of errors, so I checked them as well?

**Comment by julienfalque** [comment]
Only had the issue with the two I already mentioned for now, but sure, if I find more, I'll mention them here too :)

**Comment by julienfalque** [comment]
Thank you @kalessil :)

**Comment by kalessil** [comment]
You are welcome @julienfalque

**Comment by jcrben** [comment]
I noticed this with Addition operator used on arrays
![image](https://user-images.githubusercontent.com/5614134/37245987-da6b3b2a-2455-11e8-9bd6-f274b6043e6f.png)
with this line of code:
![image](https://user-images.githubusercontent.com/5614134/37245994-fd41b570-2455-11e8-837f-f546162e3ccc.png)

I did notice that the light bulb changed from red to yellow, though.

If you'd prefer I could open a new issue for this?

**Comment by kalessil** [comment]
@jcrben : please open a new one =)
