### ISSUE TITLE
Performance/Array_push misused/count() not required is wrong in some circumstances

### ISSUE THREAD

**Issue by Stevehans** [kalessil/phpinspectionsea#1185]
Issue type Bug?/wrong recommendations
Plugin       Php Inspections (EA Extended) 3.0.10
Language level:PHP 7.1

At present the following code will generate a message that the count() can be dropped

	public function push( $item )
	{
		$this->stack[ count($this->stack) ] = $item;
	}

However, the ->stack array maintains an array position, so if items are removed as follows:-

	public function pop( )
	{
		$count = count($this->stack);
		$context = $this->stack[ $count - 1 ];
		unset( $this->stack[ $count - 1 ] );

		return $context;
	}

Then the array pointer is left at the wrong position and the next push will leave a gap.

It may be worth adding a warning about this possibility as I'm not sure how it could be easily detected.

**Comment by kalessil** [comment]
You are correct (https://3v4l.org/ne3ku). I'll introduce a setting to disable the case reporting.

Meanwhile I can suggest 2 options:

- suppressing the warning
- refactoring pop to following (I personally strongly recommend following this one):
```php
```
public function pop( )
{
	return array_pop($this->stack);
}
```
```

**Comment by kalessil** [comment]
Added the setting.
