### ISSUE TITLE
if-else workflow: wrong auto-fix

### ISSUE THREAD

**Issue by voku** [kalessil/phpinspectionsea#1193]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | Bug                      |
| Plugin         | Php Inspections (EA Ultimate), v2.0.12 |
| Language level | PHP 7.0                        |

Code:
--

```php
                if (strpos('bar', $foo) === false) {
                    // more code here ... v1
                } else {
                    // more code here ... v2
                }
```

Current behaviour:
--

```php
                if (strpos('bar', $foo)) {
                    // more code here ... v2
                } else {
                    // more code here ... v1
                }
```

Expected behaviour
--
```php
                if (strpos('bar', $foo) !== false) {
                    // more code here ... v2
                } else {
                    // more code here ... v1
                }
```

Environment details
---
PhpStorm 2018.3.3
Build #PS-183.5153.36, built on January 9, 2019
Licensed to Portable UTF-8 /  
Subscription is active until April 5, 2019
For non-commercial open source development only.
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-141-generic

**Comment by kalessil** [comment]
Fixed!
