### ISSUE TITLE
Feature request: Comparing against quotes without type checking.

### ISSUE THREAD

**Issue by WiXSL** [kalessil/phpinspectionsea#1195]
| Issue type     | Feature request

It would be great an inspection to identify and remove equivalent evaluations when comparing against quotes without type checking.

Example:

```
if ([EXPRESION] == '' && [EXPRESION] == 0) {
}
if ([EXPRESION] == '' && [EXPRESION] == null) {
}
if ([EXPRESION] == '' && [EXPRESION] == false) {
}
if ([EXPRESION] == '' || [EXPRESION] == 0) {
}
if ([EXPRESION] == '' || [EXPRESION] == null) {
}
if ([EXPRESION] == '' || [EXPRESION] == false) {
}
//... etc ...

// All are the same as :

if ([EXPRESION] == '') {
}
```

**Comment by andreasschroth** [comment]
I strongly recommend using strict comparison, that means `===` instead of `==`.

**Comment by WiXSL** [comment]
Me too, but in large projects with legacy code is not an option to make such changes.

**Comment by kalessil** [comment]
Looks like a new pattern for suspicious binary expressions: always true/always false when second (any following) condition reached. Am I right?

**Comment by kalessil** [comment]
Implemented!
