### ISSUE TITLE
"not equal" vs "negation equals"

### ISSUE THREAD

**Issue by schlessera** [kalessil/phpinspectionsea#1197]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | Feature request                          |
| Plugin         | Php Inspections (EA Extended) or Php Inspections (EA Ultimate) |
| Language level | any                        |

Current behaviour (description/screenshot:)
--

I have noticed that my brain sometimes messes up "not equal" comparisons because of PHP operator precedence.

As an example, I often end up writing code like `if ( ! $object instanceof Interface ) {}`, which works just fine, as the `instanceof` takes precedence over the negation (`!`).

However, due to this automatism, I also sometimes end up writing code like `if ( ! $a === $b ) {}`, which does not produce the result I would expect. Here, the negation (`!`)  takes precedence over the comparison (`===`), and os instead of checking whether "$a does not equal $b", I actually check whether "not-$a equals $b" which is almost always the opposite result (but not even consistently so.

Expected behaviour
--

As I don't think comparing the negation of an operand with a non-negated operand, it would be helpful to get a warning about the `! $a === $b` construction, because the operator precedence makes this non-intuitive.

The suggested fix should be to use either `$a !== $b` or `( ! $a ) === $b` depending on what the intention was (probably the former).

**Comment by kalessil** [comment]
Implemented!
