### ISSUE TITLE
New value type (static) is not in annotated types.

### ISSUE THREAD

**Issue by icanhazstring** [kalessil/phpinspectionsea#1199]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended), 3.0.10 |
| Language level | PHP 7.1 |

This is was fixed before but is broken again.
These two issue faced the exact same problem:

https://github.com/kalessil/phpinspectionsea/issues/1092
https://github.com/kalessil/phpinspectionsea/issues/439

![image](https://user-images.githubusercontent.com/883543/53078747-33129b00-34f5-11e9-9dce-1e1288097261.png)

The interface description:
![image](https://user-images.githubusercontent.com/883543/53078803-4a518880-34f5-11e9-950d-fa41907c2483.png)

**Comment by kalessil** [comment]
Hm, which PhpStorm version is it?

**Comment by icanhazstring** [comment]
Running on IntelliJ IDEA Ultimate 2018.3.4.

Problems only happens on consecutive calls on the previous returned `static` type.

![image](https://user-images.githubusercontent.com/883543/53117970-5b79b400-354c-11e9-8f5e-314984f17297.png)

**Comment by kalessil** [comment]
Fixed!
