### ISSUE TITLE
"Cascading str_replace(...) calls", badly merged

### ISSUE THREAD

**Issue by puggan** [kalessil/phpinspectionsea#1200]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | EA Ultimate v2.0.12 |
| Language level | PHP 5.6 |

Current behaviour
--
![screenshot from 2019-02-20 11-17-53](https://user-images.githubusercontent.com/866668/53084537-53e0ed80-3501-11e9-9fe5-9f1c93e0dd70.png)

1. If you have 3 single-char replacement, following each other
2. You select the last and merge it with the one above.
3. You select the new last, and merge it with the one above.
4. The merge fails. (First char behind/outside array) (+ 2 different array types)

```php
<?php

    // before
    $s = 'ÅÄÖ';
    $s = str_replace('Å', 'å', $s);
    $s = str_replace('Ä', 'ä', $s);
    $s = str_replace('Ö', 'ö', $s);

    // after
    $s = 'ÅÄÖ';
    $s = str_replace([ , 'Ä', 'Ö' ]'Å', array( , 'ä', 'ö' )'å', $s);
```

Expected behaviour
--
```php
    // valid syntax like:
    $s = str_replace(['Å' , 'Ä', 'Ö'], ['å', 'ä', 'ö'], $s);
    // or without the array-shorthand
    $s = str_replace(array('Å' , 'Ä', 'Ö'), array('å', 'ä', 'ö'), $s);
```

Environment details
---
PhpStorm 2019.1 EAP
Build #PS-191.5532.18, built on February 13, 2019
PhpStorm EAP User
Expiration date: March 15, 2019
JRE: 1.8.0_202-release-1483-b4 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.0-13-generic

**Comment by kalessil** [comment]
So, I resolved the issue with mixing array syntax, but wasn't able to reproduce step `3`.

**Comment by puggan** [comment]
Maybe just was lag = phpstorm maybe didn't re-parse the new line before i executed the 2nd replacement.

Having multiple phpstrom, a couple of docker containers, and a lot of websites, some with some have javascript running, makes my relative fast computer go slow. :-)

I'l see if I can reproduce it after next reboot.

**Comment by kalessil** [comment]
:+1:

**Comment by puggan** [comment]
Still reproduceable, after reboot.

![screenshot from 2019-02-25 11-01-05](https://user-images.githubusercontent.com/866668/53329583-ad279300-38ec-11e9-8603-dc4af9595dc3.png)

Did some more testing:
* unicode or ascii didn't matter
* If the 2nd row is an array it fails
* Writing the code using another codestyle, made it work.
* Seams to be the whitespace in the beginging of the array thats the differens between working and not working. `["B","C"]` vs `[ "B","C"]`.

**Comment by kalessil** [comment]
Ok, next round then =)

**Comment by puggan** [comment]
Turning of this option, in the PHP-codestyle, made the original exemple of 3 str_replace, work.
![screenshot from 2019-02-25 11-44-48](https://user-images.githubusercontent.com/866668/53332099-c6cbd900-38f2-11e9-9287-b268940b48af.png)

**Comment by puggan** [comment]
Was this fixed in v2.0.13?

**Comment by kalessil** [comment]
@puggan: the changes have landed into 2.0.13, hopefully fixed. Can you confirm the fix worked?

**Comment by puggan** [comment]
Yes, can't reproduce the problem in 2.0.13

**Comment by kalessil** [comment]
Super, thank you for the great news!
