### ISSUE TITLE
[FP] Seems to be always true when reached. 2 strpos in if.

### ISSUE THREAD

**Issue by puggan** [kalessil/phpinspectionsea#1201]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | EA Ultimate v2.0.12 |
| Language level | PHP 5.6 |

Current behaviour
--
2nd strpos gives "Seems to be always true when reached."

![screenshot from 2019-02-20 11-52-11](https://user-images.githubusercontent.com/866668/53086770-074be100-3506-11e9-8752-e5413b40aaf7.png)

```php
<?php

    $a = 'https://google.com';
    if(strpos($a, '.net') > 0 || strpos($a, '.org') > 0) {
        echo $a;
    }
```

Expected behaviour
--
No warning

Environment details
---
PhpStorm 2019.1 EAP
Build #PS-191.5532.18, built on February 13, 2019
PhpStorm EAP User
Expiration date: March 15, 2019
JRE: 1.8.0_202-release-1483-b4 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.0-13-generic

**Comment by kalessil** [comment]
Duplicates #1173
