### ISSUE TITLE
[FP] Isset operations variables existence: array access on a loop

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1205]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 2.0.13 |

Current behaviour
--
For the following code:
```php
    while(true){
        if(!isset($a[1])){
            $a[1] = 50;
        }
    }
```

PHP EA Ultimate warn that "'$a' seems to be not defined in the scope". However, we are on a loop and it makes sense to check the existence of the variable to discriminate the first loop.

It works well with if(!isset($a)){ but it seems that the array access break the special case that was made for this.

**Comment by kalessil** [comment]
Declining, the `$a` is not defined in the scope. So either suppression either local variable introduction will do the trick.
