### ISSUE TITLE
Run inspection on entire folder

### ISSUE THREAD

**Issue by nhajiyani** [kalessil/phpinspectionsea#121]
Hello,
I tried running the shortcut for inspection with in PhpStorm on the entire folder or project using - Alt +Shtft + I which did not work, Thus I can currently run this tool only on 1 file at a time. This for a huge code base is very tedious. Let me know if this functionality is already supported or still needs to be built in?

Thanks.

**Comment by kalessil** [comment]
Hi @nhajiyani,

The shortcut was from PhpStorm itself, not working for me as well. 
You can also right-click the folder you want to be inspected and ~10th item will be 'Inspect code' (in PhpStorm).

**Comment by kalessil** [comment]
And more investigation: PhpStorm has no shortcuts for inspecting the complete project.

I'd advise creating a feature request in PhpStorm bug-tracker: https://youtrack.jetbrains.com/issues/WI
