### ISSUE TITLE
[FR] Foreach can be used: improved QF with array_keys

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1210]
Description :
--
I just came across something like this in an antique piece of code:
```php
    $array = ["a" => 1, "b" => 2,"c" => 3,"d" => 4];
    $array_keys = array_keys($array);
    $nb_elements = count($array_keys);
    for($i = 0; $i < $nb_elements; $i++){
        $key = $array_keys[$i];
        $value = $array[$key];

        echo "{$key} {$value}\n";
    }
```

This is just a really messed up foreach.

When I apply the "Foreach can probably be used" QF, I get:
```php
    $array = ["a" => 1, "b" => 2,"c" => 3,"d" => 4];
    $array_keys = array_keys($array);
    $nb_elements = count($array_keys); // triggers unused variable inspection
    foreach ($array_keys as $iValue) {
        $key = $iValue;
        $value = $array[$key];

        echo "{$key} {$value}\n";
    }
```
It is technically correct. But it could be so much better!

```php
    $array = ["a" => 1, "b" => 2,"c" => 3,"d" => 4];
    foreach ($array as $key => $value) {
        echo "{$key} {$value}\n";
    }
```

The inspection already dectect  $i < count($array), maybe it's possible to go a little further and detect the array_keys construct too?

**Comment by kalessil** [comment]
In our realities, we can eliminate: `$nb_elements = count($array_keys)`.
Also `$key` redundancy could be detected, but that's another inspection.

I'll check thee 2 things, but the rest is too complex for the current project state.

**Comment by orklah** [comment]
Cool!

**Comment by kalessil** [comment]
Done!

**Comment by kalessil** [comment]
Now, when starting from the original code fragment, we making 3 QF and getting to this (Ultimate):
```php
    $array = ["a" => 1, "b" => 2, "c" => 3, "d" => 4];
    foreach (array_keys($array) as $key) {
        $value = $array[$key];
        echo "{$key} {$value}\n";
    }
```

@orklah can you also trying to put the sample code in a method, will complains persist there as well?

**Comment by orklah** [comment]
> Now, when starting from the original code fragment, we making 3 QF and getting to this (Ultimate):
> 
> ```
>     $array = ["a" => 1, "b" => 2, "c" => 3, "d" => 4];
>     foreach (array_keys($array) as $key) {
>         $value = $array[$key];
>         echo "{$key} {$value}\n";
>     }
> ```
> 
> @orklah can you also try to put the original sample code in a method, will complains persist there as well?

Cool! It's way better!

Do you mean the "unused variable" inspection? Yes, there is the same warning in a method or in the global scope (depending on the settings of the inspection). I'm not sure I get the meaning of your question...

**Comment by kalessil** [comment]
Oh, I already added a new test case to cover the case, so nevermind =)
