### ISSUE TITLE
[FP] Declaration access can be weaker: overrided attribute

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1211]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         |  Php Inspections (EA Ultimate), 2.0.13|

Current behaviour
--

Start with the following code:
```php
<?php

class foo {

    protected $param = 'a';

    public function __get( $name ) {
        return $this->param;
    }


}

class bar extends foo{
    protected $param = 'b';
}

$bar = new bar();
var_dump($bar->param);
```

https://3v4l.org/rpTj0
It returns "b"

Apply the QF from "Declaration access can be weaker" inspection and make the attribute private

https://3v4l.org/dP44R
Now it returns "a"

**Comment by kalessil** [comment]
Fixed!

**Comment by orklah** [comment]
Nice!
