### ISSUE TITLE
`assertEquals()` deprecation warning seems to be incorrect

### ISSUE THREAD

**Issue by cjost1988** [kalessil/phpinspectionsea#1213]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) |
| Language level | PHP 7.2                        |

Question
--
Hi,

The extension is showing me that `$delta`, `$maxDepth` and `$canonicalize` arguments of `assertEquals()` will be deprecated from version 8 of PhpUnit, but I can't find any information about this deprecation in the `phpunit/phpunit` project.

Thank you for your time :)

**Comment by kalessil** [comment]
Hi @cjost1988, the depreciation has been announced here: https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-7.5.md

```log
The optional parameters $delta, $maxDepth, $canonicalize, and $ignoreCase of assertEquals() and assertNotEquals() are now deprecated. There is no behavioral change in this version of PHPUnit. Using these parameters will trigger a deprecation warning in PHPUnit 8 and in PHPUnit 9 these parameters will be removed.
```
