### ISSUE TITLE
FopenBinaryUnsafeUsageInspection no longer necessary?

### ISSUE THREAD

**Issue by ausi** [kalessil/phpinspectionsea#1214]
I stumbled on `FopenBinaryUnsafeUsageInspection` today and I’m not sure if the recommendation for using the `b` flag in `fopen()` is (still) necessary.

The [documentation for `fopen()`](http://php.net/manual/en/function.fopen.php#refsect1-function.fopen-changelog) states that *“As of PHP 4.3.2, the default mode is set to binary for all platforms that distinguish between binary and text mode.”*

Looking at the source of PHP this seems to be correct, see [main/streams/plain_wrapper.c:110-114](https://github.com/php/php-src/blob/php-7.3.2/main/streams/plain_wrapper.c#L110-L114) and <https://github.com/php/php-src/commit/fa342d2404a9c809d0a182d80798da2abd3a98f7>.

**Comment by kalessil** [comment]
Checked, you are right, but the b-flag usage is recommended by the official documentation (one of the notes). So I introduced a new setting ("Promote b-modifier (as per documentation)"), so we should be fine now.

**Comment by ausi** [comment]
Thank you!

I created a documentation bug in PHP for this issue: <https://bugs.php.net/bug.php?id=77781>

Should I notify this issue or create a new one if the PHP documentation gets changed?

**Comment by kalessil** [comment]
You are welcome =) Yes, please!
