### ISSUE TITLE
[FP?] replace empty with === null

### ISSUE THREAD

**Issue by puggan** [kalessil/phpinspectionsea#1217]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate) v2.0.11 |
| Language level | PHP 7.3 |

Current behaviour
--
`if(empty())` is marked as can be replaced with null, but a varaible of type `string|null` may also be null if it contains `""` or `"0"`.

![screenshot from 2019-03-01 17-05-05](https://user-images.githubusercontent.com/866668/53650352-a4182800-3c44-11e9-9ee5-739f27346f13.png)
https://3v4l.org/l2LGb

Expected behaviour
--
Don't know, but in the case above, a `if(!$foo->bar)` could be used instead.

But if the object is an decoded json, and the key may not exists, its often phpdoced as `string|null` as `string|undefined` is not valid.

Sorry for not having a clue on whats right this time, but wanted to report it as the current implemetation it felt wrong

**Comment by kalessil** [comment]
Seems this has been fixed already =)
