### ISSUE TITLE
if-return-return: new pattern

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#1218]
```php
        $local = ...;
        if ($local === ?) {
            return ?;
        }
        return $local;
```

**Comment by orklah** [comment]
For me, the case is already covered by Illusion of choice inspection:
![capture4](https://user-images.githubusercontent.com/9605520/53668791-31737080-3c75-11e9-8f2d-19780fc7366f.PNG)

**Comment by kalessil** [comment]
Right, closing then =)
