### ISSUE TITLE
"Fix all" in Laravel Blade files only fixing selected

### ISSUE THREAD

**Issue by dezio** [kalessil/phpinspectionsea#1220]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended), v3.0.11 |
| Language level |  PHP 7.3 (check project settings or composer.json) |
| Sub language | Laravel Blade |

**Current behaviour**
--
When using "Fix all unnecessary double quotes in file" via ALT+Enter menu in **Laravel Blade** files, it only fixes the selected item, instead of "all" in this file.

![image](https://user-images.githubusercontent.com/632803/53778491-3a767300-3efd-11e9-843c-fe3abfa7a504.png)
![image](https://user-images.githubusercontent.com/632803/53778397-da7fcc80-3efc-11e9-9a5c-cdfcc2bc3f8d.png)

**Expected behaviour**
--
Should also fix other "UnNecessaryDoubleQuotesInspection"-problems in the same file. For other auto-fixes, the problem also occurs. 

Environment details
---
Problem has been there since using the plugin and is not environment-based. Currently I'm on PhpStorm 2019.1 EAP
Build #PS-191.5849.26, built on February 27, 2019
PhpStorm EAP User
Expiration date: March 29, 2019
JRE: 1.8.0_202-release-1483-b31 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Workaround
--
Maybe this has something to do with the IDE itself, not iterating through all php-parts of this file. I just wanted to leave this here, as I was not able to find something about this specific way. Meanwhile I'm using the workaroung of selecting "Run inspection on" > "File" > _Select the group_ > Click "Replace with single quotes". This does the job.
![image](https://user-images.githubusercontent.com/632803/53778919-b7eeb300-3efe-11e9-8f3d-2fb4befb9b0d.png)

**Comment by rentalhost** [comment]
I think that it is related to IDE. From top of my mind, the language injection of blade treats each statement as a file (not needly it).

**Comment by kalessil** [comment]
Confirmed, that handled by IDE itself.
