### ISSUE TITLE
[FR] Override "Convert concatenation with sprintf call" to use single quotes

### ISSUE THREAD

**Issue by dezio** [kalessil/phpinspectionsea#1228]
Description (screenshot):
PhpStorm offers an autofix to change concatenated strings to sprintf calls. This then generates an sprintf call with double quotes. The PhpInspection addon then wants me to change the double quotes with single quotes. To make lifes easier, I'd like to have PhpInspection do the job by overriding the intention. This way you could directly put in single instead of double quotes.

The intention:
![image](https://user-images.githubusercontent.com/632803/54094727-46ea4800-43a3-11e9-9615-4401b6aac1e6.png)

---
Example:
![image](https://user-images.githubusercontent.com/632803/54094795-b102ed00-43a3-11e9-8f55-f5160a746e42.png)

**Comment by orklah** [comment]
Hi,

Did you try to open a ticket in PhpStorm first?

I think it will be easier to fix on their side

**Comment by kalessil** [comment]
Well, we are not focusing on intentions. I think this should be a feature request for the IDE team. Sorry.
