### ISSUE TITLE
Rule "Type casting can be used" is no longer valid. 

### ISSUE THREAD

**Issue by paranoiq** [kalessil/phpinspectionsea#1229]
rule "Type casting can be used" is no longer valid. 

functions intval, floatval, strval etc. are inlined in PHP7 and have no performance impact at all. even in PHP5.6 their performance impact is marginal. see https://3v4l.org/6aZ50

this rule should be either off by default or constrained to a PHP version

using function syntax instead of type cast may be useful for code readability (precedence) and this rule does not do a good job with its advice any more

**Comment by orklah** [comment]
It seems like in PHP 5.X it is still relevant, at least for some cases:
https://3v4l.org/F3qkl#v5632

On this version, (int) "0" is up to 3x faster.

But you're right, it is still micro optimizations on EOL versions of PHP.

On the other hand I kinda like this inspections, on our legacy code base, we have a mix of intval() and (int) for no reason and it brings uniformity. (It looks a lot like alias usage inspection which suggest replacing join() by implode() for example.)

**Comment by kalessil** [comment]
Ok. I'll relocate it into code style group and update messages.

**Comment by kalessil** [comment]
Done! I updated messages.
