### ISSUE TITLE
inspections folder

### ISSUE THREAD

**Issue by nospor** [kalessil/phpinspectionsea#1230]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) or Php Inspections (EA Ultimate), which version |
| Language level | e.g. PHP 7.2 (check project settings or composer.json)                        |

Question
--
Hi, how can I limit headless phpstorm inspections to given folder only eg src? Now it runs on all project. I was trying to set scope but it didnt help.

**Comment by funivan** [comment]
You can execute `phpstorm/bin/inspect.sh -d path/to/the/directory` 
Option `-d` stands for directory.

**Comment by nospor** [comment]
But to do it, I need to overwrite your enrtypoint. Maybe worth to think about some additional param for directory to not have to override the entrypoint?

**Comment by kalessil** [comment]
I'll check if this can be done: PhpStorm needs to index the whole project still

**Comment by nospor** [comment]
I/we can live with indexing all project. But would be really nice to inspect only given folder. Now I have milions of not related inspection errors because it checks all project and I am interested only in SRC folder

**Comment by kalessil** [comment]
Checked: no built-in settings. A possible workaround is in CI to partially copy .idea content (inspection profile) and launch inspection in that folder.

**Comment by nospor** [comment]
Ok, ta for checking
