### ISSUE TITLE
[FP] Foreach usage possible : writing in initial array

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1233]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         |  Php Inspections (EA Ultimate), 2.0.13 |

Current behaviour
--
For the following code, we suggest a wrong fix:
```php
    $array = ['a' => ['test' => 1], 'b' => ['test' => 2]];
    $count = count($array);
    for ($i = 0; $i < $count; $i++) {
        $array[$i]['test'] = 5;
    }
    var_dump($array);
```
The suggestion is:
```php
    $array = ['a' => ['test' => 1], 'b' => ['test' => 2]];
    $count = count($array);
    foreach ($array as $iValue) {
        $iValue['test'] = 5;
    }
    var_dump($array);
```
However, we can't change $array[$i]['test'] to $iValue['test'] when we write values in the array.

This cause a change of behaviour and the var_dump do not output the same value:
https://3v4l.org/oXcjJ

Interestingly, if the variable is $array[$i] instead of $array[$i]['test'], it is not replaced by $iValue.

This issue may have been caused by this issue: #1186 even if there was no write access in the examples.

Thanks!

**Comment by kalessil** [comment]
Fixed!
