### ISSUE TITLE
compact() highlight variable

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#1234]
Highlight undefined variables instead of `compact()` identifier.

**Current:**

![image](https://user-images.githubusercontent.com/421851/54154411-9de23280-4420-11e9-8c7a-85c6968bf70d.png)

**Expected:**

![image](https://user-images.githubusercontent.com/421851/54154481-bf431e80-4420-11e9-81ea-a2ecbea3fbd1.png)

**Comment by kalessil** [comment]
Oh, will fix this shortly!

**Comment by kalessil** [comment]
Fixed!
