### ISSUE TITLE
Duplicate inspection Callable name case mismatched in a call

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1235]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 2.0.13 |

Question
--
Is there a difference between the "Callable name case mismatched in a call" from PHP EA and "Case mismatch in method call or class usage" in the native PhpStorm inspections?

I think the two basically do the same thing. The PhpStorm one seem to be more complete as it checks class names too.

If there is no other features, I think we could drop this inspection.

**Comment by Stevehans** [comment]
quickfix on the EA one but I don't think there is on the native one.

**Comment by orklah** [comment]
I just tested, the QF exist on the native one, at least for a method call

**Comment by kalessil** [comment]
Yep, PhpStorm has a native one, which is disabled by default.

**Comment by kalessil** [comment]
I'll also drop our inspection since it duplicates the functionality.

**Comment by kalessil** [comment]
Done!
