### ISSUE TITLE
[FR] Unused value in foreach

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1237]
Description (screenshot):
--
Hi!

I discovered some case like this in our code:
```php
foreach($array as $key => $value) {
    //only using $key in here
}
//not using $value in here either
```
The developper needed the key's values but didn't need the actual content of the array.

(I thought I saw PhpStorm or PHP EA report $value as unused but now I can't reproduce it...)

The point is, we could suggest this fix:
```php
foreach(array_keys($array) as $key) {
    //only using $key in here
}
```

It would probably improve memory usage and CPU for big arrays but I didn't do benchmarks.

Thanks!

**Comment by orklah** [comment]
I think I'll close this issue. I tried to do some tests, and array_keys seem to perform a lot worse than just leaving the unused variable in the foreach...

It seems weird but it's worse for every recent PHP version on 3v4l...

**Comment by jdreesen** [comment]
That's because the array is traversed twice in your suggested fix. First the keys are extracted and then they are iterated over in a second run. This should be worse in both, CPU and memory.

**Comment by orklah** [comment]
Yep, probably. I thought the value assignment would be worse in comparison but clearly I was wrong :)
