### ISSUE TITLE
[FR] Foreach can be used: new pattern

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1238]
Description:
--
We could suggest replacing:
```php
while($value = array_shift($array)) { // also works with array_pop
    // not using $array here
}
//not using $array anymore
```
by this code:
```php
foreach($array as $value){
    // not using $array here
}
//not using $array anymore
```

For array_pop, it may be necessary to add an array_reverse to avoid changing the order of the loop

Thanks

**Comment by kalessil** [comment]
Invariants:
- `while($array && $value = array_shift($array)) {...}`
- `while(null != $value = array_shift($array)) {...}`

**Comment by kalessil** [comment]
Implemented!
