### ISSUE TITLE
[false-positive] "Single quotes handling is not specified"

### ISSUE THREAD

**Issue by voku** [kalessil/phpinspectionsea#1240]
### "htmlspecialchars()" -> use \ENT_NOQUOTES for single quotes handling

|  |                                                                        |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         |Php Inspections (EA Ultimate), v2.0.13 |
| Language level | PHP 7.0                         |

Current behaviour
--
"Single quotes handling is not specified, please use ENT_QUOTES or ENT_COMPAT as second argument."

Expected behaviour
--
No error about single quotes handling.

Environment details
---
PhpStorm 2018.3.5
Build #PS-183.5912.26, built on March 7, 2019
Licensed to Portable UTF-8 / Lars Moelleken
Subscription is active until February 28, 2020
For non-commercial open source development only.
JRE: 1.8.0_152-release-1343-b28 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-142-generic

**Comment by kalessil** [comment]
So, the original code was something like `htmlspecialchars($html, ENT_NOQUOTES)`?

**Comment by voku** [comment]
Yep, something like that. 😊

**Comment by kalessil** [comment]
Fixed!

**Comment by voku** [comment]
Thanks for the quick fix! 👍
