### ISSUE TITLE
[FP] Isset operations variables existence: extract & includes

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1241]
Description (screenshot):
--

For the following code:
```php
function a($params){
    extract($params);
    require('file.php');
    if(isset($foo)){

    }
}
```
PHP EA warns that $foo seems to not be defined in the scope. However, the use of extract or the require/include doesn't allow PHP EA to be aware of the variables in the scope.

I think adding a setting would be a good way to deal with this.

**Comment by kalessil** [comment]
Added a new setting: for the include/require case

**Comment by orklah** [comment]
Thanks!

The settings also handle the extract() case?

**Comment by kalessil** [comment]
Nope, only includes are respected now. It covers the code sample and annoys when extract is used.
