### ISSUE TITLE
[FP] One-time use variables: operations on new objects

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1245]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         |  Php Inspections (EA Ultimate), 2.0.13|
| Language level | PHP 5.3.X                   |

Current behaviour
--
For the following code:
```php
    $a = new RandomClass();
    echo $a->b;
```
PHP EA suggests:
```php
    echo (new RandomClass())->b;
```

But this syntax is not valid on PHP 5.3.X. It was introduced in PHP 5.4.

(Note: I don't know if you still want to support older versions of PHP. If you don't, this issue is not very critical as PhpStorm immediately tells you that this syntax is not valid with your current PHP version)

**Comment by kalessil** [comment]
Fixed!
