### ISSUE TITLE
Inspection warning 'Suspicious Binary Operator' misgiven with null coalesce

### ISSUE THREAD

**Issue by pdewouters** [kalessil/phpinspectionsea#1248]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), which version |
| Language level | e.g. PHP 7.2 (check project settings or composer.json)                        |

Current behaviour
--

<img width="691" alt="Screenshot 2019-03-19 at 10 15 15" src="https://user-images.githubusercontent.com/30460/54598521-91696580-4a30-11e9-907f-6b880b19a5d3.png">

Expected behaviour
--
I believe there should be no issue with this statement

Environment details
---

PhpStorm 2018.3.5
Build #PS-183.5912.26, built on March 7, 2019
Licensed to paul de wouters
Subscription is active until September 10, 2019
JRE: 1.8.0_152-release-1343-b28 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3

**Comment by kalessil** [comment]
The reporting is correct: https://3v4l.org/uDIEf, since the reported code fragment is the same as `isset((int)$options['...']) ? (int)$options['...']  :  0`
