### ISSUE TITLE
[FR] Encourage using local variables already defined

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1251]
Description (screenshot):
--
If a variable was already initialized with a method return, encourage using this variable instead of calling the method again.

Example
--
```php
class RandomClass{
    private $randomAttribute;
    public function getRandomAttribute(){
        return $this->randomAttribute;
    }
}

function scope(){
    $rc = new RandomClass();
    $ra = $rc->getRandomAttribute();
    if($ra !== null){
        echo $rc->getRandomAttribute(); // suggest replacing by echo $ra;
    }
}
```

We should exclude cases when the object implements Iterator.

We may want to add a setting to suggest replacing only call to methods beggining with "get" to avoid messing with working code, but I think this should be useful to deactivate this settings for some projects

Thanks!

**Comment by funivan** [comment]
function `getRandomAttribute` should be pure function and this is not so easy to detect.
```php
$rc = new RandomClass();
    $ra = $rc->getRandomAttribute();
    doSomething();
    if($ra !== null){
        echo $rc->getRandomAttribute(); // cant suggest
    }
```

**Comment by kalessil** [comment]
While the patter looks great, I can not deliver an inspection reliable enough, unfortunately.

**Comment by orklah** [comment]
Thanks for trying :)
