### ISSUE TITLE
[FR] Suspicious operations on empty array

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1254]
Description (screenshot):
--
Today, I found a code on our project who looked like that:

```php
function scope(){
    $errors = [];
    
    ...
    //the code populating $errors was since deleted
    
    if(count($errors)) {
        echo 'Errors encountered';
    }
    else {
        echo 'No error encountered';
    }
    
    foreach ($errors as $arr) {
        echo 'Error: '.$arr;
    }
    
}
```

I was surprised to see no inspections at all. There are some interesting things to report:
1. Functions working with populated arrays could be replaced instantly with QF:
count($errors) replaced by 0
array_search replaced by false
array_pop replaced by null
...
(I can try to do the complete list if you're interested)
This will then trigger additionnal simplification inspection like in my example, I will have a if(false) who will be deleted

2. foreach loops on empty arrays can be deleted

3. if($errors){} blocks can be deleted

Thanks!

**Comment by kalessil** [comment]
Thank you for sharing =) 

-QF will be a problem - too many cases have to be considered, but the loop case is implemented.

**Comment by orklah** [comment]
Thanks!
