### ISSUE TITLE
False positive: null-coalescing operator usage

### ISSUE THREAD

**Issue by thexpand** [kalessil/phpinspectionsea#1259]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) |
| Language level | PHP 7.2                        |

Current behaviour
--
![Screenshot from 2019-03-28 21-01-35](https://user-images.githubusercontent.com/14979167/55185756-b16df700-519d-11e9-8744-c8ffa585f051.png)

Expected behaviour
--
No warning

Environment details
---
PhpStorm 2019.1

**Comment by kalessil** [comment]
Fixed!
