### ISSUE TITLE
[FR] Inspection on rethrowing Exception

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1261]
Description (screenshot):
--
Hi!

I was surprised to see a lot of those in a project:
```php
try{
    //code
}
catch(Exception $e){
    throw $e;
}
```

This has absolutely no value and could be added to "Badly organized exception handling"

There must not be anything else in the catch other than the new throw, There has to be only one catch(or if there are more than one, everyone must rethrow the exception as is).

Note that on my example, I used "Exception" but this works for every class that extends Throwable (or Exception on older PHP Versions).

Thanks!

**Comment by kalessil** [comment]
Implemented!

**Comment by orklah** [comment]
cool!
