### ISSUE TITLE
array_walk: unnecessary callback closure

### ISSUE THREAD

**Issue by fruitl00p** [kalessil/phpinspectionsea#1262]
Sort of like #883 but for `array_walk`-calls:
i.e.
```php
array_walk($choices, static function (&$value) {
    $value = trim($value);
});
```
could actually be:
```php
$choices = array_map('trim', $choices)
``` 
right?
(although i understand this might be complicated to fix)

**Comment by kalessil** [comment]
Right =) It was an implementation bug in the inspection, fixed now.
