### ISSUE TITLE
[FP] 'ob_get_clean()' can be used instead

### ISSUE THREAD

**Issue by voku** [kalessil/phpinspectionsea#1263]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 2.0.14 |
| Language level | PHP 7.1                        |

Current behaviour
--
```
// start the output buffer
\ob_start();
\ob_implicit_flush(0);
require_once $foobar;
// get the contents of the output buffer
$content = \ob_get_contents();
\Safe\ob_end_clean();
```

... quick-fix generate this output ...

```
// start the output buffer
\ob_start();
\ob_implicit_flush(0);
require_once $foobar;
// get the contents of the output buffer
$content = \ob_get_clean();
```

... but now the behavior of the code has changed, because "\Safe\ob_end_clean()" will throw a Exception instead of returning false: https://github.com/thecodingmachine/safe/blob/master/generated/outcontrol.php#L25

Expected behaviour
--
Keep "\Safe\ob_end_clean()" usage.

Environment details
---
PhpStorm 2019.1
Build #PS-191.6183.95, built on March 27, 2019
For non-commercial open source development only.
JRE: 1.8.0_202-release-1483-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-142-generic

**Comment by kalessil** [comment]
Fixed!
