### ISSUE TITLE
Unused constructor dependency if property used within closure

### ISSUE THREAD

**Issue by Rarst** [kalessil/phpinspectionsea#1264]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 3.0.12.2 |
| Language level | PHP 7.3                        |

Current behaviour
--

The following code triggers "Property is only used in constructor, perhaps we are dealing with dead code here" on `$this->answer`:

```php
class Answer {

	private $answer = 42;

	public function __construct() {
		add_filter( 'answer', function () {
			return $this->answer;
		} );
	}
}
```

Expected behaviour
--

While technically this property is used "in" constructor, even more technically it is used in the _closure_ within constructor. Which can be passed outside or anything, and as such is not really contained within constructor definition.

Environment details
---
PhpStorm 2019.1
Build #PS-191.6183.95, built on March 27, 2019
JRE: 1.8.0_202-release-1483-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by kalessil** [comment]
Fixed!
