### ISSUE TITLE
'gmmktime(...)' / 'mktime(...)' usage inspection applied on 'use function mktime;' statement

### ISSUE THREAD

**Issue by SharkMachine** [kalessil/phpinspectionsea#1265]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended), v3.0.12.2 |
| Language level | PHP 7.2 |

Current behaviour
--
![image](https://user-images.githubusercontent.com/7488694/55332265-b5e82780-549d-11e9-85ee-45ddc429c593.png)

Expected behaviour
--
No warning shown for `use function mktime;`

Environment details
---
Ubuntu 18.04
PhpStorm 2019.1 (Build #PS-191.6183.95)
JRE: 1.8.0_202-release-1483-b39 amd64

**Comment by kalessil** [comment]
Fixed!
