### ISSUE TITLE
"Forgotten debug statements" inspection false positives with 'use function' statements

### ISSUE THREAD

**Issue by SharkMachine** [kalessil/phpinspectionsea#1271]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) |
| Language level | PHP 7.2 |

Current behaviour
--

The following happens with all "Forgotten debug statements" inspection functions.

![image](https://user-images.githubusercontent.com/7488694/55452791-d7522c00-55e1-11e9-80ba-35df54a5f03d.png)

![image](https://user-images.githubusercontent.com/7488694/55453167-79264880-55e3-11e9-8bcc-dba56bc98ef2.png)

Expected behaviour
--
No error as function is not called in `use function` statement.

Environment details
---
Ubuntu 18.04
PhpStorm 2019.1 (Build #PS-191.6183.95)
JRE: 1.8.0_202-release-1483-b39 amd64

**Comment by kalessil** [comment]
Fixed!
