### ISSUE TITLE
[FR] Not optimal QF for "explode misused"

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1276]
Description (screenshot):
--
For the following code, PHP EA suggest to replace with substr_count() + 1
```php
    $string_parts = explode("-", $string);

    if(count($string_parts ) > 1) {
        
    }
```
It will result in this code:
```php
    if(substr_count($string, "-") +1 > 1) {
```
Simplified to:
```php
    if(substr_count($string, "-") > 0) {
```
But for this particular case (count(explode()) > 1 or count(explode()) >= 2), I think strpos would be much more efficient and readable:
```php
    if(strpos($string, "-") !== false) {
```

Note: this works with count(explode()) > 0 or count(explode()) >= 1 too but it doesn't make much sense because explode will always return an array of one element (if you don't use the third parameter)

If this change is too specific to change this inspection, we could consider having a separate inspection to match "substr_count($string, "-") > 0" cases...

Thanks!

**Comment by kalessil** [comment]
Implemented!

**Comment by orklah** [comment]
Very quick! Thanks!
