### ISSUE TITLE
[FR] loop used as implode

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1281]
Description (screenshot):
--
While fixing "foreach could be used instead of for" warnings in my project, I spotted a lot of cases where a loop was used to perform an implode().

Here are the patterns I saw:
```php
<?php

    $array = ['a','b'];
    
    $res = '';
    for($i = 0, $iMax = count($array); $i < $iMax; $i++) {
        $res .= $array[$i];
        if($i < ($iMax - 1)) {
            $res .= '-';
        }
    }
    var_dump($res);
    
    $res = '';
    for($i = 0, $iMax = count($array); $i < $iMax; $i++) {
        if($i > 0) {
            $res .= '-';
        }
        $res .= $array[$i];
    }
    var_dump($res);

    $res = '';
    $iMax = count($array);
    foreach ($array as $i => $iValue) {
        $res .= $iValue;
        if($i < ($iMax - 1)) {
            $res .= '-';
        }
    }
    var_dump($res);
    
    $res = '';
    $iMax = count($array);
    foreach ($array as $i => $iValue) {
        if($i > 0) {
            $res .= '-';
        }
        $res .= $iValue;
    }
    var_dump($res);
```

I suspect this may be hard to translate into an inspection, so don't hesitate to close this issue if it is complicated.

Note: to be able to suggest the change, there must be no operation on $iValue or $array[$i].
Ideally, if the $res variable is already defined out of the loop, it would be best to keep the .= operator, in case there is already some content in the variable.

Thanks!

**Comment by kalessil** [comment]
@orklah: yep, it's quite complicated. So closing and will invest time into #1172 instead.
