### ISSUE TITLE
Namespace doesn't matches with folder

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#1284]
**Description:**
--
For namespaced files, should be great if it tells if the current namespace matches with the path. I think that it is available on Idea for Java.

```php
// Workdir: /myproject
// Sources dir: {workdir}/src (based on composer.json)
// Path: /myproject/src/Application/Services/ApplicationService.php

namespace Project\Application\Models;
//                            ^^^^^^
// Namespace doesn't matches with current path.
// Autofix proposal: fix to Project\Application\Services.
```

It should consider the `composer.json` section `autoload.psr-4`:

```json
{
    "autoload": {
        "psr-4": {
            "Project\\": "src/"
        }
    }
}
```

**Comment by kalessil** [comment]
Fixed!

**Comment by orklah** [comment]
Hi @kalessil ,

I'm afrais this will lead to a big pile of errors for projects who don't follow PSR-4. 

Our project for instance use composer to import some libraries but the project in itself use an old autoloader and don't match namespaces with directories.
Will we be able to disable this part of the inspection?

Thanks

**Comment by kalessil** [comment]
We should be fine: this pattern picked up only if `/src/` is in the file path. If it pops up, we'll see reports =)

**Comment by orklah** [comment]
Okay, I'll make some feedback if I have the issue :)

**Comment by SpyroTEQ** [comment]
I don't see any mention of the `/src/` restriction in doc https://github.com/kalessil/phpinspectionsea/blob/master/docs/probable-bugs.md#class-autoloading-correctness 

Is that why I only get the basic "Class path doesn't match project structure" in IntelliJ when file in `/project/sources/php(<marked as source directory)/variispace/endpoint/atom/mendeleiev/` has namespace `variispace\endpoint\atom\mendeleie` (missing "v")?

If so, why restricting on "/src/" instead of, maybe, allowing to select a pattern/select a list of base directory? Or restricting to directories marked as source root (as I did in my personnal plugin, see code below; you're free to reuse):

```java
		return new PhpElementVisitor() {

			@Override
			public void visitPhpNamespace(final PhpNamespace namespace) {
				super.visitPhpNamespace(namespace);
				final PsiElement namespaceToken = namespace.getFirstChild();
				if (namespaceToken == null) {
					// Shouldn't happen
					return;
				}

				final PhpNamespaceReference ref = ReinomUtils.getFirstNextOfClass(namespaceToken, PhpNamespaceReference.class);
				if (ref == null) {
					// Not a namespace?!
					return;
				}

				// Check the namespace and suggest the proper one
				final PsiElement next = ref.getNextSibling();
				if (!ReinomUtils.isOfType(next, PhpTokenTypes.IDENTIFIER)) {
					// Incomplete namespace
					return;
				}
				final String fullNamespace = ref.getFullName() + next.getText();

				String expectedNamespace = "";
				PsiDirectory cdir;
				for (
						cdir = namespace.getContainingFile().getContainingDirectory();
						cdir != null && !JavaDirectoryService.getInstance().isSourceRoot(cdir);
						cdir = cdir.getParent()) {
					expectedNamespace = cdir.getVirtualFile().getName()
							+ ("".equals(expectedNamespace) ? "" : "\\")
							+ expectedNamespace;
				}

				// cdir == null means we couldn't get the source root
				if (cdir != null && !fullNamespace.equals(expectedNamespace)) {
					ReinomInspection.problem(
							holder,
							namespaceToken,
							"Wrong PHP class namespace",
							ReinomLocalQuickFix.fixByReplacingWithText(expectedNamespace, ref, next));
				}
			}
		};
```

**Comment by kalessil** [comment]
@SpyroTEQ: extended checks only file name, while ultimate also checks complete path with respect to composer manifest autoloading. I'd prefer not to share ultimates' codebase.

**Comment by SpyroTEQ** [comment]
Ahah, alright, I won't make you disclose your paid version then : ) It's indeed a neat feature <3
