### ISSUE TITLE
[Bug] inspection "Unnecessary call arguments specification" less effective on ultimate

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1286]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) and Php Inspections (EA Ultimate), last version |

Hi,

I waited a long time to create this issue because I couldn't replicate it on an other project, but I still have the issue at work:

When I launch the inspect code command on the whole project, the inspection "Unnecessary call arguments specification" report a lot less cases on ultimate.

It happens every time at work, but I can't take much time to investigate on my employer time. I tried to replicate the issue at home but I couldn't manage to reproduce it.

On EA, when I launch the inspection, I have around 950 case in the whole project and when I launch it on Ulti, I don't have any (I'm pretty much sure at one time, there was around 30 cases reported, but I resolved them since...)

When at work, I use the last EAP on EA and the last stable version (2018.3.5) for Ulti.

I don't know what could trigger the issue since I can't reproduce it...

I tried:
- Launching the inspect code on the whole profile (I made sure the inspection was included in the profile)
- Launching the Run inspection by name command with only this inspection (It doesn't find any case)
- Creating a debug file with a usage of strpos with a default param and it doesn't flag it on ulti

If you have ideas of things I could test to help, tell me, I'll try to experiment a little.

**Comment by kalessil** [comment]
Synchronized codebases between plugins.
