### ISSUE TITLE
[FR] Short syntax for applied operation: new pattern

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1289]
Description (screenshot):
--
The following code show a pattern where the inspection is not optimal:
```php
function scope(){
    $a = 'a';
    $a = $a . 'b'; // warning : "Can be safely refactored as '$a .= 'b''."
    $a = $a . 'b' . 'c'; // no warning
}
```

PHP EA could suggest : "Can be safely refactored as '$a .= 'b' . 'c''."
It seems that as long as there are more than one concatenation, the inspection stop suggesting the change.

Thanks!

**Comment by kalessil** [comment]
Implemented!

**Comment by orklah** [comment]
Cool!
