### ISSUE TITLE
Random API migration, inspection false positives with 'use function' statements

### ISSUE THREAD

**Issue by SharkMachine** [kalessil/phpinspectionsea#1297]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended), v3.0.13 |
| Language level | e.g. PHP 7.2  |

Current behaviour
--
![image](https://user-images.githubusercontent.com/7488694/56267828-9c2f1d00-60f8-11e9-8132-6cc3700fd5c5.png)

Expected behaviour
--
No warning as function is not called in `use function` statement.

Environment details
---
Ubuntu 18.04
PhpStorm 2019.1 (Build #PS-191.6183.95)
JRE: 1.8.0_202-release-1483-b39 amd64

**Comment by kalessil** [comment]
Fixed!
