### ISSUE TITLE
[new, probable bugs] detect usage of two or more alphabets in class, NS, etc. names

### ISSUE THREAD

**Issue by amoseev** [kalessil/phpinspectionsea#13]
Hello!

I really enjoyed work with plugin and I advice it for my colleagues, thank a lot!

Recently I accept a mistake. I created a class with name contained Cyrillic and Latin characters.
Can you add functionality with inspection for that case (I suppose for namespaces, classes and method names)? 
Or suggest different solution for that case? 

Thanks

**Comment by kalessil** [comment]
Thank you @amoseev )

I slightly modified the title, this will help me prioritising issues. 
Would you please share what happened afterwards (autoloading issues, or something else)?

**Comment by amoseev** [comment]
My task successfully passed all test and checking two QA engineers.
The mistake was disclosed only after deploy on production server.

**Comment by kalessil** [comment]
I see, updated the title. Thank you for details @amoseev .

**Comment by funivan** [comment]
> Can you add functionality with inspection for that case (I suppose for namespaces, classes and method names)? 

Latest version of the phpstorm PhpStorm 2016.3 EAP (Build #PS-163.6957.13, ) have this feature.
Inspection group called **Naming conventions** Just add your regexp to the class. 

http://imagizer.imageshack.com/img923/3392/hZfvgv.png

**Comment by kalessil** [comment]
Cool, thanks for a hint @funivan .

**Comment by amoseev** [comment]
@funivan thanks!
