### ISSUE TITLE
Null coalescing operator can be used quick-fix broken with ternary operator

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#1300]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | U2.0.15 |

Current behaviour
--
It's a bit difficult to summarize the problem in the title, but basically it will happen in two distinct cases:

**Case 1 - Original Source:**

```php
$a = $b ? 1 : 2;

if (isset ($c)) {
    $a = $c;
}
```

**Case 1 - Quick-fixed (wrong):**

```php
$a = $c ?? $b ? 1 : 2;
```

PHP will understand the previous code as:

```php
$a = ($c ?? $b) ? 1 : 2;
```

**Case 1 - Quick-fixed (fixed):**

Note that the ternary operator was wrapped by `(` and `)`. 

```php
$a = $c ?? ($b ? 1 : 2);
```

Same will happen for assignments:

**Case 2 - Original Source:**

```php
isset($a)
    ? $a
    : $this->fixed = $b;
```

**Case 2 - Quick-fixed (wrong):**

```php
$a ?? $this->fixed = $b;
```

PHP will understand the previous code as:

```php
($a ?? $this->fixed) = $b;
```

**Case 2 - Quick-fixed (fixed):**

Note that the assignment was wrapped by `(` and `)`. Maybe it should be applied to all assignment types (`*=`, `/=`, so on).

```php
$a ?? ($this->fixed = $b);
```

**Comment by kalessil** [comment]
Ouch, will fix this shortly.

**Comment by kalessil** [comment]
Fied!
