### ISSUE TITLE
Null pointer exceptions prevention on constructor

### ISSUE THREAD

**Issue by 5lava** [kalessil/phpinspectionsea#1304]
Currently, `NullPointerExceptionInspection` targets only methods (as per [doc](https://github.com/kalessil/phpinspectionsea/blob/master/docs/probable-bugs.md#null-pointer-exceptions-prevention)). Is it planned to make it also work on constructors?

Thank you.

**Comment by kalessil** [comment]
Hi @5lava, should not be a problem. Do you use Extended or Ultimate plugin?

**Comment by 5lava** [comment]
Extended.

P.S. I wasn’t even aware of existence of Ultimate version. Gotta check it out!

**Comment by kalessil** [comment]
Ok, try it out and let me know in which version the proposed change should land to (and i need to re-check if ultimate not yet doing it already - difficult to remember all details)

**Comment by kalessil** [comment]
Checked, Ultimate checks constructors as well.
