### ISSUE TITLE
False positive: This type casting is not necessary

### ISSUE THREAD

**Issue by garak** [kalessil/phpinspectionsea#1308]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) v3.0.13 |
| Language level | PHP 7.2  |

Current behaviour
--
![Schermata da 2019-04-24 12-19-54](https://user-images.githubusercontent.com/179866/56652394-8d61e080-668b-11e9-8b47-52baa1c0d388.png)

Expected behaviour
--

Inspection should not report such case, because the value could be a float (for example, when `$csv[6]` contains a value like `2.077`)

Environment details
---

PhpStorm 2019.1.1
Build #PS-191.6707.66, built on April 17, 2019
Licensed to ******@gmail.com
Subscription is active until August 14, 2019
JRE: 1.8.0_202-release-1483-b44 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.0-18-generic

**Comment by kalessil** [comment]
Super, thank you!

**Comment by kalessil** [comment]
Fixed!
