### ISSUE TITLE
Improve SSL Server spoofing

### ISSUE THREAD

**Issue by lurkie** [kalessil/phpinspectionsea#1311]
Description (screenshot):
The check "CURL: SSL Server spoofing (SSL MITM Spoofing Attack)" could be extended to check for assignment of a single array value as well.

Example

The following does currently not trigger an inspection report:
```
$options = [];
$options[CURLOPT_SSL_VERIFYHOST] = false;
```
But this does:

```
$options = [
	CURLOPT_SSL_VERIFYHOST => false,
];
```
It would be nice if the first example would trigger an inspection as well.

**Comment by kalessil** [comment]
Will do!

**Comment by kalessil** [comment]
@lurkie: which plugin do you use (Extended or Ultimate)?

**Comment by lurkie** [comment]
I'm using the Extended plugin

**Comment by kalessil** [comment]
Ok, then will add new patter there.

**Comment by kalessil** [comment]
Implemented!

**Comment by lurkie** [comment]
Great, thanks!
