### ISSUE TITLE
auto-fix for use "array_unshift"

### ISSUE THREAD

**Issue by voku** [kalessil/phpinspectionsea#1314]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 2.0.15 |
| Language level | PHP 7.0                        |

Current behaviour
--
Auto-fix will generate non valid php code.

orig:
```php
$args = \func_get_args();
$args = \array_merge([&$this->array], $args);
\array_unshift(...$args);
```

result:
```php
$args = \func_get_args();
array_unshift($args, &$this->array);
\array_unshift(...$args);
```

Expected behaviour?
--

orig:
```php
$args = \func_get_args();
$args = \array_merge([&$this->array], $args);
\array_unshift(...$args);
```

result:
```php
$args = \func_get_args();
\array_unshift(...[&$this->array], ...$args);
```

example: https://github.com/voku/Arrayy/commit/0f70f19d2d3593112511bb73635eeac0dbdd9e51

Environment details
---
PhpStorm 2019.1.1
Build #PS-191.6707.66, built on April 17, 2019
For non-commercial open source development only.
JRE: 1.8.0_202-release-1483-b44 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-145-generic

**Comment by kalessil** [comment]
Fixed as a false-postive
