### ISSUE TITLE
preg_quote "unknown modifier" warning by error (again)

### ISSUE THREAD

**Issue by njandreasson** [kalessil/phpinspectionsea#1318]
I put a [comment](https://github.com/kalessil/phpinspectionsea/issues/113#issuecomment-487835423) in closed issue #113 as it seems like this issue has crept back again in newer versions. I just double-checked in current version 3.0.1 and it's still an issue.

**Comment by rentalhost** [comment]
Confirmed with test case:

```php
preg_quote('..c', '/');
//         ^^^^^ [ Unknow modifier 'c'. ]
```

Seems related with (as reported by @njandreasson at https://github.com/kalessil/phpinspectionsea/issues/113#issuecomment-487835423) that was added back again.

https://github.com/kalessil/phpinspectionsea/blob/c114ef367226085bb2a169a8a5c3f804f0d31d1a/src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/regularExpressions/NotOptimalRegularExpressionsInspector.java#L51

But I think that the solution is just replace:

https://github.com/kalessil/phpinspectionsea/blob/c114ef367226085bb2a169a8a5c3f804f0d31d1a/src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/regularExpressions/apiUsage/FunctionCallCheckStrategy.java#L27-L28

By:

```java
if (functionName.equals("preg_quote")) {
  if (arguments.length == 1) {
    holder.registerProblem(reference, messageQuote);
  }
}
```

**Comment by kalessil** [comment]
Fixed (that's a new case)!
