### ISSUE TITLE
Handle intersection types with parentheses

### ISSUE THREAD

**Issue by leofeyer** [kalessil/phpinspectionsea#1321]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin | EA Extended v3.0.13 |
| Language level | PHP 7.3 |

Please add support for intersection types with parentheses, so the plugin supports `@param (Foo&MockObject)|null` in addition to `@param Foo&MockObject`.

 * `Foo&MockObject`: the argument is an object of both class `Foo` and class `MockObject`
 * `(Foo&MockObject)|null`: the argument is an object of both class `Foo` and class `MockObject` or `null`

As explained by @ondrejmirtes in https://github.com/phpstan/phpstan/issues/1877, the parentheses are required to disambiguate the annotation. However, neither PhpStorm itself nor the EA Extended plugin understand the syntax:

<img width="736" src="https://user-images.githubusercontent.com/1192057/57382575-7fdd4800-71ad-11e9-8af7-45200ae383f9.png">

See https://youtrack.jetbrains.com/issue/WI-45275 for the PhpStorm bug report.

**Comment by kalessil** [comment]
Silly question, before I do investogation: will the issue remain with https://plugins.jetbrains.com/plugin/9674-phpunit-enhancement plugin installed?

**Comment by leofeyer** [comment]
I am pretty sure the issue will remain.

**Comment by kalessil** [comment]
Ok, I'll check then. Most probably we have to wait for PhpStorm ticket to happen (as we heavily using the type resolver from the IDE).

**Comment by leofeyer** [comment]
I think so, too.

**Comment by kalessil** [comment]
Checked, I'll enhance type-resolving on our end for mocking support. I also can disable the inspection in test context but will keep t as plan "B".

**Comment by kalessil** [comment]
Fixed (test-context gets skipped)!

**Comment by leofeyer** [comment]
Thank you @kalessil.
