### ISSUE TITLE
False positive warning: roave/security-advisories suggestion in composer.json even if already contains sensiolabs/security-checker

### ISSUE THREAD

**Issue by florianajir** [kalessil/phpinspectionsea#1323]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) v3.0.13  |
| Language level | PHP 7.1                      |

Current behaviour
--

Throw a warning in composer.json edition, suggesting to add roave/security-advisories in require-dev even if sensiolabs/security-checker is required (duplicate purpose)

![image](https://user-images.githubusercontent.com/3715903/57514256-5d177480-7310-11e9-97eb-ca29d534de53.png)

Expected behaviour
--
If sensiolabs/security-checker is required in composer.json, do not throw warning about missing roave/security-advisories (same purpose)

resources:
+ https://github.com/Roave/SecurityAdvisories#sources
+ https://github.com/FriendsOfPHP/security-advisories#checking-for-vulnerabilities
+ https://security.symfony.com/

Environment details
---
PhpStorm 2019.1

**Comment by kalessil** [comment]
Fixed!
