### ISSUE TITLE
FP: roave/security-advisories when require-dev section is missing

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#1324]
See https://github.com/kalessil/phpinspectionsea/issues/867

**Comment by kalessil** [comment]
Fixed!

**Comment by ThomasLandauer** [comment]
I don't know if this is a regression, or maybe I misunderstood what you fixed here.
I have version 5.1.0 and I'm getting:
> [EA] Please add roave/ security-advisories:dev-latest into require-dev as a firewall for vulnerable components.

at "require", even if I have this in my "require":
```json
"roave/security-advisories": "dev-latest",
```
