### ISSUE TITLE
implode reports first parameter as not compatible with declaration

### ISSUE THREAD

**Issue by Stevehans** [kalessil/phpinspectionsea#1326]
| fp for implode        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended), 3.0.13                                                      |
| Language level | PHP 7.1                                                                                                |

$a = implode( ".", $arr);

returns parameter "." type is not compatible with declaration.

--

Should obviously be quite happy with this as a parameter.
--

Environment details
---

**Comment by kalessil** [comment]
Thank you for reporting @Stevehans. The message doesn't look like any of our inspections. When you suppressing the complain, which inspection being referenced after `@noinspection`?

**Comment by Stevehans** [comment]
And indeed it's not, sorry, I'll report it on the jetbrains tracker!

PhpParamsInspection
