### ISSUE TITLE
Run from CLI (and e.g. inside Vim)

### ISSUE THREAD

**Issue by olleharstedt** [kalessil/phpinspectionsea#1327]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) or Php Inspections (EA Ultimate), which version |
| Language level | e.g. PHP 7.2 (check project settings or composer.json)                        |

Question
--

Can this program be run from command-line?

**Comment by Stevehans** [comment]
No idea about vim but phpstorm can integrate with jenkins etc for CI so that's your starting point.

**Comment by kalessil** [comment]
Hi @olleharstedt, PhpStorm has the capability of running from the command line (with inspections from us). You might want to check the docker-related resources in our repository.

**Comment by olleharstedt** [comment]
Well, the point was to use it without buying PHPStorm. :)

**Comment by kalessil** [comment]
Understood =) We are heavily using PhpStorm APIs under the hood, so PhpStorm is needed.
