### ISSUE TITLE
Unnecessary closures and value by reference

### ISSUE THREAD

**Issue by Jakovitz** [kalessil/phpinspectionsea#1328]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) |
| Language level | PHP 7.3                        |

I saw this using array_walk. The inspector suggests to replace the callback
```php
function (&$value) {
    $value = trim($value);
}
```
with `'trim'`, but since trim doesn't alter the value, it will break the code.

**Comment by kalessil** [comment]
Confirmed, thank you for reporting @Jakovitz !

**Comment by kalessil** [comment]
Fixed!
