### ISSUE TITLE
if-else workflow: wrong with !empty()

### ISSUE THREAD

**Issue by voku** [kalessil/phpinspectionsea#1332]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 3.0.1 |
| Language level |PHP 7.0                       |

Example Code:
--
```php
        if (!empty($headerEntry->tooltip)) {
            $title = FormHelpers::getToolTipText(
                $headerEntry->name,
                $headerEntry->tooltip
            );
        } else {
            $title = $headerEntry->name;
        }
```

Current behaviour
--
```php
        if (empty($headerEntry->tooltip)) {
			$title = $headerEntry->name;
        } else {
            $title = FormHelpers::getToolTipText(
                $headerEntry->name,
                $headerEntry->tooltip
            );
        }
```

Expected behaviour
--
I think we can keep !empty because it's !false === true

Environment details
---
PhpStorm 2019.1.2
Build #PS-191.7141.52, built on May 8, 2019
JRE: 1.8.0_202-release-1483-b49 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-148-generic

**Comment by kalessil** [comment]
Agree, will make adjustments.

**Comment by kalessil** [comment]
Fixed!

**Comment by voku** [comment]
Thanks for the quick fix.
