### ISSUE TITLE
Null pointer exceptions prevention: if - elseif

### ISSUE THREAD

**Issue by voku** [kalessil/phpinspectionsea#1334]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 3.0.1 |
| Language level | PHP 7.0                         |

Current behaviour
--
```
if ($lall->foo) { // <- complains about "$lall"
    //
} elseif ($lall->bar) { // <- complains about "$lall"
	//
}
```

```
if ($lall && $lall->foo) {
    //
} elseif ($lall->bar) {
	//
}
```

Expected behaviour
--
```
if ($lall && $lall->foo) {
    //
} elseif ($lall->bar) { // <- complains about "$lall"
	//
}
```

Environment details
---
PhpStorm 2019.1.2
Build #PS-191.7141.52, built on May 8, 2019
JRE: 1.8.0_202-release-1483-b49 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-148-generic

**Comment by kalessil** [comment]
The second complaint seems to be relevant: https://3v4l.org/8EF4D. Probably the if-construct can be wrapped with `if ($lall !== null) { ... }`
