### ISSUE TITLE
Deprecated class should not nag about missing @ deprecated for __constructor

### ISSUE THREAD

**Issue by ScreamingDev** [kalessil/phpinspectionsea#1336]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         |  Php Inspections (EA Ultimate), 2.0.15 |
| Language level | %                        |

Current behaviour
--

```
/**
 * @ deprecated 
 */
class Foo {
  _construct() {
    trigger_error(..., E_USER_DEPRECATED);
  }
}
```

This tells me to add "@ deprecated" as doc comment to the constructor. While it is already used on the whole class.

Expected behaviour
--

In my opinion this shouldn't nag about the constructor or at least have it's own option in phpStorm so that we can disable it.

**Comment by kalessil** [comment]
Correct, will fix.

**Comment by kalessil** [comment]
Fixed!
