### ISSUE TITLE
[FR] Disable PHP shorttag

### ISSUE THREAD

**Issue by fruitl00p** [kalessil/phpinspectionsea#1337]
Description: I'd like an inspection to disable the PHP shorttag (`<?`)
--

By requiring all code to disallow `<?`-opening tag (but keeping `<?php` and `<?=`) we can force everything to be more compliant. I know this seems like a no-brainer and i've voted for the [PHPStorm issue](https://youtrack.jetbrains.com/issue/WI-2059) on it, but as they aren't as quick, i thought of mentioning it here.

Thanks!

**Comment by funivan** [comment]
Can you check `Short open tag usage`  this is standard PhpStorm inspection

http://i.imgur.com/sXU4dGS.png

**Comment by fruitl00p** [comment]
@funivan i was always wondering where that was as it was already mentioned that it was included but appearantly i was looking in the wrong place! :)

Thanks, will close this request then! :+1:
