### ISSUE TITLE
docs/architecture.md : please proof English grammar/typos

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#134]
@tomzx : would you review the file or perhaps complete docs set please (it's not so big currently)?

**Comment by tomzx** [comment]
Please see #135.

**Comment by kalessil** [comment]
The doc is replacement for inspections descriptions: [examples](https://github.com/kalessil/phpinspectionsea/search?utf8=%E2%9C%93&q=blob%2Fmaster%2Fdocs%2Farchitecture.md&type=Code)

Pro is that it possible to maintain documentation without making additional releases.
Cons is that people expecting this to present in IDE itself, but embedded markup there is very limited.

**Comment by funivan** [comment]
@kalessil I thinks some short info about inspection should be placed in the Inspection description. To view it directly from the IDE. But if there are more information about inspection then add link to the github =)

**Comment by kalessil** [comment]
@funivan : tried, the embedded PS's markup is very limited - looks ugly, poor fonts and code highlighting and etc.

**Comment by kalessil** [comment]
@tomzx : thank you for your PR!

**Comment by kalessil** [comment]
@tomzx : I need some support, again... How bad is what's written here: https://www.indiegogo.com/projects/php-inspections-ea-extended-a-code-analyzer-security/x/16148880#/ ?

**Comment by tomzx** [comment]
@kalessil Sorry about the late response. Here's my quick pass over the document: https://gist.github.com/tomzx/bfd84f0848272c43b9ee2efb7a20a36f.
