### ISSUE TITLE
False-Positive: Non-optimal regular expression with regex meta-character \b

### ISSUE THREAD

**Issue by njgray** [kalessil/phpinspectionsea#1341]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type | Bug/False-Positive |
| Plugin         | PHP Inspections EA Extended v3.0.13 |
| Language level | PHP 7.0.33 |

---  

Current behavior
--
The Performance/Non-optimal regular expression inspection suggests a change
from: `preg_split('/\b/', $string)`
to: `explode("\b", $string)`

`explode()` doesn't recognize the `"\b"` regex meta-character

This might be related to the bug/fix https://github.com/kalessil/phpinspectionsea/issues/1066

Expected behavior
--
I don't know if there is a way to convert this to a single explode expression in all cases.

I noticed that `preg_split('/\W/', $string)` does not give this same suggestion, so the intention may be to convert instances of the original example to `explode(' ', $string)`

Environment details
---
PhpStorm 2019.1.3
Build #PS-191.7479.51, built on June 18, 2019
JRE: 1.8.0_202-release-1483-b53 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-150-generic

**Comment by kalessil** [comment]
Confirmed, I'll take care of fixing this.

**Comment by kalessil** [comment]
Fixed!
