### ISSUE TITLE
[FR] Unnecessary type casting: new pattern

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1344]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate) last version |
| Language level | PHP 7.2                    |

Current behaviour
--

For the following lines:
```php
    $a = (float)0.0;
    $a = (float)1.0;
    $a = (float)-1.0;
```

PHP EA only warn about unnecessary casting on the first and second line. It seems the fact that there is a negative sign avoid triggering the inspection

Thanks

**Comment by kalessil** [comment]
Fixed!
