### ISSUE TITLE
Yoda flag/switch appears to be missing

### ISSUE THREAD

**Issue by rbairwell** [kalessil/phpinspectionsea#1346]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         |  Php Inspections (EA Ultimate) 3.0.1 |
| Language level | PHP 7.2                      |
| PHPStorm Version | PhpStorm 2019.2 EAP PS-192.5281.35 |
| Operating System | Windows 10 |

Current behaviour
--

There appears to be no way to set the preferred yoda/regular style usage preference (i.e. whether to use yoda or classical).

<img width="942" alt="phpein_yoda" src="https://user-images.githubusercontent.com/775269/60253782-a32a9680-98c4-11e9-966e-ff7f21c19783.png">

(I've checked under the inspection and under "Other Settings->" where there is no option for the plugin)

The problem is it's causing all my yoda-statements now to be highlighted in the inspector :(

Expected behaviour
--
Either a link in the Inspections list or an option under "Other settings" (as per https://github.com/kalessil/phpinspectionsea/issues/963 )

Environment details
---
PhpStorm 2019.2 EAP
Build #PS-192.5281.35, built on June 21, 2019
PhpStorm EAP User
Expiration date: July 21, 2019
Runtime version: 11.0.3+12-b304.2 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 12
Registry: run.processes.with.pty=TRUE, ide.tooltip.initialDelay=577
Non-Bundled Plugins: CMD Support, Key Promoter X, PHPUnit code coverage, com.godwin.json.parser, com.perl5, com.dmarcotte.handlebars, NEON support, com.kalessil.phpStorm.phpInspectionsUltimate, com.pulyaevskiy.phpstorm.phpdi, de.espend.idea.php.annotation, izhangzhihao.rainbow.brackets, fr.adrienbrault.idea.symfony2plugin, org.psliwa.idea.composer, ru.adelf.idea.dotenv

**Comment by orklah** [comment]
If I'm not mistaken, it was moved with the last update of Ultimate.

It is now a panel (like project, structure etc...). For me, the panel was added on the right with a pink icon and the name "PHP Inspections"

**Comment by kalessil** [comment]
@rbairwell, as @orklah mentioned, the setting management was re-designed with the latest ultimate update and setting now are available on a side panel: 
![image](https://user-images.githubusercontent.com/1577185/60283194-e60e5d80-9908-11e9-99eb-72f6c85a0774.png)

Settings are project-specific, and without need to get thru IDE navigation labyrinth =)
