### ISSUE TITLE
Cannot suppress PropertyCanBeStaticInspection

### ISSUE THREAD

**Issue by andreasschroth** [kalessil/phpinspectionsea#1349]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Issue type     | Cannot Suppress                          |
| Plugin         | Php Inspections (EA Ultimate), 3.0.1 |
| Language level | PHP 7.3                        |

Current behaviour:
---

Here is some example code:

```php
<?php declare(strict_types = 1);

final class Test
{
    protected $messageTemplates = [
        'foo1' => 'bar1',
        'foo2' => 'bar2',
        'foo3' => 'bar3',
    ];
}
```

It triggers the warning "Property could be static". That's okay. But I want to suppress the warning. Unfortunately, this doesn't work:

```php
<?php declare(strict_types = 1);

final class Test
{
    /** @noinspection PropertyCanBeStaticInspection */
    protected $messageTemplates = [
        'foo1' => 'bar1',
        'foo2' => 'bar2',
        'foo3' => 'bar3',
    ];
}
```

Suggested behaviour:
---

I'd expect / want the second example to work.

Suppression on a file-level basis is working, but unfortunately leads to PHPCS code-style issues.

Here the working example:

```php
<?php /** @noinspection PropertyCanBeStaticInspection */
declare(strict_types = 1);

final class Test
{
    protected $messageTemplates = [
        'foo1' => 'bar1',
        'foo2' => 'bar2',
        'foo3' => 'bar3',
    ];
}
```

**Comment by kalessil** [comment]
My bad, the inspection targets the whole class instead of fields, will fix!

**Comment by kalessil** [comment]
Btw, why are you suppressing? Do we miss any settings there?

**Comment by kalessil** [comment]
Fixed!

**Comment by andreasschroth** [comment]
@kalessil Thanks a lot for fixing! Sorry, didn't see your question before. To answer it: This class inherits from a library class as parent and we need to overwrite that protected property here (it's intended usage... kind of crappy, but yep).
