### ISSUE TITLE
FP: Unneccessary emptiness check

### ISSUE THREAD

**Issue by tlamy** [kalessil/phpinspectionsea#1351]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         |Php Inspections (EA Ultimate) v3.0.1 |
| Language level | PHP 7.1                        |

Current behaviour
![image](https://user-images.githubusercontent.com/1841537/60419404-78eb1880-9be5-11e9-947e-03d72fd6730c.png)
![image](https://user-images.githubusercontent.com/1841537/60419605-f9aa1480-9be5-11e9-930c-2d2f45fe01e3.png)

--

Expected behaviour
--
As the count($array) is followed by array_pop($array), it should be clear we only want some value from $array, even if it's null.

Environment details
---
PhpStorm 2019.2 EAP
Build #PS-192.5438.24, built on June 27, 2019
Runtime version: 11.0.3+12-b304.2 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 1750M
Cores: 4
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: com.ppolivka.gitlabprojects, mobi.hsz.idea.gitignore, BashSupport, com.kalessil.phpStorm.phpInspectionsUltimate, de.espend.idea.php.annotation, izhangzhihao.rainbow.brackets, fr.adrienbrault.idea.symfony2plugin, org.zalando.intellij.swagger, ru.adelf.idea.dotenv

**Comment by kalessil** [comment]
thank you for reporting @tlamy, I'll take care of fixing this.

**Comment by kalessil** [comment]
Oh, it actually suggests using 'if ($users && is_array($users))'. This can be disabled by turning "Suggest simplifications" setting off. I'll also update the message to less confusing one.

**Comment by kalessil** [comment]
Fixed!
