### ISSUE TITLE
[FR] hash_equals comparing same variables

### ISSUE THREAD

**Issue by Furgas** [kalessil/phpinspectionsea#1353]
Please consider adding inspection for `hash_equals` usage with the same variables:

```php
return hash_equals($signature, $signature);
```

Yeah, I somewhat ended up with such code and didn't notice.

**Comment by rentalhost** [comment]
Maybe it could be expanded to other compare functions like `strcmp()`.

**Comment by kalessil** [comment]
For myself: strcmp, strncmp, strcasecmp, strncasecmp, substr_compare, strnatcmp, strnatcasecmp, hash_equals, openssl_verify

**Comment by kalessil** [comment]
Implemented!
