### ISSUE TITLE
Invalid Warning - Class autoloading might be broken

### ISSUE THREAD

**Issue by laurin1** [kalessil/phpinspectionsea#1358]
I can't see how this warning could be accurate. All of my classes in this project have the same warning.

Php Inspections (EA Ultimate) 3.0.1
PHP 7.3

Namespace\Class:
**\ExpressBooksellers\SearchClient**

File Path:
**src/lib/expressbooksellers/SearchClient.php**

composer.json:
		**"psr-4": {
			"ExpressBooksellers\\": "lib/expressbooksellers",
			"PRIDE\\"             : "lib/pride"
		}**

![image](https://user-images.githubusercontent.com/75857/60737033-d8676200-9f1e-11e9-9236-d44457b3a0b2.png)

Environment details
PhpStorm 2019.2 EAP
Build #PS-192.5587.32, built on July 4, 2019
PhpStorm EAP User
Expiration date: August 3, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: run.processes.with.pty=true, ide.editor.tabs.open.at.the.end=true
Non-Bundled Plugins: intellij-shellscript, com.kalessil.phpStorm.phpInspectionsUltimate, JSTestDriver Plugin

**Comment by rentalhost** [comment]
The folder name should be `ExpressBooksellers`, else *unix* system could not handle your file via autoloader once that it is case-sensitive.

**Comment by laurin1** [comment]
3 things:

1. I thought that might be the issue, so I tried that, the same warning
2. I am testing this project on a Unix system (Docker), and it's working fine
3. It's my understanding that the composer.json is the reason #2 works and why this should not be a warning, as this tells the autoloader creation processes to that use the lowercase one:

"ExpressBooksellers\": "lib/expressbooksellers",

**Comment by rentalhost** [comment]
You are right about case-sensivity in that case. As composer defines the namespace capitalized and points to lowercased, so all will works fine.

Could you please create a very small package that this warning could be triggered? So I can test on my side and check how to fix or to confirm that it is a false-positive.

**Comment by laurin1** [comment]
Not sure what all you need, but here.

[phpinspectionsea_1358.zip](https://github.com/kalessil/phpinspectionsea/files/3363699/phpinspectionsea_1358.zip)

**Comment by rentalhost** [comment]
@laurin1 thanks, it will happen.

Seems that the composer instructions are not being considered.

I have reduced the test case, so I could identify two things:

1. It will be fixed if folder is cased same as namespace;
2. It will be fixed if no intermediary folder exists between project root and the namespace root;

[phpinspectionsea_1358_reduced.zip](https://github.com/kalessil/phpinspectionsea/files/3363744/phpinspectionsea_1358_reduced.zip)

**Comment by kalessil** [comment]
Looks like we have to look up composer.json. Please follow #1330 for the bug-fix.

**Comment by kalessil** [comment]
Fixed!
