### ISSUE TITLE
[FN] Suspicious binary operations - resolve constant values

### ISSUE THREAD

**Issue by laurin1** [kalessil/phpinspectionsea#1359]
Seems to me that this should be generating a warning.

Php Inspections (EA Ultimate) 3.0.1
PHP 7.3

This generates a warning:

![image](https://user-images.githubusercontent.com/75857/60756312-a9ee9300-9fc1-11e9-93a2-22b0ee67b1a2.png)

But if I replaced "DELETEDROW" with a class constant, no warning:

![image](https://user-images.githubusercontent.com/75857/60756315-b246ce00-9fc1-11e9-8d5e-60f05d30e8cb.png)

![image](https://user-images.githubusercontent.com/75857/60756317-b96ddc00-9fc1-11e9-81cc-474e90f47a50.png)

Environment details
PhpStorm 2019.2 EAP
Build #PS-192.5587.32, built on July 4, 2019
PhpStorm EAP User
Expiration date: August 3, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: run.processes.with.pty=true, ide.editor.tabs.open.at.the.end=true
Non-Bundled Plugins: intellij-shellscript, com.kalessil.phpStorm.phpInspectionsUltimate, JSTestDriver Plugin

**Comment by kalessil** [comment]
Yep, constants are not getting analyzed, will add the missing support in the next release.

**Comment by kalessil** [comment]
Fixed!
