### ISSUE TITLE
A pilot webinar at 1st March 2017, 8pm-8:30pm CET

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#136]
Legenda:
```
- Getting started with the plugin (can be skipped/shortened);
- Recommended tweaks (isset, empty, exceptios handling and other settings overview);
- Project inspections (grouping, filtering) and best-practice workflows for resolving;
```

- Where: https://hangouts.google.com/call/qw6btk4gt5hvdnrg4gnnwhk2iye (live stream, 10 people max);

- Language: English;

- How to join/follow status updates: comment +1 in the ticket to be up to date with status updates;

**Comment by rentalhost** [comment]
To follow this topic, just click on "Subscribe" on right side of this screen.

**Comment by funivan** [comment]
+1

**Comment by davidmpaz** [comment]
+1

**Comment by metasoftware** [comment]
+1

**Comment by veewee** [comment]
+1

**Comment by kalessil** [comment]
Status update: the webinar is taking place as planned. The access link is coming soon.

**Comment by kalessil** [comment]
Here we go with a Hangout Meeting URL: https://hangouts.google.com/call/qw6btk4gt5hvdnrg4gnnwhk2iye

Hear you soon, guys!

**Comment by kalessil** [comment]
Follow-ups:
- QF-es (covered by current CF campaign);
- Documenting inspections + auto-generating inspections lists with description files content (easy to pick);
- @funivan to push on Vlad for dev-docs and onboarding process ;)
- Articles about unknown options;

**Comment by kalessil** [comment]
@rentalhost @davidmpaz : it's pity that you couldn't join. Any chance to have a chat with you all together/1-to-1 this week?

**Comment by rentalhost** [comment]
@kalessil Oh, my sorry! I just did not pay attention to the time differences. 8PM CET is 4PM for me (and this time I am not available today). Sorry! I can chat with you this week. But I do not talk english natively here and my english is a lot scratched. hehe But I can try!

**Comment by davidmpaz** [comment]
@kalessil unfortunatelly I was not able to attend! Sorry about that. Today or tomorrow we can chat. I will PM you.
