### ISSUE TITLE
One-time use variables - Not Working

### ISSUE THREAD

**Issue by laurin1** [kalessil/phpinspectionsea#1362]
Php Inspections (EA Ultimate) - 3.0.1
PHP 7.3.7 x64 (Windows)

When I first installed Php Inspections (EA Extended), I know it highlighted a number of these specific instances, but now these are no longer flagged:

![image](https://user-images.githubusercontent.com/75857/60923037-a843fa00-a263-11e9-9c8a-fdda4ca74807.png)

![image](https://user-images.githubusercontent.com/75857/60922804-3075cf80-a263-11e9-86aa-8d3ea37e9f9d.png)

PhpStorm 2019.2 EAP
Build #PS-192.5587.32, built on July 4, 2019
PhpStorm EAP User
Expiration date: August 3, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: run.processes.with.pty=true, ide.editor.tabs.open.at.the.end=true
Non-Bundled Plugins: intellij-shellscript, com.kalessil.phpStorm.phpInspectionsUltimate, JSTestDriver Plugin

**Comment by laurin1** [comment]
Ok, this works on my home machine. 

![image](https://user-images.githubusercontent.com/75857/60925134-74b79e80-a268-11e9-9199-4ad70eb4e32a.png)

Apparently, the license is only good for one machine? I was not aware of that or would not have purchased it, as that takes the cost for me from $100 to $300 per year.

**Comment by kalessil** [comment]
Hi @laurin1, answered via e-mail. I also started to worry if this is due to new PhpStorm version.
