### ISSUE TITLE
Wrong short notation applied for string concatenation 

### ISSUE THREAD

**Issue by mattiabasone** [kalessil/phpinspectionsea#1364]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) v3.0.14 |
| Language level | PHP 7.3                        |

Current behaviour
--
Short notation will swap concatenated variables:

![Schermata 2019-07-12 alle 17 20 22](https://user-images.githubusercontent.com/3951536/61139763-4afdb200-a4ca-11e9-969a-cc5fe455c601.png)
![Schermata 2019-07-12 alle 17 20 38](https://user-images.githubusercontent.com/3951536/61139771-4e913900-a4ca-11e9-89b2-ff76d8edff6a.png)

Expected behaviour
--

```php
$query .= $order.' limit '.$results_per_page.' offset '.$offset;
```

Environment details
---

PhpStorm 2019.1.3
Build #PS-191.7479.51, built on June 18, 2019
JRE: 1.8.0_202-release-1483-b53 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5

**Comment by orklah** [comment]
Hi!

This was fixed here:
https://github.com/kalessil/phpinspectionsea/issues/1343

The fix will be in the next release

**Comment by mattiabasone** [comment]
whoops, sorry!
Thank you :)

**Comment by kalessil** [comment]
Thank you @orklah for cross-linking =)

Duplicates #1343 (the bug-fix has been released already).
