### ISSUE TITLE
argument unpacking can be used breaks code with associative arrays

### ISSUE THREAD

**Issue by Grapestain** [kalessil/phpinspectionsea#1365]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) v3.0.14 |
| Language level | PHP 7.0                        |

Current behaviour
--
When 'argument unpacking can be used' automatic fix is applied, it generates invalid code, for associative arrays. Consider this example:
`call_user_func_array( 'array_merge', $my_array);`
will become:
`array_merge(...$my_array );`
However the `...` argument unpacking operator only works for non-associative arrays. When `$my_array` uses string keys, the replacement code causes:
`FATAL ERROR Uncaught Error: Cannot unpack array with string keys`.

Expected behaviour
--
One of these:
- The inspection should warn about the "fix" potentially breaking code.
- The inspection should rather use this replacement: `array_merge(...array_values($my_array))`, as array_values turns the associative array into a non-associative.
- Offer two different fixes (if possible) and let the user choose, based on their knowledge if the subject array is associative or not

Environment details
---
PhpStorm 2019.1.3
Build #PS-191.7479.51, built on June 18, 2019

**Comment by kalessil** [comment]
Fixed (updated the message)!

**Comment by Grapestain** [comment]
Great, thanks! However i guess `fo unpacking` was supposed to be `for unpacking`.

**Comment by kalessil** [comment]
Right, updated!
