### ISSUE TITLE
FP: New value type (bool) is not in annotated types.

### ISSUE THREAD

**Issue by voku** [kalessil/phpinspectionsea#1368]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 3.0.1 |
| Language level | PHP 7.3                     |

Current behaviour (https://github.com/voku/portable-utf8/blob/master/src/voku/helper/UTF8.php)
--
```php
        $fromEncodingDetected = false;
        if (
            $autodetectFromEncoding === true
            ||
            !$fromEncoding
        ) {
            $fromEncodingDetected = self::str_detect_encoding($str); // will return "false" || "string"
        }

        if ($fromEncodingDetected !== false) {
            $fromEncoding = $fromEncodingDetected;
        } elseif ($autodetectFromEncoding === true) {
            // fallback for the "autodetect"-mode
            return self::to_utf8($str);
        }
```

![Bildschirmfoto vom 2019-07-18 21-06-06](https://user-images.githubusercontent.com/264695/61484819-f82b6b00-a99f-11e9-86d7-547501f088c0.png)

---

minimal example:
```php
function lall(string $string): string
{
    /** @var string|false $falseOrString */
    $falseOrString = false;

    if ($falseOrString !== false) {
        $string = $falseOrString; // WARNING: New value type (bool) is not in annotated types.
    }
    
    return $string;
}
```

Expected behaviour
--
no warning, because I checked for "!== false" before I used the variable

Environment details
---
PhpStorm 2019.1.3
Build #PS-191.7479.51, built on June 18, 2019
JRE: 1.8.0_202-release-1483-b53 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-154-generic

**Comment by kalessil** [comment]
The issue pops up periodically: https://github.com/kalessil/phpinspectionsea/issues/987#issuecomment-407996316, unfortunately I can not provide any solution on my end.
