### ISSUE TITLE
"Cascading 'str_replace(...)' calls" gives wrong suggestion

### ISSUE THREAD

**Issue by anbuc** [kalessil/phpinspectionsea#1369]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) v3.0.14.1 |
| Language level | 7.1 |

Current behaviour
--
Given is a construct like this
```php
$string = '.-.';
// Replace "-" with "_" and "." with nothing
$result = str_replace(['-', '.'], ['_'], $string);
```
The plugin suggests that the second parameter "Can be replaced with the string from the array", implying it would be equivalent.
But doing so would change the result, as now both elements would be replaced with the same replacement, instead of just the first one.
From the documentation of `str_replace`: 
>  If **replace** has fewer values than **search**, then an empty string is used for the rest of replacement values. If **search** is an array and **replace** is a string, then this replacement string is used for every value of **search**.

Expected behaviour
--
Don't suggest anything

Environment details
---
PhpStorm 2019.1.3
Build #PS-191.7479.51, built on June 18, 2019
JRE: 1.8.0_202-release-1483-b53 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by kalessil** [comment]
Fixed!
