### ISSUE TITLE
Check dynamic method calls from array

### ISSUE THREAD

**Issue by lurkie** [kalessil/phpinspectionsea#137]
I encountered the following case while being in the midst of an upgrade project:
```
<?php
class demo {
	public function myMethod() {
		echo 'test';
	}
}
$methods = ['name' => 'myMethod'];
$obj = new demo();
$obj->$methods['name']();
```

**Output**:
PHP 5.4: test
PHP 7.0: PHP Notice:  Array to string conversion in test.php on line 9

The fix is to use curly brackets on the last line: `$obj->{$methods['name']}();`. Can this be made into an inspection to save others time?

**Comment by kalessil** [comment]
Thank you for the suggession @lurkie, it seems that PhpStorm team already working on preventing this:

- https://youtrack.jetbrains.com/issue/WI-27451
- similar issues: https://youtrack.jetbrains.com/issues/WI?q=uniform

A technical note: this related to the PHP parser from them, hopefully the'll release fixes soon.

**Comment by lurkie** [comment]
OK. Did not know that (and did not check).

If this is handled by PHPStorm, this issue can be closed I guess. Thanks!

**Comment by kalessil** [comment]
You are welcome @lurkie
