### ISSUE TITLE
mkdir race condition inspection: wrong auto-fix for === false

### ISSUE THREAD

**Issue by Dorbah** [kalessil/phpinspectionsea#1370]
Subject | Details
-- | --
Issue type | Bug
Plugin | Php Inspections (EA Ultimate), v3.0.14.1
Language level | PHP 7.0

**Code:**
```
if (!is_dir($dirPath)) {
	if (mkdir($dirPath, 0777, true) === false) {
		self::showMsg('error', "Error creating directory '$dirPath'", true);
		return false;
	}
}
```

**Current behaviour:**
```
if (!is_dir($dirPath)) {
	if (mkdir($dirPath, 0777, true) || is_dir($dirPath)) {
		self::showMsg('error', "Error creating directory '$dirPath'", true);
		return false;
	}
}
```

**Expected behaviour:**
```
if (!is_dir($dirPath)) {
	if (!mkdir($dirPath, 0777, true) && !is_dir($dirPath)) {
		self::showMsg('error', "Error creating directory '$dirPath'", true);
		return false;
	}
}
```

**Environment details:**
PhpStorm 2019.1.1
Build #PS-191.6707.66, built on April 17, 2019
JRE: 1.8.0_202-release-1483-b44 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by kalessil** [comment]
Looks like a bug, thank you for reporting @Dorbah

**Comment by kalessil** [comment]
Fixed!
