### ISSUE TITLE
Bug ForeachSource on multiple method definitions

### ISSUE THREAD

**Issue by funivan** [kalessil/phpinspectionsea#1371]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 3.0.1 |
| Language level | e.g. PHP 7.1                        |

Current behaviour
--
```php
<?php
declare(strict_types=1);
interface UserInterface{
    public function name(): string;
}
class User implements UserInterface {
    public function name(): string { return ''; }
}
class Office {
    /** @return $this */
    public function filter():self { return $this; }
    /** @return UserInterface[]|Generator */
    public function users(): Generator { yield new User(); }
}
/** @method User[] users() */
class CurrentOffice extends Office{}
$office = (new CurrentOffice())->filter();
foreach ($office->users() as $u1) { // <-- bug: expressions type was not recognized
    echo $u1->name();
}
$users = (new CurrentOffice())->filter()->users();
foreach ($users as $u2) { // <-- all works fine
    echo $u2->name();
}
```
IntelliJ IDEA 2019.2 (Ultimate Edition)
Build #IU-192.5728.74, built on July 18, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-54-generic

**Comment by kalessil** [comment]
Wow, IDE resolved '->users()' into 2 symbols, quite unexpected. Seems I have to override this types resolving as well... Will take some time.

**Comment by kalessil** [comment]
Fixed!
