### ISSUE TITLE
(string) parent would express the intention here better

### ISSUE THREAD

**Issue by y2keeper** [kalessil/phpinspectionsea#1373]
Thanks for this amazing plugin, really love it! 

That said, here is a tiny issue I noticed:

| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended), 3.0.14.1 |
| Language level | PHP 7.3           |

Current behaviour
--
The following bit of code in a class method...

`return parent::__toString();`

...results in the inspection message below:

> `(string) parent` would express the intention here better

However, implementing this change results in a PHP warning:

> Warning: Use of undefined constant parent - assumed 'parent' (this will throw an Error in a future version of PHP)

Expected behaviour
--
No  inspection message for `parent::__toString()`

Environment details
---
PhpStorm 2019.2
Build #PS-192.5728.108, built on July 24, 2019
Licensed to ***
Subscription is active until July 23, 2020
Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: BashSupport, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, org.psliwa.idea.composer, ru.adelf.idea.dotenv

**Comment by kalessil** [comment]
Fixed! PS: you are welcome =)
