### ISSUE TITLE
False positive: "Unnecessary type casting" with strstr()

### ISSUE THREAD

**Issue by mattsches** [kalessil/phpinspectionsea#1374]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate) |
| Language level | PHP 7.3                        |

Current behaviour
--
Example: https://3v4l.org/DaZAX
The plugin gives a code style warning "Unnecessary type casting" when I cast `$result` as `string` because it assumes that `strstr()` always returns a string. This is not the case, cp. the [docs](https://www.php.net/manual/en/function.strstr.php)

> Returns the portion of string, or FALSE if needle is not found. 

Expected behaviour
--
The plugin should not detect this as a code style warning when casting the result of `strstr` as string.

Environment details
---
PhpStorm 2019.2
Build #PS-192.5728.108, built on July 24, 2019

**Comment by orklah** [comment]
Hi!

The return types are provided by PHPStorm. 

This was fixed a month ago on the stubs repo:
https://github.com/JetBrains/phpstorm-stubs/blame/0eb16807e8406e775ef602974b104454fc7ffb5c/standard/standard_1.php#L311

However, I don't know how the release are done by PHPStorm (The issue is still on the recent 2019.2 release by PHPStorm)

**Comment by andreasschroth** [comment]
@orklah Correct. The PhpStorm replied on Twitter that they plan to merge the new stubs into a future 2019.2.x release. Thus it should be available for everyone soon.

**Comment by orklah** [comment]
Thanks for the info!

**Comment by kalessil** [comment]
I also added override for the function signature, so the issues goes for outdated PhpStorm instances as well.
