### ISSUE TITLE
The VariableFunctionsUsageInspection auto-fix is incorrect with argument unpacking

### ISSUE THREAD

**Issue by melkamar** [kalessil/phpinspectionsea#1376]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended), 3.0.14.1 |
| Language level | PHP 7.3 |

Current behaviour
--
- Write code such as

```
\call_user_func($factoryMethodFullName, ...$constructorArguments); 
```

where the arguments use the unpack operator. 

- PhpStorm will underline the statement and offer an automatic fix
- Apply the fix

The expected refactoring would yield:
```
$factoryMethodFullName(...$constructorArguments);
```

But instead the array unpacking operator is removed, which changes the semantics of the code. The actual refactoring result is

```
$factoryMethodFullName($constructorArguments);
```

Environment details
---

PhpStorm 2019.2
Build #PS-192.5728.108, built on July 24, 2019
Licensed to Martin Melka
Subscription is active until September 24, 2019
Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 2400M
Cores: 12
Registry: projectView.hide.dot.idea=false, run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: String Manipulation, YAML/Ansible support, com.intellij.ideolog, com.ppolivka.gitlabprojects, com.tobszarny.activetabhighlighter.plugin.id, name.kropp.intellij.makefile, NEON support, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.php.toolbox, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, ru.adelf.idea.dotenv, uk.co.ben-gibson.remote.repository.mapper, zielu.gittoolbox

**Comment by kalessil** [comment]
Fixed!
