### ISSUE TITLE
Exclude all third-party components (e.g. vendor folder)

### ISSUE THREAD

**Issue by Allkoman** [kalessil/phpinspectionsea#1379]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) or Php Inspections (EA Ultimate), which version |
| Language level | e.g. PHP 7.2 (check project settings or composer.json)                        |

Question
--
when I coding in my project ,I can see Inspections info, but in all third-party components (e.g. vendor folder) I can not see, can you help me with that? I want to modify files in vendor with inspections info please

**Comment by orklah** [comment]
Hi,

I'm pretty sure it's the default behaviour for excluded folders in native PHPStorm.

You should be able to reinclude those folders in File > Settings > Directories.

**Comment by andreasschroth** [comment]
I don't think editing files in the vendor folder directly is a good idea at all. You know that whenever you install the packages on another machine or update the packages, all your changes will be gone?

Fork the package and build an own version of it, if no other way is possible.

**Comment by kalessil** [comment]
As folks mentioned, that's standard IDE behaviour. Perhaps you can PhpStorm folks for more details, but I can not remember if it's possible to enable inspection in vendor directories (should be possible).
