### ISSUE TITLE
Typehint return absent from a vendor interface, however plugin suggesting my app library method signature use a type hint return

### ISSUE THREAD

**Issue by Kalyse** [kalessil/phpinspectionsea#1387]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) |
| Language level | 7.2                       |

Current behaviour
--

Summary of the issue. When implementing an interface from a vendor class, if that vendor interface does not use a typehint return, the plugin on my own method will suggest I use one. 

I have no control over the method signature on a vendor class/interface, and the suggestion auto adds one, but then creates an incompatible method signature in PHP and fatal error.

![Selection_148](https://user-images.githubusercontent.com/199760/63418786-94abb780-c3fb-11e9-8fe6-af0511355c65.png)

Expected behaviour
--

The expect behaviour would be to NOT suggest using a typehint return due to the interface from a vendor library package not using a type hint return.

**Comment by jdreesen** [comment]
It is okay to add **return** types in your implementations. This does not violate the contract (see https://3v4l.org/q62h3).

Adding **parameter** types would result in an incompatible signature, though (https://3v4l.org/RSFie).

**Comment by kalessil** [comment]
@Kalyse, as @jdreesen pointed out, adding the return type normally causes no problems. Can you elaborate on "but then creates an incompatible method signature in PHP and fatal error", perhaps a simplified code fragment of the problematic code?

**Comment by Kalyse** [comment]
Thank you both, and you are both totally correct. Apologies, I believe I
was getting param hinting confused. There is no issue here, and I've
hopefully solidified my understanding of interface restrictions on type
hinting now.
Please close.

**Comment by jdreesen** [comment]
> Adding **parameter** types would result in an incompatible signature, though ([3v4l.org/RSFie](https://3v4l.org/RSFie)).

Note, that [**removing** parameter types](https://www.php.net/manual/de/migration72.new-features.php#migration72.new-features.param-type-widening) is **allowed** since PHP 7.2!  (https://3v4l.org/DB2Da)

And with PHP 7.4 you'll be able to choose less specific parameter types or more specific return types instead of just removing/adding them: https://wiki.php.net/rfc/covariant-returns-and-contravariant-parameters
