### ISSUE TITLE
FP: auto-fix "?? null"

### ISSUE THREAD

**Issue by voku** [kalessil/phpinspectionsea#1388]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 3.0.3 |
| Language level | PHP 7.0                         |

code:
```php
    /**
     * @param mixed $str
     *
     * @return bool
     */
    public static function to_boolean($str): bool
    {
        // init
        $str = (string) $str;

        if ($str === '') {
            return false;
        }

        // Info: http://php.net/manual/en/filter.filters.validate.php
        $map = [
            'true'  => true,
            '1'     => true,
            'on'    => true,
            'yes'   => true,
            'false' => false,
            '0'     => false,
            'off'   => false,
            'no'    => false,
        ];

        if (isset($map[$str])) {
            return $map[$str];
        }

        $key = \strtolower($str);
        if (isset($map[$key])) {
            return $map[$key];
        }

        if (\is_numeric($str)) {
            return ((float) $str + 0) > 0;
        }

        return (bool) \trim($str);
    }
```

Current behaviour
--
```php
        return $map[$key] ?? null;
```

Expected behaviour
--
do not use "?? null" here

Environment details
---
PhpStorm 2019.2.1 RC
Build #PS-192.6262.47, built on August 16, 2019
Licensed to Portable UTF-8 / Lars Moelleken
Subscription is active until February 28, 2020
For non-commercial open source development only.
Runtime version: 11.0.3+12-b304.39 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-157-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 5120M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.tooltip.initialDelay=885, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: Key Promoter X, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, net.vektah.codeglance, NEON support, com.kalessil.phpStorm.phpInspectionsUltimate, de.espend.idea.php.toolbox, de.espend.idea.php.annotation, lv.midiana.misc.phpstorm-plugins.deep-keys, me.artspb.idea.eval.plugin, net.king2500.plugins.PhpAdvancedAutoComplete, izhangzhihao.rainbow.brackets, com.vladsch.idea.multimarkdown, fr.adrienbrault.idea.symfony2plugin, org.psliwa.idea.composer, ru.adelf.idea.dotenv, uk.co.ben-gibson.remote.repository.mapper

**Comment by kalessil** [comment]
Fixed!

**Comment by voku** [comment]
Thanks for the quick fix. 👍
