### ISSUE TITLE
Another null pointer false positive

### ISSUE THREAD

**Issue by leofeyer** [kalessil/phpinspectionsea#1389]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | EA Extended 3.0.15 |
| Language level | PHP 7.1 |

Current behaviour
--

<img width="584" alt="" src="https://user-images.githubusercontent.com/1192057/63443776-b3c73b00-c435-11e9-8367-f8382fa7a12f.png">

Expected behaviour
--

No null pointer warning 😄 

Environment details
--

The screenshot shows the Contao [`CsrfTokenCookieListener`](https://github.com/contao/contao/blob/75e6eb0974055124ef2b54389ccd0d50cf35cba5/core-bundle/src/EventListener/CsrfTokenCookieListener.php#L89) class, which uses the Symfony request. Since we are validating that the request has a session object using the `hasSession()` method, we can be 100% sure that the `getSession()` method will not return `null`.

I'm not sure if this can be fixed, though, because the two methods are not programmatically related to each other (in contrast to using an `isset()` or `instanceof` check).

**Comment by kalessil** [comment]
Checked: the method has null as possible return value and the plugin can not relate those 2 methods, no chance :(

**Comment by leofeyer** [comment]
I figured. Thanks for checking anyway. 👍
