### ISSUE TITLE
Unnecessary parentheses Vs. implicit magic method calls …

### ISSUE THREAD

**Issue by Fleshgrinder** [kalessil/phpinspectionsea#139]
This is probably the craziest edge case so far but considering the use cases it is one that should be solved. Consider the following construct:

    (new static)();

This instantiates the class and calls it via the magic `__invoke` method. However, this will trigger the _unnecessary parenthesis_ inspection.

    (new static)->__invoke();

Is more clear about what is going on but triggers the _implicit magic method calls …_ inspection.

I’d argue that both inspections are problematic here since the former is a typical PHP 7 construct and the latter a typical PHP 5 construct. Specifically for closures which are stored in properties.

```
class A {
  private $cb;
  public function __construct(callable $cb) {
    $this->cb = $cb;
  }
  public function php5() {
    return $this->cb->__invoke();
  }
  public function php7() {
    return ($this->cb)();
  }
}
```

Solving the _unnecessary parenthesis_ is probably solvable only by checking if the current value refers to an object that implements the `__invoke` method.

The _implicit magic method calls …_ inspection simply requires an exception for `__invoke`.

**Comment by rentalhost** [comment]
There are two options to check that:

- Your suggestion: check if class have the `__invoke()` method. But I guess that it should conflict with something like (SomeClass::getSubClass())(), where SubClass have too an invoke.
- Check if structure is a NewInstance for Class (ex. (new Something)() should be valid).

**Comment by Fleshgrinder** [comment]
I’m always on latest PhpStorm EAP, that’s right now: `171.3019.12`
