### ISSUE TITLE
[FR] Unnecessary use of a variable with fixed value in scope

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1390]
Description (screenshot):
--
Here is an example of code:
```php
function foo($dependancy){
    $value = $dependancy->getAttribute();
    if($value === true){
        $dependancy->doSomething($value);
    }
}
```
In that sort of cases, we could suggest replacing the last usage of $value with true as it's the only value possible in this scope.

This inspection could then trigger other inspection (for example, if doSomething as a default value =true, the plugin will suggest dropping the value altogether.

Thanks

**Comment by kalessil** [comment]
I gave a try implementing this, didn't came up with anything feasible.

**Comment by orklah** [comment]
It's okay! Thanks for trying!
