### ISSUE TITLE
[FP] Suspicious assignment

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1391]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), last version |
| Language level |  PHP 7.2               |

Current behaviour
--

For the following code:

```php
function foo(array $a){
    $value = null;
    foreach($a as $value){
        //some code
    }
    if($value  === null){
        //some code
    }
}
```

We get an error "Suspicious assignment" with $value as it's possibly overriden in the loop. However, if we delete "$value = null;" we get an error "Variable might not have been defined" on the if later.

If the variable overriden in the loop is used outside of the loop, the first statement is probably just initializing the variable...

Thanks

**Comment by kalessil** [comment]
Fixed!

**Comment by orklah** [comment]
Thanks!
