### ISSUE TITLE
Change automatic fixes to non-Yoda style

### ISSUE THREAD

**Issue by laurin1** [kalessil/phpinspectionsea#1393]
I may be mistaken, but I don't think https://github.com/kalessil/phpinspectionsea/issues/963 is the same issue. Is it possible to have the automatic fixes use the non-Yoda style?

			strpos(
				$oProcess->getOutput(),
				"syntax is incorrect") !== false

Right now, whether Yoda is checked or not, I get this, which I do not like:

			false !== strpos(
				$oProcess->getOutput(),
				"syntax is incorrect")

**Comment by kalessil** [comment]
That's a bug - inspection code generation is not checking the setting at all. I'll fix it!

**Comment by kalessil** [comment]
Fixed!
