### ISSUE TITLE
[FP] If-return-return could be simplified

### ISSUE THREAD

**Issue by voku** [kalessil/phpinspectionsea#1394]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 3.0.3.1 |
| Language level | PHP 7.0                       |

code
--

```php
function lall(): bool
{
    static $FOO = null;

    if ($FOO !== null) {
        return (bool) $FOO;
    }

    if (random_int(1, 2) === 2) {
        $FOO = true;
    } else {
        $FOO = false;
    }

    return $FOO;
}
```

Current behaviour
--

```
return random_int(1, 2) === 2;
```

Expected behaviour
--

maybe something like this ...
```
$FOO = random_int(1, 2) === 2;

return $FOO
```

Environment details
---
PhpStorm 2019.2.1
Build #PS-192.6262.66, built on August 22, 2019
Licensed to Portable UTF-8 / Lars Moelleken
Subscription is active until February 28, 2020
For non-commercial open source development only.
Runtime version: 11.0.3+12-b304.39 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-157-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 5120M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.tooltip.initialDelay=885, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: Key Promoter X, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, net.seesharpsoft.intellij.plugins.csv, net.vektah.codeglance, NEON support, com.kalessil.phpStorm.phpInspectionsUltimate, de.espend.idea.php.toolbox, de.espend.idea.php.annotation, lv.midiana.misc.phpstorm-plugins.deep-keys, me.artspb.idea.eval.plugin, net.king2500.plugins.PhpAdvancedAutoComplete, izhangzhihao.rainbow.brackets, com.vladsch.idea.multimarkdown, fr.adrienbrault.idea.symfony2plugin, org.psliwa.idea.composer, ru.adelf.idea.dotenv, uk.co.ben-gibson.remote.repository.mapper

**Comment by kalessil** [comment]
Done: code generation will keep assignments as of now.
