### ISSUE TITLE
Potentially problematic suggestion to replace an explode>in_array combination with a strpos

### ISSUE THREAD

**Issue by schlessera** [kalessil/phpinspectionsea#1396]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate) v3.0.3.1 |
| Language level | PHP 5.4                        |

Current behaviour
--
![Image 2019-08-27 at 2 23 41 PM](https://user-images.githubusercontent.com/83631/63770914-7c91d780-c8d6-11e9-9498-4f60f2a9cfbd.png)

I'm getting a suggestion that is not fully correct and might be misleading.
In the above case, the attribute is a string with one or more classes. WIth a single class, it will just be `'wp-block-image'`.

The suggestion would only work:
- if the string contains at least 3 classes AND
- if the class I'm looking for is not the first nor the last one

Also, the message uses concatenation to concatenate three hard-coded strings. It should only use concatenation if variables are used.

Expected behaviour
--

At the very least, there should be some form of caveat included that lets the developer know that this only works under certain circumstances, as the likelyhood of this being a safe change is actually pretty slim.

Environment details
---
PhpStorm 2019.2
Build #PS-192.5728.108, built on July 24, 2019
Licensed to Alain Schlesser
Subscription is active until December 17, 2019
Runtime version: 1.8.0_152-release-1226-b7 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: PS Scavenge, PS MarkSweep
Memory: 1512M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.mac.allowDarkWindowDecorations=true
Non-Bundled Plugins: DBN, HtmlEntity, PHPUnit code coverage, PlantUML integration, Referencer, Remote call, String Manipulation, YAML/Ansible support, awesome.console, com.intellij.ideolog, com.ultrahob.zerolength.plugin, org.intellij.plugins.postcss, org.intellij.tasks.navigation, com.wix.sasslint, com.dmarcotte.handlebars, com.dryabov.phpStorm.phpregexp, com.kalessil.phpStorm.phpInspectionsUltimate, com.thanosp.phpstorm.inheritdoc, de.espend.idea.laravel, de.espend.idea.php.annotation, de.espend.idea.php.phpunit, lv.midiana.misc.phpstorm-plugins.deep-keys, com.wix.eslint, cucumber-javascript, fr.adrienbrault.idea.symfony2plugin, ru.adelf.idea.dotenv

**Comment by kalessil** [comment]
I dropped the pattern, as it changes behaviour, thank you for reporting @schlessera!
