### ISSUE TITLE
Detecting XSS in PHP views

### ISSUE THREAD

**Issue by SpyroTEQ** [kalessil/phpinspectionsea#1397]
One of the main security issue in PHP could be XSS vulnerabilities. THis easily occur in newbies projects, with plain simple reflected stuff like:
```php
echo "Hello, {$_GET['username']}";
```

But this can also occur in legacy projects, with more complex stored XSS or so, like
```php
$value = $pdo->query('SELECT name FROM user WHERE id = ?', array($_GET['id']))->fetchAll()[0] ?? 'Anonymous';
echo "Hello, <i>" . $value . "</i>";
```

Some automated tools, like Coverity, might miss such things, because the DB source is unknown, or the DB source seems not injectable right now, or whatever. Plus, it's security tools is often either expensive, or uber complex to setup.

Sonar would have been a neat way to check for that, but it does not handle multiple languages, so stuff like:
```php
echo "<i>" . $unsafeData . "</i>";
```
Will be hard to distinguish against stuff like
```php
header('Content-Type: text/plain');
echo $unsafeButNotXssSensitive;
```

IntelliJ would be a great tool for that, as we already have all language parsing embeded. And if PHP EA boils up security issue when developer is typing code, then we can:
- Reduce cost of security fixes by pushing developers to fix the code before even opening the irPull Request/testing
- Teach them how to develop safe code, either with inspection fix or with links to OWASP cheat sheet or so
- Keep them up to date about potential new security findings in PHP (if we go behond XSS)

So, I would like to contribute to PHP EA by starting setting up XSS inspections. I'm actually a security product analist and pentester, so that would even help me find security issues in whitebox tested projects. Hence, it will serve me one way another, so why not trying to integrate this with PHP EA so it serves others?!

If so, I think I'll need to:
- defined cases for XSS (will probably not be exhaustive)
- allow project to say (or inspection to detect) "this variable is echo-html safe", like:
```php
$unsafe = $_GET['name'];
$safe = htmlentities($unsafe, 'utf-8');
echo $safe; // Should not be marked as "XSS unsafe"
```

- allow project to say "this function escapes html stuff, like:
```php
function html($txt): string {
return htmlentities($txt, 'utf-8');
}
echo "Hello, <I>" . html($_GET['name']) . "</i>";
```

so we avoid false positives

Would that be a neat feature to work on for contributing to PHP EA?
Or maybe I should start with potentially "simpler", like SQL injection detection (but I encounter less of them, so... both suits me)?

**Comment by kalessil** [comment]
I'd try collaborating on XSS for the Extended-version (there is XSS detection in Ultimate-plugin, but it's for completely different scope):
- it'll bring direct value for you, community and the project
- we'll see if the plugin has needed infrastructure for this sort of analysis

Do you want to do actual coding, or focus more on requirements engineering?

**Comment by SpyroTEQ** [comment]
I'm not sure what you mean by "requirements engineering", so there would be my proposal:

I do have actual PHP projects and so one way another, I will need to detect XSS in there. So I could fork the PHP EA project, integrate the use case I need in there, and from there, we might see what is generalisable to PHP EA and how we could do so? In case of failure, I'll either keep the fork to still have these inspections, or extract them into a dedicated plugin for my single case (= put it into my current personnal plugin).

I feel more confortable working with an actual specific context, even if small or maybe very scoped, rather than trying to thing globally at first glance.
Besides, do you have a read me to contribute to PHP EA? It seems rather more complex than just opening an IntelliJ plugin and right click "prepare for deployment" :/ I didn't see any in the github codebase

**Comment by kalessil** [comment]
@SpyroTEQ: forking - generalizing will work for me =)

If you used Idea as IDE, you can import the project (it's Graddle project type). If you have a Java SDK (the one from Oracle) already, then Graddle will take care of build/test routines.

Like here: 
![image](https://user-images.githubusercontent.com/1577185/64102044-61f4ae00-cd6f-11e9-80eb-d39154b2161e.png)
When it comes to the IDE/EA APIS, this inspection - src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/security/NonSecureCryptUsageInspector.java will be a good starting point to look at.

**Comment by SpyroTEQ** [comment]
Alright, but since we are behind a giant MITM proxy here, do you have any idea how to bypass (or actually fix) the `Caused by: org.gradle.internal.resource.transport.http.HttpRequestException: Could not GET 'https://jetbrains.bintray.com/intellij-third-party-dependencies/gradle/plugin/org/jetbrains/intellij/plugins/gradle-intellij-plugin/0.3.7/gradle-intellij-plugin-0.3.7.pom'...` that comes from `Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target` that I get when importing the gradle project?!...

**Comment by kalessil** [comment]
I pushed changes (workaround, to try), so gradle uses http instead of https repositories, can you give it a try?

**Comment by SpyroTEQ** [comment]
Sorry for late reply.
Ahah, that (use http instead of https in the two `build.gradle` repos lines)is exactly what I've tried few hours after my post : ) But the same problem occurs later on: `Caused by: org.gradle.internal.resource.transport.http.HttpRequestException: Could not GET 'https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIU/2016.2.5/ideaIU-2016.2.5.pom'.`

I'll check where Gradle stores its pom and components, and I'll try to manually download the missing ones (the webbrowser is configured to trust that MITM proxy... [sic]), you may revert the http/https changes so other dev won't have security issues (using plain http for such thing than dependencies seems bad to me: fixing my MITM issue should not lead to allow MITM for other devs)

**Comment by kalessil** [comment]
Ok, I'll revert back to use https then. cache-redirector is seem to be part if bintray-repositories discovery, so no chance.

According to https://docs.gradle.org/current/userguide/repository_types.html#sub:maven_local, in order to use locally cached dependecies it'll be enough to replace 'mavenCentral()' with 'mavenLocal()' in graddle.properties

I also wondering if feeding graddle implicitly with proxy settings (in the graddle.properties) will work: https://stackoverflow.com/a/37079513.

**Comment by SpyroTEQ** [comment]
That's 'the gradle properties proxy) what I tried first, but the issue is that the proxy-MITM certificate is not part of Java's trusted store, and I failed to add the proper certificate to that store...

I suppose I'll need to find a manual way for bypassing this crappy proxy...

**Comment by kalessil** [comment]
I reverted back to https, any luck with solving proxy restrictions?

**Comment by SpyroTEQ** [comment]
I guess no... I'll retry someday, but you can give no consideration to this issue: keep your setup and configs all safe and clean ;)
