### ISSUE TITLE
Possible null pointer false positive

### ISSUE THREAD

**Issue by Redominus** [kalessil/phpinspectionsea#1398]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended), 3.0.15 |
| Language level | PHP 7.2 |

Current behaviour
--
A private method calls a private property method that returns null or an object. If I checked outside of this private method that the returned value is not null. It shouldn't display a possible null value.

![image](https://user-images.githubusercontent.com/22024214/63857457-09569700-c9a4-11e9-8a73-97beeaa6767d.png)

![image](https://user-images.githubusercontent.com/22024214/63857489-15daef80-c9a4-11e9-84de-08566c5bcd26.png)

![image](https://user-images.githubusercontent.com/22024214/63857510-1d01fd80-c9a4-11e9-8781-f41a5893caa2.png)

Expected behaviour
--
Not displaying the false positive.

Environment details
---

**Comment by kalessil** [comment]
Thank you for reporting @Redominus, technically speaking this is a bug. Unfortunately I have no solution for this: the inspection is invoked in the 'falsePositive' method and has no clue what happens outside - performance requirements limitation.

I can suggest changing the workflow or suppression the warning.
