### ISSUE TITLE
Non-optimal if conditions: check for falsy values

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#140]
Currently, this inspection could check that `if(false)` is a non-optimal solution because it will never be executed, but it doesn't checks others falsy values like: _zero_ integer, _zero_ float, _empty_ string, `"0"` string, empty array and `null`.

**Comment by kalessil** [comment]
Good cases, it seems that we need to split if-conditions into smaller inspections and dedicate its a new sub-group. But before this done, I'll try to catch cases as described here.

**Comment by kalessil** [comment]
- the case from @iltar (constants) is already reported by PS, so nothing to do for me
- from the cases by @rentalhost I added `null` reporting, others are not really making sense IMO
