### ISSUE TITLE
Wrong type analisys in null-coalescing usage inspection inside foreach

### ISSUE THREAD

**Issue by Redominus** [kalessil/phpinspectionsea#1408]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) , 3.0.15 |
| Language level | PHP 7.2 |

Current behaviour
--

![image](https://user-images.githubusercontent.com/22024214/64767211-9888b080-d547-11e9-90af-2bebcfdd189f.png)
![image](https://user-images.githubusercontent.com/22024214/64767414-f61cfd00-d547-11e9-8b4c-1f599cb92a86.png)
getKeyWords returns null or 
![image](https://user-images.githubusercontent.com/22024214/64767481-13ea6200-d548-11e9-96a2-39f10233658c.png)

Expected behaviour
--
Inside a foreach, an array and an Iterator class are compaible types. The inspection should check implemented interfaces and allows,inside a foreach, native arrays with Iterators, ArrayAccess, etc.

Environment details
---
PhpStorm 2019.2.1
Build #PS-192.6262.66, built on August 22, 2019
Subscription is active until August 1, 2020
Runtime version: 11.0.3+12-b304.39 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-27-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1921M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: CMD Support, com.intellij.ideolog, net.seesharpsoft.intellij.plugins.csv, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, ru.adelf.idea.dotenv

**Comment by kalessil** [comment]
Thank you for reporting @Redominus, I'll check what can we do here. Possibly we'll drop the inspection at all - it constantly getting new bug-reports.

**Comment by kalessil** [comment]
Done: I dropped the inspection at all.
