### ISSUE TITLE
Referencing `private const` with `static` will fail in child class

### ISSUE THREAD

**Issue by SpyroTEQ** [kalessil/phpinspectionsea#1409]
Description
--
`private` class constant visibility should not be used together with `static::*` reference, as the `private` scope won't be resolved in the child class.

Example
--
Take this code:
```php
class X {
    private const FOO = 'foo';
    public static function failing(): void {
        echo static::FOO;
    }
}
class Y extends X {
    protected const FOO = 'bar';
}
Y::failing();"
```

The call to `Y::failing` will fail, with `Undefined class constant 'FOO'`, so putting a warning on static::FOO would be good.

One could say `we use static::* because child class might override this constatn value` but 
```php
class Y extends X {
    private const FOO = 'bar';
}
```

Results in `Cannot access private const Y::FOO`. The only way to get access to this const from `FOO` is by using `protected`:

```php
class Y extends X {
    protected const FOO = 'bar';
}
```

But IMO, that's a very weak way of coding, as the parent class should have made the constant `protected`, to tell "you might override this constant in child class".

So it seems more likely that people using `private + static::* + inheritance` combo end up with a `constant not found` rather than getting annoyed in the very specific case of overridding the constant value.

Implementation suggestion
--
I've fall over this case quiet often, so I've already added it to my custom personnal plugin. Feel free to adapt it to PHP EA if you consider it's worth it (and every feedback on that code is welcome, as I'm not satistied at all by the `text.startsWith("static::"))` test at the beginging...)

```java
return new PhpElementVisitor() {
	@Override
	public void visitPhpClassConstantReference(final ClassConstantReference constantReference) {
		super.visitPhpClassConstantReference(constantReference);

		final String text = constantReference.getText();
		if (!text.startsWith("static::")) {
			// Only concerns "static::*" references
			return;
		}

		final PsiElement resolved = constantReference.resolve();
		if (!(resolved instanceof ClassConstImpl)) {
			// Unresolvable constant, so ignore
			return;
		}

		final ClassConstImpl classConst = (ClassConstImpl) resolved;
		if (!classConst.getModifier().isPrivate()) {
			// Only concerns private consts
			return;
		}

		final PhpClass phpClass = classConst.getContainingClass();
		if (phpClass == null || phpClass.getModifier().isFinal()) {
			// Class is not extendable, so, it's OK to use static::* as it will always resolve like self::*
			return;
		}
		ReinomInspection.problem(
				problemsHolder,
				constantReference,
				"'static::*' refering to 'private const' will fail in child class",
				ReinomLocalQuickFix.fixByReplacingWithText(
						"self::" + text.substring("static::".length()),
						constantReference));
	}
};
```

**Comment by kalessil** [comment]
Thank you for reporting and suggessions @SpyroTEQ, I'll take care of fixing this.

**Comment by kalessil** [comment]
@SpyroTEQ, I checked the example (see here: https://3v4l.org/bOe4d, PHP 7.1+ part) and it seems to work as expected - prints "bar" from child class.

**Comment by SpyroTEQ** [comment]
Sorry, I messed up with the 1st example, I meant it without the "protected const" in the child class (see correction in my 1st message)
