### ISSUE TITLE
Exception 'JsonException' is never thrown in the function

### ISSUE THREAD

**Issue by JohnOhl** [kalessil/phpinspectionsea#1414]
Description (screenshot):
--
When using json_encode or json_decode with the JSON_THROW_ON_ERROR flag, the PHPDoc gives a notice that JsonException is never thrown.

This particular example would never fail, but you could have an input that could fail

<img width="536" alt="Screen Shot 2019-09-17 at 6 33 21 PM" src="https://user-images.githubusercontent.com/1581569/65084754-3d592280-d97a-11e9-91ed-fc979ffb90da.png">

Example
--
```
<?php
declare(strict_types=1);

class Test
{
    /**
     * Test function
     *
     * @param $data
     *  The data to encode
     *
     * @return void
     *
     * @throws \JsonException
     */
    public static function test($data): void
    {
        $test = json_encode($data, JSON_THROW_ON_ERROR);
    }
}
```

**Comment by kalessil** [comment]
Thank you for reporting @JohnOhl, this seems to be coming from IDE inspections, not from the plugin.
