### ISSUE TITLE
False positive in "Short syntax for applied operation"

### ISSUE THREAD

**Issue by fisharebest** [kalessil/phpinspectionsea#1417]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 3.0.16.2 |
| Language level | PHP 7.1                        |

Current behaviour
--
The code `$memory_limit = $memory_limit / 1024 / 1024;`

Triggers the optimisation: `Can be safely refactored as '$memory_limit /= 1024 / 1024'.`

<img width="965" alt="Screen Shot 2019-09-30 at 00 04 29" src="https://user-images.githubusercontent.com/2306088/65840883-ec501380-e315-11e9-943b-e2f265c4b3ff.png">

Expected behaviour
--

This is a false positive.

The current code is equivalent to `$memory_limit = $memory_limit / 1048576;`
The suggested refactor is equivalent to `$memory_limit = $memory_limit / 1;`

Environment details
---
PHPStorm 2019.2.3

**Comment by kalessil** [comment]
Oops, thank you for reporting @fisharebest! I'll take care of fixing this.

**Comment by kalessil** [comment]
Fixed!
