### ISSUE TITLE
Composition and inheritance on Doctrine Entities - do not prompt for final

### ISSUE THREAD

**Issue by rbairwell** [kalessil/phpinspectionsea#1418]
PHP Inspections (EA Ultimate) prompts "This class needs for be final (for aggregation) or abstract (for inheritance)" using the "Architecture->Composition and inheritance" inspection. However, due to the way Doctrine works, Doctrine entities cannot be final or include final methods ( https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/architecture.html#entities ).

Would to therefore be possible for this inspection NOT to be triggered if the file is a Doctrine entity ( `use Doctrine\ORM\Mapping\Entity;... /** @Entity **/` )

**Comment by kalessil** [comment]
Fixed!
