### ISSUE TITLE
[FR] One-time use variable: new patterns

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1419]
As discussed here https://github.com/kalessil/phpinspectionsea/issues/1410

This pattern could be matched in the One-time use variable inspection:

```php
function scope($a){
    $b = $a;
    if($b){
        echo 'ok';
    }
}
```

$b is redundant here and could be swapped by $a.

Another case that could be matched is this one:

```php
function scope(){
    $a = random_int(0,1);
    if($a){
        echo 'ok';
    }
}
```

$a is redundant here. However, for long statement, it could be preferable to keep the variable(this setting already exists for other inspection, it could make sense here too)

Thanks

**Comment by kalessil** [comment]
Will do!

**Comment by ea-inspections-team** [comment]
Thanks for reporting @orklah ! Implemented!

**Comment by orklah** [comment]
Thanks! I had little hopes for this one! Glad it was not forgotten :)
