### ISSUE TITLE
Prefix Inspection Results With Plugin Name

### ISSUE THREAD

**Issue by sprankhub** [kalessil/phpinspectionsea#1425]
First, thank your for this awesome plugin!
 
When seeing an inspection result, it is sometimes tough to see if the suggestion comes from PhpStorm itself, your plugin or another plugin. The SonarLint plugin shows a little prefix before the message, which shows where the suggestion comes from. See https://plugins.jetbrains.com/files/7973/screenshot_15543.png. In the screenshot, an identifier with a link to some doc is shown. In the case of your plugin, it may be nice to either just prefix the suggestion with the plugin name or - even better - the plugin name plus the inspection name with a link to the respective doc.

What do you think?

**Comment by kalessil** [comment]
Will include in the next release. As per a poll (https://twitter.com/kalessil/status/1183641452242460672) we'll most likely start all messages with '[EA] '.
