### ISSUE TITLE
FP: Non-optimal regular expression

### ISSUE THREAD

**Issue by voku** [kalessil/phpinspectionsea#1426]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 3.0.4.2 |
| Language level | PHP 7.1                        |

Current behaviour
--
```php
preg_quote('#~ŤÉŚŢ~#', '~');
```

Error -> /u is missing

Example -> https://3v4l.org/JfXFg

Expected behaviour
--
no error for "preg_quote"

Environment details
---
PhpStorm 2019.3 EAP
Build #PS-193.4099.12, built on October 2, 2019
PhpStorm EAP User
Expiration date: November 1, 2019
Runtime version: 11.0.4+10-b485.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-165-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 5120M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.tooltip.initialDelay=885, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: NEON support, String Manipulation, com.kalessil.phpStorm.phpInspectionsUltimate, de.espend.idea.php.toolbox, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, izhangzhihao.rainbow.brackets, lv.midiana.misc.phpstorm-plugins.deep-keys, me.artspb.idea.eval.plugin, name.kropp.intellij.makefile, net.king2500.plugins.PhpAdvancedAutoComplete, net.seesharpsoft.intellij.plugins.csv, net.vektah.codeglance, org.jetbrains.plugins.rest, org.psliwa.idea.composer, ru.adelf.idea.dotenv, uk.co.ben-gibson.remote.repository.mapper

**Comment by kalessil** [comment]
Fixed!
