### ISSUE TITLE
Nullable return type if function might throw an exception?

### ISSUE THREAD

**Issue by chrisprog20** [kalessil/phpinspectionsea#1429]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 3.0.16.2 |
| Language level | PHP 7.3                    |

Hi! 

Thank you for your great plugin. I really like to use it.
I came across a code completion from the plugin where I am not clear if it is correct.
It is about the return type of a function if this function could also possibly throw an exception.
Here is an example (which makes no sense I know but just to show you the issue):

Given this function the plugin suggests to add return type `?array`:

`use Exception;`
`     `
`/**`
` * foo.`
` * `
`* @param int $a`
`* @return array`
`* @throws Exception`
`*/`
`public function foo(int $a)`
`{`
`   if ($a === 0) {`
`     throw Exception('Your parameter is 0');`
`   }`
`   return [$a];`
`}`

But would it not be more correct to suggest return type `array`?
I mean this function always returns an array (not null, like it would be the case for `?array`) and also might throw an execption.

So what do you think about it and how would it correctly be?
Thank you for your expertise :)

--

**Comment by kalessil** [comment]
Thank you for reporting @chrisprog20, I agree with you that in this case the plugin should suggest using 'array'. I'll take care of fixing this.

**Comment by chrisprog20** [comment]
Thank you very much @kalessil for your answer and that you fill fix it.
I am also happy that I guessed it correctly :)

**Comment by kalessil** [comment]
Checked (added a test case), but could not reproduce. Let see if CI can reproduce the issue in any of environments.
