### ISSUE TITLE
Missing directory separators: __DIR__ . '..'

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#1430]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | U 3.0.4.2 |
| Language level | PHP 7.3                    |

Current behaviour
--
`require __DIR__ . '..'` is allowed.

Expected behaviour
--
It should requires the directory separator (eg. `require __DIR__ . '/..'`).

Note
--
It already works if I call a file without dots: `require __DIR__ . 'file.php'` will works and will requires the directory separator.

![image](https://user-images.githubusercontent.com/421851/66845979-6f44b100-ef47-11e9-8e0b-d515319e3abc.png)

**Comment by kalessil** [comment]
Fixed!
