### ISSUE TITLE
Dropping "compact(...)' can be used"?

### ISSUE THREAD

**Issue by andreasschroth** [kalessil/phpinspectionsea#1432]
The documentation states already:

> Note: this inspection is disabled by default as using 'compact(...)' is not a common practice

But I really don't see the purpose of using compact() instead of the in-language destructuring. You can even skip single elements and destructure multi-dimensional arrays...

Just wanted to bring it up as I think if it's an inspection that's neither recommended nor used, maybe it would be better to just remove it?

**Comment by orklah** [comment]
What do you mean by in-language destructuring?

For me, compact is the opposite of destructuring.

However, I hate that syntax too and left the inspection disabled.

**Comment by andreasschroth** [comment]
Oops. Yes, true, sorry, obviously it's the other way around. But the reasoning is basically the same - don't think it should be considered good practice to use `compact()`.

**Comment by kalessil** [comment]
The inspection is disable by default + I have to keep it as it was made specially for some of OSS frameworks.
