### ISSUE TITLE
FR: Add setting to define "long inheritance chain"

### ISSUE THREAD

**Issue by andreasschroth** [kalessil/phpinspectionsea#1433]
It would be nice if there would be a setting for the inspection "Long inheritance chain" where one could define the number of parent classes that are then considered a "long inheritance chain".

We luckily only have very few occurences with 4 instead of 3 parent classes and can then manually whitelist them (ignore the inspection), but it feels like this should be someone the developer can change and not be hard-coded.

And thanks for the hard work on the plugin!

**Comment by kalessil** [comment]
Will do!

**Comment by kalessil** [comment]
Done!
