### ISSUE TITLE
FR: Add inspection that reports useless "@noinspection" usages

### ISSUE THREAD

**Issue by andreasschroth** [kalessil/phpinspectionsea#1434]
I have no idea if this is possible to implement, but I think it would be really awesome if you could report cases where `@noinspection` annotations inside the code base are useless.

For example, because the inspection got changed / improved and it doesn't find that place anymore or for other reasons.

Right now, once in a while, we need to go through the whole code base and manually check if the `@noinspection` annotations are still required or not in every single case.

**Comment by kalessil** [comment]
Seems IDEA finally introduced this (and i don't think the differentiate own/3rd party inspections), closing this ticket.
