### ISSUE TITLE
Exposes @internal class warning on __construct()

### ISSUE THREAD

**Issue by theseer** [kalessil/phpinspectionsea#1447]
The warning when exposing an `@internal` annotated class via a public method should not apply to a constructor of a class that otherwise provides functionality (potentially among other things) based on the internal class but does not actively expose said class by providing a (public) getter.

Alternatively, the rule should be split up into a strict version (as it is now) and a variant that allows usage in a constructor.

In case it's relevant: Running PHPStorm (PhpStorm 2019.2.3
Build #PS-192.6817.20 with com.kalessil.phpStorm.phpInspectionsUltimate 3.0.5)

**Comment by kalessil** [comment]
Good catch @theseer. Introducing 2 inspections is an aption, but I was thinking about adding a new setting to switch on/off reporting of the magic methods in general.

In you opinion, should it be enabled or disabled by default?

**Comment by theseer** [comment]
Maybe just a wording issue but I'm not sure I understand the reasoning why it should be allowed for all magic methods?

Where, except for the constructor and arguably any type of setter, would any other method - not only magic ones - not expose the internal class?

I guess it all depends on your definition of exposure.

If one is (obviously, I guess?) not allowed to instantiate the internal class in unrelated 3rd party code and the original author can also not pass an instance of that internal class to anything not internal, that internal class is arguably close to pointless.

The only allowed use case would be a fully internal use, like within non-internal classes and its methods, no passing in and not providing any getter. That's what your current rule covers and for that definition make perfect sense.

I'd argue that based on my definition of exposure and maybe only because we do not have a class visibility in PHP, passing an instance of an internal class to a non-internal (public?) class to provide a facade is also valid.

To qualify as a facade, I'd argue further that said instance should be passed via constructor and not otherwise be visible via the public API. I'm undecided whether having a setter would still be okay. Given that a setter exposes the internal class to the publicly usable API (as in, after instantiation), I lean towards not liking it.

In either case, I'd opt for the less strict interpretation by default.

**Comment by kalessil** [comment]
Originally we considered as exposire:
- methods parameters
- methods return types

In context of regular methods, but you found a valid case and my thinking was like: "Snap, we didn't think about all that crazy PHP magic. Let's stay safe from too much support and generalaize the setting to all magic methods."

So it's not about deep thinking, but rather relaxing the inspection behaviour in general for the sake of maintenace.

**Comment by theseer** [comment]
Your call, but I don't think any other magic method but `__construct()` makes sense.

We can argue whether a setter type method would qualify as exposure - as stated before -, but the official signature of `__set()` does not include types for somewhat logical reasons ;).

**Comment by kalessil** [comment]
Let's follow your proposal, as more experienced person (setting for '__construct') =)

**Comment by kalessil** [comment]
Implemented!
