### ISSUE TITLE
Unknown inspection: DuplicatedCode

### ISSUE THREAD

**Issue by InvisibleSmiley** [kalessil/phpinspectionsea#1449]
| Subject        | Details                                             |
| :------------- | :-----------------------------------|
| Plugin         | Php Inspections (EA Extended) 4.0.1 |
| Language level | PHP 7.1 |

Current behaviour
--
`/** @noinspection DuplicatedCode */` generates "[EA] Unknown inspection: DuplicatedCode"

I use development.local.php and development.local.php.dist files and let PhpStorm recognize *.php.dist as PHP files, hence such files are expected to be (almost) identical.

Expected behaviour
--
No warning generated

Environment details
---
PhpStorm 2019.2.5
Build #PS-192.7142.51, built on November 13, 2019
Runtime version: 11.0.4+10-b304.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by kalessil** [comment]
Fixed!
