### ISSUE TITLE
NotOptimalIfConditionsInspection: edge case

### ISSUE THREAD

**Issue by voku** [kalessil/phpinspectionsea#1452]
Code
--
```php
    if (
        !is_file($in = array_shift($argv))
        ||
        null == $out = array_shift($argv)
    ) {
        err($fa . $exe . " -w infile outfile");
        exit(1);
    }
```

Current behaviour
--
NotOptimalIfConditionsInspection

Expected behaviour
--
non "NotOptimalIfConditionsInspection", because the function call modifies the input

**Comment by kalessil** [comment]
Thank you for reporting @voku, I'll check if we can adress the case without harming maintability of our codebase.

**Comment by kalessil** [comment]
Fixed!
