### ISSUE TITLE
This condition execution costs less than the previous one

### ISSUE THREAD

**Issue by peter-gribanov** [kalessil/phpinspectionsea#1453]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 4.0.1.1 |
| Language level | PHP 7.3                        |

Current behaviour
--

![image](https://user-images.githubusercontent.com/1954436/69442846-54dbcf80-0d5e-11ea-9770-6c8c913bfc13.png)

Expected behaviour
--

I cannot move a variable check before it is created.

**Comment by kalessil** [comment]
Fixed!

**Comment by peter-gribanov** [comment]
@kalessil thanks :+1:
