### ISSUE TITLE
[EA] This condition ist duplicated in another if/elseif branch

### ISSUE THREAD

**Issue by Starocotes** [kalessil/phpinspectionsea#1460]
I'm confused. 

I want to cleanup my code and get the following suggestion form PhPStorm:

 

"[EA] This condition ist duplicated in another if/elseif branch"

 

The statement is:

 

```
`if($nof !== '' && $not === '')
{
   $tab->where .= " and no = '".$nof."'";
}
elseif($nof !== '' && $not !== '')
{
   $tab->where .= " and no >= '".$nof."' and no <= '".$not."'";
}`
```

**Comment by orklah** [comment]
You could probably refactor like that:
```php
if($nof !== '')
{
    if($not === ''){
        $tab->where .= " and no = '".$nof."'";
    }
    else{
        $tab->where .= " and no >= '".$nof."' and no <= '".$not."'";
    }
}
```
It'd avoid checking twice $nof !== ''

**Comment by kalessil** [comment]
Thank you for reaching us out @Starocotes. As @orklah mentioned, the inspection says that '$nof !== ''' can be used as outer condition, or possible as a local variable.

**Comment by kalessil** [comment]
I personally would follow the proposal from @orklah
