### ISSUE TITLE
[JSON] Harden error handling: 512 is needless

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#1465]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | 3.0.6 Ultimate |
| Language level | 7.4                    |

Behaviour
--
```php
// Before:
json_encode([]);

// After quick-fix:
json_encode([], JSON_THROW_ON_ERROR, 512);

// Expected:
json_encode([], JSON_THROW_ON_ERROR);
```

![image](https://user-images.githubusercontent.com/421851/70755924-f204a500-1d19-11ea-8e7a-2bbb618722d9.png)

**Comment by abgit** [comment]
yeah, but on `json_decode()` `$depth` argument (512) is **before** `$options` ( JSON_THROW_ON_ERROR ), so makes sense to fill 512 on both `json_decode()` **and** `json_encode()`.

```php
// before:
json_decode([], true);

// after
json_decode([], true, 512, JSON_THROW_ON_ERROR);
```

**Comment by rentalhost** [comment]
Only for `json_decode()`, yes. But it is applied to `json_encode()` that is after `$options`.

**Comment by kalessil** [comment]
Fixed!
