### ISSUE TITLE
Suggestion for PHPUnit assertInternalType assertion is deprecated

### ISSUE THREAD

**Issue by pavlakis** [kalessil/phpinspectionsea#1467]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) or Php Inspections (EA Ultimate), which version |
| Language level | e.g. PHP 7.2 (check project settings or composer.json)                        |

Current behaviour

The suggested for PHPUnit's method `assertInternalType` is pointing to a deprecated method.

Example: 
```
static::assertTrue(is_string($encodedString));
```

--

Expected behaviour

As per PHPUnit's warning, it should suggest one of the following:

```
'assertInternalType() is deprecated and will be removed in PHPUnit 9. Refactor your test to use assertIsArray(), assertIsBool(), assertIsFloat(), assertIsInt(), assertIsNumeric(), assertIsObject(), assertIsResource(), assertIsString(), assertIsScalar(), assertIsCallable(), or assertIsIterable() instead.'
```
--

Environment details
PhpStorm: 2019.3
Plugin: 4.0.2

---

**Comment by kalessil** [comment]
Duplicates #1292
