### ISSUE TITLE
Inspection Error: Resolved index type [bool] is incompatible with possible [string, int], for is_array

### ISSUE THREAD

**Issue by torvista** [kalessil/phpinspectionsea#1468]
PHP Inspections EA Extended 4.0.2 in PHPStorm 2019.3.
Probable Bugs->Array and String Offset Validity
Inspection Report: Resolved index type [bool] is incompatible with possible [string, int].

Hi,
is this warning correct or a bug? There were similar (fixed) issues in the past.

To test it, I isolated the offending code in a single file and the warning is still triggered.

![Clipboard01](https://user-images.githubusercontent.com/4391026/70868459-51182300-1f81-11ea-9b24-4db761f2f5b5.gif)

I note that declaring $key='' prior to the loop clears the error.
thanks
Steve

**Comment by orklah** [comment]
I can't reproduce on an empty project. Is it possible you have another file in this project in which $key is affected with a bool value? PhpStorm share global variable definitions across all files.

Can you add a namespace declaration or put your code in a function to test if the issue is still here?

**Comment by torvista** [comment]
> Is it possible you have another file in this project in which $key is affected with a bool value?
Probably, it is used in 100's of files.
Putting it in a function clears the error so that explains it for me.
Any option I can set to stop this, apart from disabling this particular inspection?

**Comment by orklah** [comment]
It's a pretty old request in phpstorm:
https://youtrack.jetbrains.com/issue/WI-3962
I don't think there will be changes any time soon.

Except adding namespaces, scopes (like functions) and globally limiting variables in global scope, I don't think there is much you can do...

**Comment by torvista** [comment]
ok, thanks for the plugin and the quick response.

**Comment by orklah** [comment]
You're welcome for the answer, but you should thank @kalessil for the plugin :).

**Comment by kalessil** [comment]
Oh, don't make me shy - we have a great community, who backs me up. This ticket is a great example of this!
