### ISSUE TITLE
Smart pointers exception

### ISSUE THREAD

**Issue by rk** [kalessil/phpinspectionsea#1475]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) , 4.0.2 |
| Language level | PHP 7.2                        |

Current behavior
--

Unknown; the error icon in the status bar flashed red.

Reported Exception(s)
--

As near as I can tell, these are piling up differently each time. I wish there was a batch export.

[trace-1.txt](https://github.com/kalessil/phpinspectionsea/files/3998632/trace-1.txt)
[trace-2.txt](https://github.com/kalessil/phpinspectionsea/files/3998633/trace-2.txt)
[trace-3.txt](https://github.com/kalessil/phpinspectionsea/files/3998634/trace-3.txt)
[trace-4.txt](https://github.com/kalessil/phpinspectionsea/files/3998635/trace-4.txt)
[trace-5.txt](https://github.com/kalessil/phpinspectionsea/files/3998636/trace-5.txt)
[trace-6.txt](https://github.com/kalessil/phpinspectionsea/files/3998637/trace-6.txt)
[trace-7.txt](https://github.com/kalessil/phpinspectionsea/files/3998638/trace-7.txt)

Environment details
---

PhpStorm 2019.3.1
Build #PS-193.5662.63, built on December 19, 2019
Licensed to Robert Kosek
Subscription is active until August 1, 2020
Runtime version: 11.0.5+10-b520.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 989M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.alayouni.ansiHighlight, com.dmarcotte.handlebars, com.intellij.ideolog, com.jetbrains.CyanTheme, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.laravel, de.espend.idea.php.toolbox, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, mobi.hsz.idea.gitignore, net.king2500.plugins.PhpAdvancedAutoComplete, net.seesharpsoft.intellij.plugins.csv, org.toml.lang, ru.adelf.idea.dotenv, ru.mobiledev.plugins.uigd

**Comment by kalessil** [comment]
Thank you for reporting @rk. Seems to be same as https://youtrack.jetbrains.com/issue/WI-48119, please report to JetBrains directly, thank you.
