### ISSUE TITLE
[FP] New magic methods in PHP 7.4

### ISSUE THREAD

**Issue by skalpa** [kalessil/phpinspectionsea#1478]
| Subject  | Details |
| ------------- | ------------- |
| Plugin  | EA Extended 4.0.2  |
| Language level  | 7.4  |

PHP 7.4 added two new magic methods: `__serialize` and `__unserialize`, however the "Magic methods validity" inspection does not recognize them.

Note: it seems they are not yet documented on the PHP website, however they are supported. See the RFC for reference:

https://wiki.php.net/rfc/custom_object_serialization

**Comment by kalessil** [comment]
Fixed!
