### ISSUE TITLE
[FP] Foreach usage possible: `while ($item = array_shift($this->items))` change of behaviour

### ISSUE THREAD

**Issue by jdreesen** [kalessil/phpinspectionsea#1482]
| Subject        | Details                                                                       |
| :------------- | :---------------------------- |
| Plugin         | Php Inspections (EA Ultimate) |
| Language level | PHP 7.2                       |

Current behaviour
--
The inspection/quick-fix suggests to replace `while ($token = array_shift($this->tokens))` with `foreach ($this->tokens as $token)`.

This changes the behavior of the code, because the original code manipulates the class field while the `foreach` only iterates over it.

An example can be found here: https://github.com/sensiolabs/SensioGeneratorBundle/blob/28cbaa244bd0816fd8908b93f90380bcd7b67a65/Manipulator/Manipulator.php#L43

Expected behaviour
--
The inspection is not being triggered.

**Comment by kalessil** [comment]
Fixed!
