### ISSUE TITLE
'explode(...)' limit can be used - invalid warning / incorrect QuickFix

### ISSUE THREAD

**Issue by laurin1** [kalessil/phpinspectionsea#1484]
Correct:

```
[
	$iThisYear,
	$iThisMonth,
	$iThisDay
] =
	explode(
		" ",
		date(
			"Y n j",
			Format::getTimeStamp(
				"01/09/2020")));

var_dump(
	$iThisYear,
	$iThisMonth,
	$iThisDay);
```

string(4) "2020"
string(1) "1"
string(1) "9"

Plugin flags this and suggests adding the limit of 2:

```
[
	$iThisYear,
	$iThisMonth,
	$iThisDay
] =
	explode(
		" ",
		date(
			"Y n j",
			Format::getTimeStamp(
				"01/09/2020")),
		2);

var_dump(
	$iThisYear,
	$iThisMonth,
	$iThisDay);
```

string(4) "2020"
**string(3) "1 9"
NULL**

![image](https://user-images.githubusercontent.com/75857/72155623-18e5e380-3379-11ea-87f7-65581e07d0d7.png)

**Comment by jdreesen** [comment]
Should hopefully be fixed with #1463 (not released yet).

**Comment by orklah** [comment]
> (not released yet).

Are your sure? There was a release of both Extended and Ultimate 4 days ago.

**Comment by jdreesen** [comment]
Oh, I missed that! Then it may be a new FP indeed.

**Comment by kalessil** [comment]
It's a new FP, I'll take care of it.

**Comment by kalessil** [comment]
Fixed!
