### ISSUE TITLE
"$var === null construction should be used" gets triggered for is_null($var)

### ISSUE THREAD

**Issue by peter-gribanov** [kalessil/phpinspectionsea#1486]
Description (screenshot):
--

Example
![image](https://user-images.githubusercontent.com/1954436/72257079-c2e49a80-361b-11ea-9ff8-17ad017176e9.png)

I'm used to writing like this:

```php
if ($var === null) {
}
```

But recent tests have shown that in the latest versions of the PHP, a function call `is_null()` is faster and a function call is preferable to a comparison operation, respectively.

https://3v4l.org/WQk7Q
https://3v4l.org/cq2aN/vld#output

Perhaps we should revise this rule?

**Comment by orklah** [comment]
Here's the same test in a namespace:
https://3v4l.org/Qru9q

You'd have to use \is_null or a "use function is_null" to avoid that.

"===" is immune to that...

**Comment by kalessil** [comment]
I tend to agree with @orklah, also '=== null' will be working with the same performance in all PHP version, supported by IDE.

PS: it also possible to use '$variable = $variable ?? $defaultValue' construct in newer PHP versions.

**Comment by peter-gribanov** [comment]
@orklah i did not notice such a feature. Thanks.

**Comment by rybakit** [comment]
Here are my benchmark results: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4015#issuecomment-568508507
