### ISSUE TITLE
Nested if() optimization

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#1499]
Example
--
```php
if (expr1) {
    if (expr2) {
        statement1;
    }
    else {
        statement2;
    }
}
else {
    statement2;
}
```

Could be optimized to just:

```php
if (expr1 && expr2) {
    statement1;
}
else {
    statement2;
}
```

If `expr1` is true and `expr2` is true, then `statement 1` (true-way);
If `expr1` is true and `expr2` is false, then `statement 2` (false-way);
If `expr1` is false, then `statement 2` (false-way);

So we can just check if `expr1 && expr2` to be true, else is false.

Real example
--

```php
if (1 === 1) {
    if (2 === 2) {
        echo 'true';
    }
    else {
        echo 'false';
    }
}
else {
    echo 'false';
}
```

**Comment by kalessil** [comment]
@rentalhost : tested locally, the pattern is gets reported already 👍

**Comment by rentalhost** [comment]
Ops! You are right! 😄 For some reason I was unable to simulate at the time of posting, but now it worked. Thanks!
