### ISSUE TITLE
[WIP, new]  follow "Yoda Conditions"

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#15]
Original link: https://bitbucket.org/kalessil/phpinspectionsea/issues/255/new-inspection-follow-yoda-conditions-rule
Author Eduard Ruffert 

I like to follow "yoda conditions", meaning that constants in a condition are on the left. E.g. if( MY_CONSTANT === $this->getSomeData() )

+see original link comments

**Comment by samdark** [comment]
I like to avoid these. It doesn't make much sense in PHP and reads worse. So while it's useful to have such check, it should be actually two for both camps: yoda conditions wanted, yoda conditions unwanted.

**Comment by kalessil** [comment]
@samdark : in the original ticket we ended up with the same approach: a drop down with options:
- no preference (skip analysis)
- prefer Yoda style (force Yoda style)
- forbid Yoda style (force Classic style)

**Comment by samdark** [comment]
Yep. That would be good.
