### ISSUE TITLE
Broken Functionality - Rename class

### ISSUE THREAD

**Issue by mbadolato** [kalessil/phpinspectionsea#1509]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 3.0.8 released today |
| Language level | e.g. PHP 7.4 (check project settings or composer.json)                        |

Current behaviour
--
It seems like the newest version of EA-U broke class renaming. I just installed about 10 minutes ago. After, when PhpStorm was reopened, I went to use the Rename Refactor. The dialogs all popped up but the refactor wasn't done (class name still the same after hitting Ok). Tried twice, restarted storm, tried again, disabled EA-U and restarted and it worked as expected with the plugin disabled

Expected behaviour
--
Rename Refactor should rename

Environment details
---
PhpStorm 2019.3.2
MacOs 10.15.3

**Comment by jdreesen** [comment]
Just tested it on my machine

PhpStorm 2019.3.2
Windows 10 19.03
PHP 7.3

Php Inspections (EA Ultimate), 3.0.7: ✔️ 
Php Inspections (EA Ultimate), 3.0.8 released today: ✔️ 

Everything seems to be okay here.

**Comment by mbadolato** [comment]
Hmmmmm. Definitely breaks as I enable and disable the plugin. So now the question is what's conflicting...

**Comment by mbadolato** [comment]
Well go figure. I just enabled it again (3rd time) and now it's working. So, I must have hit the right voodoo chant. Sigh. closing. Thanks for looking.
