### ISSUE TITLE
Fixer "Use boolean casting" is broken with 'complex' boolean expressions

### ISSUE THREAD

**Issue by HenkPoley** [kalessil/phpinspectionsea#1514]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | EA Extended 4.0.3 |
| Language level | PHP 7.1.33                       |

Current behaviour
--
What steps will reproduce the problem?
1. I was trying to coax PhpStorm 2019.3.3 in simplifying some pretty complex logic (with many smaller/larger than, etc.).

So I applied a couple of NOT's like much this:
```php
if(!(!($a || $b))) {}
```
2. Alt+Enter run the "Use boolean casting" fixer out of curiousity.
3. What happens instead?
```php
if((bool)$a) {}
```

(NB: maybe prepend the fixer text with "[EA]" so I don't post to JetBrains issue tracker)

Expected behaviour
--
I guess, given the context, something like:

```php
if((bool)($a || $b)) {}
```

Environment details
---
PhpStorm 2019.3.3
EA Extended 4.0.3

**Comment by kalessil** [comment]
Fixed! Regarding '[EA] ' prefix in Quick-Fixes: I'll think about it :+1:
