### ISSUE TITLE
[FP] "Short syntax for applied operation" does not work for strings

### ISSUE THREAD

**Issue by jdreesen** [kalessil/phpinspectionsea#1515]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate) |
| Language level | PHP 7.4                        |

Current behaviour
--
The "Short syntax for applied operation" inspection gets triggered for the following code:
![grafik](https://user-images.githubusercontent.com/424602/74763576-5a26b880-5280-11ea-8c87-809b08c920e9.png)

Expected behaviour
--
The inspection/quick fix does not get triggered, because it breaks the code: https://3v4l.org/rVXrV

**Comment by kalessil** [comment]
Fixed!
