### ISSUE TITLE
toString ignores property type declaration

### ISSUE THREAD

**Issue by garak** [kalessil/phpinspectionsea#1530]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 4.0.3 |
| Language level | PHP 7.4                        |

```php
<?php

final class Foo
{
    private string $bar;

    private static array $allowedValues = [0 => 'foo', 1 => 'bar', 2 => 'baz'];

    public function __construct(int $key)
    {
        if (!isset(self::$allowedValues[$key])) {
            throw new \InvalidArgumentException();
        }
        $this->bar = self::$allowedValues[$key];
    }

    public function __toString(): string
    {
        return $this->bar;
    }
}
```

In the code above, I get "[EA] __toString must return string." error.

I'm expecting to avoid such error, since my property can't be anything but a string (being declared as such)

--

Environment details
---

PhpStorm 2019.3.3
Build #PS-193.6494.47, built on February 12, 2020
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-42-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1936M
Cores: 4
Registry: run.processes.with.pty=TRUE, documentation.show.toolbar=true
Non-Bundled Plugins: com.alayouni.ansiHighlight, com.bashorov.mainMenuToggler, com.intellij.ideolog, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.php.annotation, de.espend.idea.php.phpunit, fr.adrienbrault.idea.symfony2plugin, izhangzhihao.rainbow.brackets, name.kropp.intellij.makefile, org.jetbrains.plugins.node-remote-interpreter, org.psliwa.idea.composer

**Comment by kalessil** [comment]
Fixed!
