### ISSUE TITLE
Replace foreach loop with a call to array_column

### ISSUE THREAD

**Issue by JacekAndrzejewski** [kalessil/phpinspectionsea#1534]
Description:
Sometimes people use foreach loop to reindex arrays. But php already has a built-in function for that, array_column. It should be suggested to replace unneccesary foreach loops with calls to array_column. Not only it's more readable but also it should be faster.

Example

```
$array = [
    [
        'id' => 1,
        'text' => 'sometext'
    ],
    [
        'id' => 2,
        'text' => 'anothertext'
    ],
    [
        'id' => 3,
        'text' => 'notext'
    ],
    [
        'id' => 4,
        'text' => 'blahblah'
    ],
];

$result = [];
foreach($array as $item) {
    $result[$item['id']] = $item['text'];
}
```
Last 3 lines can be replaced with
```
$result = array_column($array,'text','id');
```

In general
```
$result = [];
foreach($array as $item) {
    $result[$item[<KEY>]] = $item[<COLUMN>];
}
```
can be replaced with
```
$result = array_column($array,<COLUMN>,<KEY>);
```

There is also one particular example of this
```
$result = [];
foreach($array as $item) {
    $result[$item[<KEY>]] = $item;
}
```
can be replaced with
```
$result = array_column($array,NULL,<KEY>);
```

**Comment by rentalhost** [comment]
Just to be sure... `$result` should be empty initially, right? Else, `array_column()` must replace the original content with the `$array` data.

**Comment by JacekAndrzejewski** [comment]
You are right, for this replacement we need `$result` to be empty or not set. In other cases I would suggest using a temporary variable and additional `array_replace()`. That's because said loop replaces data if it already was there and appends it otherwise. `array_merge()` appends data when numeric keys collide, and that is a different behaviour.

So here

```
$array = [
    [
        'id' => 1,
        'text' => 'sometext',
    ],
    [
        'id' => 2,
        'text' => 'anothertext2',
    ],
    [
        'id' => 3,
        'text' => 'notext',
    ],
    [
        'id' => 4,
        'text' => 'blahblah',
    ],
];

$result = [2 => 'anothertext'];

foreach ($array as $item) {
    $result[$item['id']] = $item['text'];
}
```
We can replace the foreach with either
```
$resultTemp = array_column($array, 'text', 'id');
$result = array_replace($result, $resultTemp);
```
or with
```
$result = array_replace($result, array_column($array, 'text', 'id'));
```
All of those 3 give the same results. Well, maybe in some cases not, documentation says that `array_replace()` can return a NULL instead of array when error occurs, but I have no clue when that could happen.

**Comment by JacekAndrzejewski** [comment]
I found similar thing and I don't know if I should make new issue for it, because replacement is really similar.
```
$result=array_combine(array_column($data, 'id'), $data);
```
can be replaced with
```
$result=array_column($data, NULL, 'id');
```

**Comment by ea-inspections-team** [comment]
Thanks for reporting @JacekAndrzejewski ! We've been recently working on similar patterns, as part of refactoring in Php Inspections (EA Ultimate). Hence closing as duplicate.
