### ISSUE TITLE
__sleep() array return value type incorrectly identified

### ISSUE THREAD

**Issue by Synchro** [kalessil/phpinspectionsea#1535]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended), 4.0.3 |
| Language level | PHP 7.3                        |

## Current behaviour

The array returned by my `__sleep` method is not identified as an array:
![image](https://user-images.githubusercontent.com/81561/77166253-35f30d00-6ab4-11ea-9576-9c60c4ef09b6.png)

and yet...

![image](https://user-images.githubusercontent.com/81561/77166316-51f6ae80-6ab4-11ea-9baf-ecd6a7421ce5.png)

I get this in all my classes that have `__sleep` methods, but there are no syntax errors or other major issues flagged in them. It doesn't make any difference if I declare the return value from the function or in a phpdoc.

### Expected behaviour
`__sleep` return value is identified as an array when it is an array.

### Environment details
PhpStorm 2020.1 EAP
Build #PS-201.6487.22, built on March 19, 2020
macOS 10.14.6

**Comment by rentalhost** [comment]
I could confirm using last available version (U3.0.8.1). Bot `__sleep()`, `__serialize()` and `__debugInfo()` is also affected ([code](https://github.com/kalessil/phpinspectionsea/blob/cd797453da82dcc945bf3fa38c114975ccaffde5/src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/magicMethods/MagicMethodsValidityInspector.java#L167)).

**Comment by kalessil** [comment]
Duplicates #1557 (fixed today).
