### ISSUE TITLE
Factory classes recognition: add settings for specifying factory methods prefixes

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#154]
Follow-up of #126

**Comment by funivan** [comment]
http://verraes.net/2014/06/named-constructors-in-php/ article for new developers =)

@kalessil maybe we can contact author, rewrite article according to the latest php (php7) version and add it to the `docs` of this project ? Or just add it and post a link to the authors page =)

**Comment by kalessil** [comment]
I'd write a brief chapter about the inspection and added the article as it is.
Term `Named constructors` is pretty questionable, but the article content looks like a good reference to naming practices we are promoting here.

//cc @Fleshgrinder

**Comment by kalessil** [comment]
Since I dropped design-patterns related inspections, closing this one as well.
