### ISSUE TITLE
False positive:  resolved index type 

### ISSUE THREAD

**Issue by paveldvorak5** [kalessil/phpinspectionsea#1541]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 3081 |
| Language level | PHP 7.4     |

Current behaviour
--
It says get_class can return false if parameter is and object
![obrazek](https://user-images.githubusercontent.com/14863835/78502726-0863c000-7752-11ea-8fa9-ca974ccf9269.png)

Expected behaviour
No error

Environment details
PhpStorm 2020.1 RC
Build #PS-201.6668.78, built on April 2, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.19.0-8-amd64
GC: ParNew, ConcurrentMarkSweep
Memory: 1450M
Cores: 6
Registry: run.processes.with.pty=TRUE, ide.editor.tabs.open.at.the.end=true, bigger.font.in.project.view=true, documentation.show.toolbar=true, debugger.valueTooltipAutoShowOnSelection=true, ide.tooltip.initialDelay=199, vcs.annotations.preload=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: zielu.gittoolbox, com.chrisrm.idea.MaterialThemeUI, com.jetbrains.annotations.preloader, com.mallowigi, commit-template-idea-plugin, de.netnexus.camelcaseplugin, krasa.CpuUsageIndicator, com.kalessil.phpStorm.phpInspectionsUltimate, de.espend.idea.php.phpunit, lv.midiana.misc.phpstorm-plugins.deep-keys, net.king2500.plugins.PhpAdvancedAutoComplete, ru.adelf.idea.dotenv, izhangzhihao.rainbow.brackets
Current Desktop: GNOME-Classic:GNOME

**Comment by kalessil** [comment]
@paveldvorak5 : looks like we can exclude the possible false from function return types - it'll emit warnings, so we are good.

**Comment by kalessil** [comment]
Fixed!
