### ISSUE TITLE
Mkdir Race Condition

### ISSUE THREAD

**Issue by AlexeyKosov** [kalessil/phpinspectionsea#1544]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 4.0.3 |
| Language level | PHP 7.2 |

Question
--

https://github.com/kalessil/phpinspectionsea/blob/master/docs/probable-bugs.md#mkdir-race-condition

The suggested fix for 
```
    /* before */
    if (!is_dir($directory)) {
        mkdir($directory);
    }
```

is 

```
    /* after */
    if (! is_dir($directory) && ! mkdir($directory) && ! is_dir($directory)) {
        throw new \RuntimeException(sprintf('Directory "%s" was not created', $directory));
    }
```

But in [PHP docs](https://www.php.net/manual/en/function.is-dir.php), it's stated that `is_dir` results are cached: 

>     Note: The results of this function are cached. See clearstatcache() for more details.

So the question is: does it make any real difference when we call the function twice without clearing the stat cache?

**Comment by dryabov** [comment]
I could be wrong, but only successful (i.e. existing files/dirs) calls seem to be cached (see https://github.com/php/php-src/blob/master/main/streams/streams.c#L1982).

**Comment by AlexeyKosov** [comment]
@dryabov Thanks for checking into it, makes sense now. Probably, it should have been reflected in PHP docs.

**Comment by kalessil** [comment]
@dryabov, @AlexeyKosov: is there anything to document on our side?

**Comment by AlexeyKosov** [comment]
@kalessil No, your docs are fine. I meant PHP docs: https://www.php.net/is_dir

**Comment by kalessil** [comment]
@AlexeyKosov: super, thank you for clarification!
