### ISSUE TITLE
Inspection of typed properties in classes that have a parent at the vendor

### ISSUE THREAD

**Issue by wilcorrea** [kalessil/phpinspectionsea#1545]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin               | Php Inspections (EA Extended), 4.0.3 |
| Language level | PHP 7.4                                                                                                |

Question
--

I am getting warnings about typed properties, but I cant override the parent that is a vendor (laravel)

My class:
![image](https://user-images.githubusercontent.com/803733/79672978-d0766700-81ac-11ea-9caf-06ee9cc942bb.png)

Their class:
![image](https://user-images.githubusercontent.com/803733/79672998-061b5000-81ad-11ea-943a-771947b54ffb.png)

Is it possible the inspections be conditional in this cases?

**Comment by kalessil** [comment]
Thank you for reporting @wilcorrea. Depends on which inspection it is, what's the exact message there?

**Comment by wilcorrea** [comment]
The message is: "Missing property's type declaration"

![image](https://user-images.githubusercontent.com/803733/80213901-485eea00-8610-11ea-82b4-c12ead1c4ec1.png)

**Comment by kalessil** [comment]
@wilcorrea: this an IDE bundled inspection. All EA Extended messages are starting with '[EA] ' prefix, to not confuse devs =) Closing the issue as a third-party.

**Comment by wilcorrea** [comment]
Ohhhh, it is true! Sorry!
Thanks for clarifying @kalessil
