### ISSUE TITLE
with phpunit 9: assertContains is deprecated

### ISSUE THREAD

**Issue by michabbb** [kalessil/phpinspectionsea#1548]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 4.0.3 |
| Language level | PHP 7.4                        |

Current behaviour
--
```php
$this->assertTrue(in_array('PNG', $supportedFormats, true));
```
![image](https://user-images.githubusercontent.com/3524595/80216528-74915f80-863e-11ea-9704-952b82074d68.png)

if i follow this suggestion, i end up here:

```php
$this->assertContains('PNG', $supportedFormats);
```

where phpstorm says: it´s deprecated

![image](https://user-images.githubusercontent.com/3524595/80216713-c5a15380-863e-11ea-8f5a-210fc5790147.png)

Expected behaviour
--
i don´t know, but i guess i shouldn't get a recommendation for a deprecated function 

Environment details
---
PhpStorm 2020.1.1 Preview
Build #PS-201.7223.29, built on April 20, 2020
Runtime version: 11.0.6+8-b765.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
phpunit/phpunit: 9.0.1

**Comment by kalessil** [comment]
@michabbb: so, after deep dive I'm pretty sure that my plugin suggests correct replacement which doesn't change behaviour. The suggestion from PhpStorm is probably incorrect, so probably it worth filing a bug in JetBrains bug-tracker.

**Comment by michabbb** [comment]
@kalessil here: https://github.com/sebastianbergmann/phpunit/issues/3426 sebastian says:

> Remove support for using assertContains() and assertNotContains() on string haystacks

and my example here shows a "string haystack". when i change my code from:

```php
$this->assertContains('PNG', $supportedFormats);
```
to
```php
$this->assertContains(['PNG'], $supportedFormats);
```
phpstorm no longer gives me a warning, because the my haystack is no longer a string.
so i´m sure, you have overseen this situation here: phpstorm is 100% right and based on the parameters, you are offering a "deprecated" function, which is not helpful 😏

**Comment by kalessil** [comment]
Snap, thank you for more input @michabbb. I limited the behavior so it appears only for PhpUnit below v9.0. PhpStorm will take care of migration according to your feedback.
