### ISSUE TITLE
Backslash should not be suggested before magic constants

### ISSUE THREAD

**Issue by BenMorel** [kalessil/phpinspectionsea#155]
Take the following code:

    echo __METHOD__;

This plugin will underline `__METHOD__` and suggest the following:

> Using '`\__METHOD__`' would enable some of opcache optimizations

This is correct with traditional constants, but is wrong in the case of [magic constants](http://php.net/manual/en/language.constants.predefined.php). When a leading backslash is used with these, you get a parse error:

    echo \__METHOD__;

> ParseError: syntax error, unexpected '`__METHOD__`' (T_METHOD_C), expecting identifier (T_STRING)

This inspection should be disabled for all the constants listed in the above link.

**Comment by kalessil** [comment]
Thank you for reporting @BenMorel, working on it.

**Comment by kalessil** [comment]
Fixed by ede5e0f827d6ff8728c2d5198fda067ac34e9148

**Comment by BenMorel** [comment]
Wow that was fast, thanks a lot!

**Comment by kalessil** [comment]
Bugfixing goes with higher prio and are fast to fix, but features needs staging time ;)
