### ISSUE TITLE
FP: "may not support offset operations" with "explode()"

### ISSUE THREAD

**Issue by voku** [kalessil/phpinspectionsea#1550]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 3.0.9  |
| Language level | PHP 7.2                |

Current behaviour
--
```php
$label = 'foo:&nbsp;lall';
$labels = explode(':', $label);
$foo = explode('&nbsp;', $labels[1]);

var_dump($foo);
```

-> but it shows this error:

> [EA] '$labels' may not support offset operations (or its type not annotated properly: [bool, array]).
> $labels false|string[]

Expected behaviour
--
no errors because "explode" only return "false" if the first parameter is an empty string

Environment details
---
PhpStorm 2020.1
Build #PS-201.6668.153, built on April 13, 2020
Licensed to Portable UTF-8 / Lars Moelleken
Subscription is active until February 27, 2021
For non-commercial open source development only.
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-177-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 5120M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.tooltip.initialDelay=885, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.dubreuia, uk.co.ben-gibson.remote.repository.mapper, Key Promoter X, String Manipulation, com.alayouni.ansiHighlight, com.andrey4623.rainbowcsv, com.intellij.ideolog, com.upsolver.PreCommitHook, dev.arunvelsriram.desccron, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, net.seesharpsoft.intellij.plugins.csv, net.vektah.codeglance, tanvd.grazi, ru.adelf.idea.dotenv, NEON support, de.espend.idea.php.toolbox, lv.midiana.misc.phpstorm-plugins.deep-keys, com.kalessil.phpStorm.phpInspectionsUltimate, me.artspb.idea.eval.plugin, net.king2500.plugins.PhpAdvancedAutoComplete, izhangzhihao.rainbow.brackets
Current Desktop: Unity

**Comment by kalessil** [comment]
I added logic to infer type for this case.

Still, there are a lot of places where native IDE types solver can not be aggregated, so array|false will definitely pop up again.

**Comment by voku** [comment]
Thanks for the fix. :+1:
