### ISSUE TITLE
Harden errors handling with JSON_THROW_ON_ERROR will add an option too many.

### ISSUE THREAD

**Issue by MetalArend** [kalessil/phpinspectionsea#1555]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 3.0.9.1 |
| Language level | PHP 7.4                        |

Current behaviour
--
`json_encode($value)` is marked by the inspection "[EA] Harden errors handling", and after accepting it, it becomes `json_encode($value, JSON_THROW_ON_ERROR)`. But it still gets marked by the inspection "[EA] Harden errors handling" to change it to `json_encode($key, JSON_THROW_ON_ERROR | JSON_THROW_ON_ERROR)`.

Expected behaviour
--
I think `json_encode($value, JSON_THROW_ON_ERROR)` should be good enough. If there's already a JSON_THROW_ON_ERROR, it should not be added once again to the list.

**Comment by kalessil** [comment]
@MetalArend : I added the case into test cases and it gets no reports. Not sure why, but I can not reproduce.

**Comment by kalessil** [comment]
@MetalArend : btw, which PhpStorm version is it?

**Comment by rentalhost** [comment]
I be able to reproduce it, but I do not have a clue why:

![image](https://user-images.githubusercontent.com/421851/82123527-4cde7480-9770-11ea-8ae0-6837b181d259.png)
![image](https://user-images.githubusercontent.com/421851/82123533-536cec00-9770-11ea-8960-138f42d94877.png)

**Comment by darthf1** [comment]
Hi @kalessil, I noticed you closed the issue as "not able to reproduce".

I'm on PhpStorm 2020.1.3 with  Php Inspections (EA Extended) 4.0.5. and have the same issue.

Before:
![image](https://user-images.githubusercontent.com/17253332/88182099-115c9c80-cc30-11ea-925c-8afd200ecd40.png)

After:
![image](https://user-images.githubusercontent.com/17253332/88182042-f9851880-cc2f-11ea-8b8d-b5f3a2f8dff7.png)

**Comment by kalessil** [comment]
Hi @rentalhost @darthf1 , I made another attempt to fix the issue in db20a997169fdcbd75454876d1284154ae3cc944 (can not reproduce though, but probably it's the constant resolving issue).

**Comment by darthf1** [comment]
Hi @kalessil, apologies for not getting back to you sooner.

How can I retrieve your change? My plugin still says v4.0.5 from July 07, 2020.
