### ISSUE TITLE
Loop inspection not working on blade templates

### ISSUE THREAD

**Issue by vituxre** [kalessil/phpinspectionsea#1556]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) v4.0.4.1 |
| Language level | PHP 7.2                  |
|PhpStorm|2020.1.1|

it drops the inspection even tho it shouldn't, the loop actually properly loops thru array so warning shouldn't be here

![Screenshot 2020-05-05 10 36 08](https://user-images.githubusercontent.com/2478416/81052938-3efd3980-8ebc-11ea-8fe6-922f79ffbfd3.png)

**Comment by kalessil** [comment]
Fixed!
