### ISSUE TITLE
_sleep must return array

### ISSUE THREAD

**Issue by arueckauer** [kalessil/phpinspectionsea#1557]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin               | Php Inspections (EA Extended), 4.4.0.1 |
| Language level | PHP 7.2                                                 |

What does that message mean? I don't understand what inspection is trying to tell me here.

![Magic method declaration violation](https://user-images.githubusercontent.com/1815979/81286274-11052a00-9061-11ea-941e-db06f2d036a3.jpg)

**Comment by kalessil** [comment]
@arueckauer : added new test cases to cover your code snipplet. Unfortunately can not reproduce. Which PhpStrom version is it?

**Comment by kalessil** [comment]
Okay, reproduced in CI. It's 2020.1, will check how to fix.

**Comment by kalessil** [comment]
Fixed!
