### ISSUE TITLE
false possitive warnings

### ISSUE THREAD

**Issue by mitsh** [kalessil/phpinspectionsea#1558]
![image](https://user-images.githubusercontent.com/895798/81296435-947f4500-907a-11ea-8eed-176a99d0b29d.png)
![image](https://user-images.githubusercontent.com/895798/81296450-98ab6280-907a-11ea-8963-f9be2478f0b8.png)

**Comment by kalessil** [comment]
Thank you for reporting @mitsh.

1) Works, I tested locally (the suggested replacement is correct).
2) IDE resolves $CONF as 'array|string' (and ignores workflow in this case), so the warning gets there. I can only suggest using separate variables as e.g. $configuration/$configurationFileContent, so IDE could properly recognize types there.

**Comment by mitsh** [comment]
@kalessil thanks
