### ISSUE TITLE
Cannot iterate inspection

### ISSUE THREAD

**Issue by mirago** [kalessil/phpinspectionsea#156]
I have a 'Collection' object, which extends another object, which implements an interface that extends Countable, IteratorAggregate, ArrayAccess interfaces. When I loop through this object, I get an inspection 'Can not iterate. Must implement one of Iterator interfaces'. I was wondering if it would be possible to fix this?

**Comment by rentalhost** [comment]
Please, post a reduced code to we check it better. You are running last version of PS and EA?

**Comment by kalessil** [comment]
As @rentalhost mentioned, a code snippet and PhpStorm version would help to find where the issue is.
I recall something similar in older EAP versions, but really need the mentioned information.

**Comment by mirago** [comment]
@kalessil @rentalhost Sorry guys, apparently there was a different class in phpdoc which indeed does not implement iterator interface.. Really sorry for this, should have tried to replicate it in the first place, as that helped to find out what's wrong.  Thank you for quick reply though!

**Comment by kalessil** [comment]
@mirago : no worries, we are happy to help :)
