### ISSUE TITLE
missing "[EA] Null pointer exception may occur here." in non class files

### ISSUE THREAD

**Issue by dmitriyha** [kalessil/phpinspectionsea#1563]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended)  4.0.4.1 |
| Language level | PHP 7.4                     |

Current behaviour
--
The inspection works fine on class level, as shown in this example:
![image](https://user-images.githubusercontent.com/3742709/82083518-88d2f480-96f2-11ea-890a-c863f80657bb.png)

but if you do the same in a regular file, you won't get the inspection:
![image](https://user-images.githubusercontent.com/3742709/82083648-bd46b080-96f2-11ea-9408-8b0cf14fff04.png)

Expected behaviour
--
The second example should have the same inspection as the first example

Environment details
---

Below it says win10, but the same result can be achieved on Ubuntu

PhpStorm 2020.1.1
Build #PS-201.7223.96, built on April 30, 2020
Runtime version: 11.0.6+8-b765.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 4
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: com.github.lppedd.idea-conventional-commit, com.intellij.ideolog, mobi.hsz.idea.gitignore, BashSupport, com.kalessil.phpStorm.phpInspectionsEA, org.psliwa.idea.composer

**Comment by ea-inspections-team** [comment]
Thanks for reporting @dmitriyha !

Unfortunately, this is the intended behaviour - the inspection is not analyzing global scope (the second case) 
as we can not provide stable and reliable results there. Sorry.
