### ISSUE TITLE
Optimize ternary operator

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#1568]
```php
// Non-optimized.
return $a ? ($b ? $c : $d) : $d;
```

Only if `$a` and `$b` is truth, `$c` is returned, else will be always `$d`.

```php
// Optimized.
return $a && $b ? $c : $d;
```

**Comment by kalessil** [comment]
@rentalhost : working on it. Once done, we'll also release all ultimate specific patterns from NullCoalescingOperatorCanBeUsedInspector, so extended folks gets more awesome stuff.

**Comment by kalessil** [comment]
Done!
