### ISSUE TITLE
is_array() resulting in "Makes no sense, because this type is not defined in annotations"

### ISSUE THREAD

**Issue by reedy** [kalessil/phpinspectionsea#1570]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended), 4.0.4.1 |
| Language level | PHP 7.2                    |

Current behaviour
--
Plugin gives "Makes no sense, because this type is not defined in annotations" on an is_array() call, when the default is an array

<img width="676" alt="Screenshot 2020-05-25 at 00 17 53" src="https://user-images.githubusercontent.com/67615/82767155-380f7a00-9e1d-11ea-923f-233e93e5b03a.png">

function defintion is (with no php docs)

```lang=php
	public function selectSQLText( $table, $vars, $conds = '', $fname = __METHOD__,
		$options = [], $join_conds = []
	) {
```

https://github.com/wikimedia/mediawiki/blob/master/includes/libs/rdbms/database/Database.php#L1882-L1967

super method definition is

```lang=php
	 * Take the same arguments as IDatabase::select() and return the SQL it would use
	 *
	 * This can be useful for making UNION queries, where the SQL text of each query
	 * is needed. In general, however, callers outside of Database classes should just
	 * use select().
	 *
	 * @see IDatabase::select()
	 *
	 * @param string|array $table Table name
	 * @param string|array $vars Field names
	 * @param string|array $conds Conditions
	 * @param string $fname Caller function name
	 * @param string|array $options Query options
	 * @param string|array $join_conds Join conditions
	 * @return string SQL query string
	 */
	public function selectSQLText(
		$table,
		$vars,
		$conds = '',
		$fname = __METHOD__,
		$options = [],
		$join_conds = []
	);
```

I know it should have phpdoc/at least `@inheritDocs`, but as it's defaulting to an empty array, it certainly could be an array

Expected behaviour
--
Not complain about it making no sense, because the default is an array

Environment details
---
```
PhpStorm 2020.1.2 Preview
Build #PS-201.7846.17, built on May 14, 2020
Licensed to MediaWiki / Sam Reed
Subscription is active until April 30, 2021
For non-commercial open source development only.
Runtime version: 11.0.7+10-b765.53 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.ssh.library.backend.webDeployment.use.sshj=false
Non-Bundled Plugins: com.kalessil.phpStorm.phpInspectionsEA, org.mediawiki
```

**Comment by orklah** [comment]
Well, in your example, the default is an empty string. It's the parent default that is an empty array.

So, as long as there is no docblock on the child method, Static Analysis sees a string only...

**Comment by reedy** [comment]
Oh. Duh. I misread it. I thought it was an array. I'll blame being tired. Sorry!
