### ISSUE TITLE
FP: "Unknown inspection"

### ISSUE THREAD

**Issue by voku** [kalessil/phpinspectionsea#1571]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 3.0.9.1  |
| Language level | PHP 7.2                |

Current behaviour
--

If I try to mute js error in php, I see many "[EA] Unknown inspection" notices.

```php
<?php

/* @noinspection FunctionNamingConventionJS */
/* @noinspection JSLastCommaInObjectLiteral */
/* @noinspection UnnecessaryLabelJS */
/* @noinspection ReservedWordAsName */
/* @noinspection JSJQueryEfficiency */
// ...
```

Expected behaviour
--
no error

Environment details
---
PhpStorm 2020.1.1
Build #PS-201.7223.96, built on April 30, 2020
Subscription is active until February 27, 2021
Runtime version: 11.0.6+8-b765.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-178-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 5120M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.tooltip.initialDelay=885, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.dubreuia, uk.co.ben-gibson.remote.repository.mapper, Key Promoter X, String Manipulation, com.alayouni.ansiHighlight, com.andrey4623.rainbowcsv, com.intellij.ideolog, com.upsolver.PreCommitHook, dev.arunvelsriram.desccron, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, net.seesharpsoft.intellij.plugins.csv, net.vektah.codeglance, izhangzhihao.rainbow.brackets, ru.adelf.idea.dotenv, NEON support, lv.midiana.misc.phpstorm-plugins.deep-keys, de.espend.idea.php.toolbox, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, com.kalessil.phpStorm.phpInspectionsUltimate, me.artspb.idea.eval.plugin, net.king2500.plugins.PhpAdvancedAutoComplete, de.espend.idea.php.generics
Current Desktop: Unity

**Comment by orklah** [comment]
I'm curious, does this happens when you have JS code in a .php file that needs to be suppressed or is it something else entirely?

**Comment by voku** [comment]
@orklah yes we have some js stuff (e.g. select2 and other UI stuff) that are used directly in the php  code :-/

**Comment by InvisibleSmiley** [comment]
My problem is probably related:
```
/** @noinspection HtmlUnknownTarget */
```
from such a line:
```
$link = sprintf('Please <a href="%s">authenticate</a> first', $authUrl);
```

I can open a separate issue for that if you want but I reckon JS and HTML language injections are similar enough.

**Comment by kalessil** [comment]
Ooooookay, l think I have a solution for this. Will check if it's performance is in reasonable borders...

**Comment by kalessil** [comment]
Fixed!

**Comment by voku** [comment]
Thanks for the fix. :+1:

**Comment by voku** [comment]
Here is one more "Unknown inspection":

```/** @noinspection SqlRedundantOrderingDirection */``` === "[EA] Unknown inspection: SqlRedundantOrderingDirection."

**Comment by ea-inspections-team** [comment]
Hey @voku, thanks for leaving a comment. `SqlRedundantOrderingDirection` should probably be `SqlRedundantOrderingDirectionInspection`, but what's placed by IDE when you suppress original warning at the statement level?
