### ISSUE TITLE
Error when marking a composer.json as text

### ISSUE THREAD

**Issue by BinaryKitten** [kalessil/phpinspectionsea#1572]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         |  Php Inspections (EA Ultimate), 3.0.9.1 |
| Language level | e.g. PHP 7.2 settings synced with composer.json        |

Current behaviour
Marking non-project synced composer.json "as text" triggers an IDE Fatal Error

In project we have multiple directories which pertain to the live site. this includes a "bin" directory and a laravel directory both of which have a composer.json

The Composer settings for current project is set to point to the laravel/composer.json (Sync)
When marking the bin/composer.json as plain text, while having a PHP class with json_encode call in code, triggers an exception: 
java.lang.AssertionError: PSI can be created only for a file with LanguageFileType but actual is class com.intellij.openapi.file.exclude.EnforcedPlainTextFileType.

Expected behaviour
-- No Error occurs as this file is not the one to be referenced 

Environment details
---PhpStorm 2020.1.1
Build #PS-201.7223.96, built on April 30, 2020
Licensed to 
Subscription is active until March 22, 2021
Runtime version: 11.0.6+8-b765.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.4.0-31-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1929M
Cores: 12
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: mobi.hsz.idea.gitignore, com.alicannklc.tailwind, com.bum.intellij.tailwindcss, to.bri.intellij.clubhouse, com.mallowigi, BashSupport, ru.adelf.idea.dotenv, de.espend.idea.laravel, com.kalessil.phpStorm.phpInspectionsUltimate, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, org.asciidoctor.intellij.asciidoc
Current Desktop: XFCE

[ide-stacktrace.txt](https://github.com/kalessil/phpinspectionsea/files/4685371/ide-stacktrace.txt)

**Comment by kalessil** [comment]
Thank you for reporting @BinaryKitten, I'll take care of fixing this =)

**Comment by kalessil** [comment]
Fixed!
