### ISSUE TITLE
BadExceptionsProcessingInspection triggered on single json-statement

### ISSUE THREAD

**Issue by puggan** [kalessil/phpinspectionsea#1585]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate) 3.0.9.1 |
| Language level | PHP 7.4 |

Current behaviour
--
```
        try {
            $data = \json_decode($this->data, false, 512, JSON_THROW_ON_ERROR);
        } catch (\JsonException $ignore) {
            $data = $this->data;
        }
```
![Screenshot from 2020-06-18 01-54-07](https://user-images.githubusercontent.com/866668/84962216-9ff86e00-b106-11ea-9633-6591b42cee30.png)

Expected behaviour
--
BadExceptionsProcessingInspection should only trigger when you have 4 or more statements in the try-part?

Environment details
---
PhpStorm 2020.2 EAP
Build #PS-202.5428.31, built on June 12, 2020
PhpStorm EAP User
Expiration date: July 12, 2020
Runtime version: 11.0.7+10-b931.3 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-37-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1923M
Cores: 8
Registry: run.processes.with.pty=TRUE, documentation.show.toolbar=true
Non-Bundled Plugins: Shell Process, String Manipulation, in.xiv.cs, name.kropp.intellij.makefile, net.seesharpsoft.intellij.plugins.csv, net.vektah.codeglance, org.intellij.RegexpTester, com.wix.eslint, intellij.prettierJS, com.aurimasniekis.phppsr4namespacedetector, de.espend.idea.laravel, com.kalessil.phpStorm.phpInspectionsUltimate, com.raket.silverstripe, net.king2500.plugins.PhpAdvancedAutoComplete, izhangzhihao.rainbow.brackets
Current Desktop: ubuntu:GNOME

**Comment by kalessil** [comment]
@puggan : the inspection report multiple cases:
```java
    private static final String messagePattern          = "Consider moving non-related statements (%s in total) outside the try-block or refactoring the try-body into a function/method.";
    private static final String messageFailSilently     = "The exception being ignored, please don't fail silently and at least log it.";
    private static final String messageChainedException = "The exception being ignored, please log it or use chained exceptions.";
    private static final String messageRethrown         = "The exception being re-throws without any processing.";
```

In this case it's probably asking to handle $ignore (e.g. logging or checking error code).
.
