### ISSUE TITLE
'$parts' may not support offset operations (or its type not annotated properly: [bool, array]).

### ISSUE THREAD

**Issue by WinterSilence** [kalessil/phpinspectionsea#1586]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 
| Language level | PHP 7.2                       |

~~~
$parts = explode('-', $language);
foreach ([$parts[0], implode(DIRECTORY_SEPARATOR, $parts)] as $path) {
~~~
> [EA] '$parts' may not support offset operations (or its type not annotated properly: [bool, array]). 
 Inspection info: Analyzes offset operations (adding to index, index-based read, write, etc.) and reports issues found.

But it's can be only
> If delimiter is an empty string (""), explode() will return FALSE.

**Comment by torvista** [comment]
If you put in a check for $parts !== false before using it as an array, EA error is cleared.

**Comment by WinterSilence** [comment]
> 
> 
> If you put in a check for $parts !== false before using it as an array, EA error is cleared.

extended code it's not solution, plugin can check first argument and ignore constant if it not empty string

**Comment by torvista** [comment]
I'm not sure what you mean, but what I was pointing out is that the result of explode can be an array or false.
So $parts[0] may not exist (if $parts === false).
If you use a check on $parts before using $parts as an array, the EA error is cleared as $parts is proved to be array.
```
$parts = explode('-', $language);
if ($parts !== false) {
foreach ([$parts[0], implode(DIRECTORY_SEPARATOR, $parts)] as $path) {
```
I'm not saying what is right or wrong, just pointing out what is needed to remove the error, which I think is correct: the condition of $parts **should** be checked before using it.

**Comment by WinterSilence** [comment]
@torvista
> If separator is an empty string (""), explode() will return false.
https://www.php.net/manual/en/function.explode.php

but it's can't be because first argument is string-constant `'-'`

**Comment by torvista** [comment]
Yes you are are right/I understand, explode can **only** return false if the separator is an empty string.
So the EA should check for that condition and the check I suggested is not applicable if the separator is not empty.

**Comment by ea-inspections-team** [comment]
Thanks for reporting @WinterSilence and @torvista for joining the discussion!
This issue duplicates #1550, which has been fixed already.
