### ISSUE TITLE
Only when the alias passed to class_alias starts with a backslash, this triggers the inspection "::class can be used".

### ISSUE THREAD

**Issue by Inwerpsel** [kalessil/phpinspectionsea#1589]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) version 4.0.4.1 |
| Language level | e.g. PHP 7.2                        |

**Current behaviour**:
When the alias passed to `class_alias` starts with a backslash, this triggers the inspection "::class can be used" and presents the action to change it to a ::class notation. After performing the action no inspections or warnings are shown, even though the code would run into a fatal error, because there is no class definition when the argument is evaluated.

If you navigate to the declaration of the non-existent class, this jumps the cursor to the beginning of the file the `class_alias` call is in. So likely the inspection (or PHPStorm, or both) is not taking into to account that it should handle class references differently when they are passed as the second argument to `class_alias`. 

Note that the fact that it doesn't pick up the fatal error actually happens independently from the first issue (that it presents the action to change it), both with and without leading underscore. So it might be a separate issue, but likely both issues have the same underlying cause.
![Screenshot from 2020-06-25 19-03-19](https://user-images.githubusercontent.com/7604138/85768973-ddb65180-b719-11ea-9cd2-fb8e87579299.png)
![Screenshot from 2020-06-25 19-03-37](https://user-images.githubusercontent.com/7604138/85768996-e27b0580-b719-11ea-9e17-2f5c5a4c24f2.png)
![Screenshot from 2020-06-25 19-04-12](https://user-images.githubusercontent.com/7604138/85769008-e4dd5f80-b719-11ea-8e11-ed3d701f6e3e.png)

--

**Expected behaviour**:
* The intention to change to a ::class notation should not be shown for the alias passed to `class_alias` (maybe unless it's referencing a class that is declared outside.).
* If the code passes a ::class reference as the second argument it should notice this as a fatal error if that class doesn't exist somewhere outside the function.

**Environment details**
PhpStorm 2020.1.2
Build #PS-201.7846.90, built on June 3, 2020
Runtime version: 11.0.7+10-b765.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.3.0-59-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 4012M
Cores: 12
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false
Non-Bundled Plugins: uk.co.ben-gibson.remote.repository.mapper, IdeaVIM, name.kropp.intellij.makefile, ru.adelf.idea.dotenv, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, org.sylfra.idea.plugins.linessorter
Current Desktop: ubuntu:GNOME

**Comment by orklah** [comment]
Using ::class on a inexistant symbol shouldn't cause any error:
https://3v4l.org/R8aEe

It doesn't call the autoloader either.

This syntax is more to show intent of using a class than using a real symbol. You can do that sort of thing for example:
https://3v4l.org/VDmq9

We can indeed argue if class_alias is a legitimate use of this syntax(because the class won't ever exists as such), but I'm personnally in favor of it because it can help IDE with symbol search

**Comment by Inwerpsel** [comment]
> Using ::class on a inexistant symbol shouldn't cause any error:
> https://3v4l.org/R8aEe
> 
> It doesn't call the autoloader either.
Wow I should have checked this before blindly opening this ticket, I was assuming it behaved like other references to classes and wasn't aware that it treats it that way.

But given that ::class works like that, maybe to remove confusion the inspection should also show when there is no underscore preceding the class? I assume now it's not detecting whether these strings could be intended class names any differently than strings in other places. However in this case you can assume that everything as the 2nd argument of `class_alias` is intended as a class name.

**Comment by orklah** [comment]
I'd expect the same warning with or without the backslash indeed.

And yeah, given that class_alias will expect a valid class name, the ::class syntax will at least permit IDE/compiler checks to see if the symbol is legal (like no spaces, no reserved keyword...)

**Comment by kalessil** [comment]
Fixed!

**Comment by kalessil** [comment]
@orklah: inspection should not check calss_alias's second argument at all, I totally missed this use-case originally.
