### ISSUE TITLE
Suggest to use class constants instead of static properties

### ISSUE THREAD

**Issue by funivan** [kalessil/phpinspectionsea#159]
Source: @Fleshgrinder
> We could check the configured PHP version for the project and recommend the usage of a [public] const instead of a public static.

In some cases we can convert class static property to the class constant.

For example we have following code:
```php
class User{
 public static $statuses = [
   'a'=>'Active',
   'd'=>'Deleted',
 ];
}
```
Inspection can handle property `$statuses` and suggest to use constant:
```php
 class User{
    const STATUSES = [
      'a'=>'Active',
      'd'=>'Deleted',
    ];
  }
```

This inspection can be implemented in different ways:
1. Detect static property in class and suggest to use Constant
2. Check if all references to the property are Read Only. (No writes)

I prefer 1 case ;)

**Comment by rentalhost** [comment]
On PHP 7.1, it could checks for privates and protecteds too.

**Comment by Fleshgrinder** [comment]
I prefer case 2, there is nothing wrong about writing to `static` properties.

**Comment by funivan** [comment]
@Fleshgrinder static properties change global state. And global state is always a bad way. 
2 case can be implemented only if we have private property. With public properties it will be hard to scan whole  project and find writes.

**Comment by Fleshgrinder** [comment]
Obviously I was thinking of a max. visibility of `protected` since having a `public` property (other than a DTO) is always a huge smell in my book. 😉

**Comment by kalessil** [comment]
That'd be a complete semantics change, so I'll keep this closed. @funivan: feel free to take the issue over for your plugin.
