### ISSUE TITLE
Reports unnecessary type castings

### ISSUE THREAD

**Issue by licxisky** [kalessil/phpinspectionsea#1591]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 4.0.4.1 |
| Language level | PHP 7.0  |

Current behaviour
--

![image](https://user-images.githubusercontent.com/20389946/85918909-660f3080-b899-11ea-9e4d-a5e1b060edd6.png)

Expected behaviour
--
The result of the expression is still not an integer type, and type conversion should be required, but the plug-in prompt does not

Environment details
---

PhpStorm 2020.2 EAP
Build number #PS-202.5958.28, build at June 25, 2020
PhpStorm EAP User
Expiration date: July 25, 2020
Runtime version: 11.0.7+10-b944.13 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0

**Comment by kalessil** [comment]
Fixed!
