### ISSUE TITLE
plugin recommends PSR-2 despite being deprecated

### ISSUE THREAD

**Issue by RobJonesWeb** [kalessil/phpinspectionsea#1593]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) or Php Inspections (EA Ultimate), 4.0.4.1|
| Language level | e.g. PHP 7.4.0               |

Question
--
When attempting to do if ($something == false) return;

the plugin recommends wrapping the body in braces inline with what PSR-2 advises, but after checking, PSR-2 is now deprecated for PSR-12

**Comment by orklah** [comment]
If I'm not mistaken, It seems like PSR-12 recommends basically the same thing? 

> 5. Control Structures
The body of each structure MUST be enclosed by braces. This standardizes how the structures look and reduces the likelihood of introducing errors as new lines get added to the body.

What would you change for this inspection?

**Comment by RobJonesWeb** [comment]
the message is completely fine, I would just suggest updating the PSR number from 2 to 12 so users looking in to this don't land on a page that says this is deprecated. That is pretty much a curse word to developers ;)

**Comment by kalessil** [comment]
Done!
