### ISSUE TITLE
Warn about counting without checking for Array or Traversable

### ISSUE THREAD

**Issue by pretzlaw** [kalessil/phpinspectionsea#1595]
Description (screenshot):
--

The [count($x)](php.net/count) function returns 1 when x is not an array or Traversable. 

Example
--

```php
$x = new class() {};
if(count($x) > 0)
    shuffle($x);
```

https://3v4l.org/1qr9u

Possible solutions
--

* PHP >= 7.3 : `is_countable($x) && count($x)` 
* other: `(is_array($x) || $x instanceof Traversable) && count($x)` 
* or: `false === empty($x)` (removing the count, which may not be 100% suitable for the dev's situation)

**Comment by kalessil** [comment]
Thank you for reporting @pretzlaw, looks like we have a related issue already: #741 
Hope bug-reports rate lowers with the next releases and we'll get to the feature implementation.
