### ISSUE TITLE
Wrong inspection behavior

### ISSUE THREAD

**Issue by xepozz** [kalessil/phpinspectionsea#1596]
Local variable is needed, but inspection says it isn't
![image](https://user-images.githubusercontent.com/6815714/86882430-ef73fd80-c0f8-11ea-9521-6128c5292b91.png)
![image](https://user-images.githubusercontent.com/6815714/86882439-f1d65780-c0f8-11ea-824a-e982c000d5c1.png)

**Comment by WinterSilence** [comment]
@xepozz `$response` not uses

**Comment by xepozz** [comment]
`$response` is used in `finally` statement

**Comment by WinterSilence** [comment]
@xepozz  you cant use `return $response = ...`

**Comment by orklah** [comment]
> @xepozz you cant use `return $response = ...`

You definitely can:
https://3v4l.org/PiOFX

I'm not sure if you should, but there's no technical issue

**Comment by WinterSilence** [comment]
@orklah technically possible, but this is bad practice:
 > result will be returned after the finally block is executed

if `$response` is object, then it's can be changed in "finally" block

**Comment by xepozz** [comment]
I can move the `return` statement out of try/catch block, but this is a short form looks and works nice, I don't want to do this.

**Comment by kalessil** [comment]
Hm, that pretty awesome use of finally =) I made a fix to support this case.

**Comment by xepozz** [comment]
Thanks!
