### ISSUE TITLE
Optimize to null coalesce operator

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#1599]
```php
$a ? $a->property : null;
```

Could be optimized to:

```php
$a->property ?? null;
```

**Comment by kalessil** [comment]
Implemented! Should we also handle '! empty($a) ? $a->property : null;' ?

**Comment by rentalhost** [comment]
@kalessil seems valid for me!

**Comment by kalessil** [comment]
@davidmpaz : done!

**Comment by rentalhost** [comment]
@kalessil not the same "david", but it is ok! 🤣 Thanks!

Ah, maybe you can do #1568?

**Comment by kalessil** [comment]
@rentalhost : will check =)
