### ISSUE TITLE
FP: str_starts_with() suggestion for PHP7.3 project

### ISSUE THREAD

**Issue by tlamy** [kalessil/phpinspectionsea#1602]
`str_starts_with()` is available from PHP 8.0 (https://wiki.php.net/rfc/add_str_starts_with_and_ends_with_functions).
But it is suggested for my PHP 7.3 project:
![Bildschirmfoto 2020-07-20 um 11 33 14](https://user-images.githubusercontent.com/1841537/87923200-66a47c80-ca7d-11ea-9efe-affc80046fd8.png)
![Bildschirmfoto 2020-07-20 um 11 32 16](https://user-images.githubusercontent.com/1841537/87923211-6a380380-ca7d-11ea-9e92-98dd73e395e0.png)

For some reason, `final boolean isTargetVersion = PhpLanguageLevel.get(holder.getProject()).atLeast(PhpLanguageLevel.PHP800);` in StrStartsWithCanBeUsedInspector.java:51 does not work properly

EA Ultimate 3.0.10

PhpStorm 2020.2 Beta
Build #PS-202.6397.25, built on July 16, 2020
PhpStorm EAP User
Expiration date: August 15, 2020
Runtime version: 11.0.7+10-b944.20 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1638M
Cores: 6
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: String Manipulation, com.alayouni.ansiHighlight, zielu.gittoolbox, org.zalando.intellij.swagger, NEON support, com.kalessil.phpStorm.phpInspectionsUltimate, de.espend.idea.php.annotation, de.espend.idea.php.phpunit, izhangzhihao.rainbow.brackets

**Comment by kalessil** [comment]
@tlamy: looks like a symfony polyfill package for PHP 8 was installed. The plugin finds relevant polyfills even on lower language levels.
