### ISSUE TITLE
"The closure can be replaced with ..." suggests replacing with wrong value

### ISSUE THREAD

**Issue by jdreesen** [kalessil/phpinspectionsea#1608]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate) |
| Language level | PHP 7.4                      |

Current behaviour
--

EA suggests replacing the closure `fn ($id) => Document::getById($id)` inside an `array_map()` with just `'getById'`.

Suggestion:
![grafik](https://user-images.githubusercontent.com/424602/88519384-5565ed80-cff2-11ea-84dd-5de8f9b50f35.png)

Applied suggestion:
![grafik](https://user-images.githubusercontent.com/424602/88519596-a675e180-cff2-11ea-8c85-b87cd7ace4a2.png)

This is obviously wrong.

Expected behaviour
--

It suggests replacing the closure with `[Document::class, 'getById']` instead.

Environment details
---
PhpStorm 2020.1.4
Build #PS-201.8743.18, built on July 22, 2020
Runtime version: 11.0.7+10-b765.65 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 4.15.0-112-generic

**Comment by kalessil** [comment]
Oops, thank you for reporting @jdreesen, I'll take care of fixing this.

**Comment by kalessil** [comment]
@jdreesen, one question here. 

It was intended to work with functions only, so I'm wondering if we should handle methods references at all.
What do you think?

**Comment by jdreesen** [comment]
Well, I somehow like to use the array form (`[Document::class, 'getById']`) instead of closures (`fn ($id) => Document::getById($id)`) when possible.

But with PHP 7.4 and short closures I'd be totally fine if EA doesn't support this.

After all, closures have advantages over arrays, as they're more explicit (especially with multiple arguments).

**Comment by kalessil** [comment]
Uh, happy to hear that. I also prefer using short closures in this specific case.

**Comment by kalessil** [comment]
Well, I actually like using the short closures everywhere =)

**Comment by kalessil** [comment]
Fixed!
