### ISSUE TITLE
Prophecy: Method autocomplete not working with extend/implement addition

### ISSUE THREAD

**Issue by icanhazstring** [kalessil/phpinspectionsea#1609]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 4.0.5 |
| Language level | PHP 7.4                        |

Current behaviour
--
Using prophecy `prophesize` the method autocomplete does not work properly if extended with `willExtend` or `willImplement`. E.h. when dealing with final classes which can't be mocked but implement multiple interfaces.

![image](https://user-images.githubusercontent.com/883543/88530180-463a6c00-d001-11ea-9e5f-9c5e8351bdfe.png)
![image](https://user-images.githubusercontent.com/883543/88530164-3e7ac780-d001-11ea-9ee4-8eddd540b3cc.png)

Expected behaviour
--
Autocomplete should work.

**Comment by kalessil** [comment]
Hi @icanhazstring, I'm trying to better understand what happens. As I understood, adding 'willImplement' causes a false positive, or?

**Comment by icanhazstring** [comment]
Correct. this happens for every method that can be used after `prophesize` which will add more information to the stub.
`willExtend`, `willImplement` and others.

**Comment by kalessil** [comment]
Hi @icanhazstring, I'm checking the related inspections but can not find the related one. What's the exact message show on the highlighted method?

**Comment by icanhazstring** [comment]
![image](https://user-images.githubusercontent.com/883543/89183311-4ef9e780-d597-11ea-8700-93fb0cd9f5b1.png)

**Comment by icanhazstring** [comment]
Also the different type resolution on the variable it self:
Without `willImplement`

![image](https://user-images.githubusercontent.com/883543/89183395-73ee5a80-d597-11ea-8861-dd9f672c5104.png)

With `willImplement`
![image](https://user-images.githubusercontent.com/883543/89183416-7fda1c80-d597-11ea-9912-1bafd8174819.png)

Which shows the difference as outlined in the screen about (method not found)

**Comment by kalessil** [comment]
Thanks! We prefix all messages with '[EA] ', so this is coming from another plugin.

Perhaps this is related: https://github.com/Haehnchen/idea-php-phpunit-plugin/issues/43?

**Comment by icanhazstring** [comment]
Damn u are right. Sorry :)
Will head over to @Haehnchen then ;)
