### ISSUE TITLE
Discussion about to constantify static values on classes

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#161]
Is very uncommon we use constants on class because devs are not too familiar with that (at least on PHP world) and do not know how much it is important. I think that is important we discuss about this topic (not need implement that, initially) to improve code quality and style of devs, and I guess that we can do it in a lot of things, avoiding to use static values in place of constants.

**For instance:**

```php
class MyClass {
    public function something($mode = null) {
        $mode = $mode ?: 'default';

        if ($mode === 'weak') {
            return rand();
        }

        if ($mode === 'mt') {
            return mt_rand();
        }

        return custom_rand();
    }
}

$myClass = new MyClass;
echo $myClass->something('default');
```

In this case, is a lot visible that it should be a constant. The argument `$mode` have three static possible values and null (that is same of "default"). It should suggests that user change it to be constant. Like that:

```php
class MyClass {
    const MODE_DEFAULT = 'default';
    const MODE_WEAK = 'weak';
    const MODE_MT = 'mt';

    public function something($mode = null) {
        $mode = $mode ?: self::MODE_DEFAULT;

        if ($mode === self::MODE_WEAK) {
            return rand();
        }

        if ($mode === self::MODE_MT) {
            return mt_rand();
        }

        return custom_rand();
    }
}

$myClass = new MyClass;
echo $myClass->something('default');
```

And on last line you should see that I can continues passing the static value "default". With a implementation to help devs to constantify static values, it could be avoided with a warning: "argument $mode requires a constant MODE_*" (it could be done by analisys, for now, because I guess that current phpdoc doesn't supports that).

```php
$myClass = new MyClass;
echo $myClass->something('default'); // Warning.
echo $myClass->something(MyClass::MODE_DEFAULT); // Good.
```

The major problem on this discussion is about "how check if string should be constant or not". Then because of that I like to discuss if it can be handled by this plugin, then think about how do that to improve code quality. :)

**Comment by Fleshgrinder** [comment]
Sorry, but I completely disagree that this is good style, there are multiple smells here:
- primitive obsession
- switch instead of polymorphism
- flag arguments
- open/closed violation
- …

Your particular example is crying out loud for a strategy pattern, I will not provide a solution here because it should be more than obvious how to solve the issue at hand.

However, I _think_ that I understand where you want to go with this, enumerations. A classical enum example are card suits or day of the week, and yes, PHP people tend to implement them with constants (e.g. vimeo/psalm#16). I am always dying a little when I encounter that. No, seriously, just create yourself an enum and enjoy the type system. It is sad that we are missing the enum sugar in PHP, and it is true that we should be lazy, but there is no reason to give in to _such_ bad and ancient practices.

```php
final class Suit {
    private const CLUBS = 0;
    private const DIAMONDS = 1;
    private const HEARTS = 2;
    private const SPADES = 3;

    private $suit;

    private function __construct(int $suit) {
        assert(in_array($suit, [self::CLUBS, self::DIAMONDS, self::HEARTS, self::SPADES], true));
        $this->suit = $suit;
    }

    public static function Clubs(): self {
        return new self(self::CLUBS);
    }

    public static function Diamonds(): self {
        return new self(self::DIAMONDS);
    }

    public static function Hearts(): self {
        return new self(self::HEARTS);
    }

    public static function Spades(): self {
        return new self(self::SPADES);
    }

    public static function variants(): array {
        return [self::Clubs(), self::Diamonds(), self::Hearts(), self::Spades()];
    }

    public function __toString() {
        return ['clubs', 'diamonds', 'hearts', 'spades'][$this->suit];
    }

    public function ordinal(): int {
        return $this->suit;
    }

    public function isClubs(): bool {
        return $this->suit === self::CLUBS;
    }

    public function isDiamonds(): bool {
        return $this->suit === self::DIAMONDS;
    }

    public function isHearts(): bool {
        return $this->suit === self::HEARTS;
    }

    public function isSpades(): bool {
        return $this->suit === self::SPADES;
    }
}
```

Now we have a basic enum and perfect type safety and everything:

```php
final class Rank { /* … */ }

final class Card {
    private $rank;
    private $suit;

    public function __construct(Rank $rank, Suit $suit) { /* … */ }
}

$ace_of_spades = new Card(Rank::Ace(), Suit::Spades());
// 😍
```

**Comment by rentalhost** [comment]
@Fleshgrinder Thanks for you opinion for this topic. I just think that your example is too complex to a simple enum. The next one example should works in a lot cases:

```php
final class Suit {
    const CLUBS = 0;
    const DIAMONDS = 1;
    const HEARTS = 2;
    const SPADES = 3;
}
```

And just uses that statically. The _bad side_ (that not happen with your code), is that I have no way to control it on code typehint (like expects only a `Suit` constant as argument), once that PHP don't really supports enum nativelly and there no way to know from "where the value come from", once that I uses `Suit::CLUBS` it will turn `0` instead of `0 that comes from Suit class`. Your code is very clear and very flexible, but I still guess that is very heavy for simple cases where constants could works fine.

My initial idea about this discussion is turn code less static by using constants, making possible you change class options by just modifying constants if you need from child classes. Like that:

```php
class ParentClass {
	const SPEED = 100;
 
	static public function getSpeed() {
		return static::SPEED;
	}
}
 
class ChildClass extends ParentClass {
	const SPEED = 200;
}
 
// It will print 200.
echo ChildClass::getSpeed();
```

Of course that, on this last simplified case, maybe is not a good thing to do: turn absolutely _all_ static values in constants. But my original example could shows better that _sometimes_ is better than works with raw strings.

**Comment by Fleshgrinder** [comment]
This example is something that is okay for me. Not seen very often, I guess because most languages do not have something like it, but totally fine with late static binding. Although I'd argue that the constants must be `protected` (if possible, since it depends on the PHP version).

The example from your first post is not good at all. As I said, strategy pattern is much better in that particular case.
