### ISSUE TITLE
Php Inspections (EA Extended) | Probable bugs | Magic methods validity

### ISSUE THREAD

**Issue by WinterSilence** [kalessil/phpinspectionsea#1610]
~~~php
public function __toString(): string
{
     return $this->getRealPath() ?: $this->getPathname();
}
~~~
Don't understand why inspection display error, method always return string: `getRealPath(): string|false` ,  `getPathname(): string`.

| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) |
| Language level | PHP 7.2                    |

**Comment by kalessil** [comment]
Fixed!
