### ISSUE TITLE
Non-null default value parameters: Example for code refactoring is confusing

### ISSUE THREAD

**Issue by speich** [kalessil/phpinspectionsea#1611]
Code Styles: Non-null default value parameters
https://github.com/kalessil/phpinspectionsea/blob/master/docs/code-style.md#non-null-default-value-parameters

I'm not sure if this is on purpose or not. The second step of refactoring changes the parameters from optional to required.

If that's not the case, then shouldn't the parameters
```
/* code refactoring step 2 (further hardening, perhaps the plugin will assist here in the future) */
function calculateRadial(float $radius, ?float $pi, ?float $multiplier): float {
    return $radius * ($pi ?? M_PI) * ($multiplier ?? 1);
}
```
be like this ?
```
function calculateRadial(float $radius, ?float $pi = null, ?float $multiplier = null): float {
```
otherwise they are not optional anymore.

**Comment by kalessil** [comment]
Oh, thank you for pointing out @speich - I'll revisit the documentation today.

**Comment by kalessil** [comment]
Fixed!

**Comment by speich** [comment]
nice, thanks :-)
