### ISSUE TITLE
FP: `Symfony\Component\HttpFoundation\ParameterBag::get() === '…'` "is always false"

### ISSUE THREAD

**Issue by jdreesen** [kalessil/phpinspectionsea#1615]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate) |
| Language level | PHP 7.4                        |

Current behaviour
--
EA warns that the condition is always false:
![image](https://user-images.githubusercontent.com/424602/89634968-9093d680-d8a6-11ea-9381-e472def1b3d2.png)

The `attributes`, `request` and `query` objects are instances of [`Symfony\Component\HttpFoundation\ParameterBag`](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/HttpFoundation/ParameterBag.php). The return type of [`get()`](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/HttpFoundation/ParameterBag.php#L67-L78) is `mixed` and thus can be anything.

Expected behaviour
--
No warning from EA.

Environment details
---
PhpStorm 2020.2
Build #PS-202.6397.115, built on July 29, 2020
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 4.15.0-112-generic

**Comment by kalessil** [comment]
Fixed!
