### ISSUE TITLE
"Pointless boolean expression" inspection for PHP

### ISSUE THREAD

**Issue by Haehnchen** [kalessil/phpinspectionsea#1622]
Lately if found some code statements that do strict comparsion on a already clean bool return. Inside Java there is a inspection for this code. So i guess it would be also helpful inside PHP inspections.

**Code Examples**

```php
    private function isFoo(): bool {}

    public function getFoo(): int
    {
        if ($this->isFoo() == true) { }
        if ($this->isFoo() === true) { }
        if (isset($test) === true) { }
        if (empty($test) === false) { }
    }
```

**Java Inspection** 

![image](https://user-images.githubusercontent.com/1011712/90956541-bebd0d00-e487-11ea-8f52-d079fc7180c7.png)

![image](https://user-images.githubusercontent.com/1011712/90956499-7271cd00-e487-11ea-8a7e-403c9deba2cc.png)

**Comment by ea-inspections-team** [comment]
Thanks for the proposal @Haehnchen! Implemented!
