### ISSUE TITLE
False positive ElvisOperatorCanBeUsedInspection

### ISSUE THREAD

**Issue by hypnotox** [kalessil/phpinspectionsea#1626]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 4.0.5 |
| Language level | PHP 7.2 |

Current behaviour
--
This ternary expression falsely being reported as being able to reduce to an elvis operator, even though this changes behaviour.
![Screenshot 2020-09-01 at 09 19 27](https://user-images.githubusercontent.com/47070257/91817213-865ec100-ec35-11ea-97c5-8f7daba66169.png)

Expected behaviour
--
Not being reported as being able to reduce to elvis operator.

Environment details
---
PhpStorm 2020.2.1
Build #PS-202.6948.87, built on August 27, 2020
Licensed to IWAVES Medientechnik e.U. / Josua Müller
Subscription is active until November 8, 2020
Runtime version: 11.0.8+10-b944.31 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1502M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: Key Promoter X, String Manipulation, com.andrey4623.rainbowcsv, com.chrisrm.idea.MaterialThemeUI, com.intellij.ideolog, com.mallowigi, com.wakatime.intellij.plugin, net.seesharpsoft.intellij.plugins.csv, net.vektah.codeglance, zielu.gittoolbox, com.intellij.lang.jsgraphql, de.espend.idea.laravel, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, izhangzhihao.rainbow.brackets, ru.adelf.idea.dotenv

**Comment by kalessil** [comment]
Hi @hypnotox, I couldn't reproduce the case. Ah also, you closed the ticket already (did the issue go away?).
