### ISSUE TITLE
Improvement: Show documentation link in inspection result and/or context menu

### ISSUE THREAD

**Issue by simonberger** [kalessil/phpinspectionsea#1632]
I like the documentation which describes suggested changes that might not be obvious in the first moment or dangerous in general.
It would be handy if the documentation link could be accessible in the inspection results or at least in the context menu when changing in code.
I don't know the IntelliJ plugin interfaces and am aware that it might be not possible.

**Comment by ea-inspections-team** [comment]
Thanks for reaching us @simonberger. Unfortunately, how IDE displays descriptions is not something we could change.
Still, we believe messages and QF titles (prefixed with '[EA] ') could be improved. If you have specific cases when those could be improved, don't hesitate to share with us.
