### ISSUE TITLE
Redundant type declaration

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#1635]
Description (screenshot):
--
![image](https://user-images.githubusercontent.com/421851/94043628-920c5600-fda3-11ea-9637-46c6dce14fdb.png)

`/** @var bool|null */` is redundant here once that type is set to `?bool`, so it could be safety discarded.

**Comment by orklah** [comment]
I'm pretty sure there's already an inspection that does exactly that. If it's not native or EA, it must be PhpClean

**Comment by jdreesen** [comment]
PhpStorm has a quick-fix since 2020.2: https://blog.jetbrains.com/phpstorm/2020/07/phpstorm-2020-2-release/#remove_unnecessary_phpdocs

**Comment by rentalhost** [comment]
@jdreesen seems exactly what I have reported, but it doesn't works for me. That strange.

![image](https://user-images.githubusercontent.com/421851/94049521-7c029380-fdab-11ea-9edb-46c73cb87e67.png)
![image](https://user-images.githubusercontent.com/421851/94049534-802eb100-fdab-11ea-9691-3bc07be1356e.png)
![image](https://user-images.githubusercontent.com/421851/94049573-8b81dc80-fdab-11ea-9d1d-4eac9fc746e1.png)
![image](https://user-images.githubusercontent.com/421851/94049660-a3596080-fdab-11ea-999d-461ae21f7e4f.png)
