### ISSUE TITLE
New inspection: Unnecessary else

### ISSUE THREAD

**Issue by funivan** [kalessil/phpinspectionsea#164]
Here we go:
```
if (1 > 4) {
    return 1;
} else {
    return 5;
}
```
As we can see `else`  keyword can be removed without any break. Also if we have `elseif` statements in some cases they can be replaced with `if` keyword.
How inspection should work: find `else` or `elseif` keywords and detect if previous statement stop code execution. 
If this inspection will be interesting I can continue to work on it =)

**Comment by kalessil** [comment]
https://bitbucket.org/kalessil/phpinspectionsea/issues/245/redundant-else-clause-from-ocramius

**Comment by funivan** [comment]
Nice) I will continue to work on it and add `continue`, `break` statements check.

**Comment by kalessil** [comment]
I'm on it today)

**Comment by kalessil** [comment]
I only left to deal with QFs: your ideas are clear, but PS does it own magic: e.g. if you drop a keyword, the in-memory if-expression tree got corrupted. 

PS: inspector itself already pushed, can you take a look at it for discussing changes further?

**Comment by funivan** [comment]
Hello. I will contact you with twitter)

**Comment by kalessil** [comment]
Ready. The new name is "Redundant 'else' keyword", the inspection is enabled by default.

@funivan : would you please give it a try?
Known issue: PS not aligns comments properly when QFing

**Comment by funivan** [comment]
@kalessil ok, I will check it as soon as possible.

p.s. What does it mean "VR to make PR" ? ;)

**Comment by kalessil** [comment]
VR is me, PR suppose to be a Pull Request

**Comment by funivan** [comment]
1. In some cases if we have about 30-50 line of code inside elseif statement then QF works about 1second (or more)
2. There is one difference if we apply QF to the `elseif` or `else`. After `elseif` QF cursor goes to the end of last statement. If we apply QF to the `else` cursor goes to the end of previous statement
```php
public function test() {
      if (!empty($a) and $b) {
        return $a;
      } elseif (!empty($c)) {
        return $c;
      } // Cursor will be here
      return $b;
    }

```
```php
public function test() {
      if (!empty($a) and $b) {
        return $a;
      } /*Cursor will be here*/ else {
        return $b;
      } 
      
    }

```

**Comment by kalessil** [comment]
Thanks for checking!
QFes performance will not improve most probably, but I'll try to make cursor positioning more consistent.

**Comment by kalessil** [comment]
False positives: `if else if <else>` <else> reported, but should not - refactoring breaks logic

**Comment by kalessil** [comment]
@funivan: fixed version pushed, cursor behaviour should be fixed new. Can you give it the 2nd try, please?

PS: QFing speed without changes, no chance to improve it...

**Comment by funivan** [comment]
I will check it tomorrow. 

P.S. Now it is time to  ... 
 - create nightly builds repository =) it is not so hard
 - create tests for QF (I have no idea how to do this)
 - use travis-ci )

**Comment by kalessil** [comment]
The whole automatization topics is indeed relevant, once we finish with this inspection, calling a method on null inspection and current false-positives pool the Graddle + travis topic will be next point.

With Travis I'll need a PR - migration to Gradle going to exhaust me...
