### ISSUE TITLE
Declare closure static: ignore option for short functions

### ISSUE THREAD

**Issue by Bilge** [kalessil/phpinspectionsea#1641]
Please consider adding an option to disable the *declare closure static* inspection for short functions (`fn`). The purpose of this syntax is to be brief, so it may be desirable to ignore the static micro-optimization since `fn` maintains brevity better than `static fn` and the infinitesimal performance benefit is seldom worth the effort.

**Comment by ea-inspections-team** [comment]
Thanks for the proposal @Bilge ! It's a great one, we'll add the option shortly.

**Comment by ea-inspections-team** [comment]
Thank you for reporting @Bilge! Implemented!
