### ISSUE TITLE
Will it be able to purchase on jetbrains marketplace?

### ISSUE THREAD

**Issue by ayaka209** [kalessil/phpinspectionsea#1646]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate) |

Question
--
I noticed that the purchase channel on the official website is temporarily suspended
Will it be possible to purchase the ultimate version on jetbrains plugin marketplace in the future?

**Comment by ea-inspections-team** [comment]
Thank you for reaching us out @ayaka209. 
The sales will be back soon, please follow https://twitter.com/kalessil to not miss the announcement.

**Comment by pppdns** [comment]
Any update on this?

**Comment by kalessil** [comment]
Yes, it was an announcement in Twitter today: https://twitter.com/EaInspections/status/1400783610823778304
