### ISSUE TITLE
Replaces usages of PhpThrow with new PhpThrowExpression

### ISSUE THREAD

**Issue by wbars** [kalessil/phpinspectionsea#1655]
For [throw expression](https://wiki.php.net/rfc/throw_expression) we introduced new PSI element `com.jetbrains.php.lang.psi.elements.PhpThrowExpression`. After this change necessity of separate `PhpThrow` statement is unnecessary, in 2020.3 PS will still parse throw expression that are effectively statements (e.g. `throw new E();)` as `PhpThrow` with single child `PhpThrowExpression`, but starting from 2021.1 it will be replaced with simple `Statement` with single child `PhpThrowExpression`. 
Clients are encouraged to use `PhpThrow` (and `com.jetbrains.php.lang.psi.visitors.PhpElementVisitor#visitPhpThrowExpression`) instead to not miss any throw expression usages.

for references: https://jetbrains.org/intellij/sdk/docs/products/phpstorm/php_open_api_breaking_changes_203.html

**Comment by ea-inspections-team** [comment]
Thank you for the hint @wbars, we are working on a solution to address the change.

**Comment by ea-inspections-team** [comment]
Fixed!
