### ISSUE TITLE
False Positive: Nullsafe operator

### ISSUE THREAD

**Issue by SpiGAndromeda** [kalessil/phpinspectionsea#1675]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 3.0.10 |
| Language level | 8.0                        |

Current behaviour
--
EA shows an error if a method of a nullable object is used with nullsafe operator. (Please excause the horrible colors. I am working on a color scheme that looks less like an acid-trip but is still good readable.)

![False Positive - Nullsafe operator](https://user-images.githubusercontent.com/15141351/103424575-68867600-4bad-11eb-9fcc-ed1c04b2d219.png)

Expected behaviour
--
PHP8 supports the nullsafe operator: [PHP 8: the null safe operator](https://stitcher.io/blog/php-8-nullsafe-operator). With that feature the "Null pointer exception may occur here." is obsolete if used. PHPStorm already detects that.

**Comment by digitalsounds** [comment]
+1 on this, php8 has been out for a while now, so would be great if this could be sorted, I don't want to particularly want to disable set the 'Null reference' inspection.

**Comment by mattjanssen** [comment]
Very interested in support for this, too 😁

**Comment by tsadiq** [comment]
So do i 👌

**Comment by JParkinson1991** [comment]
Came across this today, would be great to see this fixed!

**Comment by ea-inspections-team** [comment]
Folks, this has been fixed now. We'll rollout hot-fix releases for all plugins next week.
