### ISSUE TITLE
Variable not set in scope false positive

### ISSUE THREAD

**Issue by uuf6429** [kalessil/phpinspectionsea#1681]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 4.0.6 |
| PhpStorm         | 2020.3.1 |
| Language level | 5.6 (💩 I know)                        |

Current behaviour
--
<img src="https://user-images.githubusercontent.com/230049/104106295-fb619780-52b4-11eb-8e5f-2fbc104219d9.png" width="400">

Expected behaviour
--
I did not expect the inspection to be triggered because:
1. `isset($undefinedVariable)` is generally intentional - AFAIK PhpStorm itself by default does not show warnings for undefined variables preceded with an isset.
2. actually, PhpStorm allows navigation to the `require`'ed file, where that variable is actually declared unconditionally so it could analyse that file.

Frankly, it feels like this extension is doing miracles already so maybe point 2 is a stretch. 😄

**Comment by ea-inspections-team** [comment]
Thanks for reporting @uuf6429 !

This is a limitation of the analyzer in general - while IDE can navigate to the file, we don't have APIs in place to access this information. But suppressing the warning is an option, hope that helps.
