### ISSUE TITLE
PHP_OS const is suggested

### ISSUE THREAD

**Issue by Xantios** [kalessil/phpinspectionsea#1683]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended)  |
| Language level | PHP 8                        |

Current behaviour
--
as described in this issue https://github.com/kalessil/phpinspectionsea/issues/1171  which state it's resolved in currently trying to use the following snippet:

```php

#[Pure]
    private function platform(): string {

        return strtolower(php_uname('s')) ?? 'unknown';
    }
```

First of, your plugin is an absolute beauty! big fan!
the problem arrises when looking at the `php_uname` function call, which tells me to use a predefined constant.

Considering performance I can imagine why. but the implied result is not entirely the same.

eg: I can (cross)compile a PHP binary on any arbitrary picked unix system and move it to a Mac and run it. the defined const would refer to the unix version its build upon as stated in PHP documentation ( https://www.php.net/manual/en/reserved.constants.php )

the `php_uname()` however returns the current running environment which in this case is what I want. 
maybe change up the message to better highlight the (arguably subtle) difference?

As stated above, its implied to be fixed. but there is no update for the plugin as far as I can figure? so maybe im missing something. if so feel free to inform me of my own wrongdoings 

Expected behaviour
--

A better suited message or maybe no message at all, I'd say you be the judge on that one

Environment details
---

PhpStorm 2020.3.1
Build #PS-203.6682.180, built on December 30, 2020
License stuff
Runtime version: 11.0.9.1+11-b1145.63 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 24
Registry: run.processes.with.pty=TRUE, documentation.show.toolbar=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.kalessil.phpStorm.phpInspectionsEA,<stuff>

**Comment by ea-inspections-team** [comment]
Thanks for reporting @Xantios.

That's a valid point. We are not sure how to handle that, what option in your opinion looks better?

- introduce new setting to toggle the function analysis on and off
- extend the message with a remark clarifying the point, so people could decide to suppress it or to refactor

**Comment by Xantios** [comment]
I think changing up the message to clarify that the constant can be used still would confuse people. 

The "most correct" approach to me would feel like using uname to get the current host OS and tell those who use the constant that they might want to consider using uname if they want to be sure of the current running environment. something along the lines of: "Use of this constant refers to the compile time, use uname for runtime information" (or something along those lines)

So the warning for uname can be dropped and one for `PHP_OS(_FAMILY)` can be added perhaps?

It seems a lot of people think the constant ```PHP_OS``` and ```PHP_OS_FAMILY``` are related to runtime so I'd feel as if it would help a lot to really drive the point home that is does not. so people don't only get the benefit of better code from the EA Inspections but they might also learn a tiny bit of PHP under the hood.

**Comment by ea-inspections-team** [comment]
Hey @Xantios, we completely removed `php_uname` analysis and the changes were released earlier this week already.

> and one for PHP_OS(_FAMILY) can be added perhaps

That's a good proposal. We had several chats with OSS maintainers, but they are sharing opinion that it's an edge case and they wouldn't benefit from this inspection. Sorry for the bad news.
