### ISSUE TITLE
Php Inspections (EA Ultimate) - License activation locked - New box

### ISSUE THREAD

**Issue by icawebdesign** [kalessil/phpinspectionsea#1684]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate) |

Question
--

I built a new box and forgot to release one of my 2 activations and now can't re-activate it on my new box and had no response to any emails :(

How can I get my 2nd activation back?

**Comment by digiservnet** [comment]
This has now been sorted and can be closed. Thanks Vlad 😄

**Comment by icawebdesign** [comment]
This has now been sorted and can be closed. Thanks Vlad 😄
