### ISSUE TITLE
Not all eligible closures flagged as being possible to be marked static

### ISSUE THREAD

**Issue by reedy** [kalessil/phpinspectionsea#1687]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended), 4.0.6 |
| Language level | 7.2                        |

Current behaviour
--
Multiple closures in the same function aren't necessarily all marked as being eligible to be marked static

<img width="750" alt="Screenshot 2021-02-06 at 19 23 09" src="https://user-images.githubusercontent.com/67615/107127845-ca26b800-68b0-11eb-8296-5b6b0d856484.png">

This is with MediaWiki core - https://github.com/wikimedia/mediawiki

Seen in `tests/phpunit/includes/deferred/DeferredUpdatesTest.php` in `testTryOpportunisticExecute` and other functions. Not sure if it's because of more complex code usages, or what... But nothing obvious in the closure that should prevent it being marked static (such as use of `$this`

Note, we're starting to migrate usages, so depending on when you checkout master, it might be changed. As of writing, master is at 458ae7e38a7dca6e2444e21710baac9f888f5914

Expected behaviour
--
All closures where appropriate should be flagged

Environment details
---
PhpStorm 2021.1 EAP
Build #PS-211.5538.21, built on February 5, 2021
PhpStorm EAP User
Expiration date: March 7, 2021
Runtime version: 11.0.10+8-b1304.1 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.ssh.library.backend.webDeployment.use.sshj=false
Non-Bundled Plugins: com.dmarcotte.handlebars (211.5538.10), com.kalessil.phpStorm.phpInspectionsEA (4.0.6), org.mediawiki (0.5)

**Comment by reedy** [comment]
And after enabling the check in phan to find this... It seems many many more aren't being highlighted...

MW master as of d7decde5f583960122ca22902d5c4717ccc41792, these have been highlightedt - https://gerrit.wikimedia.org/r/c/mediawiki/core/+/662111

The plugin highlights ~102, most (all) of which are fixed in https://gerrit.wikimedia.org/r/c/mediawiki/core/+/662085 but the patch linked above finds maybe over 600 more...

**Comment by ea-inspections-team** [comment]
Thanks for reporting @reedy !

The closure was passed into a static call, that prevented the analyzer from suggesting to use static. Solved now!
