### ISSUE TITLE
Is this plugin still being maintained?

### ISSUE THREAD

**Issue by maxacarvalho** [kalessil/phpinspectionsea#1688]
Hello,

I'd like to know if the plugin is still being maintained?  

I can see lots of issues opened without any reply from the maintainer.  
I have the paid version, but emails are not being answered.  
The **support** link on the plugin's homepage leads to this repo, which seems to be abandoned.

**Comment by kalessil** [comment]
Hi @maxacarvalho : I'm the project lead.

I didn't have any capacity last several months (lost a close family member) but getting back to this project.
Thank you for using the paid version and for your patience.

I'll be processing emails and pings next 2 weeks, so you'll hear from me soon.

**Comment by luukverhoeven** [comment]
@kalessil is there a way to purchase the paid version? My trail is expired and on your website the payment is disabled.

**Comment by kalessil** [comment]
Responded in Twitter =)
