### ISSUE TITLE
roave/security-advisories changed their preferred branch to `latest`

### ISSUE THREAD

**Issue by binotaliu** [kalessil/phpinspectionsea#1693]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended)  4.0.6 |
| Language level | PHP 8.0                       |

when having `"roave/security-advisories": "dev-latest"` in composer.json, plugin reports "Please use dev-master instead."

They changed the preferred default branch name, its now `latest`, while `master` can still be used:
https://github.com/Roave/SecurityAdvisories/commit/5ae6aa6482b72946bc0d279c3b54dc1dbeae68d8#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by jdreesen** [comment]
Duplicate of #1647 and #1682

**Comment by binotaliu** [comment]
@jdreesen Right! Sorry I just searched open issues and found nothing. Didn't think about to look pull requests before.

**Comment by ea-inspections-team** [comment]
Closing as duplicate: one PR is merged and the second one will be merged as soon as merge conflict solved. 
Thank you folks for reporting and clarifying the current status!
