### ISSUE TITLE
Suspicious ternary operator

### ISSUE THREAD

**Issue by WinterSilence** [kalessil/phpinspectionsea#1694]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 4.0 |
| Language level | PHP 5.6                 |

`return $userID !== $row->designer_id ? $row->designer_id : $userID;`
not same to `$value = $argument === '' ? '' : $argument;`

**Comment by orklah** [comment]
Your two snippets doesn't use the same variable names, it's really confusing

**Comment by WinterSilence** [comment]
@orklah  [second snippet](https://github.com/kalessil/phpinspectionsea/blob/master/docs/confusing-constructs.md#suspicious-ternary-operator) not my

**Comment by orklah** [comment]
Ok. I suppose PHP EA suggests replacing by `return $row->designer_id;` ?

I'm not sure why it could be wrong

**Comment by WinterSilence** [comment]
> I'm not sure why it could be wrong

then write tests to be sure

**Comment by ea-inspections-team** [comment]
Thanks for reporting @WinterSilence !

We are also not sure what's wrong with the suggested QF, so indeed tested the case - https://3v4l.org/jOrpe. There is no behaviour change. 

We'll close the issue, but if you have an example where behaviour changes, don't hesitate to share it.
