### ISSUE TITLE
Inspection's severity

### ISSUE THREAD

**Issue by WinterSilence** [kalessil/phpinspectionsea#1696]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 4.x |
| Language level | PHP 7.3

Плагин игнорирует пользовательские настройки: для данной инспеции выставлен уровень week warning, а она все равно продолжает обрабатываться как error

![изображение](https://user-images.githubusercontent.com/3521094/109131580-fd4bc100-7763-11eb-8ecf-21fbc41328d8.png)

---

**Comment by ea-inspections-team** [comment]
Fixed!

**Comment by WinterSilence** [comment]
@ea-inspections-team please, update version in market

**Comment by ea-inspections-team** [comment]
@WinterSilence: thanks for the ping. FYI, a patch release is planned and will be available this week.
