### ISSUE TITLE
FP: `'array_merge(...)' misused`

### ISSUE THREAD

**Issue by jdreesen** [kalessil/phpinspectionsea#1697]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 3.0.10 |
| Language level | PHP 7.4                        |

Current behaviour
--
Given:
- `$dependencies` is an array of arrays: `[[...], [...], ...]`
- `$fixtures` is a simple array: `[...]`

I want to flat-merge them with `$fixtures` at the end and EA warns me with this message:

![grafik](https://user-images.githubusercontent.com/424602/109175917-925fb180-7786-11eb-873b-65f8d6bafd2b.png)

When I apply the quick-fix I get: `$result = [...$dependencies, $fixtures];` which is **not** the same (it's not flat anymore).

See here for an example: https://3v4l.org/aL8Kv

Expected behaviour
--

The quick-fix is not proposed in this case.

Environment details
---
PhpStorm 2020.3.2
Build #PS-203.7148.74, built on January 27, 2021
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 4.15.0-135-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 4
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false
Current Desktop: ubuntu:GNOME

**Comment by ea-inspections-team** [comment]
Fixed!
