### ISSUE TITLE
Using fully-qualified function calls is faster, details and benchmarks doesn't work with 'mb_strtolower'

### ISSUE THREAD

**Issue by tarlepp** [kalessil/phpinspectionsea#170]

**Comment by kalessil** [comment]
@tarlepp : do you mean you've been benchmarking mb_strtolower or something else?

**Comment by tarlepp** [comment]
![image](https://cloud.githubusercontent.com/assets/595561/23660418/0cc45da2-0352-11e7-8d43-cd98bdc2e674.png)

That validation is not triggered for `mb_strtolower` function

**Comment by kalessil** [comment]
Confirmed, it seems like PS didn't resolve the function. Will check this (https://github.com/tarlepp/symfony-backend/search?utf8=%E2%9C%93&q=mb_strtolower).

**Comment by tarlepp** [comment]
Also I think that this should also catch `\array_map('trim', ['foo ', ' bar']);`

**Comment by kalessil** [comment]
It should be the same root-case for mb_strtolower and array_map, the only question what exactly causes the issue.

**Comment by kalessil** [comment]
@tarlepp, I'm not able to reproduce the issue with the latest build - I getting 39 reported with the inspection.

I also not really getting what you meant by catching `\array_map('trim', ['foo ', ' bar']);`

**Comment by tarlepp** [comment]
@kalessil `\array_map('trim', ['foo', 'bar']);` versus `\array_map('\trim', ['foo', 'bar']);`

**Comment by kalessil** [comment]
@tarlepp, oh I see now. Should be pretty easy to implement =)

**Comment by tarlepp** [comment]
Hmm, I think this isn't working - just updated plugin to `2.3.9.1` and I still don't see error on `mb_` functions.

![image](https://user-images.githubusercontent.com/595561/29132615-7c44bf3a-7d39-11e7-98a3-10cc2ecd5a3c.png)

On that screenshot only error is raised from `strtolower` function, but not on those three `mb_*` functions.
