### ISSUE TITLE
"Null pointer exception may occur here" with PHP 8 null safe operator

### ISSUE THREAD

**Issue by smares** [kalessil/phpinspectionsea#1702]
| Subject | Details |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin | Php Inspections (EA Ultimate) 3.0.10 |
| Language level | PHP 8 |

Current behaviour
--
![image](https://user-images.githubusercontent.com/818380/110655543-6ea55e00-81bf-11eb-9961-ca454f0453ec.png)

Expected behaviour
--
No error, as the PHP 8 null safe operator is used

Environment details
---
IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 26, 2021
Licensed to Sebastian Mares
You have a perpetual fallback license for this version.
Subscription is active until December 24, 2021.
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: com.markskelton.one-dark-theme, mobi.hsz.idea.gitignore, com.jetbrains.php, com.jetbrains.php.blade, com.kalessil.phpStorm.phpInspectionsUltimate, net.king2500.plugins.PhpAdvancedAutoComplete, org.jetbrains.plugins.phpstorm-remote-interpreter, ru.adelf.idea.dotenv, com.laravel_idea.plugin

**Comment by garak** [comment]
Still present on 4.0.6.3

**Comment by ea-inspections-team** [comment]
Folks, this has been fixed now. We'll rollout hot-fix releases for all plugins next week.
