### ISSUE TITLE
Licensing information is not available (error: null).

### ISSUE THREAD

**Issue by ktomk** [kalessil/phpinspectionsea#1705]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), com.kalessil.phpStorm.phpInspectionsUltimate (3.0.11) |
| Language level | irrelevant                        |

After upgrading to Phpstorm EAP (the installation folder changed IIRC), PHP Inspections (EA Ultimate) is unable to find the licensing information any longer:

> Licensing information is not available (error: null).

Activating or releasing the key (also with force) is doing nothing.

**Comment by ea-inspections-team** [comment]
Similar to #1690 (fixed).

**Comment by ktomk** [comment]
Confirm fix in #1690
