### ISSUE TITLE
json_encode and json_decode named arguments incorrect behaviour

### ISSUE THREAD

**Issue by AlexLisenkov** [kalessil/phpinspectionsea#1708]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 4.0.6.2 |
| Language level | PHP ^8.0                        |

Current behaviour
--
`json_encode` and `json_decode` suggests to harden error handling when flag is set with named argument on a different position.

![image](https://user-images.githubusercontent.com/3088831/111755090-03334e80-8899-11eb-96bd-dfb3ef8cb4b1.png)

Different position (1st argument, named)
![image](https://user-images.githubusercontent.com/3088831/111755472-6cb35d00-8899-11eb-856a-2a2417f4fb84.png)
Same position (2nd argument, named)
![image](https://user-images.githubusercontent.com/3088831/111755577-8ce31c00-8899-11eb-94cd-5d0c3535f3cf.png)

Expected behaviour
--
No more suggest

Environment details
---

**Comment by AllenJB** [comment]
This appears to be a duplicate of #1639

**Comment by AlexLisenkov** [comment]
duplicate of #1639

**Comment by ea-inspections-team** [comment]
Thank you for reporting @AlexLisenkov   ! Fixed in #1977.
