### ISSUE TITLE
i can't buy the ultimate version, when i go to the website, it tell me "Note (10.08.2020): sales are temporary suspended"

### ISSUE THREAD

**Issue by souhaiebtar** [kalessil/phpinspectionsea#1712]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) or Php Inspections (EA Ultimate), which version |
| Language level | e.g. PHP 7.2 (check project settings or composer.json)                        |

Current behaviour
--

Expected behaviour
--

Environment details
---

**Comment by kexxt** [comment]
You should check out his patreon https://www.patreon.com/kalessil

**Comment by souhaiebtar** [comment]
@kexxt  thanks for the help
