### ISSUE TITLE
Failed to set the TurboActivate.dat location.

### ISSUE THREAD

**Issue by laurin1** [kalessil/phpinspectionsea#1715]
For the last couple of PHPStorm versions (not sure what version of PhpInspections this started), I get this on launch every time:

![image](https://user-images.githubusercontent.com/75857/113428824-1bc55d80-939d-11eb-85df-e3f996112456.png)

Missing the license:

![image](https://user-images.githubusercontent.com/75857/113428949-562efa80-939d-11eb-9c95-f6c01f302cfe.png)

PhpStorm 2021.1 RC
Build #PS-211.6693.78, built on April 1, 2021
Licensed to P.R.I.D.E. / Keith Davis
Subscription is active until January 11, 2022.
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: com.funivan.idea.phpClean (2020.12.22), com.kalessil.phpStorm.phpInspectionsUltimate (3.0.11.2), com.kalessil.idea.jsInspectionsUltimate (0.0.5-beta)

I am guessing this is related to https://github.com/kalessil/phpinspectionsea/issues/1690.

**Comment by laurin1** [comment]
Continues to happen on every load. Currently on:

PhpStorm 2021.1.1
Build #PS-211.7036.8, built on April 15, 2021
Licensed to P.R.I.D.E. / Keith Davis
Subscription is active until January 11, 2022.
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: com.funivan.idea.phpClean (2020.12.22), com.kalessil.phpStorm.phpInspectionsUltimate (3.0.11.2), com.kalessil.idea.jsInspectionsUltimate (0.0.5-beta)

**Comment by ea-inspections-team** [comment]
Closing as a duplicate: the issue has been fixed while migrating to JetBrains marketplace.
