### ISSUE TITLE
After the latest update, both IDEA and PHPStorm crash after the plugin is installed

### ISSUE THREAD

**Issue by bbuske** [kalessil/phpinspectionsea#1717]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate)|
                    |

Current behaviour
--
I updated both, PHPStorm and IntelliJ IDEA IU to the latest version 2021.3. Then I installed the PHP Inspections Ultimate plugin. After restarting the IDE, it would crash right after the splash screen, logging the following error: 

`Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.sun.jna.Native.open(Ljava/lang/String;I)J+0
j  com.sun.jna.NativeLibrary.loadLibrary(Ljava/lang/String;Ljava/util/Map;)Lcom/sun/jna/NativeLibrary;+257
j  com.sun.jna.NativeLibrary.getInstance(Ljava/lang/String;Ljava/util/Map;)Lcom/sun/jna/NativeLibrary;+154
j  com.sun.jna.Library$Handler.<init>(Ljava/lang/String;Ljava/lang/Class;Ljava/util/Map;)V+205
j  com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;Ljava/util/Map;)Lcom/sun/jna/Library;+68
j  com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;)Lcom/sun/jna/Library;+5
j  com.wyday.turboactivate.TurboActivateNative.<clinit>()V+5
v  ~StubRoutines::call_stub
j  com.wyday.turboactivate.TurboActivate.SetPDetsLocation()V+138
j  com.wyday.turboactivate.TurboActivate.<init>(Ljava/lang/String;Ljava/lang/String;)V+24
j  com.kalessil.phpStorm.phpInspectionsEA.license.LicenseService.initializeClient()V+263
j  com.kalessil.phpStorm.phpInspectionsEA.EAUltimateApplicationComponent.initLicensing()V+34
j  com.kalessil.phpStorm.phpInspectionsEA.EAUltimateApplicationComponent.initComponent()V+109`

Removing the plugin, makes the IDE work again. I have tried this on both PHPStorm and IDEA IU. I did not install the plugin on WebStorm, but I am fairly sure, that the issue will be there as well. 

Expected behaviour
--
The IDE should start up, with the PHP Plugin properly installed and working - or in case of an error disabled. It should not prevent the IDE from starting up at all. 

Environment details
---

IDEA IU 2021.3 / PHPStorm 2021.3 

- The project support is powered by community funding via [Patreon](https://www.patreon.com/kalessil)
-->

**Comment by jdreesen** [comment]
I updated today to the latest PhpStorm version 2021.1 and everything works as expected.

| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate)|
| Language level | PHP 7.4                       |

Environment details
---
PhpStorm 2021.1
Build #PS-211.6693.120, built on April 7, 2021
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 4.15.0-140-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 4
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false

**Comment by bbuske** [comment]
Well, since it is a Java issue, could it be related to that? 

What version of Java are you running? 

I am on Manjaro, running Java 8, OpenJDK 15 and Java 16. The system defaults to the Oracle Java 16, though. OpenJDK 15 was what came by default and Java 8 I installed manually from Oracle because some of the software I run still requires it. 

It is interesting, that it crashed for me on both IDEs. So, it could be something Java or system specific. I had originally contacted Jetbrains Support about it and they told me to open an issue here, as it was plugin related. Indeed, removing the plugin, made both IDEs work again.

**Comment by bbuske** [comment]
Well, since it is a Java issue, could it be related to that? 

What version of Java are you running? 

I am on Manjaro, running Java 8, OpenJDK 15 and Java 16. The system defaults to the Oracle Java 16, though. OpenJDK 15 was what came by default and Java 8 I installed manually from Oracle because some of the software I run still requires it. 

It is interesting, that it crashed for me on both IDEs. So, it could be something Java or system specific. I had originally contacted Jetbrains Support about it, and they told me to open an issue here, as it was plugin related. Indeed, removing the plugin, made both IDEs work again.

**Comment by jdreesen** [comment]
I'm using JetBrains included Java VM. 

I think it is:

> Runtime version: 11.0.10+9-b1341.35 amd64
> VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.

**Comment by apphancer** [comment]
I had to disable the plugin as it's giving me irrelevant warnings.

**Comment by ea-inspections-team** [comment]
Thanks for reporting @bbuske, this was happening on new Macs and sometimes WSDL due to licensing solution we used.

This has been addressed recently and we released https://plugins.jetbrains.com/plugin/16935-php-inspections-ea-ultimate- via JetBrains marketplace.

Let us know the new plugin version works as expected (you will need to uninstall all Php Inpections (EA *) plugins as a prerequisite).

**Comment by ea-inspections-team** [comment]
@apphancer: did you run into the same error, or you are referencing to something else?

**Comment by bbuske** [comment]
Hi,



Thanks for getting back.

Yes, the new plugin version works indeed as intended for us.

Good work on this one! Keep it up.

**Comment by ea-inspections-team** [comment]
Thanks for getting back @bbuske, that's great news!
