### ISSUE TITLE
Constant array merge assignment

### ISSUE THREAD

**Issue by evans-xjw** [kalessil/phpinspectionsea#1719]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) or Php Inspections (EA Ultimate), which version |
| Language level | e.g. PHP 7.2 (check project settings or composer.json)                        |

Current behaviour
--
![image](https://user-images.githubusercontent.com/45864805/114966547-61a61980-9ea5-11eb-9eca-c2d644e94e3f.png)
For the merging of constant arrays, it is inappropriate to use array_merge instead of +, which will cause syntax errors
Expected behaviour
--
This prompt should be removed
Environment details
---

**Comment by ea-inspections-team** [comment]
Thanks for reporting @evans-xjw, the bug has been fixed.
