### ISSUE TITLE
StrStartsWithCanBeUsedInspection does not respect language level

### ISSUE THREAD

**Issue by Philosoft** [kalessil/phpinspectionsea#1720]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 3.0.11.2 |
| Language level |7.4                        |

Current behaviour
--

```php
strpos($message, $expectedError) === 0
```
is suggested to replace with

```php
str_starts_with($message, $expectedError)
```

Expected behaviour
--

Inspection does not consider this an error, since language level for project is < PHP 8.0

Environment details
---

PhpStorm 2021.1.1
Build #PS-211.7036.8, built on April 15, 2021
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.0-50-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.intellij.ideolog (203.0.27.0), mobi.hsz.idea.gitignore (4.1.0), NEON support (0.5.1), com.kalessil.phpStorm.phpInspectionsUltimate (3.0.11.2), de.espend.idea.php.toolbox (5.1.1), de.espend.idea.php.annotation (8.0.0), fr.adrienbrault.idea.symfony2plugin (0.23.208), ru.adelf.idea.dotenv (2021.1)
Current Desktop: ubuntu:GNOME

**Comment by rentalhost** [comment]
Hello!

Could you check if `str_starts_with()` is really not available to your project? Because some packages implements it (as https://packagist.org/packages/symfony/polyfill-php80), so EA will consider that to report.

**Comment by Philosoft** [comment]
Yeah, it's there. Didn't notice that, sorry.

**Comment by ea-inspections-team** [comment]
Hey folks, FYI we recently released a fix for the case when the polyfill is a dev-dependency.
If polyfill a prod-dependency, the inspection keeps reporting the suggestion.
