### ISSUE TITLE
Case in namespace reference doesn't match the case in declaration  

### ISSUE THREAD

**Issue by MHCreations** [kalessil/phpinspectionsea#1721]
PHP Inspection (EA Extended) Version : 4.0.6.3

I have a new project with some existing imported classes, and PHP Inspection (EA Extended) plugin for PHPStorm is coming up with:

> Case in namespace reference doesn't match the case in declaration

when setting a namespace on a PHP page. Yet the case is **identical** to the filepath, class references and all usage cases that I can find. 

I can't find any useful reference when searching for this term. 

# PHP Class:

    <?php
        namespace myVendorName\ProjectName;
        
        Class AbstractClass {
        
        }

# Filepath: 

>   /classes/vendor/myVendorName/ProjectName/AbstractClass.php<br>
>   /classes/vendor/autoloader.php<br>
>   (etc)

# Endpoint PHP File:

    <?php

    use myVendorName\ProjectName\AbstractClass;
    $dropValue  = new AbstractClass();

# What does it claim is correct? 

PHP Inspection EA Extended wants to change my namespace call in my class files to `namespace myvendorname\ProjectName`.  It wants to lower the case of the primary vendor name to all lower case. 

Yet the [Autoloading standard](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md) states: 

> Alphabetic characters in vendor names, namespaces, and class names may be of any combination of lower case and upper case.

# Inconsistency? 

The namespace declaration of `namespace myVendorName;` (with no project subname) in the class file raises no flags with the Inspector. Yet with the project name it suddenly wants to change the case of the vendor name prefix. The projectname is required for the autoloader pathing so.... ? 

----

I have looked over the whole project and I can't find anywhere where anything references this namespace, I believe I have checked and confirmed all the settings and values both in PHPStorm as well as on the live server. 

- Am I being really stupid and missing something? 
- Is this an issue with the plugin? 
 
**What is the "declaration" that the Inspector is referencing as the source for its complaint?**

**Comment by MHCreations** [comment]
PS > The code runs fine and all classes are found in the Vendor folder.

**Comment by MHCreations** [comment]
Found it.

The issue was that PHPStorm has an "include Path" listing of, er, include paths, and within this listing was a path to a server folder for a few shared files.

Within this server side file structure was one root leveled class that had a namespace declared on it which was a lowercase duplication of the vendor namespace.

PHP Inspection (EA Extended) was detecting this and concluding somehow that the files in the server shared folder was taking precendent over the project-specific /vendors/ folder.

The class file that was in the shared folder is not used by this project and is not referenced by this project, the reference is entirely within PHPStorm's settings only.

Removing this reference (acutally, removing the erroneous namespace call to myvendorname) clears up all these issues.

To Clarify: 

The code `use myvendorname;` was used in one class file that was in a shared folder that was referenced in PHPStorm's settings but the file was NOT referenced in any way by this PHPStorm project. Somehow PHP Inspector EA Extended had decided this class namespace took precedent over file structure on the local disk, etc.

**Comment by ea-inspections-team** [comment]
Hey @MHCreations, thanks for reporting. The messages reported by Php Inspections (EA *) plugins are starting with '[EA] ', how did you verify that this warning is coming from the analyzer?

**Comment by ea-inspections-team** [comment]
Closing the issue as not activity here.
