### ISSUE TITLE
"Use return instead" results in more confusing looking code

### ISSUE THREAD

**Issue by reedy** [kalessil/phpinspectionsea#1722]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended), 4.0.6.3 |
| Language level | PHP 7.2                        |

Current behaviour
--
```
			if ( $info['type'] !== OPENSSL_KEYTYPE_RSA ) {
				return false;
			}
			return true;
```

is turned into

```
			return !( $info['type'] !== OPENSSL_KEYTYPE_RSA );
```

Expected behaviour
--

Code is simplifed and turned into

```
			return ( $info['type'] === OPENSSL_KEYTYPE_RSA );
```

Environment details
---
```
PhpStorm 2021.1.1
Build #PS-211.7036.8, built on April 15, 2021
Licensed to MediaWiki / Sam Reed
Subscription is active until April 5, 2022.
For non-commercial open source development only.
Runtime version: 11.0.10+9-b1341.35 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.ssh.library.backend.webDeployment.use.sshj=false
Non-Bundled Plugins: com.dmarcotte.handlebars (211.6693.44), com.kalessil.phpStorm.phpInspectionsEA (4.0.6.3), org.mediawiki (0.5)
```

**Comment by ktomk** [comment]
When, then I would have had expected:

~~~
return OPENSSL_KEYTYPE_RSA === $info['type'];
~~~

(without the parenthesis and having Yoda style switched on)

which I actually got offered from EA. I could even choose in which order I wanted to apply the fixes.

so wondering what might have prevented that on your end?

perhaps it's the edition? Using ultimate here, perhaps a good reason to try it out?

**Comment by ea-inspections-team** [comment]
Thanks for the proposal, @reedy. We enhanced the fixer in order to do the simplification.

**Comment by ea-inspections-team** [comment]
@ktomk: to keep it simple, we'll use the same operands order as in the original condition. The inspection you are mentioning, will take care of the order check.
