### ISSUE TITLE
Condition is always 'false' because '$str' is already 'false' at this point

### ISSUE THREAD

**Issue by onlomk** [kalessil/phpinspectionsea#1727]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) or Php Inspections (EA Ultimate), which version |
| Language level | e.g. PHP 7.2 (check project settings or composer.json)                        |

Current behaviour
--

![image](https://user-images.githubusercontent.com/40257554/117533275-7f871a00-b01e-11eb-878b-c57c7573d73d.png)

Expected behaviour
--

Environment details
---

Php 7.2
PhpStorm 2021.1.2
Php Inspections ​(EA Ultimate) 4.0.6.3

**Comment by ktomk** [comment]
Despite this weak warning created by an inspection looks fishy at first glance, it seems unrelated to the _php inspections (EA Extended)_ plugin as it will show up if you disable the plugin as well.

It looks like this is a standard Phpstorm inspection:

>Condition always evaluates to 'true/false'

>Reports the conditions that are already covered by earlier conditions and thus have no effect.

The [tracker to report issues in Phpstorm](https://youtrack.jetbrains.com/) may reveal more or better information.
