### ISSUE TITLE
[FR] PHP 8.0 - Comparison functions can no longer return a boolean

### ISSUE THREAD

**Issue by fraserredmond** [kalessil/phpinspectionsea#1736]
After upgrading to PHP 8.0 I got the following error...

> **uasort():** Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero

... when running this...

```
uasort(
    $fooArr,
    static function ($a) {
        return ($a !== null && $a !== '');
    }
);
```

(Solved by adding ` ? -1 : 1` to the end of the line.)

**Comment by niconoe-** [comment]
Yes, this is deprecated in PHP 8.0, but I don't think this is related to this project. 

Like you said, the way to fix it is doing this:

```php
uasort($fooArr, static fn (mixed $a): int => ($a !== null && $a !== '') ? -1 : 1);
```

**Comment by orklah** [comment]
I think the author is suggesting a new inspection to detect and fix those

**Comment by fraserredmond** [comment]
Yep, "FR" in the title was short for Feature Request :-) 

(Look for `uasort` which has a function that returns a bool.)

**Comment by orklah** [comment]
> Yep, "FR" in the title was short for Feature Request :-)

Oh, so those weren't your initials? 😄

**Comment by niconoe-** [comment]
> Yep, "FR" in the title was short for Feature Request :-)
> 
> (Look for `uasort` which has a function that returns a bool.)

Oh, sorry, I didn't understand it was for a feature request.  
That could be a cool feature to detect this 🙂

**Comment by ea-inspections-team** [comment]
Thanks for the proposal @fraserredmond! Implemented!
