### ISSUE TITLE
PHP 8.0 - Nullsafe operator

### ISSUE THREAD

**Issue by maisoui** [kalessil/phpinspectionsea#1737]
Description (screenshot):
Add new PHP 8.0 nullsafe operator and don't trigger a "Null pointer exception may occur here".

Example
From PHP documentation:
`$country = $session?->user?->getAddress()?->country;`

![image](https://user-images.githubusercontent.com/9716075/121142092-ed03b180-c83b-11eb-907b-a167d6080ea4.png)

Best regards

**Comment by jdreesen** [comment]
Duplicate of #1675

**Comment by ea-inspections-team** [comment]
Closing, thanks @jdreesen !

**Comment by ea-inspections-team** [comment]
Folks, this has been fixed now. We'll rollout hot-fix releases for all plugins next week.
