### ISSUE TITLE
UnSafeIsSetOverArrayInspection should not be used for magic properties

### ISSUE THREAD

**Issue by Denitz** [kalessil/phpinspectionsea#174]
```php
/**
 * Class test
 *
 * @property string $test
 */
class Test
{
	/**
	 * Get desc, required to display notice.
	 */
	public function get()
	{
		if (isset($this->test))
		{
			die;
		}
	}
}
```

`test` property can be really not set at this stage, hence null comparison won't work. Probably it can be only allowed if class or trait has `__isset()` method

**Comment by kalessil** [comment]
To keep it simple, we'll check if fields are declared for similar cases.
Thank you for reporting @Denitz.

**Comment by kalessil** [comment]
Fixed, releasing today.
