### ISSUE TITLE
How do I activate the plugin if I got it through an educational license (free)?

### ISSUE THREAD

**Issue by lsalazarm99** [kalessil/phpinspectionsea#1740]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate) 2021.1 |

Question
How do I activate the plugin if I got it through an educational license (free)?

When I start the IDE, it doesn't show the window where I can log in with my account in order to activate the plugin (like other plugins). It just starts and shows a warning, which says that I have to introduce a product key for the plugin. But, since the product key is "integrated" with my account, I can't get any product key.

![image](https://user-images.githubusercontent.com/42286051/121949348-fac6a480-cd1d-11eb-96b2-c10a5ec563b8.png)

**Comment by ea-inspections-team** [comment]
Hi @lsalazarm99, congrats with getting a license! You should be able to manage licenses under 'Help -> Register' menu. Let us know if it worked for you.

**Comment by lsalazarm99** [comment]
I noticed I was using the maintenance version. I downloaded the correct version and the register menu popped up with the plugin requesting activation. Thanks!
