### ISSUE TITLE
Define same property inspection doesn't work as expected in classes PhpDoc

### ISSUE THREAD

**Issue by algorhythm** [kalessil/phpinspectionsea#1742]
Here we can see the Inspection in a special context. A class uses a trait, inside the trait is a property that type is an Object of class `A`. Class `B` extends `A` and added a method. If I'm sure in my context that my Property from Trait only contains Objects of type `B`, how can I tell the IDE to know this? 

![Bildschirmfoto 2021-06-18 um 12 35 00](https://user-images.githubusercontent.com/427134/122548891-33be8c00-d032-11eb-8b7b-b52cbd7d2a45.png)
![Bildschirmfoto 2021-06-18 um 12 35 39](https://user-images.githubusercontent.com/427134/122548887-31f4c880-d032-11eb-9696-1e5ce032192a.png)

Above are two tries, first we add the property again with another type. That results in this inspection. **But when I define `@property B property` in classes PhpDoc, I don't expect the Inspection there, because the property is not physically in that class. It's just documented to habe another type, isn't it?**

Without both solutions I cannot use code completion here:
![Bildschirmfoto 2021-06-18 um 12 36 37](https://user-images.githubusercontent.com/427134/122549462-cb23df00-d032-11eb-8337-6a243f00a805.png)

Here is the rest of the used code:
![Bildschirmfoto 2021-06-18 um 12 36 47](https://user-images.githubusercontent.com/427134/122549536-e262cc80-d032-11eb-94ba-ce41ca578842.png)
![Bildschirmfoto 2021-06-18 um 12 36 54](https://user-images.githubusercontent.com/427134/122549546-e5f65380-d032-11eb-9a16-db50f25591ec.png)
![Bildschirmfoto 2021-06-18 um 12 37 00](https://user-images.githubusercontent.com/427134/122549552-e989da80-d032-11eb-9894-6511087b084d.png)

Maybe the issue is similar to this one: https://github.com/kalessil/phpinspectionsea/issues/1232

**Comment by ea-inspections-team** [comment]
Thanks for reporting @algorhythm! Fixed!
