### ISSUE TITLE
Wrong suggestions on Laravel Eloquent models

### ISSUE THREAD

**Issue by valkedev** [kalessil/phpinspectionsea#1747]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) |
| Language level | PHP 7.4                       |

Current behaviour
--
![image](https://user-images.githubusercontent.com/1539181/124242130-1820ae80-db25-11eb-92ae-d2ef2d0298f8.png)

Problem with barryvdh/laravel-ide-helper package.

The problem doesn't exist with EA Inspections turned off.

The method helper generated by laravel-ide-helper located in `_ide_helper.php`:
![image](https://user-images.githubusercontent.com/1539181/124242492-764d9180-db25-11eb-9179-b92c1f0944ad.png)

The problem is not just with whereIn method but all methods that can be called both: static and not.

Expected behaviour
--

Environment details
---
Laravel 8

**Comment by ea-inspections-team** [comment]
Thanks for reporting @valkedev. Looking into the signature, the inspection does its' job as expected. Probably it's better to disable the inspection in Laravel projects, as the framework is heavily using magic which is know issue for analyzers.

**Comment by rentalhost** [comment]
@ea-inspections-team there are some possibility to add a list of ignored classes? I think better than disable inspection totally, because it is very useful for other things.

**Comment by orklah** [comment]
@rentalhost Well, PHPStorm allow you to set a scope for your inspections, this scope can be created to contain any set of files from the project so there is no need for this plugin to reimplement this

**Comment by ea-inspections-team** [comment]
@rentalhost : yes, we can add a setting similar ''Except PHPUnit assertions" to handle the query builder class specifically (is that only this class from Eloquent, or there are other builders there?).

**Comment by ea-inspections-team** [comment]
@orklah : thanks for the hints! In this case we could enhance the inspection, so developers have less to do with initial configuration.

**Comment by valkedev** [comment]
@ea-inspections-team there's also Query Builder

**Comment by ea-inspections-team** [comment]
Sounds good, thanks folks! We added support for Eloquent models and enabled it by default.
