### ISSUE TITLE
[EA Ultimate] "Development dependencies usage" inspection has no docs

### ISSUE THREAD

**Issue by JacekAndrzejewski** [kalessil/phpinspectionsea#1748]
EA Ultimate has an inspection for development dependencies which redirects to [docs](https://github.com/kalessil/phpinspectionsea/blob/master/docs/architecture.md#development-dependencies-usage), but the section for that inspection doesn't exist.
At the same time inspection tooltip isn't really helpful and it has mistakes.
![obraz](https://user-images.githubusercontent.com/29729811/124285519-4666b400-db4e-11eb-9d45-5d508f14aec5.png)

I guess that in "directly **on** indirectly" the "on" should be replaced by "or", and later "actualize" should probably be "update".
It would also be great if the tooltip (or docs) mentioned what could be a possible fix.

**Comment by ea-inspections-team** [comment]
Thanks for reporting @JacekAndrzejewski : we added the documentation chapter and updated wording.
