### ISSUE TITLE
Advise against undefined property reading and writing

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#175]
Currently PHP supports reading and writing in class instances even if this property doesn't exists. But it reduces the code quality because you will do not know where it happen, the property name, etc. 

**For instance:**

```php
class MyClass { }

$myClass = new MyClass;
$myClass->number = 123;
```

It's a valid code, but the property `$number` is not defined in any place, only here. It generally is allowed with a `\stdClass` because it is generic - _I still think that it should be avoided, btw_.

Then I think that EA should advice against undefined property reading and writing. Are two similar validation, in case: one for reading and another for writing.

**It should consider that:**

* Class not is `\stdClass` (_should consider instance of too?_);
* Class do not defines `__get()` for magic reading and `__set()` for magic writing;
* Class do not annotate the property with `@property`;
* Class do not annotate the property with `@property-read` on a writing outside the class scope;

**Comment by orklah** [comment]
I'm pretty sure this is now part of "Undefined field" in PHPStorm. The code now triggers a warning on "number" with "Field declared dynamically" warning.

**Comment by funivan** [comment]
@kalessil We can close this issue. `Undefined fields` works fine for me too.

**Comment by andreasschroth** [comment]
I confirm. PhpStorm warns about this now.

**Comment by kalessil** [comment]
Done, closing as duplicate.
