### ISSUE TITLE
BUG: The inspection finds an "error" and offers to fix it, corrected code causes another inspection "error"

### ISSUE THREAD

**Issue by WinterSilence** [kalessil/phpinspectionsea#1751]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 4.0.6.4  |
| Language level | PHP 7.3                       |

The inspection "PHP | Php Inspections (EA Extended) | Probable bugs | Addition operator used on arrays" finds problem and offers to fix it:
![Addition operator used on arrays](https://user-images.githubusercontent.com/3521094/126908429-ab4d9097-7672-47cd-a59f-6c62db7adb69.png)
corrected code causes inspection "PHP | Php Inspections (EA Extended) | Performance | Slow array function used in loop":
![изображение](https://user-images.githubusercontent.com/3521094/126908571-210db733-0198-40b1-8a69-73652d90a0d2.png)
dead loop...

**Comment by rentalhost** [comment]
@WinterSilence could you please show more code?

Generally, the `array_merge()` in loop could be avoided.

**Comment by WinterSilence** [comment]
@rentalhost Inspection "Addition operator used on arrays" must ignore `array += array` in cycles.

**Comment by jdreesen** [comment]
Why? `array_merge` and `+=` on arrays behave differently - and mostly the behavior of `array_merge` is the intended one.

The fix to avoid `array_merge` in loops is mostly something like:

```php
$result = [];
foreach ($input as $key => $values) {
	$result[] = $values;
}

return array_merge(...$result);
```

**Comment by WinterSilence** [comment]
~~~php
$default = ['public' => 0];
$allData = [
    ['id' => 1, 'public' => 1],
    ['id' => 2],
];
foreach ($allData as &$data) {
       $data += $default;
}
unset($data);
~~~

**Comment by WinterSilence** [comment]
@jdreesen also, you example not so useful:
`$input = array_merge(...array_values($input));`

**Comment by jdreesen** [comment]
> $input = array_merge(...array_values($input));

Yes, that should work too in this specific case (if you don't want to do anything else in the loop).

**Comment by ea-inspections-team** [comment]
Thanks for joining the discussion @jdreesen !

**Comment by ea-inspections-team** [comment]
@WinterSilence, the inspection which complained about '+=' has been dropped in one of recent releases.
