### ISSUE TITLE
Warn if using a dev dependency in non-dev code!

### ISSUE THREAD

**Issue by garethellis36** [kalessil/phpinspectionsea#1752]
Hello :)

I'm not sure if what I am proposing is possible... but it would be awesome if it is.

We had a bug reach staging, which I luckily caught through manual smoke tests before it reached production: I had accidentally used a library that was only installed as a dependency of one of our `require-dev` dependencies, in application code. All our tests passed, so I assumed that all was well until I saw the error!

If there was a way for PhpStorm to warn me that I've done something idiotic at write-time, it would probably have stopped this from happening. Do you think it's possible?

**Comment by ea-inspections-team** [comment]
Thanks for a great proposal @garethellis36 ! This feature is available in [Php Inspections (EA Ultimate)](https://plugins.jetbrains.com/plugin/16935-php-inspections-ea-ultimate-) (it's a paid extension though).
