### ISSUE TITLE
Macbook M1 Support? PHP 7.3, Inspections 3.0.12

### ISSUE THREAD

**Issue by Atomzwieback** [kalessil/phpinspectionsea#1754]
Current behaviour

Plugin could not be loaded due missing compatible architecture.

`/Users/somename/Library/Caches/JetBrains/PhpStorm2021.1/tmp/jna8488280580868138828.tmp: dlopen(/Users/somename/Library/Caches/JetBrains/PhpStorm2021.1/tmp/jna8488280580868138828.tmp, 0x0001): tried: '/Users/somename/Library/Caches/JetBrains/PhpStorm2021.1/tmp/jna8488280580868138828.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/lib/jna8488280580868138828.tmp' (no such file)
`

Expected behaviour

Plugin should be provide a compatible architecture. In this case "arm64e".

Environment details

MacBook Pro 13 M1 2020

**Comment by Atomzwieback** [comment]
@ea-inspections-team

**Comment by ea-inspections-team** [comment]
Thanks for reporting @Atomzwieback, looks like you are on a deprecated version of Php Inspections (EA Ultimate) plugin.
The relevant one is here: https://plugins.jetbrains.com/plugin/16935-php-inspections-ea-ultimate-

Do you have an active license for your version of the plugin (are you a Patreon supporter or purchased a license (when))?

**Comment by Atomzwieback** [comment]
I have an active license via the Jetbrains Store ( bought the same day i wrote this report but also was an patreon supporter a while ago)

**Comment by ea-inspections-team** [comment]
Hey @Atomzwieback, is everything working well for you with regards to the previous comments?
