### ISSUE TITLE
Bug with inspection of mkdir "Some checks are missing" when they are present

### ISSUE THREAD

**Issue by Girgias** [kalessil/phpinspectionsea#1758]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended), PHPStorm 2021.2  (4.0.6.4) |
| Language level | PHP 8.0                       |

Current behaviour
--

The following two code snippets generate the following error:

> [EA] Some check are missing: '!mkdir($directory, 0644, true) && !is_dir(...)'.

```php
    if (!\is_dir($directory)) {
        if (!mkdir($directory, 0644, true)) {
            throw new \RuntimeException('Directory "' . $directory . '" was not created');
        }
    }
```
and
```php
    if (!\is_dir($directory) && !\mkdir($directory, 0644, true)) {
            throw new \RuntimeException('Directory "' . $directory . '" was not created');
        }
    }
```

Expected behaviour
--

No error message

Environment details
---

PhpStorm 2021.2
Build #PS-212.4746.100, built on July 28, 2021
Licensed to PHP / George Peter Banyard
Subscription is active until September 7, 2021.
For non-commercial open source development only.
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 726M
Cores: 4
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: com.intellij.ideolog (203.0.27.0), com.kalessil.phpStorm.phpInspectionsEA (4.0.6.4), cz.jiripudil.intellij.nette.tester (2.1.0)

**Comment by ea-inspections-team** [comment]
Thanks for reporting @Girgias !

That's expected behaviour, the race condition safe approach is `! \is_dir( ... ) && ! mkdir( ... ) && ! is_dir( ... )` and [here](https://github.com/kalessil/phpinspectionsea/blob/master/docs/probable-bugs.md#mkdir-race-condition) explained why.

We'll close the issue, but if the documentation is not helpful enough, please reach comment here so we could together make it better.
