### ISSUE TITLE
False positive: 'empty(...)' usage

### ISSUE THREAD

**Issue by foobar13372** [kalessil/phpinspectionsea#1759]
I have a method `getId(): ?int`

EA suggests for `if (empty($obj->getId())) {}` to use `null ===` instead.

This is wrong. 0 is also empty and also checked for in my case, my else branch should onyl trigger if it is `> 0`, neither `null` nor `0`. 

Either drop this check or suggest an additional alternative if the type is `?int`:
`null === || 0 ===`

**Comment by ea-inspections-team** [comment]
Thanks for reporting @foobar13372 !
Would you please share details about the plugin version? Thanks!

**Comment by foobar13372** [comment]
I'm currently using verison 4.0.6.5. I reported the issue in some older version, but this newer version still has it.

**Comment by ea-inspections-team** [comment]
Thanks, we'll look into it.

**Comment by ea-inspections-team** [comment]
Done! We added a new inspection setting "Suggest null-comparison for scalars", which needs to be disabled in this case.
