### ISSUE TITLE
Forgotten Debug Statements: make error_log/etc. configurable

### ISSUE THREAD

**Issue by aikar** [kalessil/phpinspectionsea#176]
Please remove error_log from the forgotten debug statements inspection.
Software might use this as their logging mechanism. 

This is not a debug method that results in feedback that the end user would see viewing a webpage.

There is no way to remove just this case from the inspection, leaving the others on.

An inspection about debug statements should not relate to opinions about application logging.

**Comment by kalessil** [comment]
Thank you for reporting @aikar, making default methods/function configurable seems reasonable here.

**Comment by kalessil** [comment]
Update: I'll move all default methods/function into the custom list in the inspection settings.
You'll be able then to configure the inspection according to your needs.

**Comment by kalessil** [comment]
All frameworks debug methods, error_log, phpinfo will appear in custom debug methods list - so you'll be able to turn off the challenged reports =) Should be pretty neat IMO.
