### ISSUE TITLE
"Development dependencies usage" should exclude test sources and fixtures

### ISSUE THREAD

**Issue by donquixote** [kalessil/phpinspectionsea#1761]
| Subject        | False positive: "Development dependencies usage" should exclude test sources and fixtures                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate) 4.91 |
| Language level | PHP 7.4                        |

## Steps
Create a project.
Require "phpunit/phpunit" in "require-dev" in composer.json (and not in "require").
Create subdir "tests/src", mark as "Test sources root" (and assign a namespace).
Create a test class inside tests/src, inherit from `PHPUnit\Framework\TestCase`. Make sure this class is imported with a "use" statement, instead of using the FQCN in-place.

### Current behaviour
Inspection warning from "Development dependencies usage":

> [EA] The class belongs to a package which is directly on indirectly belongs to dev-dependencies in composer.json file. Please actualize composer.json if this is intended.

See https://github.com/kalessil/phpinspectionsea/blob/master/docs/architecture.md#development-dependencies-usage

### Expected behaviour
No inspection warning, because this usage is within "test sources".
Or perhaps this could be an option.

## Environment details
PhpStorm 2021.2
Build #PS-212.4746.100, built on July 28, 2021
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.11.0-31-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1904M
Cores: 8
Registry: run.processes.with.pty=TRUE, search.everywhere.settings=true, ide.tooltip.initialDelay=952
Non-Bundled Plugins: com.kalessil.phpStorm.phpInspectionsUltimate-mp (2021.2), de.espend.idea.php.annotation (8.0.0)
Current Desktop: KDE

**Comment by donquixote** [comment]
Hi,
any news on this?
Is the "expected behavior" reasonable, or do you think I am doing it wrong?

**Comment by SelrahcD** [comment]
Hi!

I'm dealing with the same issue. I've changed the inspection settings to not show up when in the test scope. Hopes it help you.

**Comment by ea-inspections-team** [comment]
Thanks for checking in @donquixote, @SelrahcD ! 

The inspection skips the context of the test [here](https://github.com/kalessil/phpinspectionsea/blob/master/src/main/java/com/kalessil/phpStorm/phpInspectionsEA/openApi/BasePhpElementVisitor.java#L106) and as you can notice it checks certain file and class name patterns.

We'll surely check if we could recognize the folders marked as tests, but it would help a lot to understand why referenced test sources detection is not working for you. Is it an OSS project? Or perhaps file/class names could be shared here?

**Comment by ea-inspections-team** [comment]
Update: we found a way to recognize folders, marked as tests sources, working on integrating the functionality.

**Comment by ea-inspections-team** [comment]
Done!

**Comment by SelrahcD** [comment]
I didn't have time to check yet, but wanted to thank you anyway :)

**Comment by ea-inspections-team** [comment]
You are welcome! The changes will be available in the next release (~ end of the next week).
