### ISSUE TITLE
Typec variadics parameters flagged as "no-sense evaluation"

### ISSUE THREAD

**Issue by Geolim4** [kalessil/phpinspectionsea#1763]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) or Php Inspections (EA Ultimate), which version |
| Language level | 7.2+                       |

Current behaviour
--
![image](https://user-images.githubusercontent.com/1332071/131261950-e0fc47e7-66d0-498c-8fe0-3ad621a97333.png)

Expected behaviour
--
![image](https://user-images.githubusercontent.com/1332071/131261938-ab9ed84e-fa9b-4cd4-9553-cccbf9b16729.png)

Environment details
---

I think that the plugin wrongly evaluates typed variadics that are array of "specified type" in method/function definitions.

**Comment by orklah** [comment]
Is there any case where the type could be anything else than an array? I agree that the wording is wrong, but the warning in itself seem to make sense

**Comment by Geolim4** [comment]
A variadic parameter can only be an array. An array of parameters (typed or not) but a variadic parameter can only be an array.

**Comment by ea-inspections-team** [comment]
Fixed!
