### ISSUE TITLE
PHP 8: remove default assignment fails with null

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#1764]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | U 2021.2 4.0.6.4 |
| Language level | PHP 8.0             |

Current behaviour
----
```php
class Test {
    private StdClass|Closure|null $test = null;
    
    public function test() {
        return $this->test;
    }
}
```

In that example, `$test = null` is required, else will can get the error _typed property Test::$test must not be accessed before initialization_ ([3v4l](https://3v4l.org/BcpGQ#v8.0.10)).

**Comment by rlempa** [comment]
Duplicate #1753.
