### ISSUE TITLE
Inspection `PHP | Php Inspections (EA Extended) | Type compatibility | 'empty(...)' usage`

### ISSUE THREAD

**Issue by WinterSilence** [kalessil/phpinspectionsea#1766]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 4.0.6.4 |
| Language level | PHP 7.4                       |

Current behaviour
--
![изображение](https://user-images.githubusercontent.com/3521094/133127587-f9da7fec-72f4-4e35-b4dd-c1ce879750e9.png)
![изображение](https://user-images.githubusercontent.com/3521094/133127537-e065ea90-f979-4bec-bfb7-6da793184ff2.png)

Expected behaviour
--
`$user` can be `bool|null|object`, `$user !== null` ignore boolean value.

Environment details
---
yii2

**Comment by ea-inspections-team** [comment]
Thanks for reporting @WinterSilence !
We couldn't reproduce the issue, but added a new test case to ensure it's not appearing again.

**Comment by WinterSilence** [comment]
@ea-inspections-team sorry but I'm don't use your plugin now - negative aspects outweighed positive ones. your inspections in most cases focus on code optimization, but don't analyzes code

**Comment by rentalhost** [comment]
@WinterSilence if you are using Yii2, so `User::getIdentity()` will returns `IdentityInterface|null` ([source](https://github.com/yiisoft/yii2/blob/dcd1810d87a5ed496b47470cd40c9957ec7c0561/framework/web/User.php#L182-L213)). In that case, the `bool` is incorrect and it is based on the own IDE itself, because the `$this->_identity` is initially `false`, but it is never returned by this method.

In this case, the inspection works fine.

**Comment by ea-inspections-team** [comment]
Thanks for sharing feedback and all your reports @WinterSilence, that helped greatly!

If you could share what you mean by "but don't analyze code", that would be terrific. 
What sort of analysis (or perhaps which tools) do you find helpful in your daily work?

**Comment by WinterSilence** [comment]
@rentalhost  you can't read description to class but true learn me... https://github.com/yiisoft/yii2/blob/dcd1810d87a5ed496b47470cd40c9957ec7c0561/framework/web/User.php#L31

**Comment by WinterSilence** [comment]
@ea-inspections-team in most case your inspection find "errors" by regexp, without static analize

**Comment by ea-inspections-team** [comment]
@WinterSilence, many thanks for sharing more details!

**Comment by rentalhost** [comment]
@WinterSilence what I mean here is that the `bool` return type inference is **wrong** and will **never happen**. It is an incorrect analysis did by the PhpStorm itself, and not by this plugin ([**I have reported it here**](https://youtrack.jetbrains.com/issue/WI-64284)).

So you really don't need to use `!empty($user)`, and the inspection suggestion is correct: you could use safetly `$user !== null`.
