### ISSUE TITLE
Preg match output data detection

### ISSUE THREAD

**Issue by funivan** [kalessil/phpinspectionsea#177]
```php
$content = 'aabaab';
preg_match_all('/a([a-z]+)b/',$content, $items);
foreach ($items[1] as $data) {   // Expressions type was not recognized
  echo $data;
}
```
I do not know if this is a bug of the current inspection, or feature for the new one.
Also if we write `$items[0]` we have the same error even. But in all cases `$items[0]` will be an array

**Comment by kalessil** [comment]
It looks like rather a bug report for PS =) I'll post it today and share a link here back (JB are already remembered my name, let see if it helps anyhow).

**Comment by kalessil** [comment]
I started writing the ticket, but found a solution instead:

```php
        /* @var $items string[][] */
        preg_match_all('/.+/','.', $items);
        foreach ($items[1] as $data) {   // Expressions type was not recognized
            echo $data;
        }
```
