### ISSUE TITLE
Php Inspections (EA Extended) | Performance | Cascading 'str_replace(...)' calls

### ISSUE THREAD

**Issue by WinterSilence** [kalessil/phpinspectionsea#1773]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) last version |
| Language level | PHP 7.4                      |

before
~~~php
$pattern ='glob://foo\bar\*';
$pattern = str_replace('glob://', '', $pattern);
$pattern = str_replace(['\\', '/'], DIRECTORY_SEPARATOR, $pattern); // `foo/bar/*` 
~~~
after
~~~php
$pattern ='glob://foo\bar\*';
$pattern = str_replace(['glob://', '\\', '/'], ['', DIRECTORY_SEPARATOR], $pattern); // `foobar*` 
~~~

**Comment by WinterSilence** [comment]
not combine arguments when first and second arguments dont' have same type

**Comment by ea-inspections-team** [comment]
Thanks for reporting @WinterSilence ! That's a valid point, we'll address the issue in #1776.

**Comment by ea-inspections-team** [comment]
Re-opening, that's another bug.

**Comment by ea-inspections-team** [comment]
Fixed!
