### ISSUE TITLE
cascading str_replace calls when one is an array and the other not

### ISSUE THREAD

**Issue by Stevehans** [kalessil/phpinspectionsea#1776]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) ,4.0.6.4 |
| Language level |8.0                    |

$str = str_replace('=', '=3D', $str);
$str = str_replace(self::$qpKeys, self::$qpReplaceValues, $str);
The two class constants are arrays.

These are merged as follows:-
        $str = str_replace(array('=', self::$qpKeys), array('=3D', self::$qpReplaceValues), $str);

However, we now have an array containing an array

--

Expected behaviour

Should not attempt to merge these.

**Comment by ea-inspections-team** [comment]
Thanks for reporting @Stevehans!
Agree, that should not merge this way. Should be `$str = str_replace(['=', ...self::$qpKeys], ['=3D', ...self::$qpReplaceValues], $str);` when language level allows.

**Comment by ea-inspections-team** [comment]
Fixed!
