### ISSUE TITLE
Wrong warning?: [EA] Makes no sense, because it's always ...

### ISSUE THREAD

**Issue by max4ever** [kalessil/phpinspectionsea#1778]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate) 2021.2 |
| Language level |  PHP 7.0                     |

Current behaviour
--
Hi,
I get these warnings which I think are not correct: 
![immagine](https://user-images.githubusercontent.com/1863265/142653659-6486ca4e-0ab7-4a77-9305-ce25e807bb4a.png)

It is only correct if we type hint  the parameter with a class or something, without typehint it is a wrong suggestion.

Expected behaviour
--

I can always pass `null` manually, this has actually caused me to break my code, as I was not careful enough.
Source code: https://github.com/kalessil/phpinspectionsea/blob/master/testData/fixtures/types/parameter-types-checks.php#L10

Environment details
 ---

Phpstorm 2021.2.3
![immagine](https://user-images.githubusercontent.com/1863265/142653825-7d0d1066-bf0b-4087-96a0-8e815d555982.png)

**Comment by ea-inspections-team** [comment]
Thanks for reporting @max4ever !

Unfortunately, the information about possible types, in this case, is provided by IDE itself, and we can not do much about it.
Likely doc-block for the method can be added/updated to reflect that it could be null and the warning will not be shown.
