### ISSUE TITLE
Bug in "foreach" quickfix

### ISSUE THREAD

**Issue by mambax7** [kalessil/phpinspectionsea#1779]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate)  2021.2 |
| Language level | PHP 7.2                        |

Current behaviour
--
I had this code:
![image](https://user-images.githubusercontent.com/613686/142714158-8bf46d2b-eedc-4d0e-9ad0-a728b15d5f86.png)

and the quickfix converted it to this:

![image](https://user-images.githubusercontent.com/613686/142714164-ffad62cb-ddfe-44ce-83c8-a86b551f1349.png)

Expected behaviour
--
Unfortunately, the result was not the same, because we've missed the "&" in:

![image](https://user-images.githubusercontent.com/613686/142714185-dc662892-25e1-4dc3-8296-e7e57f448854.png)

Environment details
---
PhpStorm 2021.3 EAP

**Comment by kalessil** [comment]
Note: `cleanupChars` and `wrapCdata` has the first parameter declared as a reference. The QF shouldn't replace those entries.

**Comment by ea-inspections-team** [comment]
We couldn't reproduce in regular releases, but tweaked possible reason and added more test cases to see if it starts failing at some point.
