### ISSUE TITLE
Type inference is incorrect with closure

### ISSUE THREAD

**Issue by alvin0319** [kalessil/phpinspectionsea#1780]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 4.0.6.4 |
| Language level | PHP 8.0|

Current behaviour
--

The following code cannot be null, but Inspection says this can be null
![스크린샷(1)](https://user-images.githubusercontent.com/32565818/142728744-1b918972-04dc-4295-9af6-3fd15b4af458.png)

In this image, `$category->getShops()` returns the `Shop[]`, and cannot contain null because in `Shop` constructor the null values will be removed.
![image](https://user-images.githubusercontent.com/32565818/142728781-df8b9d2a-51b3-4bfe-afd5-db207cd9a102.png)
(The code from `Category->getShops()`)
![image](https://user-images.githubusercontent.com/32565818/142728790-a5d17698-e1bd-4db2-850c-25c1f955f46f.png)

Expected behaviour
--
`$shop->getDesignedItem()` should be inferred that cannot be null.

I think this bug was caused by the code inside closure, which defines `$shop` variable and on that code `$shop` can be null.

Environment details
---

IDE: IntelliJ IDEA IU-212.5457.46 with PHP plugin version 212.5457.49.

**Comment by ea-inspections-team** [comment]
Thanks for reporting @alvin0319!

What about line 57, where `$shop` values is set to result of `getShop` method? Can the method return `null`?

**Comment by alvin0319** [comment]
> Thanks for reporting @alvin0319!
> 
> What about line 57, where `$shop` value is set to result of `getShop` method? Can the method return `null`?

Yes, `getShop()` can return null.

**Comment by ea-inspections-team** [comment]
Ok, that's why the inspection is complaining.Looks like a proper behaviour to us.
