### ISSUE TITLE
False positive: [EA] ': void' can be declared as return type hint.

### ISSUE THREAD

**Issue by N-Molham** [kalessil/phpinspectionsea#1785]
Thanks for the amazing plugin, it is pretty helpful and productive

| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) |
| Language level | PHP 7.0 |

Current behaviour
--
After updating to the latest version of PhpStorm 2021.3 (Build #PS-213.5744.279, built on December 2, 2021), I started to get return type hint warning with project with PHP language level at 7.0 (specially void return)

![image](https://user-images.githubusercontent.com/3770036/144638625-74ef2f94-b410-4039-a311-738ba1e9ffe6.png)

Expected behaviour
--
As before the IDE update, if the language level is 7.0 the return type hint doesn't show up

Environment details
---
MacOS Big Sur

**Comment by ea-inspections-team** [comment]
Thanks for reporting @N-Molham! Fixed!

**Comment by N-Molham** [comment]
@ea-inspections-team thanks for the quick solution, is there a way to implement it till the new version get released? maybe a pre-release?

**Comment by ea-inspections-team** [comment]
@N-Molham, unfortunately not. The next release is expected early January 2022, with Christmas time approaching it'll very soon.
