### ISSUE TITLE
Nightly build (again)

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#1786]
Lately I've noticed that @ea-inspections-team is giving all the power to resolve the pending issues, which made me very excited (and yes, I intend back to help, but I need to format my PC and I still don't know when I'll be able to do that -- everything's chaotic here).

However, I still miss being able to test the new features as soon as they are implemented.

So I wanted to know about the possibility of having a nightly build version of the plugin, like in #325.

And, if you allow me a slightly more "intrusive" opinion, it would be interesting if the ultimate nightly version was published officially and for free on the Jetbrains platform (as an alternative to the paid Ultimate version).

With that, I see the following opportunities:

- It would give all developers a "taste" of the Ultimate version, which might make them interested in paying for the stable version in the future. It could be something like 14 days of license whenever a new version is released (auto-renewable, but in this case, you would have to ensure that every day new versions would be released, so the license, in theory, would never expire). If I'm not mistaken, it's a similar model to what SmartGit does: you can use it for free, as long as you're helping to test the tool, knowing that there are possible risks that you must take when installing it.

- A discount could be offered to users who use this model for long periods. For example: 3 months = 15% off, 6 months = 30% off, 1 year = 50% off. In my case, for example, I would be interested in using the development version for personal projects, at home, but at work I would use the stable version.

- It could be a package version with more debugging tools (which helps in development "from the Java side"). As an automatic sending of errors to Sentry (or even ask the user for more information, perhaps sending more data than usual), as it will take into account that the user has accepted the proposal to use this way.

- It could activate by default some very-alpha inpections or little used inspections, to find out what the developer thinks about it.

- Another alternative to licensing would be to ask the user for feedback (something like a Google Form) so they can say what they think about the new updates. Something like once a month creating a form asking if the user has used any new tools, if they have encountered any problems, or if they have any suggestions.

- All this would help a lot before an official release. And updates could be daily or immediate (but it depends of Jetbrains, and I don't know if today is more faster to publish updates).

The only detail I don't know is if Jetbrains allows it.

**Comment by ea-inspections-team** [comment]
Hi @rentalhost! Yes, we addressed a bunch of bugs from the backlog, that was a great experience =)

Other points are great, but the licensing system we are using is the same as for JetBrains IDEs, and the options you are mentioning are not available for us.

Even nightly-builds would need a regular license, so we would rather follow the approach of the monthly releases. That should help keeping high-quality mark people are expecting from the project.
