### ISSUE TITLE
Rethink Unnecessary boolean expression

### ISSUE THREAD

**Issue by paveldvorak5** [kalessil/phpinspectionsea#1789]
Description (screenshot):
We don't think it's a good idea to simplify "false" condition.
Our code style is to write positive conditions (we don't use === true for position expressions), so when there's "=== " in the condition, we know automatically that it's an unusual condition.
Also you can totally miss the "!" when you have got a smaller font.

Example
--
`if( $expression === true ) {}`
It's good here to drop the "true" part.

But
`if( $expression === false ) {}`
It's probably not the best idea to simplify it to `!$expression`.

**Comment by ea-inspections-team** [comment]
Thanks for reporting @paveldvorak5!  We added a new setting "Simplify false-statements (to '! <expression>')", so you could tune the inspection to better match the code style you are using.
