### ISSUE TITLE
Code completion class constats access modifier for PHP 7.0

### ISSUE THREAD

**Issue by eyedmax** [kalessil/phpinspectionsea#1790]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended), 4.0.7 |
| Language level | PHP 7.0                        |

Current behaviour
--
![image](https://user-images.githubusercontent.com/3912541/145239798-7c4571da-69c7-4001-a0d5-65558657d6d1.png)

When agreed,
![image](https://user-images.githubusercontent.com/3912541/145240036-62f0236e-7f9c-4b78-96e8-de1244968312.png)

Expected behaviour
--
There are no const access modifiers in PHP 7.0

Environment details
---

PhpStorm 2021.3
Build #PS-213.5744.279, built on December 2, 2021
Runtime version: 11.0.13+7-b1751.19 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by ea-inspections-team** [comment]
Thanks for reporting @eyedmax! Fixed in 7ac76a2a55b4e66e4fdf1f367b0d7d79bff554de !
