### ISSUE TITLE
JSON_THROW_ON_ERROR doesn't make sense with JSON_PARTIAL_OUTPUT_ON_ERROR

### ISSUE THREAD

**Issue by ranvis** [kalessil/phpinspectionsea#1791]
| Subject        | Details                               |
| :------------- | :------------------------------------ |
| Plugin         | Php Inspections (EA Extended) , 4.0.7 |
| Language level | PHP 8.0                               |

Current behaviour
--
`json_encode()` with `JSON_PARTIAL_OUTPUT_ON_ERROR` flag triggers warning:
> [EA] Please consider taking advantage of JSON_THROW_ON_ERROR flag for this call options.
```php
<?php
$d = new stdClass();
$d->d = $d;
throw new InvalidArgumentException('invalid value: ' . json_encode($d, JSON_PARTIAL_OUTPUT_ON_ERROR));
```

Expected behaviour
--
No warning if `JSON_PARTIAL_OUTPUT_ON_ERROR` is specified.
While both flags can be specified at the same time, it is almost no-op (although throw-on-error flag makes the last JSON error retained on function entry.)

Environment details
---
PhpStorm 2021.3
Build #PS-213.5744.279, built on December 2, 2021
Runtime version: 11.0.13+7-b1751.19 amd64

**Comment by ea-inspections-team** [comment]
Thank you for reporting @ranvis! Fixed!
