### ISSUE TITLE
non optimal if conditional

### ISSUE THREAD

**Issue by bordunosp** [kalessil/phpinspectionsea#1792]
```php
if ($errors = $validator->validate($req) and $errors->count() > 0) {
    throw new RequestValidationException(errors: $errors);
}
```
<img width="760" alt="Screenshot 2021-12-14 at 16 38 21" src="https://user-images.githubusercontent.com/4907275/146019097-d06fded7-2505-42d7-ae29-cd6bbde37ce0.png">

"&&" not really is "best practices"

"AND" vs "&&" work differently
the sequence from left to right is important to me

if I change "and" to "&&" I will got exception "Undefined variable $errors"
Exception can't be  best practices :)

**Comment by rentalhost** [comment]
I agree with you. But at the same time, assuming that `AND` and `&&` have the same behavior is a common mistake in PHP.

In that case, I would agree to change the information contained in the text (removing the "best practices"), but keep the inspection alerting of a possible problem.

In the case of your code, I would suggest changing it to avoid using `AND`. At the same time it avoids assigning variables inside an `if()`.

A last option would be to make the inspection more complex to the point of understanding that the `AND` complements the assignment of the variable declared before and allow it.

**Comment by bordunosp** [comment]
do you think it would be better?)

```php
$errors = $validator->validate($req);

if ($errors !==null && $errors->count() > 0) {
    throw new RequestValidationException(errors: $errors);
}
```

imho mistake in PHP is "&&" 
mb add a warning not to use "&&"? 
many young people do mistakes with them..

**Comment by rentalhost** [comment]
Yes, I think it better describes the "step by step" of events, without confusing the meaning of `AND`.

Regarding the problem being between `AND` and `&&`, I believe that the functioning of `&&` is more common in all languages, and it seems that only PHP makes this distinction. In any case, the confusion is general and both have distinct features that cannot be ignored.

**Comment by ea-inspections-team** [comment]
Thanks for reporting @bordunosp and for joining the discussion @rentalhost !

We'll stay aside from personal preferences here =) But, good news is that the inspection has settings to report literal `or`, `and` and you can disable reporting this by un-checking corresponding check-box.

**Comment by bordunosp** [comment]
ok, other example :)

```php
if (
    $errors = $validator->validate($req) and 
    $errors->has('some_special_error') and
    $special_error = $errors->get('some_special_error') and
    $special_error->hasMessage()
) {
    throw new RequestValidationException($special_error->getMessage());
}
```
vs

```php
$errors = $validator->validate($req);
        
if ($errors->has('some_special_error')) {
    $special_error = $errors->get('some_special_error');
            
    if ($special_error->hasMessage()) {
        throw new RequestValidationException($special_error->getMessage());
    }
}
```

which is easier to perceive?

**Comment by jdreesen** [comment]
Definitely the second one. Those big if condition blocks are unreadable for me.

**Comment by jdreesen** [comment]
> We'll stay aside from personal preferences here =) But, good news is that the inspection has settings to report literal or, and and you can disable reporting this by un-checking corresponding check-box.

Maybe there should be a warning that it is a behavior change?

**Comment by bordunosp** [comment]
>> Maybe there should be a warning that it is a behavior change?

mb ignoring both?
Any can use any)


p.s.
the second one is still cleaner?

```php
if (
    $errors = $validator->validate($req) and
    $errors->has('some_special_error') and
    $special_error = $errors->get('some_special_error') and
    $special_error->hasMessage() and
    $this->getUser() and
    $this->getUser()->isAdmin()
) {
    throw new RequestValidationException($special_error->getMessage());
}
```

vs

```php
$errors = $validator->validate($req);

if ($errors->has('some_special_error')) {
    $special_error = $errors->get('some_special_error');

    if ($special_error->hasMessage()) {
        $user = $this->getUser();
                
        if ($user !== null && $user->isAdmin()) {
            throw new RequestValidationException($special_error->getMessage());
        }
    }
}
```

**Comment by jdreesen** [comment]
> the second one is still cleaner?

Sure, the first one still has a big condition block ;)

But I would rather write it something like this:

```php
function getSpecialErrorMessage($req): ?string
{
	  $errors = $validator->validate($req);
	  
	  if (!$errors->has('some_special_error')) {
	      return null;
	  }
	  
	  $specialError = $errors->get('some_special_error');
	      
	  return $specialError->hasMessage() 
	      ? $specialError->getMessage()
	      : null;
}

function isAdmin(): bool
{
	  $user = $this->getUser();
	              
	  return $user && $user->isAdmin();
}


if (isAdmin() && $specialErrorMessage = getSpecialErrorMessage($req)) {
	throw new RequestValidationException($specialErrorMessage)
}
```

**Comment by rentalhost** [comment]
@bordunosp The problem is not "how nice it looks", but how easy it is to be interpreted by other users who might come to works your code in the future (if this is a possibility -- but even if it isn't, i always prefer not to leave any surprises for the future-me).

In your example, I'd rather create a separate method to validate without needing to nest the `if()`'s.

@jdreesen I was just now preparing this example. You were faster! haha

**Comment by bordunosp** [comment]
> ```
> if (isAdmin() && $specialErrorMessage = getSpecialErrorMessage($req)) {
> ```


"without needing to nest the "

:)

**Comment by jdreesen** [comment]
Well, write it like this, if you want :stuck_out_tongue: 

```php
$specialErrorMessage = getSpecialErrorMessage($req)
if (isAdmin() && $specialErrorMessage) {
    throw new RequestValidationException($specialErrorMessage)
}
```

**Comment by bordunosp** [comment]
The bottom line is that "and" is predictable because it executes code from left to right.
which cannot be said about "&&".

And if we are talking about the perception of your code by other people, 
then I would like to read the code from left to right.

Accordingly, it is impossible to impose (even in a mild form) the replacement of one with the other.
Even if other languages ​​use the "&&" you are used to

**Comment by bordunosp** [comment]
> Well, write it like this, if you want 😛
> 
> ```
> $specialErrorMessage = getSpecialErrorMessage($req)
> if (isAdmin() && $specialErrorMessage) {
>     throw new RequestValidationException($specialErrorMessage)
> }
> ```

in truth, no difference.
My example avoids multiple “if” influences.
No more, no less

**Comment by rentalhost** [comment]
I particularly don't see a problem with nesting `if()`'s, as long as there's no exaggeration, as it certainly raises the possibility of improving the code.

```php
if (isAdmin()) {
    $specialErrorMessage = getSpecialErrorMessage($req);

    if ($specialErrorMessage) {
        throw new RequestValidationException($specialErrorMessage)
    }
}
```

In some languages (if I'm not mistaken, Python) there is an interesting feature that would help a lot in this specific case, but the folks behind PHP didn't really accept the idea, which would basically be this:

```php
if (isAdmin()) {
    $specialErrorMessage = getSpecialErrorMessage($req);

    throw new RequestValidationException($specialErrorMessage)
        if $specialErrorMessage;
}
```

But if you really hate nested `if()`'s with all your might, you can still do something like this (https://3v4l.org/6D37P#v8.1.0):

```php
if (isAdmin()) {
    $specialErrorMessage = getSpecialErrorMessage($req);

    $specialErrorMessage and
        throw new RequestValidationException($specialErrorMessage);
}
```

But getting back to the discussion itself, the biggest problem with using `AND` is the confusion generated by the existence of `&&`. Whenever there is an `&&` we read "and", and never a "right precedence and" (the same goes for `AND`).

I suggest reading this thread:

https://stackoverflow.com/questions/2803321/and-vs-as-operator

I understand that you would like to use `AND` in your code, and you are free to do so. But generally speaking, I still advocate avoiding it for the general public. However, as advised by @ea-inspections-team, you can disable this notice without being interfered with by the mechanics of this inspection.

![image](https://user-images.githubusercontent.com/421851/146049764-2aabbc2f-d091-41ac-95f3-00578f796c8f.png)

**Comment by jdreesen** [comment]
> but since you yourself wrote the same thing, apparently you also consider this a convenient approach
>
> I see a clear similarity)
>
> `if ($errors = $validator->validate($req) and $errors->count() > 0) {`

Sure, sometimes it is, I would just write it like this:

```php
if (($errors = $validator->validate($req)) && $errors->count() > 0) {
```

With the parenthesis, it's very clear to me what happens first, and I can read it from left to right.

And EA even has an inspection if you forget the parenthesis:
![image](https://user-images.githubusercontent.com/424602/146052280-88cb2cab-718d-4072-bc35-182380d3a4f9.png)

**Comment by bordunosp** [comment]
You are doing a very important job. The plugin is great overall. Thanks a lot
