### ISSUE TITLE
Typo trains -> traits

### ISSUE THREAD

**Issue by mambax7** [kalessil/phpinspectionsea#1793]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) or Php Inspections (EA Ultimate), which version |
| Language level | e.g. PHP 7.2 (check project settings or composer.json)                        |

Current behaviour
--

![image](https://user-images.githubusercontent.com/613686/146616879-942880ae-de1c-4bbf-836a-d57c99ea21f5.png)

Expected behaviour
--
traits

Environment details
---

Information from Help - About dialog

**Comment by ea-inspections-team** [comment]
Thank you for reporting @mambax7! Fixed!
