### ISSUE TITLE
Make in_array misusage inspection stricter

### ISSUE THREAD

**Issue by laacz** [kalessil/phpinspectionsea#1795]
Could it be wise to always suggest identical comparison (`===`) instead of equality (`==`)? Now it suggests identical comparison only when `in_array` has `strict` parameter set to true. However, after quick-fixing this, the next suggestion is to apply strict comparison.

Showing "'in_array(...)' is misused" inspection:

![image](https://user-images.githubusercontent.com/181486/147133696-ec904799-c513-4a70-a1e9-6f5b8e563315.png)

After the quick-fix it immediately shows "Type unsafe comparison" inspection:

![image](https://user-images.githubusercontent.com/181486/147133719-36874f03-501b-4cfe-b21a-c3c0d8e76b2c.png)

In following case, of course, we are doing the same:

![image](https://user-images.githubusercontent.com/181486/147133991-c48f46ef-2cbe-4261-bd39-a9a2559af9ef.png)

**Comment by ea-inspections-team** [comment]
Thanks for the proposal @laacz ! We evaluated several options and came up with adding a new setting: 'Force strict comparisons'. The setting is disabled by default, so you have to enable it. The next analyzer release is planned for the early January 2022.
