### ISSUE TITLE
[new, compatibility] binary-unsafe fopen usage

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#18]
Original link: https://bitbucket.org/kalessil/phpinspectionsea/issues/240/fr-validate-second-argument-in-fopen-and
Author @dryabov 

1. Check that second argument (mode) matches `/[rwaxc]b?\+?/` regex.
2. If mode string doesn't include `b` flag, suggest to use corresponding binary-safe mode (`'w+'` -> `'wb+'`, etc.) to make code to be cross-platform.

**Comment by ausi** [comment]
@kalessil I stumbled on this warning today and I’m not sure if the recommendation for using the `b` flag is (still) necessary.

The [documentation for `fopen()`](http://php.net/manual/en/function.fopen.php#refsect1-function.fopen-changelog) states that *“As of PHP 4.3.2, the default mode is set to binary for all platforms that distinguish between binary and text mode.”*

Looking at the source of PHP this seems to be correct, see [main/streams/plain_wrapper.c:110-114](https://github.com/php/php-src/blob/php-7.3.2/main/streams/plain_wrapper.c#L110-L114) and <https://github.com/php/php-src/commit/fa342d2404a9c809d0a182d80798da2abd3a98f7>.

**Comment by kalessil** [comment]
@ausi: might be a case, please create a new ticket, as we don't look much into closed once too often.

**Comment by ausi** [comment]
Done: #1214
