### ISSUE TITLE
License key

### ISSUE THREAD

**Issue by eNzyOfficial** [kalessil/phpinspectionsea#1829]
Emailed but no response.

Please can you check your email and allow me to use this plugin? I haven't changed my machine but reinstalled PHPStorm, now it won't let me use the key.

**Comment by laurinkeithdavis** [comment]
I had to contact the owner via Twitter (@kalessil).

**Comment by eNzyOfficial** [comment]
So I have to create a twitter account just to use a product I paid for? Kind of dumb ahaha

Thanks for the heads up, I guess I don't have much choice

**Comment by laurinkeithdavis** [comment]
I agree this situation has become problematic. We have a lot of time invested in using this product to improve our overall code quality and looks like it is no longer supported. I assume your license has not been transitioned to the JetBrains Marketplace? When did you purchase it?

**Comment by kalessil** [comment]
Sorry for this situation folks. I'm waiting this week to get access to all needed resources for getting things fixed and released.

**Comment by laurinkeithdavis** [comment]
Thanks for the reply, let me know if I can help in any way.

**Comment by eNzyOfficial** [comment]
Still having a hard time getting in contact, it's been months since I've been able to use this extension. @kalessil can you check your emails and reset my license so I can actually use it please?

Thanks

**Comment by ea-inspections-team** [comment]
Hi everyone, sorry for lack of responses here and emails.

We are so sorry for the frustration caused by lack of support back then. Please contact us on [ea.inspections.team@gmail.com](mailto:ea.inspections.team@gmail.com) (we will arrange one year free license for you).
