### ISSUE TITLE
::class can be used fix creates the use statement as a trait instead of an import if there's already a trait defined

### ISSUE THREAD

**Issue by Garethp** [kalessil/phpinspectionsea#183]
When trying to use the fix for `::class can be used` on a property, and the class already has `use` statements for traits, the class is imported as a trait instead of a class import.

Steps to reproduce:
Have the following files

```php
namespace NamespaceOne;

class A
{
}
```
```php
namespace NamespaceTwo;

class B
{
    use C;
    
    protected $property = 'NamespaceOne\A';
}
```
```php
namespace NamespaceTwo;

trait C
{
}
```

Try to run the fix on `NamespaceTwo\B::$property` and see that `NamespaceOne\A` gets imported as a trait

**Comment by kalessil** [comment]
Note for myself: check com.jetbrains.php.refactoring.PhpAliasImporter#insertUseStatement* methods

**Comment by kalessil** [comment]
@Garethp : the fix works, thanks! I extended tests with testing fixes: 2593558f65d2cbdade5e6c2b70099388cc0e2214

**Comment by Garethp** [comment]
Thanks. Are there any other quick fix bugs you'd like me to look at? Or test existing ones? I'd love to contribute, and those seem like good starting points for learning the plugin.

Also, are you able to explain the checkHighlighting function at all? I don't understand what the three booleans do, but any other values caused errors, and I wasn't able to get the available quick fixes without that function first.

**Comment by kalessil** [comment]
Perhaps increasing test coverage will be a good point: https://github.com/kalessil/phpinspectionsea/blob/master/RULES.md#inspections-lists-type-compatibility: IsEmptyFunctionUsageInspection doesn't have tests yet. Best will be to reference to last commits for adding tests.

I don't remember the meaning of the flag, but this combination will apply given inspector, ensure that all warnings (error, warning, weak_warning "tags" in fixtures) and will fail when results are not as expected.

If the idea with test works, I'll assign a ticket for you.
