### ISSUE TITLE
Reports the usage of 'at' operator

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#186]
It should be avoided as much as possible, because you can create some unfindable issues on your code. For instance: if used on a method that throws an exception, it will can't be treated.

```php
// Warning: avoid at operador.
@my_error();
```

But there are some fews exceptions to `at` operator, when it handles some race conditions like by using `unlink()`. Then in this case, it should be allowed (I guess that it can happen with all file operations functions).

**Comment by funivan** [comment]
I can try to implement this feature =)

**Comment by kalessil** [comment]
Go ahead @funivan =)

**Comment by funivan** [comment]
There is standard inspection "Usage of a silence operator" =) But this inspection does not have any options.
So there are 2 cases. 
1. Add configurable inspection to the plugin (allow to modify functions list, or hardcode functions that can be used with `@` operator)
2. Create issue https://youtrack.jetbrains.com/issues/WI

**Functions that can be used with `@` operator:**
```php
@mkdir()
@trigger_error()
@unlink()
```
**This one is from symfony**
```php

@ldap_add()
@ldap_bind()
@ldap_connect()
@ldap_delete()
@ldap_get_entries()
@ldap_get_option()

@posix_isatty
@posix_isatty()
@posix_kill()
// ... 
```

**Comment by kalessil** [comment]
Let's add our own inspection - less headache for everyone =)

**Comment by funivan** [comment]
Ok)

**Comment by kalessil** [comment]
@funivan : FYI, I added content-aware behaviour and corresponding [documentation](https://github.com/kalessil/phpinspectionsea/blob/master/docs/code-style.md#usage-of-the-silence-operator). 

If the content awareness settings switched off, the inspection gets behaves as in original version.

**Comment by funivan** [comment]
@kalessil nice documentation. Simple inspection become smarter. Nice job ;)

**Comment by kalessil** [comment]
Thank you @funivan, it was a good basis there ;)
