### ISSUE TITLE
realpath() works differently in a stream context

### ISSUE THREAD

**Issue by PatrickBauer** [kalessil/phpinspectionsea#189]
Hi, I have the following code print the error message above:

`$webroot = realpath(DRUPAL_ROOT . '/../epaper/' . end($sitePath));`

I see in [this](https://github.com/kalessil/phpinspectionsea/blob/master/src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/apiUsage/fileSystem/RealpathInSteamContextInspector.java) file that its triggered by having ".." inside the checked path: why is that?

**Comment by kalessil** [comment]
Real life example is an application packed into phar will break here, because of the way how realpath dealing with streams.

Perhaps [this](https://github.com/kalessil/phpinspectionsea/blob/master/docs/probable-bugs.md#phar-incompatible-realpath-usage) will help to understand the issue better?

**Comment by PatrickBauer** [comment]
I understand the problem but why triggers this outside of a steam context? Could't the inspection check if its using a steam instead of just checking for the ".."?

**Comment by kalessil** [comment]
Ah I see =)
How, can you elaborate a little bit more?

**Comment by PatrickBauer** [comment]
I see now too, I got it wrong due to the wording.
Maybe the wording should be changed a bit? 
The error message says this:

`'realpath()' works differently in a stream context (e.g. for phar://...). Consider using 'dirname()' instead.`

The way I understood this is, that its wrong to use '..' in realpath while the path I'm checking is using a stream (pretty normal for Drupal).

Meaning I shouldn't use something like `realpath('public://path/to/../file')`, while its actually meant differently.

**Comment by kalessil** [comment]
I could've tried reporting "'dirname(DRUPAL_ROOT) . '/epaper/' . end($sitePath)' should be used instead (due to how realpath handles streams)".

Will it be better?

**Comment by PatrickBauer** [comment]
Yes, I think that would be a good idea.

**Comment by kalessil** [comment]
I did enhance message generation for some cases + added QF for the cases when we are able to suggest the replacement. 

Note: only simple cases are hinted with suggestions, in general case we are falling back to the original message.
