### ISSUE TITLE
`ClassConstantCanBeUsedInspector` should not be triggered within `class_exists` call

### ISSUE THREAD

**Issue by Aberdeener** [kalessil/phpinspectionsea#1892]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | <img width="426" alt="image" src="https://github.com/kalessil/phpinspectionsea/assets/26070412/2c5836fe-f441-42b5-bdcd-11b7242ca578"> |
| Language level | <img width="243" alt="image" src="https://github.com/kalessil/phpinspectionsea/assets/26070412/2819c375-3277-41c2-9c3c-9d9792b08986">  |

**Current behaviour**
<img width="762" alt="image" src="https://github.com/kalessil/phpinspectionsea/assets/26070412/0cd10825-c108-463a-95ae-5cde1d83b9cb">

**Expected behaviour**
I believe that this should not happen because if we follow the suggestion and use the `::class` syntax and the class does not exist, PHP will throw an exception.

**Environment details**
<img width="483" alt="image" src="https://github.com/kalessil/phpinspectionsea/assets/26070412/9102a569-9864-4715-a43d-412ce35a3add">

**Comment by jdreesen** [comment]
No it won't? It's perfectly fine to use `::class` constants for non-existing classes: https://3v4l.org/HbUSS
