### ISSUE TITLE
Put the name of the inspection in the tooltip

### ISSUE THREAD

**Issue by pauljura** [kalessil/phpinspectionsea#1899]
Hi, I recently added this plugin and while I agree with most of the inspections, there are a couple that I wanted to disable due to personal preference. But I noticed it's not a trivial task to figure out which inspection is responsible for the warning.

For example, I found one that has the tooltip "[EA] Child instructions can be extracted here" and the action "[EA] Split the workflows" but searching for "child" or "instruction" or "split" or "workflow" doesn't reveal the inspection. Eventually I found it was "Redundant 'else' keyword". Admittedly it didn't take very long, but it could have been easier.

It would be nice if there was some common keyword we could search for, or a code, or a number, that would link the warning with the inspection to make it easier to find.

Thanks.

**Comment by jdreesen** [comment]
Just press `Alt + Enter`, expand the first line in the popup and select `Edit inspection profile setting` and you're there:

![grafik](https://github.com/kalessil/phpinspectionsea/assets/424602/3779c381-4852-49e3-8a48-f72e62497907)

**Comment by pauljura** [comment]
OMG 🤯

With my colour theme I never noticed that first line could be expanded! I can barely even see the 3 dots now, even when I know to look for it.

![image](https://github.com/kalessil/phpinspectionsea/assets/42629973/e0e555e2-fdc3-4eb4-bffd-accf1cbdaf3e)

Thank you!

**Comment by pauljura** [comment]
Closing.
