### ISSUE TITLE
Project maintenance (or lack thereof)

### ISSUE THREAD

**Issue by tlamy** [kalessil/phpinspectionsea#1909]
First of all: Sorry to bring this up again.

Is there a plan / roadmap for plugin maintenance?
As a paying customer I would at least expect work on the PHP 8 compatibility issues, now that even PHP 8.0's support sunset is in sight - but the only "real" change (imo) was merging a pull request from a 3rd party.

If things get done, this is invisible to your users. 
More so, my reception is things only happen if @kalessil exerts pressure on the (unnamed) development team.

The arguments are the same as in ending 2022/ beginning of 2023: There are paying customers, and they _deserve_ that issues are worked on, paid by their monthly/yearly fee. If you cannot provide a minimum of work, the plugin must be abandoned or completely transferred to a trustful maintainer.

**Comment by kalessil** [comment]
That's probably on me for not sharing updates, thanks @tlamy.

Short version: quarterly releases are the goal. The content of the releases and who'll triage the backlog should be finalized by November. 

PS: As I get new insights I'm allowed to share will post it here.

**Comment by kalessil** [comment]
Okay, I got an update: triaging is in progress, focusing on bugs and PHP version compatibility for the subsequent four releases.
