### ISSUE TITLE
Undefined function 'mime_content_type' 

### ISSUE THREAD

**Issue by uzdevid** [kalessil/phpinspectionsea#1919]
https://www.php.net/manual/en/function.mime-content-type.php

**Comment by COil** [comment]
Not reproduced. Do you have ```"ext-fileinfo": "*",``` in your composer file?

<img width="539" alt="Capture d’écran 2024-02-04 à 11 50 46" src="https://github.com/kalessil/phpinspectionsea/assets/177844/f399e12d-9fc6-403c-b77b-a6159b8e7a58">
