### ISSUE TITLE
Maintenance: final checking on bug-fixing and development constraints

### ISSUE THREAD

**Issue by ea-inspections-team** [kalessil/phpinspectionsea#1920]
@kalessil, we are working on fixes, and realistically next 4 releases will be focused on bug-fixes only. To be clear about big-fixes, is about addressing failing tests, catching up on new PHP features and addressing the most severe false-positives. 

But as you have the most context of this plugin, can you please share your guidance in following:
- any adjustments in priorities for the mentioned types of bug-fixes?
- the fixes we are working one using different development style, any thing to consider here?

**Comment by kalessil** [comment]
> any adjustments in priorities for the mentioned types of bug-fixes?

Yes, I can recommend using the following iterations over next 6 months
- two issues are declined or details requested
- one bug is closed
- one test is fixed

This way you'll get a better idea of what needs more attention.

> the fixes we are working one using a different development style, any anything to consider here?

Don't want to be a duck shooter, but you are forgetting that Ultimate is based on Extended and fixes will happen in both repositories. When you merge fixes from Extended into Ultimate, changing the coding style will lead to massive merge conflicts.

So, I cannot recommend it - implementation is average, but it's better to invest in fixing things.

**Comment by kalessil** [comment]
PS: I don't see any public activity from you folks in this repository, that's not good.

**Comment by kalessil** [comment]
@ea-inspections-team: I am closing the issue, but don't hesitate to continue the conversation, and please speedup.
