### ISSUE TITLE
Pattern seems to be not valid.

### ISSUE THREAD

**Issue by uzdevid** [kalessil/phpinspectionsea#1921]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) or Php Inspections (EA Ultimate), which version |
| Language level | e.g. PHP 7.2 (check project settings or composer.json)                        |

Question
--
Is this a bug or did I make a mistake somewhere?

![image](https://github.com/kalessil/phpinspectionsea/assets/104216283/12821286-2907-4b95-aab7-986afbc0a538)

**Comment by jdreesen** [comment]
Try `$path = "%s/%s.%s";`.

**Comment by uzdevid** [comment]
😑🤦‍♂️ Thanks.
