### ISSUE TITLE
False positive: This statement seems to be disconnected from its parent foreach.

### ISSUE THREAD

**Issue by inDeev** [kalessil/phpinspectionsea#1924]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 5.0.0.0 |
| Language level | PHP 8.2  |

Current behaviour
--
![Snímek obrazovky 2023-12-18 v 8 07 02](https://github.com/kalessil/phpinspectionsea/assets/33215381/7f83ba3e-b9e4-410a-8fb4-eea851852e71)

Expected behaviour
No alert shown

**Comment by martineiber** [comment]
I had the same Issue. Reported here: 
https://youtrack.jetbrains.com/issue/QD-7094/It-is-not-a-problem-EA-This-statement-seems-to-be-disconnected-from-its-parent-foreach.

**Comment by PetrKaterinak** [comment]
This EA looks too dificult for me. In my opinion it is almost not possible to know what exactly affects something out of foreach scope. This EA should be removed, I'm seeing it often and in some cases it helped to me, but in global perspective it has more false positives than true.

**Comment by kalessil** [comment]
@ea-inspections-team: this inspection is receiving a lot of complains. Can you disable it by default, please in the next release?

**Comment by ea-inspections-team** [comment]
@kalessil: yes, we'll disable it by default.

@inDeev: is `addRow` is part of any OSS package, or it is a proprietary code base? We would like to research a bit on false-positives vs pure/tinted methods and functions.

**Comment by inDeev** [comment]
Hi, it is part of PHPWord package https://github.com/DerekMarcinyshyn/phpword/blob/master/samples/Sample_09_Tables.php

**Comment by ea-inspections-team** [comment]
We are pushing a commit which disables the inspection by default and closing the issue.

We also analyzed the method and similar reports, and suggesting to not report method calls and re-enable the inspection by default. What is your opinion about this idea @kalessil @inDeev @andrew-demb @PetrKaterinak @COil?

**Comment by kalessil** [comment]
@ea-inspections-team: if reported issues consistently prompt methods calls, go for it.
