### ISSUE TITLE
AmbiguousMethodsCallsInArrayMappingInspection used in both Extended and Ultimate plugin

### ISSUE THREAD

**Issue by t0mm1e** [kalessil/phpinspectionsea#1929]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended)  5.0.0.0 and Php Inspections (EA Ultimate) 2024.1.1 |
| Language level | PHP 8.2                       |

I'm getting a `com.intellij.diagnostic.PluginException: Short name 'AmbiguousMethodsCallsInArrayMappingInspection is not unique` exception when I enable both Extended and Ultimate plugins.
I can see it referenced in Extended for the `Performance → Non-optimized arrays mapping` inspection, I cannot find  the Ultimate inspection which might clash with that.

Are more people getting this exception on startup? Have configured a funky setting triggering this?

**Comment by ea-inspections-team** [comment]
Thank you for reporting @t0mm1e!

It's a know limitation of running multiple Php Inspections (EA *) plugins, which we documented in description of Php Inspections (EA Ultimate) plugin: `IMPORTANT: please uninstall Php Inspections (EA *) plugins if installing this one.`.

Currently, IDE APIs not allowing to handle this case.
