### ISSUE TITLE
Inspections slow to refresh

### ISSUE THREAD

**Issue by bizley** [kalessil/phpinspectionsea#1931]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 2024.1.1 |
| Language level | most probably N/A, checked on PHP 7.4 - 8.2 |

Current behaviour
--

During coding quite often code is in invalid state (new variables, "unknown" variables, classes without import, etc.) which triggers inspections warnings, error highlighting and so on. Unfortunately after "fixing" the problem (like finishing typing the variable name, or its type) the highlighted text is not returning to normal (= not highlighted) and it takes some time for the code to return to "ok" state. If it would take only few seconds this would be irritating but acceptable, but sometimes it takes 20+ seconds or even stays like that until reopening the file. Usually cutting out the line and pasting it back again resolves the problem immediately.

I have seen some old reports on YouTrack with the same behavior described so I guess it might be because of some interaction this plugin does with PhpStorm. To be sure that it's not some other plugin causing it I disabled `Php Inspections`, did coding session (everything worked smoothly) and enabled it again (again problems with inspections "refreshing"). I have tried clearing the cache without success here.

Expected behaviour
--

Reported coding problems (highlighted) should be gone immediately after fixing the cause of highlighting.

Information from Help - About dialog

PhpStorm 2023.3.4
Build #PS-233.14475.35, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-94-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 6000M
Cores: 20

Registry:
  debugger.new.tool.window.layout=true
  run.processes.with.pty=TRUE
  ide.allow.merge.buttons=false
  ide.experimental.ui=true

Non-Bundled Plugins:
  com.github.leomillon.uuidgenerator (4.5.1)
  some.awesome (1.15)
  com.jetbrains.CyanTheme (1.3)
  org.intellij.plugins.hcl (233.13135.65)
  com.intellij.ideolog (222.3.1.0)
  com.godwin.json.parser (1.7.1)
  String Manipulation (9.12.0)
  org.sylfra.idea.plugins.linessorter (1.0.1)
  net.seesharpsoft.intellij.plugins.csv (3.2.3-233)
  ru.adelf.idea.dotenv (2024.1)
  de.espend.idea.php.toolbox (6.2.0)
  de.espend.idea.php.annotation (9.4.0)
  com.github.copilot (1.4.14.4554)
  izhangzhihao.rainbow.brackets (2024.2.1)
  fr.adrienbrault.idea.symfony2plugin (2022.1.263)
  zielu.gittoolbox (500.1.10+222)

Current Desktop: ubuntu:GNOME

**Comment by kalessil** [comment]
@ea-inspections-team: IIRC, you haven't investigated this type of issues so far. Leaving some hints: under IDE `Help -> Diagnostic Tools`, there are several profiling tools the community can run and share profiling results. Hope that helps!

**Comment by ea-inspections-team** [comment]
Thank you for reporting @bizley! Would it be possible to record a video capturing "refresh" and side-pannel with setting before we get into profiling?

**Comment by bizley** [comment]
If I could only fix all my issues just by waiting 7 months 🤣 
Anyway - I switched on the plugin again and so far it looks like everything is working. I'll let you know if anything new develops.

Just for reference, my setting now is:

PhpStorm 2024.2.1
Build #PS-242.21829.154, built on August 29, 2024
Runtime version: 21.0.3+13-b509.11 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.8.0-45-generic
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 6000M
Cores: 20
Registry:
  debugger.new.tool.window.layout=true
  run.processes.with.pty=TRUE
  ide.allow.merge.buttons=false
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.github.leomillon.uuidgenerator (4.5.1)
  some.awesome (1.15)
  org.intellij.plugins.hcl (242.21829.3)
  com.jetbrains.CyanTheme (1.3)
  com.jetbrains.space (242.21829.142)
  com.intellij.ideolog (242.21829.162)
  com.godwin.json.parser (1.7.1)
  String Manipulation (9.14.1)
  org.sylfra.idea.plugins.linessorter (1.0.1)
  com.intellij.ml.llm (242.21829.196)
  org.jetbrains.plugins.gitlab (242.21829.162)
  org.jetbrains.plugins.github (242.21829.162)
  net.seesharpsoft.intellij.plugins.csv (3.4.0-242)
  izhangzhihao.rainbow.brackets (2024.2.6-241)
  ru.adelf.idea.dotenv (2024.2.1)
  com.kalessil.phpStorm.phpInspectionsUltimate-mp (2024.1.1)
  de.espend.idea.php.toolbox (6.2.0)
  de.espend.idea.php.annotation (11.0.3)
  fr.adrienbrault.idea.symfony2plugin (2024.1.276)
  com.github.copilot (1.5.23.6819)
  zielu.gittoolbox (600.0.0+242)
Current Desktop: ubuntu:GNOME

**Comment by ea-inspections-team** [comment]
Thank you @bizley!

> If I could only fix all my issues just by waiting 7 months 🤣

To cover this seven months gap, we will be happy to provide a discount coupon for the next license renewal. If you are interested, you can reach us out at ea.inspections.team@gmail.com.

**Comment by bizley** [comment]
Nah, thanks, I'm good and happy to support you guys!
