### ISSUE TITLE
Inline Error Highlights Take an Hour to Disappear After Errors Are Resolved or Do Not Disappear At All

### ISSUE THREAD

**Issue by JSabelli-FDX** [kalessil/phpinspectionsea#1949]
| Subject (See Title) | Details (See Current behaviour) |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) or Php Inspections (EA Ultimate), which version |
| Language level | PHP 7.1.16 |

Current behaviour
--
I was inserting brackets for casting. When [EA] highlighted all the code-lines because it thought I had open brackets, the in-line error highlights wouldn't go away. They still haven't gone away. (Update: They disappeared after 1 hour and +/-30mins)
 To resolve this, I usually have to restart my IDE and they all disappear, but this has become a nuisance. 

It crashes with this issue log:  (File names and File paths modified for NDA privacy)

> java.lang.RuntimeException: View provider Multi root injected file [REDACTED FILE].blade.php'  refused to parse text with Language: HTML; languages: [Language: HTML, Language: PHP]; base: Language: PHP; copy: com.jetbrains.php.lang.PhpFileViewProvider{vFile=LightVirtualFile: \[REDACTED FILE].blade.php, content=VirtualFileContent{size=11470}, eventSystemEnabled=false}; copy.base: Language: PHP; vFile: VirtualFileWindow in [REDACTED PATH].blade.php; copy.vFile: LightVirtualFile: \[REDACTED FILE].blade.php; fileType: com.jetbrains.php.lang.PhpFileType@40e64ef; copy.original(): VirtualFileWindow in [REDACTED PATH].blade.php
> 	at com.intellij.psi.impl.BlockSupportImpl.getFileCopy(BlockSupportImpl.java:312)
> 	at com.intellij.psi.impl.BlockSupportImpl.makeFullParse(BlockSupportImpl.java:283)
> 	at com.intellij.psi.impl.BlockSupportImpl.reparse(BlockSupportImpl.java:90)
> 	at com.intellij.psi.impl.BlockSupportImpl.reparseRange(BlockSupportImpl.java:63)
> 	at com.intellij.pom.core.impl.PomModelImpl.reparseFile(PomModelImpl.java:238)
> 	at com.intellij.pom.core.impl.PomModelImpl.reparseParallelTrees(PomModelImpl.java:216)
> 	at com.intellij.pom.core.impl.PomModelImpl.commitTransaction(PomModelImpl.java:189)
> 	at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$1(PomModelImpl.java:151)
> 	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:535)
> 	at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$2(PomModelImpl.java:103)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:269)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:277)
> 	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:57)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:277)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:268)
> 	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:92)
> 	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:141)
> 	at com.intellij.psi.impl.source.tree.CompositeElement.replaceChild(CompositeElement.java:632)
> 	at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.replaceChild(CodeEditUtil.java:162)
> 	at com.intellij.extapi.psi.ASTDelegatePsiElement.replaceChildInternal(ASTDelegatePsiElement.java:365)
> 	at com.intellij.extapi.psi.ASTDelegatePsiElement.replace(ASTDelegatePsiElement.java:355)
> 	at com.kalessil.phpStorm.phpInspectionsEA.fixers.UseSuggestedReplacementFixer.applyFix(UseSuggestedReplacementFixer.java:51)
> 	at com.kalessil.phpStorm.phpInspectionsEA.fixers.UseSuggestedReplacementFixer.applyFix(UseSuggestedReplacementFixer.java:21)
> 	at com.intellij.codeInspection.ex.QuickFixWrapper.invoke(QuickFixWrapper.java:154)
> 	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$invokeIntention$14(ShowIntentionActionsHandler.java:395)
> 	at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:85)
> 	at com.intellij.openapi.application.impl.RwLockHolder.runWriteAction(RwLockHolder.kt:364)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:893)
> 	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:84)
> 	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invokeIntention(ShowIntentionActionsHandler.java:395)
> 	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$chooseActionAndInvoke$9(ShowIntentionActionsHandler.java:313)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:225)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:177)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:167)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:153)
> 	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:312)
> 	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:292)
> 	at com.intellij.codeInsight.daemon.impl.DaemonTooltipAction.execute(DaemonTooltipActionProvider.kt:57)
> 	at com.intellij.codeInsight.daemon.impl.DaemonTooltipWithActionRenderer$addActionsRow$runFixAction$1.invoke(DaemonTooltipWithActionRenderer.kt:146)
> 	at com.intellij.codeInsight.daemon.impl.DaemonTooltipWithActionRenderer$addActionsRow$runFixAction$1.invoke(DaemonTooltipWithActionRenderer.kt:144)
> 	at com.intellij.codeInsight.daemon.impl.DaemonTooltipWithActionRendererKt$createActionLabel$1.hyperlinkActivated(DaemonTooltipWithActionRenderer.kt:366)
> 	at com.intellij.ui.HyperlinkAdapter.hyperlinkUpdate(HyperlinkAdapter.java:14)
> 	at com.intellij.ui.HyperlinkLabel.fireHyperlinkEvent(HyperlinkLabel.java:241)
> 	at com.intellij.ui.HyperlinkLabel.processMouseEvent(HyperlinkLabel.java:164)
> 	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
> 	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
> 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
> 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4969)
> 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4583)
> 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4524)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
> 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2809)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
> 	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
> 	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:699)
> 	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:638)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:584)
> 	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:138)
> 	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:129)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:584)
> 	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:77)
> 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:362)
> 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:361)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
> 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:361)
> 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:356)
> 	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1022)
> 	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
> 	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1022)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:356)
> 	at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:209)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:398)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

Expected behaviour
-- 
- No lingering inline messages when errors/warnings have been resolved.
- No crashes.

Environment details
---
IDE: PHPStorm
Languages/Frameworks: PHP, HTML, CSS, Laravel, Symfony, Blade
Allocated RAM to IDE: 8GB or 8192MB

Information from Help - About dialog

**Comment by ea-inspections-team** [comment]
Thank you for reporting @JSabelli-FDX!

It is not clear from the stack trace which quick-fix action caused this, but our guess is that the problem could be in blade support implementation on IDE side. Could be still issue with our plugin, but we don't have enough information for analysis.

We are pushing a commit which targeting blade-files and not surfacing exceptions if quick-fix failing.
With more information about inspection causing this and what quick-fix was trying to apply we can do a better try.
