### ISSUE TITLE
Prefix functions and constants from global scope in namespace

### ISSUE THREAD

**Issue by Denitz** [kalessil/phpinspectionsea#195]
Is it possible to add an inspection which will suggest to prefix global scope functions and constants with backslash if they are used any namespace? It helps to minimize namespaces lookup, e.g.:

strtolower() is changed to \strtolower()
__DIR__ is changed to \__DIR__ 

Auto-correction is a dream :)

**Comment by kalessil** [comment]
Do you mean this one (selected)?

![image](https://cloud.githubusercontent.com/assets/1577185/24236660/1b4e7544-0fa3-11e7-97ab-f32875c7ccc5.png)

**Comment by kalessil** [comment]
It disabled by default but does what probably you mean. QF is already there.

PS: I guess I did announce it loudly in Twitter, perhaps it worth following there each other.

**Comment by Denitz** [comment]
Yes, that's it, super!

**Comment by kalessil** [comment]
Great =) Closing the issue.
