### ISSUE TITLE
[ideas] not optimal if conditions

### ISSUE THREAD

**Issue by dryabov** [kalessil/phpinspectionsea#20]
There were many issues related to dependencies of conditions in "not optimal if conditions" inspections. Actually, this task is similar to topological sorting (https://en.wikipedia.org/wiki/Topological_sorting) and may be solved using existing algorithms. And advantage of topological sorting approach is possibility to implement "Quick Fix" solution to reorder conditions correctly.

Currently I see following possible dependencies:
1) `isset($var)`, `!is_null($var)`, `!empty($var)` before usage of `$var`.
2) `isset($var[$key])`, `array_key_exists($key, $var)` before usage of `$var[$key]`.
3) Type check (`is_array`, `is_object`, `is_bool`, `is_int`/`is_integer`/`is_long`, `is_float`/`is_double`/`is_real`, `is_numeric`, `is_string`, `is_scalar`, `is_callable`, `instanceof`, `is_a`, `is_subclass_of`) before usage.
4) `function_exists`, `method_exists`, `property_exists`, `class_exists`, `interface_exists`, `trait_exists` before corresponding usage.
5) Pass a `$var` by reference to a function, then usage of `$var` on the left and right of this condition shouldn't be mixed.
6) Order of functions calls shouldn't be changed (as they may have side effects).

PS. Not so easy to implement, but maybe someone will have free time to do it.

**Comment by funivan** [comment]
> `isset($var), !is_null($var), !empty($var) before usage of $var.`
Following code:
```
$log = $this->getLogger();
if($log->isVerbose() ){ // If we are using nullable pattern than we know that $log is not null =) 
}
``
2. In most cases agree=)
3,4. Same as 1.

**Comment by rentalhost** [comment]
Just to I understand, you mean:

1. Suggests to not use `isset($var)` before `$var` declaration; or,
2. Suggests implements a _conditional_ to `$var` then it can generate the `isset($var)`?

If the answer is "two", you are describing an _intention_ (not an _inspection_), and it is out scope of project. But, maybe we can start working over a `phpintentionsea`, who knows?

**Comment by kalessil** [comment]
Commenting to keep stalebot away.

**Comment by ea-inspections-team** [comment]
Thanks for reporting @dryabov !  Added test cases for items from entries 1, 2, 3, and 4 (fixed several false positives on the way). We'll leave 5 (Pass a $var by reference to a function, the usage of $var on the left and right of this condition shouldn't be mixed.) out of scope and if you run into 6 (Order of functions calls shouldn't be changed (as they may have side effects).) breaking something, please get back to us and we'll revisit it.
