### ISSUE TITLE
[optional, opinionated] Report multiple returns in class methods (ignore traits)

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#203]
? static methods ?

**Comment by kalessil** [comment]
@funivan : thanks for a link ;)

**Comment by funivan** [comment]
Emmm.. what link? ))

**Comment by rentalhost** [comment]
And I'm curious if you are talking about methods like [this](https://github.com/laravel/framework/blob/fda32246e66decb0e83813daf5ff4c79356e1a90/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L456):

```php
    /**
     * Cast an attribute to a native PHP type.
     *
     * @param  string  $key
     * @param  mixed  $value
     * @return mixed
     */
    protected function castAttribute($key, $value)
    {
        if (is_null($value)) {
            return $value;
        }
        switch ($this->getCastType($key)) {
            case 'int':
            case 'integer':
                return (int) $value;
            case 'real':
            case 'float':
            case 'double':
                return (float) $value;
            case 'string':
                return (string) $value;
            case 'bool':
            case 'boolean':
                return (bool) $value;
            case 'object':
                return $this->fromJson($value, true);
            case 'array':
            case 'json':
                return $this->fromJson($value);
            case 'collection':
                return new BaseCollection($this->fromJson($value));
            case 'date':
                return $this->asDate($value);
            case 'datetime':
                return $this->asDateTime($value);
            case 'timestamp':
                return $this->asTimestamp($value);
            default:
                return $value;
        }
    }
```

If yes, which should be the solution?

**Comment by Fleshgrinder** [comment]
There is absolutely nothing wrong with multiple `return` statements!?!

**Comment by kalessil** [comment]
@funivan : https://www.youtube.com/watch?v=qAxLtSYN0nw

**Comment by kalessil** [comment]
@Fleshgrinder : no worries, it's optional tool for myself.

The rule indicates methods written in a procedural style, but can be simplified. 
Such methods harder to test and might be a good candidate for more precise review.

**Comment by kalessil** [comment]
@rentalhost : same answer as above =)

**Comment by Fleshgrinder** [comment]
All fine if it is disabled by default, and available for those who really need it.

For any user arriving here in search of more info on this, please go through [this Stackoverflow thread](https://stackoverflow.com/questions/36707) where people discuss this topic in extreme length. There is lots of great literature being quoted from Steve McConnell, Martin Fowler, Kent Beck, … of which I recommend every single one to buy and read. 🐱

**Comment by funivan** [comment]
@kalessil yep. After this video I started to look at my code from another side. Single return has pros and cons, but having such inspection would be great. 
I see this inspection simple, if you would like I can implement it =) What do you think?

**Comment by kalessil** [comment]
@funivan, go ahead =)
