### ISSUE TITLE
Improve dev docs

### ISSUE THREAD

**Issue by davidmpaz** [kalessil/phpinspectionsea#207]
Hi there,

can somebody help with images from docs/DEVELOPERS.md file? I am trying to set up the project but links are broken.

also just noticed that .idea/ dir is not ignored completely. Is this on purpose to get some defaults settings? 

Could we consider ignoring .idea/ dir completely and describe in more details what is needed to be done for the full setup without using the settings committed. 

For me there are several changes/new files in .idea files. I would gladly write all what is need after setting up everything. It is a bit confusing for someone coming new like me :)

This issue relates also to #206 

Cheers,
David

**Comment by kalessil** [comment]
Since it's n time escalated, will add missing images next days...

**Comment by funivan** [comment]
@kalessil developers can install php plugin to the intellij, then you can change openapi path (like CSS lib)
So all developers just need to install php plugin without any path change. What do you think?

**Comment by kalessil** [comment]
I recommend to keep IDEA fresh and build against older PS version - because of enterprise users.
But of course I'll add a note to your proposal, it makes sense and balance out my approach perfectly.

**Comment by kalessil** [comment]
[Dev-docs](https://github.com/kalessil/phpinspectionsea/blob/master/docs/DEVELOPERS.md) as been reworked, images there + cleanup done.

//cc @tomzx @funivan @veewee
