### ISSUE TITLE
Overrided property by constructor

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#219]
Consider the next code:

```php
class MyClass
{
    private $property = 1000;

    public function __construct($initial = null)
    {
        $this->property = $initial;
    }
}
```

You will note that the `$property` is initially `1000`, but is overrided immediately by constructor, by considering the `$initial` argument. 

In this case, it should display a warning on `$property`: this value is immediately overrided by constructor (autofix: unset an initial value on property).

It should only consider when the property is affected on root of constructor, then if you have conditionals (if) or complex structures (calls to another method), for instance, you can ignore that inspection.

```php
$this->property = 'new value'; // Warning.
$this->property = expr() ? 1 : 2; // Warning.

if (expr()) {
    $this->property = 'new value'; // Not warning.
}

$this->anotherMethod() => {
   $this->property = 'new value'; // Not warning. (because is hard to implements, except if you follow up all calls in constructor)
}
```

**Comment by kalessil** [comment]
@rentalhost : sounds like extension of [this](https://github.com/kalessil/phpinspectionsea/blob/master/src/test/resources/fixtures/codeStyle/property-initialization-override.php#L26)

**Comment by funivan** [comment]
This feature is already implemented
![07 35 33](https://cloud.githubusercontent.com/assets/425208/24536691/bbfe19a8-15e4-11e7-988e-cfaf2c6008c9.png)

**Comment by kalessil** [comment]
@rentalhost : would you please check the inspection and close the issue if we are talking about the same thing?

**Comment by rentalhost** [comment]
@funivan (cc @kalessil) yep, for some reason, I have disabled that inspection on past. My fault! 😄
