### ISSUE TITLE
[proposal] Naming convention inspection

### ISSUE THREAD

**Issue by funivan** [kalessil/phpinspectionsea#222]
All php developers follow naming conventions. One of the best example is symfony framework:
http://symfony.com/doc/current/contributing/code/standards.html#naming-conventions
```
Prefix abstract classes with Abstract. 
Suffix interfaces with Interface;
Suffix traits with Trait;
Suffix exceptions with Exception;
```

I thing this inspection should be disabled by default and have some configuration options.

Here is how we can configure naming convention:

| Type          | Regex                          | Base class FQN          |
| ------------- |:-----------------------------:| ---------------------------:|
| trait           | .+Trait$                         |                                    | 
| class         | .+ConsoleCommand$   | \My\BaseCommand   |

Rules that will be applied to the code:
1. All traits should end with `Trait`
2. All classes that extends `\My\BaseCommand` should end with `ConsoleCommand` 

Possible types:
 - trait
 - class
 - abstract class
 - interface

P.S. @kalessil I want to implement this inspection, but I need some advices how to make this inspection simple for the developers (Configuration part)

**Comment by kalessil** [comment]
@funivan : that's would be a big piece of work, I'd rather think of introducing a new plugin instead.

To give advice I need understand your intention better at first place:
- does it only to support symfony naming standards?
- will it be beneficial to Zend/Shopware/Magento/Laravel communities?
- can it be done with already existing naming convention inspections by JB?

**Comment by funivan** [comment]
> does it only to support symfony naming standards?

No. This inspection should support user naming convention. Before using this inspection developers should configure it.

> will it be beneficial to Zend/Shopware/Magento/Laravel communities?

If developers of this frameworks use phpstorm and share inspections than YES.

> can it be done with already existing naming convention inspections by JB?

Existing naming convention does not cover this cases (for example: Controller classes should end with Controller)

The most hard part for me is configuration. I should create form with 3 elements and store results in the inspection configuration.  I already investigate `PrettyListControl` and this inspection configuration would be  something similar to `ForgottenDebugOutputInspector`

**Comment by kalessil** [comment]
Then:
- Will work as inspection in the EA plugin;
- Ensure that symfony-alike config available by default;
- You need to provide basic strategies (isAbstract, isInterface, isTrait, isFinal, isExtending) which invoked with the corresponding regex;
- Take care about older classloading: e.g. Zend_Date_<analyze only this part>DateObject</analyze only this part>;
- For configuration: pretty list with expression language entries like:
  - when (<abstract|trait|interface|final>) match <regex here>;
  - when (extends <FQN>) match <regex here>;
  - the configuration should contain those expressions, which then translated on change and on load into a collection of strategy objects applied by the inspection.

**Comment by kalessil** [comment]
@funivan : I want to put some labels on the ticket and wondering if this is it WIP?

**Comment by funivan** [comment]
Yes. You can put `WIP`. I work on it (current stage is prototyping)
But do not set milestone. I do not know how much time i will spent on this inspection ;)

**Comment by funivan** [comment]
Close due to nonactivity. 
Found a big nice idea: create an external plugin (NamingConvention) and include some framework rules there.

**Comment by kalessil** [comment]
Framework-specific presets would be awesome, worth also checking with communities you are in touch with!
