### ISSUE TITLE
Change echo to short code

### ISSUE THREAD

**Issue by Denitz** [kalessil/phpinspectionsea#224]
Is it possible to add inspection which highlights `<?php echo ` and allows to change it into `<?= `

**Comment by kalessil** [comment]
Yes, should be easy to do.

**Comment by funivan** [comment]
@kalessil I suggest you to create new label `easy-pick` This label can indicate that any contributor can work on it =) In some repositories I saw this label and for me it very useful.

**Comment by kalessil** [comment]
@funivan : added the new label

**Comment by rentalhost** [comment]
I guess that we should think about a reversed-way too as option. I personally prefer to use the long term (`<?php echo`) instead of short term (`<?=`).

**Comment by Denitz** [comment]
@kalessil  Why closed?

**Comment by kalessil** [comment]
We added a bot which closes tickets without activity for ~1 year, reopening.

**Comment by kalessil** [comment]
@dccampbell : makes sense to include in this one as well. Thank you for the proposal.

**Comment by kalessil** [comment]
Implemented (+same patter with print-construct)!

@rentalhost: as per your input I disabling the inspection by default
@dccampbell: your proposal implemented as well
