### ISSUE TITLE
Strictness and coalesce operators

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#227]
In case where we have a strict type, coalesce operators should be avoided. Both case above should be avoided.

```php
/** @var stdClass $class */
echo $class ?? true;
echo $class ?: true;
```

But could be allowed for:

```php
/** @var stdClass|null $class */
```

**Comment by kalessil** [comment]
Reopening

**Comment by kalessil** [comment]
For myself: alternative type should be sub-set of subject types.

**Comment by kalessil** [comment]
Implemented!
