### ISSUE TITLE
[suspicious BOs] ! $nullable <|<= 5

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#235]
In some cases, it should create more confusion than solve anything. For instance, when you read `!$number < 5`, probably you mean `$number >= 5` (_considering that this variable is really an integer, [because on PHP, null is lower than 5](https://3v4l.org/YuAKa)_).

**Then my suggestion is:** if I am not treating a strict boolean, the not-operator should be avoided, by defining exactly what you really expects on your expression.

**Comment by rentalhost** [comment]
Notes:
* `BinaryExpression` with left operand as unary expression negative not enclosed by parentheses;
* Double check for instanceof operator (eg. `!$number instanceof X`).

**Comment by kalessil** [comment]
What about making this a new pattern for suspicious binary operations @rentalhost ?

**Comment by rentalhost** [comment]
It is okay for me.

**Comment by kalessil** [comment]
Super, thanks for share awesome finding !!!

**Comment by kalessil** [comment]
Implemented
