### ISSUE TITLE
Discourage non-booleans in expressions

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#236]
While I write up the #235 I thought that it can do more, by discourage non-boolean in expressions. For instance, is very common things like `if(count($arr))`, and it is very clear because we know what `count()` does, but it can be a problem if we don't know too much about a method (_from vendor code, for instance_).

Then, like strong typed languages does, maybe is interesting if EA checks if the return is a boolean, else it should turn into by specificy exactly what do you mean with your expression. For instance:

```php
count($arr) => count($arr) > 0
!count($arr) => count($arr) === 0
```

It's more code, but specific well what do you want to do, Another advantage is that it'll avoid methods with two differents falsy returns. For instance: if method returns `null` or `false` maybe is the case where you should check if your method is a good one.

**Comment by kalessil** [comment]
So, I put some efforts into research of this case - it's pretty noisy, so I don;t think we can make use of.
