### ISSUE TITLE
Where I can get info about using "&&" instead "and"?

### ISSUE THREAD

**Issue by andreyshade** [kalessil/phpinspectionsea#238]
In code when I use the operator 'and'  inspection receives message: '&&' should be used instead (best practices)". Where I can get info about using "&&" instead "and"?

**Comment by rentalhost** [comment]
What do you mean? You wants to disable this inspection? If is the case, you could go to `Settings: Editor / Inpections / PHP / Php Inspections (EA Extended) / Control Flow / Non-optimal if conditions / (Uncheck) Report literal and-or operators`,

**Comment by andreyshade** [comment]
I want to read articles or another info about this best practice.

**Comment by kalessil** [comment]
The official docs are pretty good: http://php.net/manual/en/language.operators.logical.php

Short answer:
`The reason for the two different variations of "and" and "or" operators is that they operate at different precedences. (See Operator Precedence.)`

`Example #1 Logical operators illustrated` also helps to get an idea why the plugin encourages to use &&, ||.

**Comment by kalessil** [comment]
I'll update our docs accordingly.

**Comment by rentalhost** [comment]
It's not like "the best pratice" but "the most common pratice". Then this inspection suggests that for you. I guess that PSR, for instance, don't suggests a best use for that, for instance. 

Is the same case for the "for: endfor;", the common pratice on PHP is "for {}". But PHP allows both.

**Comment by funivan** [comment]
see this http://stackoverflow.com/a/2803576/4053996

**Comment by kalessil** [comment]
I extended our documentation, brief explanation is [here](https://github.com/kalessil/phpinspectionsea/blob/master/docs/control-flow.md#literal-and-or-operators-usage)
