### ISSUE TITLE
Suggests reverts simple conditions with else-only

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#239]
Hard to explain, but consider the next code:

```php
if (!expr()) {
    doA();
}
else {
    doB();
}
```

It could be writed as:

```php
if (expr()) {   // Removed the not-operator
    doB();      // The previous "else" statements
}
else {
    doA();      // The previous "if" statements
}
```

It is... keeps the `if()` always positive. It'll help a lot with simple ifs conditionals. I guess that I see that in some IDE (maybe for C#).

**Edit:** ah, yeah. The own PS allows you flip if-else statements. Then I guess that need justs an inspection. If possible, uses the own QF from PS.

**Comment by funivan** [comment]
1. Flip if else is standard phpstorm intention
2. For me it would be interesting to find ` NOT NOT ` conditions. 
for example:
```php
!$dealer->isInactive();
!$dealer->withoutEmail();
!isInvalid();
```
And suggest user to rewrite this conditions, because is is really hard to understand them.

**Comment by rentalhost** [comment]
I guess that your examples will works fine if applied in a general way too. Suggests flip for both cases will make easier to understand, `!$dealer->isActive()` or `!$dealer->isInactive()`. It will avoid a mapping for negative words.

**Comment by rentalhost** [comment]
Closing: PR #249
