### ISSUE TITLE
ReturnTypeCanBeDeclaredInspector: enhance QF - auto-import would be nice to have

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#243]

**Comment by rentalhost** [comment]
It's related to FR #255 and PR #320?

**Comment by kalessil** [comment]
Can not say right now, this most probably will be shifted to next release - we have a just week.
I'll clean up the milestone today to prevent further confusion.

**Comment by kalessil** [comment]
Re-opening
