### ISSUE TITLE
iterable is valid in foreach

### ISSUE THREAD

**Issue by royallthefourth** [kalessil/phpinspectionsea#244]
Putting an `iterable` typehinted item into a `foreach` (in my code these are `\Generator` and `array`) shows a problem where the code works perfectly fine. [This inspection](https://github.com/kalessil/phpinspectionsea/blob/master/docs/types-compatibility.md#foreach-source-to-iterate-over) doesn't seem quite right in that regard.

Here's an example:
```php
function generate(): \Generator
{
    yield 'this is ';
    yield 'an example';
}

function iterate(iterable $iter)
{
    foreach ($iter as $i) {
        echo $i;
    }
}

iterate(generate());
```

This executes fine, but the inspection highlights a problem area at `$iter`.

**Comment by rentalhost** [comment]
Can you please post a code that shows that issue?

**Comment by kalessil** [comment]
@royallthefourth : let me check if I can reproduce this (we re-worked the inspection in an upcoming release). Or perhaps code fragment would speed up investigation a lot =)

**Comment by kalessil** [comment]
Thank you @royallthefourth, checking this.

**Comment by kalessil** [comment]
Seems to be resolved: 

![image](https://cloud.githubusercontent.com/assets/1577185/24992527/260457d0-2022-11e7-93a7-e07a674075d7.png)

**Comment by kalessil** [comment]
To not wait for the release you can download PhpInspectionsEA.jar from master branch and install it manually: File -> Setting -> Plugins, under the plugin list click "Install from disk" and select the downloaded file.

The dev-build is stable: @funivan and me running dev builds.

**Comment by whale001** [comment]
Can not iterate '\iterable' (must implement one of iterator interfaces)

I get this message over variable which is returned from function with return type iterable 
function() : iterable
installed version 2.3.6

@kalessil will it help in this particular case?

Thank you in advance
![iterable](https://cloud.githubusercontent.com/assets/5070812/25189657/1907fe30-252a-11e7-9cd0-980a154c0c05.png)

**Comment by kalessil** [comment]
@whale001 : thanks for reporting, yes all needed information is here.

**Comment by whale001** [comment]
@kalessil Thank you for awesome plugin

**Comment by kalessil** [comment]
You are welcome @whale001 =)

I added support for the `iterable` type.
