### ISSUE TITLE
"Variable is redundant" refactoring is wrong

### ISSUE THREAD

**Issue by vladyslavstartsev** [kalessil/phpinspectionsea#245]
The refactoring works wrong because it will fail because of `Parse error`

Before refactoring
![](http://dl3.joxi.net/drive/2017/04/13/0015/2269/1046749/49/f96a0ff385.png)

After refactoring
![image](https://cloud.githubusercontent.com/assets/17382248/24997063/e786726a-203d-11e7-86be-3618578d1b6f.png)

The right way to refator
![image](https://cloud.githubusercontent.com/assets/17382248/24997101/0fabad46-203e-11e7-9c09-5eb3fd88f63e.png)

http://sandbox.onlinephpfunctions.com/code/ab96f13ac1676851a0d88615dc54fabcea1a8006 how it works before refactoring
http://sandbox.onlinephpfunctions.com/code/6586bfbb31c134adb6a38f4803a97da2f5e55636 how it doesn't work after refactoring
http://sandbox.onlinephpfunctions.com/code/4f2afbd98798b8867f0950c329e2e736769f8bda how it does work after refactoring

It's easy to understand. I don't know what other info I should put here

**Comment by kalessil** [comment]
That enough info here, thank you @vladyslavstartsev.

For myself: the same applies to the clone operations.

**Comment by kalessil** [comment]
Fixed =)
