### ISSUE TITLE
[bug] Tests are bundled inside the plugin

### ISSUE THREAD

**Issue by MaXal** [kalessil/phpinspectionsea#25]
Inside a jar file there is a folder: PhpInspectionsEA.jar!/com/kalessil/phpStorm/phpInspectionsEA/tests

It's not required and cause PhpStorm compatibility tool to issue warning:
com.kalessil.phpStorm.phpInspectionsEA:2.0.1 has 1 problem

------- Stderr: -------
#accessing to unknown class junit.framework.TestCase
    at com.intellij.testFramework.UsefulTestCase

I would like to help to fix the issue but unfortunately I couldn't find any script or configuration that actually build jar.

**Comment by kalessil** [comment]
Thank you for reporting @MaXal. We have #8 for this, it's still WIP.

Meanwhile, the case is fixed now - I'll perform release until the end of the next week.

**Comment by kalessil** [comment]
@MaXal : a new release is out, let me know please if the issue resolved

**Comment by MaXal** [comment]
The issue is solved! Thank you!

**Comment by kalessil** [comment]
You are welcome. Thank you for reporting!
