### ISSUE TITLE
Warning if property / field type is not consistent with the one specified on the interface

### ISSUE THREAD

**Issue by fabioi** [kalessil/phpinspectionsea#251]
Warning if property / field type is not consistent with the one specified on the interface

**Comment by kalessil** [comment]
@fabioi : can you provide an example, please - I guess it was a real-life issue, which I would like to understand in first place.

**Comment by fabioi** [comment]
eg: on a repository:

User repository
`/**
     * @param int|array $id
     *
     * @throws ModelNotFoundException
     *
     * @return User|User[]|Collection
     */
    public function findOrFail($id);`

its interface 

`/**
     * @param string $id
     *
     * @throws ModelNotFoundException
     *
     * @return void
     */
    public function findOrFail($id);`

**Comment by kalessil** [comment]
Means DocBlocks are inconsistent, I see now. But DocBlocks are meta-information - we in fact not relying on them for this specific reason, only implicit types hints matters (and supported when we are talking about parameters, PHP is pretty good here).

I want to reject this feature request, but with some hints:
- implicit type hints declaration in the interface is the right way to go;
- in case if the interface provided by the third party, introduce a new one with type hinting done right;
- profit.

**Comment by kalessil** [comment]
But still, we'll consider topics with class properties doc-blocks - because PHP doesn't support type hints there.
