### ISSUE TITLE
@type -> @var: contribute to Php CS Fixer

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#258]
Following https://github.com/kalessil/phpinspectionsea/issues/250#issuecomment-294795977 we could think about suggests some normalizations. As from this comment, for instance, we could think about normalize `@var` over `@type` (to be discussed).

For instance:

```php
// Weak: @var is more widespread than @type.
/** @type mixed */
```

This is a topic for discussion, then you could suggests another normalizations (if there are), and too if you think better uses `@type` or `@var`.

**Comment by funivan** [comment]
Easy to pick: +1 for `@var` 
I think this inspection should be placed in `code style`

**Comment by davidmpaz** [comment]
I can say also that what I have seen more is the `@var` usage.

**Comment by Fleshgrinder** [comment]
There was once a setting for this in PhpStorm where one could choose between `@var` and `@type`, but it seems as if it was removed in the latest version. I liked the `@type` much more because it is more descriptive, but the bad tool support and fact that the community settled with `@var` convinced me to stick to `@var` everywhere.

**Comment by Garethp** [comment]
I may be a bit unclear on the scope of PhpInspectionsEA, but isn't this out of that scope? It feels like the responsibility of a different plugin, maybe a PHPDocs plugin

**Comment by Fleshgrinder** [comment]
We need to be careful to avoid feature creep, but this is definitely within the scope. The extension is about PHP best practices, and phpDoc is an integral part of PHP; even if it is not an official part of the language.

**Comment by kalessil** [comment]
Apparently, finding time for CS Fixer contribution is a problem...
