### ISSUE TITLE
Activities coordination

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#260]
Here I want to structure my vision of activities around the plugin:

- Q2 2017: stabilization, crowdfunding obligations
  - bug-fixes
  - QFes
  - dev-stuff (graddle, Jenkins)
- Q3 2017: further stabilization
  - key features hardening (probable bugs, NPEs, not optimal if conditions)
  - next battle for reasonable performance
  - backlog big cleanup
- Q4 2017: to be planned

Small features will be picked up, but nothing fundamental - I expect a reduction of OSS availability starting Q2.

**Comment by kalessil** [comment]
@rentalhost @funivan @davidmpaz @Garethp  : I want to define some focus in my activities and understand how to align our activities.

Would you please share your thoughts - are there any ways for you to work on some topics together or perhaps I have to dedicate fixed time for some activities?

**Comment by rentalhost** [comment]
If you mean about issues, I like to work on issues that I have reported and QFs/UQFs for current features (based on RULES.md). Maybe first QFs to respect Q2. And I suggest that, if possible, each one could do the same, then we can reduce the issues list a lot (current 61 items) and create a lot of QFs.

**Comment by funivan** [comment]
@kalessil totally agree. I think we should reduce number of new inspections and try to close all `false-positive`

What i`m planing to do. I have a lot of interesting ideas for new inspections. But i will try to implement them in the separate plugin and test it in my project. Q3 or Q4 can be a good period to push some inspections to this plugin (step by step)
In this repository I will try to fix some bugs and write some  QF  (I love them))

**Comment by rentalhost** [comment]
Ah, a good idea that I see in some projects, like Laravel, is separates the issue to a `internals` project (something like _kalessil/internals_ or _kalessil/phpinspectionsea-internals_). Then we could discuss what we could do in each case before create an issue on this project. On this project, only issues "closest to WIP" will remain. For instance, in last day I sent about 5 issues, but I guess that we could discuss before turn it a "priority", but currently we have no "space" for that. It'll reduce a lot the issues and keep only "currently important issues". The major problem is that the people that don't know how it works probability will create an issue directly on this project, and I don't know if we can move to internals on github.

**Comment by kalessil** [comment]
It was lying on the surface, how I could miss that idea ). 
Community edition (CE) version of the plugin should resolve current bottleneck issues (back-merge is another topic, but if each of new inspections is self-contained we are on the safe side).

Should I fork a new project (propose name please) and create a new plugin for it?

**Comment by rentalhost** [comment]
I prefer just a new empty project, just tô handle discussions and future features. I don't know if you mean that. Two plugins code is too much.

**Comment by kalessil** [comment]
And how to be with what @funivan experimenting with?

**Comment by Garethp** [comment]
I don't mind an internals repository or going this way. I'm also happy just to grab an issue and run with it, and if someone else is also going to be working on that issue, then communicating over the issue. Either way works for me. I'd probably be most useful bug-fixing, but I'd like to tackle some new QF's. Can't say how efficient I'll be at it, but I'd like to give it a shot.

**Comment by davidmpaz** [comment]
I would like stick to Docs and review Code, not having so much time now and I feel currently that starting with Inspections and QFes implementation, then I would need support from one of you and dont want to take time from you for that.

Ofcourse if at some point you found something that could be easily done or even boring to do (the coding i mean), I could take it and that would serve as an entry point for me to the current API.

Regarding splitting the project, I have concern about increasing the amount of organizational works that such split would require. If there is the case that you need a "dummy someone" to take care of organizing issues or at least categorizing them or streamlining the job, I could take care of that. I hope to help in that point instead creating more troubles :)

But all in all I am fine with what ever you guys decide.

**Comment by funivan** [comment]
I think that Community Edition is not the best choice. All inspections in this plugin (CE) will be unstable. And I can not use inspection from @rentalhost and he can not use mine. 
Why I will create inspection in closed source plugin: 
- check if i can implement it
- check if it is useful
- test how it works.

Only after this steps I can create issue and then polish this inspection if needed. 
If I can not write inspection, and it seems to be very useful - then I will just create issue in this repository.

**Comment by kalessil** [comment]
@funivan @rentalhost 

Ok, then we don't need to add new repositories - I get used to using milestones for picking up stories in 1-2 next releases. Other requests/discussions are not harming at all, or we can just label them properly.

**Comment by kalessil** [comment]
@Garethp @rentalhost : I'll check which tickets you can pick up - to start gaining experience, will assign to you directly.

PS: there is no boring work in this project, just matter of priorities =)
