### ISSUE TITLE
assertStringEqualsFile: re-check correctness, use variant lookup

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#263]

**Comment by kalessil** [comment]
@keradus: can you recall what was a problem with migrating assertSame/assertEquals to assertStringEqualsFile you had in PHP CS Fixer?

**Comment by keradus** [comment]
if I remember correctly:
`$this->assertSame('expected', file_get_contents('foo.txt'));`
was raising warning it shall use dedicated assertion, while only:
`$this->assertSame(file_get_contents('foo.txt'), 'input');`
should trigger it.

same issue with `->assertCount`

-------------

but in the end, after that much time I could be wrong

**Comment by kalessil** [comment]
Right! And the calls have the same meaning, or I missing something?

**Comment by keradus** [comment]
No. First param is expected value, 2nd param is actual value you want to test against expected value from fixture. When you swap params, you got totally confusing error message (in case of assertion failure)

**Comment by kalessil** [comment]
Got it: kind of usability issue caused by argument order.
 
Taking into account that the both cases gets normalized to `$this->assertStringEqualsFile('foo.txt', 'expected')`, does it mean that assertStringEqualsFile message is less informative that `$this->assertSame(file_get_contents('foo.txt'), 'input')`?

**Comment by keradus** [comment]
it's not less informative, it's simply wrong
when PHPUnit reports what was expected and what was actual value, user often grep for one of those printed values. And usually he have one in repo, other is generated on the fly. When values are replaced, he looks for different value instead.

what's more, when assertion is overwritten (directly as defined method in class (with compatible interface  and behaviour!), or indirect by registering custom comparator to PHPUnit), it got even worse when you swap order of parameters

**Comment by kalessil** [comment]
@keradus : thank you, seems we have to make more adjustments here.

**Comment by kalessil** [comment]
Fixed.
