### ISSUE TITLE
Exception for "Missing or empty conditionals group statement" when body is on same line

### ISSUE THREAD

**Issue by mnpenner** [kalessil/phpinspectionsea#266]
I know not everyone will agree, but I think this should be allowed:

```php
if($x) y();
```

But *not* this:

```php
if($x)
    y();
```

Can you add option to "Missing or empty conditionals group statement" to allow the first case?

------

PS: This should also *not* be allowed:

```php
if($x) y(); z();
```

Because `y()` is in the conditional but `z()` is not.

**Comment by rentalhost** [comment]
I can't confirm that. You are receiving an exception or an inspection? What is version of PS and EA plugin?

**Comment by kalessil** [comment]
@rentalhost : probably @mnpenner request a special handling - mixed style of placing `{}`

**Comment by kalessil** [comment]
@mnpenner, [PSR-2](http://www.php-fig.org/psr/psr-2/#if-elseif-else) defines no such exceptions.

The behavior you are requesting, where ist coming from (a PSR or CS used by your team)?

**Comment by rentalhost** [comment]
Ah, I understand now! And I agree with @mnpenner. Currently I always uses `{}`, but on past when I don't, I had serious issues with that.

**Comment by kalessil** [comment]
From my experience always placing `{}` is extremely useful as preventing bad merges, but still my question about such CS source needs answer =)

**Comment by mnpenner** [comment]
I didn't realize this was strictly following PSR. This is a personal
request for my team. I'd recommend leaving it off by default.

**Comment by mnpenner** [comment]
Oh.. I see where the confusion is now. I'm requesting an exception (special
handling) for mixed brace usage -- I'm not hitting an exception caused by
the plugin.

**Comment by kalessil** [comment]
Sooo, I looked up more deep to check if options can be added, but apparently, all if-related inspections requiring `{}` - they simply stop when the body is not wrapped.

Means it makes no sense to add options - too many inspections would need re-work.

I'd encourage you guys to follow the PSR, as it enables other inspections to support you.
