### ISSUE TITLE
Only variables should be passed by reference

### ISSUE THREAD

**Issue by vladyslavstartsev** [kalessil/phpinspectionsea#270]
no highlighting for this

![](http://dl4.joxi.net/drive/2017/04/21/0015/2269/1046749/49/6be65d668f.png)

but it has one for this (with message "Only variables should be passed by reference")

![](http://dl4.joxi.net/drive/2017/04/21/0015/2269/1046749/49/b0104e3b59.png)

Works the same way (I'm getting error).
Can provide any additional info if needed.

**Comment by kalessil** [comment]
Hm, that's not reported by Php Inspection (EA Extended). Please report to [JetBrains](https://youtrack.jetbrains.com/issues/WI).

**Comment by aik099** [comment]
@vladyslavstartsev , does work for me. It is covered by PHP EA Extended plugin (this one): `PHP | Php Inspections (EA Extended) | Probable bugs | Passing arguments by reference correctness`.

**Comment by aik099** [comment]
The https://youtrack.jetbrains.com/issue/WI-9368 does tell, that it's this plugin inspection and not PhpStorm built-in one.

**Comment by kalessil** [comment]
Wuut, I'll re-check then.

**Comment by kalessil** [comment]
Checked, the red marking is coming by PhpPassByRefInspection.
