### ISSUE TITLE
iterable is valid in is_array

### ISSUE THREAD

**Issue by jdreesen** [kalessil/phpinspectionsea#271]
`iterable` support for `foreach` has been added in #244 but is still broken for `is_array()`. 

installed version 2.3.6

![iterable](https://cloud.githubusercontent.com/assets/424602/25316340/9dc83458-2865-11e7-9425-9ea468efd85b.png)

**Comment by rentalhost** [comment]
I do agree. Once `iterable` could be an array, then `is_array()` should accept `iterable` for test, although it will naturally fail.

**Comment by funivan** [comment]
@jdreesen try to download binary from the master and install plugin from disk (https://github.com/kalessil/phpinspectionsea/blob/master/PhpInspectionsEA.jar)
@kalessil set milestone 2.3.7 so as I can see this version is not published yet.

**Comment by jdreesen** [comment]
I did but it doesn't seem to change anything. Even #244 seems not to be fixed. Do I need to do anything else apart from installing the plugin from disk (downloaded from your link) and restarting PhpStorm?

**Comment by funivan** [comment]
@jdreesen nope. Maby @kalessil did not update binary. 
There are 2 ways:
1. wait for 2.3.7 release
2. wait for new binary (we will ping you when it will be available)

**Comment by kalessil** [comment]
That's lack of the iterable type support: see [here](https://github.com/kalessil/phpinspectionsea/blob/8235cc5c72087b0b355e13111c6d7456d6669512/src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/semanticalAnalysis/CallableParameterUseCaseInTypeContextInspection.java#L111).

Thank you for reporting @jdreesen.

**Comment by kalessil** [comment]
Picking up - the inspection needs refactoring and UTs.
