### ISSUE TITLE
Simplify return statment

### ISSUE THREAD

**Issue by vladyslavstartsev** [kalessil/phpinspectionsea#275]
I think in this situation we can simplify this return statments
![](http://dl4.joxi.net/drive/2017/04/25/0015/2269/1046749/49/cc7c5b7210.png)

to `return null !== $role ? $role->id : null;`

**Comment by Fleshgrinder** [comment]
```
return $role->id ?? \null;
return $role ? $role->id : \null;
```

**Comment by vladyslavstartsev** [comment]
@Fleshgrinder second one will work I think. The first one I can't use because I have old php version on this project. (not 7.X)

**Comment by rentalhost** [comment]
I could be detected from IDE then suggest the best fix.

**Comment by vladyslavstartsev** [comment]
@rentalhost I think it will be `return $role ? $role->id : \null;` because in my particular situation this will be converted to bool and will equal `false`.
But the `return $role->id ?? \null;` is short for `return isset($role->id) ? $role->id : \null;` it's not useful (in my particular situation).

**Comment by rentalhost** [comment]
At least on your original code it seems to be returned like `?int` (`int|null`), then [I still don't see reason](https://3v4l.org/seWhlm) to not use `??` for PHP 7.x instead of `?/:`. Can you provide a code where it could cause a problem if applied with `??`?

**Comment by vladyslavstartsev** [comment]
@rentalhost yeah, you're right. I've tested, can't provide the code.
