### ISSUE TITLE
Optimize files and directories

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#278]
And finally, to completes my issues sequence, optimize (read "reorder") the files and directories. Currently it conflicts with the own inspection type declared on `plugin.xml`. It should be reworked to make it more simple to future devs. Seems a simple task, but it should be done with caution to avoid more confusions.

One of my suggestion is package like that:

> {root}.inspections.{group}.{inspection}

For instance:

> {root}.inspections.architecture.callableParameterUseCaseInTypeContext

Then the inspection will be a file called `Inspection.java` only. It will help we split the file into a lot of another files when need, for instance:

> **Inspection**: the base declaration of inspection;
> **InspectionNotOperator**: a sub-inspection that checks not-operator;
> **InspectionFix**: the default quick fix (_if have only one_);
> **InspectionNotOperatorFix** a sub-quickfix to not-operator;
> **InspectionOptions**: to avoid declares options directly on inspection file;

And it will not be a easy task.

**Comment by kalessil** [comment]
Checked, breaks merge into ultimate completely...
