### ISSUE TITLE
Send variable to compact()

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#279]
I need some help here to know it it can run out the project scope. Although that I think yes, maybe can be like an exception, because it should be useful to avoid some warnings. Basically, my idea is suggests as a optional-quickfix add current variable to `compact()` if it exists on scope.

For instance:

```php
function example() {
    $a = 123;
    $b = 456;

    return compact('a');
}
```

Here  `$b` is unused because I pretends put it on `compact()`. Currently I should do that manually, but a optional-quickfix (from *show intents actions* action) could allows it be done automatically by select an option like "use on compact()".

Some thinks about that:

* Scope should have a `compact()` definition, else option will not be displayed;
* Variable should not exists on `compact()`, else option will not be displayed;
* Variable _not needly_ should be "unused" to option be displayed;

**Comment by funivan** [comment]
I think it is out of scope

**Comment by Fleshgrinder** [comment]
I think that the usage of `compact` is so seldom, that it makes no sense to include in the first place. The extension is about best practice, not necessarily about how to use PHP correctly. On top, PhpStorm will already mark `$b` as unused in your example.

**Comment by rentalhost** [comment]
It is not true. It is very used when you works with MVC, for instance. The controller prepares all variables then send to view, for instance. The `$b` is marked as unused because the idea is send it to `compact()`. And is this that this issue suggests.

**Comment by Fleshgrinder** [comment]
Oh, my bad, PhpStorm marks all of them as unused because they are referenced as strings; true that.

I am not working much with frameworks besides Symfony from time to time, but never encountered much in the wild. You guys probably know better than me on this one. Disregard my previous comment, I leave this to you. 😸

**Comment by kalessil** [comment]
This would be out of our scope.

**Comment by rentalhost** [comment]
Yes, I do agree. It mean an intention and not a inspection. But then, the ultimate is to close that? Do the honors in this case.

**Comment by kalessil** [comment]
@funivan : can this be a feature request for your plugin?

**Comment by rentalhost** [comment]
And also tell us what is the name of your plugin. I do not think I know it.

**Comment by kalessil** [comment]
https://plugins.jetbrains.com/plugin/9178-refactoring

**Comment by funivan** [comment]
@kalessil yes, it can be implemented in 'refactoring' plugin. This can be a good place to intentions ;)

**Comment by kalessil** [comment]
Good, the it's yours now =)
