### ISSUE TITLE
Long Inheritance Chain (add special case for PhalconPHP)

### ISSUE THREAD

**Issue by strayobject** [kalessil/phpinspectionsea#280]
In [Long Inheritance Chain](https://github.com/kalessil/phpinspectionsea/blob/master/docs/architecture.md#long-inheritance-chain) there is a note stating that some framework specific assumptions are made, please add Phalconphp to those assumptions.

**Comment by kalessil** [comment]
@strayobject : gladly, but I need input on which inherited classes got reported - I'm not involved into the community or related development.

**Comment by kalessil** [comment]
Almost, I need just a few classes (2-3, except controllers) like here: https://github.com/kalessil/phpinspectionsea/blob/master/src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/semanticalAnalysis/classes/LongInheritanceChainInspector.java#L25

**Comment by strayobject** [comment]
I see. In this case would it not be better to count only userland inheritance by allowing people to set partial namespaces that are not to be counted or counted as 1 (example would be adding '\\Phalcon\\' to adjust the count if "extends" matches)?

As for the classes, I would consider the following (although other people might think otherwise):
```
\\Phalcon\\Forms\\Form
\\Phalcon\\Db\\Adapter\\Pdo
\\Phalcon\\Db\\Adapter\\Pdo\\Mysql
\\Phalcon\\Db\\Adapter\\Pdo\\Postgresql
\\Phalcon\\Db\\Adapter\\Pdo\\Sqlite
\\Phalcon\\Mvc\\View\\Engine\\Volt
\\Phalcon\\Mvc\\View\\Engine\\Php
```

**Comment by kalessil** [comment]
Great, the list looks good.

Some frameworks are using older PSRc, so namespace fragments there will not work.

**Comment by kalessil** [comment]
I did check the stubs and ended up with adding \Phalcon\Di\Injectable. 

Feedback would be appreciated: you can download PhpInspectionsEA.jar from master, 
in IDE: File - Settings - Plugins and under the plugins list click "Install from disk", point to the file and apply changes.

Let me know if the fix helps please.

**Comment by strayobject** [comment]
Yes this works :) Thank you.

**Comment by kalessil** [comment]
Super, and thank you for reporting!
