### ISSUE TITLE
[New Check] Check if used class is inside composer requirements

### ISSUE THREAD

**Issue by Koopzington** [kalessil/phpinspectionsea#281]
Sometimes you are working with PHP libraries which consist of multiple repositories.
Let's take Zend Framework as an example.

Your project might have a requirement on zendframework/zend-mvc which in return depends on [zendframework/zend-modulemanager](https://github.com/zendframework/zend-mvc/blob/master/composer.json#L19).
Your vendor folder will contain the classes from zend-modulemanager.
If you happen to use one of those classes, it'd automatically imply that your project requires zend-modulemanager to run.

Let's say zend-mvc releases a new version and was able to make zend-modulemanager optional and move it from require to suggest.
After doing a composer update, zend-modulemanager will get removed and you'll stumble upon a "Class not found" error.

To prevent that, i'd like to see this awesome Plugin checking if a class (residing inside vendor) used inside your project is not inside your composer requirements and underline the classname with a tooltip suggesting the user to add the class' libary to his composer requirements.

**Comment by Fleshgrinder** [comment]
This is a brilliant feature request. The same could be done for PHP extensions. Full support on this one!

**Comment by rentalhost** [comment]
I guess that is a great idea. I don't promiss nothing for now, because I am working with another inspections, but I like to give attention on it soon if no one take it. Seems easy-to-pick.

**Comment by kalessil** [comment]
Requirements ingeniering:
- indexing of composer.json
- analyze use statements only: resolve, check class file path against the index
- QF is not available

**Comment by kalessil** [comment]
Not easy, I'll give a try but no promises (other priorities may shift this).

**Comment by kalessil** [comment]
Note for myself: also document CI-friendly https://github.com/maglnet/ComposerRequireChecker in the inspection documentation.

**Comment by kalessil** [comment]
Implemented
