### ISSUE TITLE
Check if required extensions are specified in Composer config

### ISSUE THREAD

**Issue by Fleshgrinder** [kalessil/phpinspectionsea#282]
Same feature request as in #281 but for elements that originate from PHP extensions. I created a separate issue, because this might sound trivial, but in fact is very hard to implement. The problem is, that it is hard to maintain a list of available extensions.

An [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product) of this feature could support available core extension only (e.g. `ext-openssl`), and we gradually add other extensions. That is how it is being handled in the [PhpStorm stubs project](https://github.com/JetBrains/phpstorm-stubs).

**Comment by kalessil** [comment]
MVP would be to rely on this info (but I need to find a way to get this info):
![image](https://cloud.githubusercontent.com/assets/1577185/25457982/6d9605f6-2ad8-11e7-81cc-0fb97ea0b973.png)

**Comment by funivan** [comment]
We can create map of `function => extentions` 
For example: `openssl_cipher_iv_length => ext-openss`
Then if project call function `openssl_cipher_iv_length` then we can check `composer.json` for specified extension.
But it can be very-very slow inspection. Maybe it will be better to write custom tool or other plugin for that (collect php extensions)

**Comment by kalessil** [comment]
Yep, building the mapper on our own is total overkill. The ways which would make sense is to catch up on the settings from the screenshot.

**Comment by Fleshgrinder** [comment]
Reusing that info is the best way, absolutely. It would also ensure that the plug-in is always up-to-date with the latest PhpStorm info on these things, and people can contribute to a single code base to extend it.

**Comment by orklah** [comment]
I believe this functionnality is present in PHPStorm since 2018:
https://blog.jetbrains.com/phpstorm/2018/06/phpstorm-2018-2-eap-182-3458-35/

There is a QF to add the extension in composer.json and an intention to add the extension in the settings if it's missing.

**Comment by andreasschroth** [comment]
@orklah Yep, true. We use this inspection from PhpStorm already for several months and it works fine.

**Comment by kalessil** [comment]
Confirmed, this has been covered by PhpStorm already.
