### ISSUE TITLE
GitHub pages for docs ?

### ISSUE THREAD

**Issue by davidmpaz** [kalessil/phpinspectionsea#285]
What do you think guys of using this feature from GitHub ?

https://github.com/blog/2233-publish-your-project-documentation-with-github-pages

**Comment by kalessil** [comment]
+1 from me

**Comment by davidmpaz** [comment]
@kalessil Could you create a branch in repo called: `gh-pages`? 

The branch name is just a convention since most people use that for github pages. You can named like you want. Later on in settings when activating pages you need to say which branch will be used for such purpose. Just let me know against which branch should I make the pull request.

**Comment by kalessil** [comment]
@davidmpaz : done

**Comment by kalessil** [comment]
@davidmpaz : what do we need to do next here?

**Comment by davidmpaz** [comment]
Closed since we have already github pages :) at https://kalessil.github.io/phpinspectionsea/
