### ISSUE TITLE
ComparisonOperandsOrderInspector: avoid double-disabling

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#288]
Following https://github.com/kalessil/phpinspectionsea/pull/283#pullrequestreview-34976722, we should avoid the double-disabling of "_Yoda/regular conditions style usage_" (currently you could enable the inspection, but _disable the inspection_ that it does by unchecking both available options). 

* [x] By default, the inspection will be disabled by default;
* [x] When enabled, the Yoda style will be checked automatically;
* [x] The checkbox should be replaced by radio;

I like to work on that after merge of #283, because is possible that I change a bit how the `OptionsComponent` works with the radio type (using real radio buttons instead of checkboxes).

**Comment by rentalhost** [comment]
Fixed with 2a4b6a59ff5dce82be98666ac00927167f10242f (waiting for #283 to a PR).

**Comment by Fleshgrinder** [comment]
Just want to express publicly, but go ahead: _why Yoda as default!?! Why?!? 😢 _

**Comment by rentalhost** [comment]
It make a bit sense on PHP at least, but I too prefer regular style as default. But @kalessil thinks better Yoda. In all way, as it is not disabled by default (previously too, but not explicity) then on enable you have the oportunity to select you prefered style.

**Comment by kalessil** [comment]
I think that since the inspection is deactivated by default, making Yoda the default one will not hurt.

Yoda is harder to read and write, so people forced to pay more attention - unfair, but more attention ~ less bugs.

**Comment by Fleshgrinder** [comment]
I am currently working on an `Equalable` interface for PHP with operator overloading. People who write Yoda conditions would need to change the way they write code, because such an implementation always calls on the LHS and not RHS. However, let’s see if it makes it into core. Operator overloading is not something internals like.

**Comment by rentalhost** [comment]
Initially this inspection was "enabled by default", but "disabled by options". It because none option as "yoda" or "regular" was checked by default (then the inspection is just ignored). What happen now is that the inspection was "disabled by default" and the "yoda" is default when you enable it (it should keep your last settings if you yet have this enabled).

**Comment by Fleshgrinder** [comment]
Guys, all fine, my comment was really just a public outburst of disgust, keep it.

It’s just that this extension gains more and more traction and any and every default setting you choose, or recommendation you make, has an impact. An impact that is only going to increase if more people start using it. 😉

**Comment by rentalhost** [comment]
@kalessil Can we consider that? I still prefer regular style instead of Yoda - although in PHP it makes sense, it's kind of weird for me.

**Comment by kalessil** [comment]
@rentalhost , taking into account that warnings from @Fleshgrinder materialized several times already, please make the regular one enabled by default...

**Comment by rentalhost** [comment]
PR
