### ISSUE TITLE
Howto fix unknown type inside foreach with phpdoc ?

### ISSUE THREAD

**Issue by michabbb** [kalessil/phpinspectionsea#290]
hi,

i have this foreach:

```php
foreach ($data['attachmentspaths'] as $attachmentpath) {
  echo 'do something';
}
```

what is the correct phpdoc i have to insert so that `$data['.....']` gets recognized as array ?
many thanks.

**Comment by rentalhost** [comment]
You have two ways to do that.

**First: check if key is an array.**

```php
if (is_array($arr['subArray'])) {
    foreach ($arr['subArray'] as $value) {
        echo $value;
    }
}
```

**Second: store into a variable, then phpdoc it as an array.**

```php
$arr = [ 'subArray' => [ 1, 2, 3 ] ];

/** @var array $subArray */
$subArray = $arr['subArray'];

foreach ($subArray as $value) {
    echo $value;
}
```

Currently phpdoc has no support to determine each array key typehint. But I suggests you to check if you can replace this array by an object. Then you can do that.

```php
class MyObject
{
    /**
     * @var array
     */
    public $array = [ 1, 2, 3 ];
}

$myObject = new MyObject;
foreach ($myObject->array as $value) {
    echo $value;
}
```

**Comment by michabbb** [comment]
@rentalhost many thanks !! 👍

**Comment by kalessil** [comment]
/* @var array[] $data */ or /* @var string[][] $data */ will do the treak - you can specify any level if types are consistent.

**Comment by rentalhost** [comment]
The problem with that solution is that all array values will be treated like an array. Then a case like:

```php
$arr = [
    'years' => 26,
    'phones' => [ 123, 456 ]
];
```

Then `$arr['years']` will be treated as an array too. It could be valid if on context you uses only `$arr['phones']`, but on a general context, it doesn't works well. BUT, is a solution too.

**Comment by michabbb** [comment]
@kalessil no, none of your recommendations is working for me, latest phpstorm (2017.1.3) and php inspections (EA Extended) version 2.3.6

![ausschnitt_ohne_titel_042817_061952_pm](https://cloud.githubusercontent.com/assets/3524595/25537570/4737cf26-2c3f-11e7-9b11-5f5df2e8a255.jpg)

**Comment by kalessil** [comment]
Interesting, will this code fragment inside a test function work?

```php
        /* @var $data string[][] $data */
        foreach ($data as $array) {
            foreach ($array as $string) {
                echo $string;
            }
        }
        foreach ($data[''] as $string) {
            echo $string;
        }
```
![image](https://cloud.githubusercontent.com/assets/1577185/25537854/8398fa0c-2c40-11e7-8762-b579c369827e.png)

**Comment by michabbb** [comment]
@kalessil interesting ;)

heres a line of my code, i didn´t show:

`if (array_key_exists('attachmentspaths', $data) && $data['attachmentspaths']) {`

and if i put your phpdoc above that line, then my code is marked as "okay".
i have put your phpdoc _after_ the `if` and then i still get the error....

**Comment by kalessil** [comment]
Ideally, it should be something like this (mostreliable way):

```php
     /* @var string[][] $data */
     $data = ....;
```

@rentalhost : yes, your also correct - my approach is for plain arrays.
