### ISSUE TITLE
Detect Magic Numbers

### ISSUE THREAD

**Issue by quantumpacket** [kalessil/phpinspectionsea#293]
Could we have support to detect magic numbers? Right now, I'm using this https://github.com/povils/phpmnd to scan my code, but it would be great if this was part of the plugin. the default JS plugin for PHPstorm has support for it already, but there is currently none for PHP.

I'd also mark `0` and `1` as non-magic in a default editable list, which we can add/remove numbers that should be excluded.

**Comment by rentalhost** [comment]
I like this. We should only wait if it could be part of plugin (I guess so), and too if we can do the same for things like booleans, strings, floats (do it make sense?). ping @kalessil

**Comment by kalessil** [comment]
@rentalhost: magic numbers (ints, floats) are in the scope.

**Comment by rentalhost** [comment]
I am working on that, but for now, I do not understand why `return 0` should not be warned, while `return $allNumberExceptZeroOrOne` should be.

**Comment by rentalhost** [comment]
Closing: PR #323
