### ISSUE TITLE
Change release strategy II

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#296]
Following #284.

Currently, the releases are made without a _standard strategy_, being made out at any time. So maybe we can think in a way that there is a more reasonable pattern. This will allow delivery and real world testing cases (_of users_) on top of the latest news.

As _semver_ currently is infeasible "_as is_", then we could thinks about a new release strategy, without worrying about two working branches ("_master_ and _bugfixes-only_").

**How it should works:**

Releases should be done each 15 days (1st monday*, and 3rd monday of each month). It should includes: internal changes, new features or feature changes, workaroundable bugfixes (eg. _when user can just disable the inspection until the next release_). (_Current cycle is variable about 10~30 days, avg 19 days._)

\* @kalessil _Change it to a better week day that you are available._

**Then, on starts a new release process:**

* From 1st to 12th day: implementations, merges and unit tests (_when feasible_);
* 13th and 14th day: doc, rules, last review, preparing to release;
* 15th day: release day and start of a new release cycle (_1st day_).

If during 15 days we have no news or then just internal changes that not affects userland directly, then no release is done - _should wait to the next release_ (15 days). _But_, even that we have a simple bugfix or a small new feature or change, then release should be done (and we should not try to avoid this as it will help to show regular users that we are constantly working on the plugin, _even with minor changes_).

**About version numbering:**

* If during the 15 days no new feature was created (just feature or internal changes or bugfixes), then we should consider it as bugfix-only, then just _+version.patch_.
* If during the 15 days at least one new feature was created (it is, a _new inspection_ needly), then we should consider it as a feature (even it if includes bugfixes), then _+version.minor_, _0.version.patch_.

**Exceptional branch:**

We should avoid works in two branches, because it is hard and confuse. But we should consider an exceptional cases where we have critical bugs (eg. _NPE_). Then in this case, we should checkout the last released version to a temporary branch, _fix only this critical bug_, then release immediately (_+version.patch_). The fix should be applied too to master.

**About milestone:**

I guess that it do not works fine to us. We should only prioritize bugfixes, then features. Then just tag as WIP, do code, then PR.

**Conclusion:**

With that, we could do the release process fast and easy, because we should care with small changes or few new features. It should be easy to doc and review.

**Comment by funivan** [comment]
> About milestone

Milestones works fine. We know in what version bug was fixed. And we can see if this version is under development.

**Comment by rentalhost** [comment]
It could be replaced by tags, or not? And we have the freedom to choice exactly what you wants to work without assign nothing directly.

**Comment by funivan** [comment]
> It could be replaced by tags, or not?
I think not. With milestones we track progress in easy way.
And you can work on any issue (without WIP tag) ;)

**Comment by kalessil** [comment]
For release strategy change we need a constant pool of resources to be available - that's not a case.
Max what I can do is to ping @rentalhost and @funivan for feedback on milestone and version to be given, though I have to change milestones naming to not mix up with versions and milestones.

**Comment by funivan** [comment]
@kalessil you can just ping me if new binary is available =)

**Comment by kalessil** [comment]
@funivan : ping =), bug-fixes and QFes are bundled since NCO inspection was added.

**Comment by funivan** [comment]
@kalessil fresh version installed. Wait for feedback ;)

**Comment by kalessil** [comment]
Getting back to this: what shall be the next release (see estimate scope for 2.3.8 milestone)?

**Comment by rentalhost** [comment]
@kalessil The last release (2.3.7) was two days ago (sunday 2017-M05-14). If we consider 15 days cycle, the next release should be on 1st (to round up, then next-next release should be 15th) or then 28th (then next-next release should be 11th).

BTW, I will try do some work on milestone too this weekend.

**Comment by kalessil** [comment]
It's rather 4 weeks =) I was asking about the version in regards to semantic versioning.

No worries, I'd prefer you to focus on open PRs - I need them merged until codebase is not moved forward too much.

**Comment by rentalhost** [comment]
Closing: no more to discuss.
