### ISSUE TITLE
MigLayout dependency: migrate to standard swing components

### ISSUE THREAD

**Issue by funivan** [kalessil/phpinspectionsea#3]
`import net.miginfocom.swing.MigLayout;`
Is this dependency necessary to this inspection?

**Comment by kalessil** [comment]
Yes, see [here](https://github.com/kalessil/phpinspectionsea/blob/master/src/com/kalessil/phpStorm/phpInspectionsEA/inspectors/apiUsage/IsEmptyFunctionUsageInspector.java#L128): used for adding settings for the inspection.

**Comment by funivan** [comment]
@kalessil I see. But why you are not using standard swing components?
https://github.com/JetBrains/intellij-community/blob/306d705e1829bd3c74afc2489bfb7ed59d686b84/spellchecker/src/com/intellij/spellchecker/inspections/SpellCheckingInspection.java#L180

p.s. When I first commit some code to this plugin I just configure phpopen api. But now I need to install `miginfocom` library. This is not a big problem but IMHO it is easy to use standard libraries =)

**Comment by kalessil** [comment]
Hm, it shouldn't be a case, here my settings:
![ps-plugin-libs](https://cloud.githubusercontent.com/assets/1577185/19429744/8d32069e-9451-11e6-9f36-16538a79437a.png)

Standard swing components might be a good idea, I don't remember why I used MigLayout exactly.

**Comment by funivan** [comment]
@kalessil I configured php-openapi. But also I should install MigLayout =) 
1. I can rewrite all `MigLayout` usages to standard swing components
2. Just install `miginfocom` library. 
What do you prefer?

**Comment by kalessil** [comment]
@funivan : 2nd one.

I'll take care about migrating to components as you referenced - it's 10 classes and I'd like to avoid massive refactoring in next release.
