### ISSUE TITLE
[followup] disallow writing into static properties (optional)

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#31]
Original link: https://bitbucket.org/kalessil/phpinspectionsea/issues/299/disallow-writing-to-static-properties
Author @bram123

See original ticket

**Comment by kalessil** [comment]
Shifting fresh-look review to 2.3.7, need to focus on 2.3.6

**Comment by rentalhost** [comment]
I don't know...

If I can't write on static properties, then maybe I should use constants, instead this. I rarely create static properties. Basically I use to store a single instance, but it is an anti-pattern (now I am using the `App::singleton()` of Laravel to do that).
