### ISSUE TITLE
Checking for null is not needed

### ISSUE THREAD

**Issue by davidmpaz** [kalessil/phpinspectionsea#311]
Is this or similar checked already?

```php
class ValueObject {
    // Object doesn't have a constructor, only accessor and mutators
}
```
then somewhere else in code:
```php
$var = new ValueObject();
// and later, without mutating the object, this:
if ($var->getSomeField() !== null) {
    $var2 = $var3->callMethod();
}
// or...
$var2 = $var->getSomeField() !== null ? $var3->callMethod() : $var3->callOtherMethod();
```
For whatever reason we came into this situation a refactor is obviously needed.

**Comment by kalessil** [comment]
So we are more and more reaching java SCA level =)

**Comment by rentalhost** [comment]
I guess that it is related to #221, can you confirm?

**Comment by kalessil** [comment]
@rentalhost : not really a case #221, rather a companion inspection for NPE detection.

**Comment by funivan** [comment]
@kalessil I thing you can check not only `null` For example we can check different types in strict comparison 
```
$val = 123;
if($val===''){} //<- this statement will always be false
```
So you can create inspection to catch mismatch type comparison.

**Comment by kalessil** [comment]
@funivan : in nut-shell yes. Practically I'll be able to start with null and instanceof.
Expansion of what you are referencing to is no problems if ultimate will generate enough revenue.

**Comment by kalessil** [comment]
Seems to be implemented already =)
