### ISSUE TITLE
Multiplying by 24. False positive.

### ISSUE THREAD

**Issue by jaimz22** [kalessil/phpinspectionsea#319]
It seems to me that any time I find myself multiplying by 24, the plugin believes that I'm doing date/time math when I'm not.

This triggers a red error line to be drawn under my equation when in fact there is nothing wrong at all.

**Comment by kalessil** [comment]
Thank you for reporting @jaimz22 , but unfortunately we can not provide any fix for this (was already reported and investigated).

The suggested solution is to use a constant/local variable but not a hardcoded `24` in the reported code fragment.

**Comment by jaimz22** [comment]
Ok, thanks. I searched the issues prior to reporting it but didn't find anything.

also, thanks for this plugin, it's the best!

**Comment by kalessil** [comment]
Right, the old issues in the old bug tracker at bit-bucket: https://bitbucket.org/kalessil/phpinspectionsea/issues/257/false-consider-using-datetime-for-dst-safe

You are welcome =) If you find new issues, please report - I'm trying to fix false-positives with high prio normally.

**Comment by funivan** [comment]
@jaimz22 can you provide some samples
In cases like:
`$lang_col_width   = ( $lang_count - 1 ) * 24 . "px"; ` we can check concatenation with string

**Comment by kalessil** [comment]
@funivan: `$dateTimeInput = ($hours / 24) . ' days'` - cconcatenation is not reliable enough to judge the usage context, but @jaimz22 : +1 from me for sharing the code sample - perphaps we can learn accidentally find a way to fix the case.

**Comment by jaimz22** [comment]
I was using this when I decided to put in the issue:

`time()+(180*24*60*60)`

I've had other instances where I was trying to figure out the size of something and I was just simply multiplying by 24

**Comment by rentalhost** [comment]
@jaimz22 Seems that you are reality working with datetime. Maybe you can refactoring that to use `\DateTime`.

**Comment by jaimz22** [comment]
@rentalhost in this case. kind of... I mean I was setting a cookie ttl.

in other cases I wasn't

**Comment by kalessil** [comment]
@jaimz22 

That's a great bet! 24 in a combination of 3600/60 is the criteria to reduce the number of false-positives.

**Comment by kalessil** [comment]
Fixed, the fix is coming with the next release - ETA mid of June
