### ISSUE TITLE
unchecked nullable parameter usage

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#32]
Original link: https://bitbucket.org/kalessil/phpinspectionsea/issues/141/optional-parameter-usage

See original link

**Comment by Fleshgrinder** [comment]
May I add nullable types in general to this issue, e.g.:

```php
function f(): ?T {}

$t = f();
$t->f(); // requires null check
```

[I just wrote](https://medium.com/@Fleshgrinder/the-case-of-the-null-reference-a50382de7ed0) about this and would love to link your brilliant extension as an example that can help to prevent this kind of mistakes. 😻

**Comment by kalessil** [comment]
This is going to be a main feature of the next release ;)
I just hope that amount of reported bugs will be low after 2.3.3 released today, so we could take finally more features into the next release...

**Comment by kalessil** [comment]
So, I want to start with original scope - only parameters. And we'll make a followup ticket for chained calls.

Step by step we'll get to fully functional NPEs inspection =)

**Comment by kalessil** [comment]
Ready, fresh binary pushed as well. Please also note [limitations](https://github.com/kalessil/phpinspectionsea/blob/master/docs/probable-bugs.md#null-pointer-exceptions-prevention).

**Comment by kalessil** [comment]
For beta-testing:
- download PhpInspectionsEA.jar file from our master branch;
- in IDE follow this path: File -> Settings -> Plugins;
- under the plugins list click "Install from disk" and point to the downloaded file;
- apply chnages, restart ide and activate the inspection (File -> Settings->Editor -> Inspections -> Php -> Php Inspections (EA Extended) -> Probale bugs -> Null pointer exceptions prevention (beta)
