### ISSUE TITLE
PropertyCanBeStaticInspection should suggest class constants

### ISSUE THREAD

**Issue by nCrazed** [kalessil/phpinspectionsea#324]
As far as I can tell you can only have the following scenarios:

 1. Property is modified - the inspection is not relevant because static is not viable.
 2. Property is modified statically - the inspection not relevant because the the property is already static
 3. Property is should never be modified - it's a constant and is better represented as class constant.
 4. Property is upon for modification by subclass - see 1.
 5. Property is open for static modification by subclasses - see 2.

Am I missing some other scenario?

If not, the inspection's suggested solution should at least mention class constant instead of pushing the developer towards a static if not replace it completely.

**Comment by nCrazed** [comment]
@koopzington

**Comment by rentalhost** [comment]
It's hard to identify, once that PHP can hide some properties from analysis (eg. if I read via [`ReflectionProperty`](https://3v4l.org/#preview)). But I think that it is valid once that it should not happen in a good code case.

**Comment by kalessil** [comment]
Re-visiting the ticket: if I understand correctly, we don't need to change behavior.
We need an option: suggest static field/constant, right (or probably I miss something)?

**Comment by nCrazed** [comment]
@kalessil I think the best solution is to keep the current behaviour, but change the wording of the suggested from class constants to static properties.

**Comment by kalessil** [comment]
Looks like it's not much work here, picking up.
