### ISSUE TITLE
Milestone setup

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#328]
Well, I am doing some work on milestones. I have created three last time and I am creating this topic to explain why I do that:

**Milestones:**

* [**Internal:**](https://github.com/kalessil/phpinspectionsea/milestone/14) 
Are issues that solves some internal thing. Different of label `internal`, it mean that we have something to be fixed internally needly, while the label is just an internal discussion.

* [**2.3.+:**](https://github.com/kalessil/phpinspectionsea/milestone/12)
Are issues that are required to be fixed on nexts releases (short term fixes), but not needly on next after current. After the next release (eg. for _2.3.9_, considing that we are on _2.3.8_), then we get some issues from this milestone and move to _2.3.9_ (but not all of them).
If version is changed to 2.4, then we just rename this milestone to 2.4.+.

* [**3.0.+:**](https://github.com/kalessil/phpinspectionsea/milestone/13)
Are long term issues, that should be fixed on end of year or next year. 
Are long term fixes.

I tried to move all milestone to the compatible one, but you are free to move it again to a better milestone. And we currently have some [no-milestoned](https://github.com/kalessil/phpinspectionsea/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20no%3Amilestone%20) issues that should be moved too.

**Comment by kalessil** [comment]
Milestones looking good, IMO also transparent about prios.

**Comment by rentalhost** [comment]
Closing: the message has been passed. 😄
