### ISSUE TITLE
[contrib] Codeception's/Yii's debug statements

### ISSUE THREAD

**Issue by zbrag** [kalessil/phpinspectionsea#33]
Hi,

Awesome plugin, I use it all the time 👍 

However, [Codeception](http://codeception.com/) the debug statements look like \Codeception\Util\Debug::debug() and those should of course not be present when you commit the code. It would be  awesome if PHP Inspections EA would warn me about this.

Also, sometimes PHPStorms adds the use statement for Codeception\Util\Debug, so it is possible there is only Debug::debug() present in the code.

**Comment by kalessil** [comment]
Hi,

Thank you)

You are able to add own debug statements via configuration of the inspection:
- Right click on the method name, click copy reference;
- Click "+" icon as on the screenshot below, insert from the buffer;
- Save configurations;

![custom-debug-statements](https://cloud.githubusercontent.com/assets/1577185/20002493/700b015e-a281-11e6-886d-a9e359d37466.png)

**Comment by zbrag** [comment]
Cool, I will add it there, but I think it is useful if this statement is implemented into the code of this plugin, don't you agree?

**Comment by zbrag** [comment]
Cool, I will add it there, but I think it is useful if this statement is implemented into the code of this plugin, don't you agree?

**Comment by zbrag** [comment]
Cool, I will add it there, but I think it is useful if this statement is implemented into the code of this plugin, don't you agree?

**Comment by zbrag** [comment]
Cool, I will add it there, but I think it is useful if this statement is implemented into the code of this plugin, don't you agree?

**Comment by kalessil** [comment]
Why not, could be added [here](https://github.com/kalessil/phpinspectionsea/blob/master/src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/apiUsage/debug/ForgottenDebugOutputInspector.java).

Or perhaps you could provide FQNs for "debug" methods in Codeception.

**Comment by zbrag** [comment]
Codeception has two functions which should be marked, both in the [same file](https://github.com/Codeception/Codeception/blob/2.2/src/Codeception/Util/Debug.php)
\Codeception\Util\Debug::pause
\Codeception\Util\Debug::debug

Thank you

**Comment by kalessil** [comment]
@samdark : any debug methods from Yii you'd suggest adding as well?

**Comment by kalessil** [comment]
@dryabov : any debug methods from Joomla! you'd suggest adding as well?

**Comment by samdark** [comment]
@kalessil not really. Usually it's the same as general PHP: var_dump, echo etc.
