### ISSUE TITLE
Suggests remove the typehint if is declared on language

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#332]
Following #256, but at reserve...

Currently we can dupe the typehint definition on `@return`. I suggests that, if typehint is declared on language, then it should be deleted from docblock.

```php
// Not acceptable: void already declared as return type.
/** @return void */
function something(): void { }
```

I like to be possible too for `@param`, but I guess that we can't do that because it will conflicts with the param description (eg. `@param $param It is my param`, the word "It" is confused by the `It` class).

**Comment by Stevehans** [comment]
@return can have a description, surely just verify that the code hint and @return types match?

**Comment by rentalhost** [comment]
@Stevehans ahh... then maybe we can verify if we have a description in both cases (`@param` and `@return`). If we haven't, then we can omit that, else, we should match types. What do you think?

**Comment by rentalhost** [comment]
In fact, I believe that the parameters should be sufficient to describe their meanings. In more complex cases, the description of the method should do so. So, the description of parameters and return end up becoming redundant, which is important to be removed from the code to avoid double maintenance.

**Comment by Fleshgrinder** [comment]
It is possible to omit all these things already with existing PhpDoc parsers.

```php
/**
 * @param $p
 *     description goes here
 * @return
 *     description goes here
 */
```

One added nice thing about writing documentation like this is that the fight over alignment of the description is gone. Drupal does its documentation everywhere like this.

**Comment by kalessil** [comment]
Will not happen.
