### ISSUE TITLE
Normalize aliases imports

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#335]
I will starts with an example. Laravel have two classes called `Builder`, in differents namespaces, of course. Is common you use both on same class, then you should import both, aliasing one of them.

The problem is that you usually import one, then other, and possibly in different order. Then for instance, sometimes I import `Query\Builder` first, then `Eloquent\Builder` next, then I aliases it to `EloquentBuilder`. In other files, I do import `Eloquent\Builder` first then `Query\Builder`, then I aliases it to `QueryBuilder`.

**My idea here is analyzes cases like that an suggests a normalization, and this is the logic:**

1. Check if a file imports other classes;
1. Check if one of this files are aliases because of conflict on imports (it should ignore if the alias is because of class name, for instance);
1. Check if in other files, you do the same import (of both classes) and check if you have aliased as you aliased on current file, if different, then warn.

---

**FirstClass.php**

```php
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Query\Builder as QueryBuilder;
```

**SecondClass.php**

```php
use Illuminate\Database\Eloquent\Builder as EloquentBuilder;
use Illuminate\Database\Query\Builder;
```

For **FirstClass.php** we should suggests to normalize like **SecondClass.php** (alias `Eloquent\Builder` as `EloquentBuilder` and remove alias from `Query\Builder`), and vice-versa (the most important here is you treat both aliases equals in both files).

**Comment by kalessil** [comment]
This would need adding new indexer, just to maintain naming consistency.
Let's keep focus and not go into naming direction.
