### ISSUE TITLE
Overcomplex type inspection

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#340]
In an ideal world, we should always expect that a variable, parameter or method have a single type. For instance, no make sense a method returns `int` and `string` (even) conditionally. It is probably a design failure.

This inspection should identify any case of overcomplex types.

**To consider:**

* [ ] Identify overcomplex types (eg. `int|string`);
* [ ] Identify usage in:
  * [ ] `@return`
  * [ ] `@param`
  * [ ] `@type` and `@var`
  * [ ] `@property`, `@property-read` and `@property-write`
  * [ ] `@method` 
* [ ] Should accept nullable (eg. `int|null`);
  * [ ] Except for booleans (eg. `bool|null` or `false|null`);
* [ ] Should accept array mixin; Eg.
  * [ ] `Collection|array`;
  * [ ] `Collection|string[]`;
  * [ ] Make sure to accept nullable here too (eg. `Collection|string[]|null`);
* [ ] Make sure that even close types not be allowed (eg. `Carbon|DateTime`);
* [ ] Ignore inspection if variable name starts with `$complex[A-Z]` (eg. `$complexNumber`) -- it should allows some rare cases where it should be allowed;

**Comment by rentalhost** [comment]
**Off-topic**: I am working on a new plugin called [laravel-insight](https://github.com/rentalhost/laravel-insight/). It is specific to Laravel framework (inspired on your plugin), and I like to not implements things like that above because it is related to PHP itself, not with Laravel. And it should be very useful to Laravel too.

**Comment by b1rdex** [comment]
This plugin should allow `type|false` or `type|bool`, because it's used in php internal functions and in other code as result. Maybe these should be controlled by separate option checkmark.

**Comment by rentalhost** [comment]
For PHP internal functions it should not be applied (unfortunatelly). I guess that `type|false` is not good, for that we have nullable types (eg. `int|null`).

**Comment by b1rdex** [comment]
@rentalhost I can say that `null`able returns are bad practice and it's not any different from `false` — best option for me is `throw`ing exceptions. But that's not a law, each one should decide how to do things best.
So we should deal — there is client code with such behaviour.

Simple example: some wrapper around internal function that can return `false`. Am I required to return null instead of false? No.

**Comment by rentalhost** [comment]
Hmm... I don't know why `null` returns are bad pratice (including, PHP offers native support now eg. `?User`). Other features on PHP expects nulls too, as coalesce operator (eg. `getUser() ?? new User`). It `getUser()` returns false, then the coalese "else" will never run.

Can you write some example for internal functions that returns `false` instead of `null`?

**Comment by b1rdex** [comment]
Lots of them :)

http://php.net/array_search
http://php.net/strpos
http://php.net/explode
http://php.net/preg_match

**Comment by b1rdex** [comment]
Worst function that I remember that returns false|null|mixed is http://php.net/parse_url

**Comment by rentalhost** [comment]
But PHP internal functions will not be inspectioned, only user land. You could use it too without problem, the inspection should works only on declaration, not on usage.

**Comment by kalessil** [comment]
A PhpDoc topic ;)
