### ISSUE TITLE
Feature request: type casting with other actions detection.

### ISSUE THREAD

**Issue by tensor146** [kalessil/phpinspectionsea#344]
Hello!
Just found the bug in some code:
`$param = (int) $array['key'] ?? $bar;`
In this code, variable $param always will have value "0" if $array['key'] is undefined.
(because php sees it like: `$param = ((int) $array['key']) ?? 12345;` => (int) from unexisting element is 0 => 0 is "isset" => `0 ?? $bar` means `0`)
I fixed it like:
`$param = (int) ($array['key'] ?? $bar);`
But possibly such issues can be detected by parser?

**Comment by kalessil** [comment]
Thank you for reporting @tensor146, that's a nice new pattern for an existing inspection.
I'll try to deliver it with the next release (ETA ~ mid of June)

**Comment by kalessil** [comment]
Done, a fresh binary has been pushed as well.
