### ISSUE TITLE
Add a logo to readme

### ISSUE THREAD

**Issue by samdark** [kalessil/phpinspectionsea#348]
I've found out that a logo in readme gives a good boost to the project because it becomes eye-catchy.

Would be cool to get professional logo. Meanwhile I did a quick mock:

![phpinspections_ea](https://user-images.githubusercontent.com/47294/26991958-2a7ee9f4-4d65-11e7-8d60-f57ca8cbb46a.png)

**Comment by kalessil** [comment]
That's a great idea @samdark, thank you!

**Comment by samdark** [comment]
@fazeful, @eshill this is really important OpenSource project. Could be good for your portfolios ;)

**Comment by kalessil** [comment]
Added, thank you @samdark !
