### ISSUE TITLE
Null pointer implicit check

### ISSUE THREAD

**Issue by acelaya** [kalessil/phpinspectionsea#349]
I was wondering if it would be possible to improve the null pointer exception check so that it takes into account implicit checks.
I mean. Let's consider this case. I have a model with a nullable `parent` property.

```php
$category = new Category();
$category->getParent()->getId();
```

If I try to call methods on that property, the check tells me there could be a null pointer exception,  which is cool.

However, I already have a method in the category object called `hasParent` which checks if parent is null.

```php
public function hasParent(): bool
{
    return $this->parent !== null;
}
```

If later in my code I do this:

```php
$category = new Category();
if ($category->hasParent()) {
    $category->getParent()->getId();
}
```

I still get the warning. If I do this instead, then I don't get the warning

```php
$category = new Category();
$parent = $category->getParent();

if (null !== $parent) {
    $parent->getId();
}
```

Would it be possible to make this check consider this case?

**Comment by kalessil** [comment]
That's would hit performance really bad, I'd suggest altering `getParent()` so it doesn't return null, but throw an exception when a property is null.

**Comment by Fleshgrinder** [comment]
Could we please stop calling this _null pointers_, it is the wrong terminology. This is PHP, not Java. 😉 

https://medium.com/@Fleshgrinder/the-case-of-the-null-reference-a50382de7ed0

@kalessil I still need to incorporate a link to your extension there …

**Comment by acelaya** [comment]
I called it "null pointer" because that's how it's called in the plugin, and that was the easiest way to refer to it.

@kalessil, ok, I see the problem. I think I can live with it :-)

**Comment by Fleshgrinder** [comment]
Well, than we really need to update the documentation in the plug-in. Haven’t noticed that it is incorrectly named there.

**Comment by kalessil** [comment]
@Fleshgrinder : ths! Will correct naming.

**Comment by kalessil** [comment]
@acelaya, great!
