### ISSUE TITLE
argument same as default (e.g. in_array(...,...,false)) but leaving it out gives another warning

### ISSUE THREAD

**Issue by Doqnach** [kalessil/phpinspectionsea#350]
I have parts of legacy code where we simply need to do an `==` unsafe check, e.g. in the use of `in_array()`. I'm sure that before a recent update, it was not a problem giving the third argument as `false`, but now this gives the inspection: "The argument can be safely dropped, as it identical to the default value.". If you remove the `false` though, it gives the inspection "Third parameter should be provided to clarify if types safety important in this context.".

Of course I can set the initial inspection to not warn me (what exactly does "no highlight, only fix" actually mean?), but I do want to be notified of this for other methods/functions. PHPStorm isn't giving me a `@noinspection` option to disable the inspection for each specific case?

Am I correct in thinking this behaviour changed with a recent update? And what would be the right thing to do now, other than doing strict compares (which is not an option in this legacy codebase)? I prefer not to disable this inspection globally.

**Comment by kalessil** [comment]
That's something I didn't look carefully at - please keep the 3rd parameter and I'll add in_array, array_search into exceptions for the inspection which complaints.

**Comment by Doqnach** [comment]
Maybe you could also correct the spelling on the second inspection?
"Third parameter should be provided to clarify if types safety important in this context."

I think this should be more in the lines of: "Third parameter should be provided to clarify if type safety is important in this context."

**Comment by kalessil** [comment]
Will do =)

**Comment by Doqnach** [comment]
PS: 'is' is also missing from the first inspection while you are at it ;-] 

"The argument can be safely dropped, as it is identical to the default value." or "The argument can be safely dropped, as it's identical to the default value."

**Comment by kalessil** [comment]
Ok, will fix both =)
