### ISSUE TITLE
Exceptions handling workflow: add options (white-list to be not reported)

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#354]

**Comment by rob006** [comment]
Whitelist for exceptions was implemented in PhpStorm: https://youtrack.jetbrains.com/issue/WI-22936

Is this plugin will respect these settings?

**Comment by kalessil** [comment]
Nope: there is no API which we can use for accessing those settings. 

I updating ticket status as our settings has been released in v2.3.15.
