### ISSUE TITLE
Is it possible to export the results?

### ISSUE THREAD

**Issue by leac** [kalessil/phpinspectionsea#360]
Hi

First of all, great plugin.
Second of all, I would like to send the results to a team I work with. Specifically, I need to send the results of the security inspection to our information security team.
Is there a way to easily do that?

Thanks

**Comment by kalessil** [comment]
Yes, just export as HTML and send generated html+js files to your team for reviewing security section
![image](https://user-images.githubusercontent.com/1577185/27323799-28ba291c-55a3-11e7-9943-0707350341e3.png)

Hope this helps, also ping me at kalessil (at) gmail (dot) com if you need external consulting/support.
