### ISSUE TITLE
Date interval specification validity - report "PT"

### ISSUE THREAD

**Issue by downace** [kalessil/phpinspectionsea#361]
"Probable bugs | Date interval specification validity"

Inspection doesn't report the "PT" string, but it is invalid

![image](https://user-images.githubusercontent.com/7350510/27413797-8dd5d742-5738-11e7-873a-3f2e414ed07f.png)

**Comment by rentalhost** [comment]
**Closing reason: fixed.**
It should be available on next release.

If you have any new question on this issue, please, feel free to open it again.
