### ISSUE TITLE
Variable can be final

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#363]
It is a big confuse, once that PHP don't have support to `final` modifier, but we can implement that by creating some king of "variable annotation". Then I think about prefix a variable with `$f` to identify that it is  final and should not be overrided.

```php
// Allowed:
$number = 123;
$number = 456;

// Warned: $number could be final -> $fNumber
$number = 123;
echo $number;

// Not allowed: final variable $fNumber was overrided.
$fNumber = 123;
$fNumber = 456; // or
$fNumber.= 456;
```

It should works like we did with parameters, by prefixing it by `$pName`.

**Comment by kalessil** [comment]
I think we shouldn't go into meta-programming and wait for the corresponding RFC instead.

**Comment by rentalhost** [comment]
I don't found any RFC about final variables. 
Where did you found it?

**Comment by Fleshgrinder** [comment]
Introduction of Hungarian notation is not a good idea. I also think that there is no RFC as it would be very hard to implement this in PHP due to the way arrays are implemented, this also stopped the work on the immutable data class RFC. That being said, an annotation could be used:

```php
/**
 * @var int
 * @final
 */
$num = 42;
```

**Comment by rentalhost** [comment]
I don't like annotations like that (phpdoc). Unfortunatelly PHP internals doesn't accepts the `@Annotation` outside a phpdoc. It should resolve the problem for IDEs, like:

```java
@final $num = 42;
```

I really don't understand. I guess that is a conflict with the silence operator.

The reason for the Hungarian notation is to avoid the phpdoc. But it could be done together, depending of preference of developer.

**Comment by kalessil** [comment]
There were no RFC yet for final variables, but I think we are going to see such RFC in near future =)

**Comment by Fleshgrinder** [comment]
Annotations where discussed ad infinitum but no conclusion could be found, too many opinions and hard to implement.

Are you creating one @kalessil?

**Comment by davidmpaz** [comment]
For the time being, I give +1 to annotations. I also think Hungarian notation will make no good. PHP has more type safety now. As @kalessil said RFC for this, as well as for real Polymorphismus or others related to typing should not be far away.

@Fleshgrinder with:

> this also stopped the work on the immutable data class RFC

did you mean this one? https://wiki.php.net/rfc/immutability, if not, can you share the link?

With annotations, something like:
```
/** @final */
$num = 42
```
Adds more code that sometimes just look ugly to see even in a local variable usage; but compromise should be made if is desired such checking in code. 

Regarding what annotation to use I really don't have any idea what to use, `@final` looks as good as any other to me.

**Comment by Fleshgrinder** [comment]
@davidmpaz that's exactly the one I referred to, yes.

**Comment by kalessil** [comment]
@Fleshgrinder: nope =)
