### ISSUE TITLE
Quick-fix for SenselessCommaInArrayDefinitionInspection

### ISSUE THREAD

**Issue by njohansson** [kalessil/phpinspectionsea#368]
I'm not sure if there's a reason why inspection [SenselessCommaInArrayDefinitionInspection ](https://github.com/kalessil/phpinspectionsea/blob/master/src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/codeSmell/SenselessCommaInArrayDefinitionInspector.java) does not have a Quick-fix?

I'm working on a project where I'd like to replace hundreds of such occurrences to make code style consistent but it's quite tedious doing it manually so a quick-fix would have been very handy! :)

**Comment by rentalhost** [comment]
No special reason. I will work on that.

**Comment by rentalhost** [comment]
- **Closing reason:** fixed on PR #369
- Dropping milestone (_moved to reference PR_).
