### ISSUE TITLE
AutoloadingIssuesInspector: ignore if namespace is not declared

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#372]
It we are not declaring a namespace, I think that we can ignore this inspection. Or then we can make it optional (new option).

**Real world usage:** on Laravel we have a feature called "migrations", that are global classes (_without namespace_) that runs only over specific cases (when we run `php artisan migrate:*`). The problem is that it requires that the file be called like "<date>_<classname>.php" (eg. "2017_06_29_000000_Version000100.php" for `Version000100` class).

**Comment by kalessil** [comment]
@rentalhost: is the `\d{4}_\d{2}_\d{2}_\d{6}_Version\d+_.php` consistent pattern for migration file naming or variations are possible?

**Comment by rentalhost** [comment]
It should be like: `(\d{4}_\d{2}_\d{2}_\d{6})_(.+)_.php`. 

But it is very related to Laravel migration, and I guess that EA should not care about that directly. Then the best option is the possibility to ignore this inspection if you are not using namespace (that is, PSR-0).

A bit more complicated option, that I really don't think needly, is create a customization list to you write regular expression with exceptions like that. Then I could write like: `\d{4}_\d{2}_\d{2}_\d{6}_(.+)` where the group `$1` determines the file class name.

**Comment by kalessil** [comment]
Laravel is Laravel... The easiest way is for the inspection to skip files with this pattern.

Regarding the original request: we have e.g. PhpUnit test cases which often not in any NS.

**Comment by kalessil** [comment]
Fixed (no binary this time).

**Comment by rentalhost** [comment]
Oh, sorry by reliving this topic... But just now I have remembered that you have fixed that, but actually it doesn't works like the expected. The pattern considered (_that works, anyway_) was:

    \d{4}_\d{2}_\d{2}_\d{6}_.+_.php

But just now I have noted that it have an underline on end of filename, and it is incorrect. The correct should be that:

    \d{4}_\d{2}_\d{2}_\d{6}_.+.php

And I have checked that it was my fault. So, sorry. :smiley:

**Comment by kalessil** [comment]
So, I need to revert the change 3932202 ?

**Comment by rentalhost** [comment]
**No!**

It works as expected, except that it expects an _underline_ on end of filename that not exists actually.

- `2017_12_14_162100_Table.php` (correct way, without underline on end, but do not works)
- `2017_12_14_162100_Table_.php` (it works now, and should keeping working)

**Comment by kalessil** [comment]
Ok,got it now =)

**Comment by kalessil** [comment]
Done
