### ISSUE TITLE
Suggests defining return type hints ': void' - probably bug

### ISSUE THREAD

**Issue by ganchclub** [kalessil/phpinspectionsea#375]
': void' can be declared as return type hint.'
Suggests defining return type hints (incl. nullable types when language level supports them)

It happens when array is received from json_decode() function. 
![void_return_type_error](https://user-images.githubusercontent.com/7393570/27781217-aa731180-5fd5-11e7-968c-60972b256332.png)

**Comment by kalessil** [comment]
Good catch @ganchclub, we shouldn't suggest anything at all in this case.

**Comment by ganchclub** [comment]
right!

**Comment by kalessil** [comment]
Fixed
