### ISSUE TITLE
Proposal: predict undefined offset errors

### ISSUE THREAD

**Issue by b1rdex** [kalessil/phpinspectionsea#379]
I propose to add warning for unchecked array access as it can produce runtime errors.

Example:
```php
$a = ['foo' => 'bar', 'baz' => 'foo'];

$c = 'some key';
$b = $a[$c];
```

It'd be great to warn `$a[$c]` place as it can produce offset access error.
Expressions like `$var[$key] ?? null` (or any other expression after `??`) should be ignored.
Flow with `isset` or `array_key_exists` before access should be ignored too.
I'm not sure, but I think that such access to `ArrayAccess` implementors should be ignored too, as behavior is controlled by implementation (silent `null` return or some default value or some exception).

I think this should be also disabled for exact string/position access like `$var['key']` or `$var[2]`, as it's very common usage for configs.

**Comment by kalessil** [comment]
I got an idea what do you mean, makes sense. Do you have any OSS references, so I could put proper priorities when planning releases?

**Comment by dryabov** [comment]
Maybe it's necessary to check that the array is not changed by a function, because of above mentioned case is quite rare, in most cases it looks like
```php
$config = ['few' => 'default', 'values' => 'here'];
overrideByUserConfig($config);
$value = $config['key']; // it's impossible to say is 'key' presented in $config
```
but it's not clear is it "bad" code or not.

IMHO (in support of @b1rdex idea), if all array's keys are known initially, it's better to create a `class` instead, and `array` type should be used for arrays and maps only<sup>[1](#ftn1)</sup>. So, in the case of array access with integer key there is nothing to warn, and in the case of "map" access with string key, it seems to be reasonable to warn if access is not pre-checked with corresponding `isset` or `array_key_exists` call.

<a name="ftn1"><sup>1</sup></a> Moreover, I'd add an inspection to found mixed usage of integer and string keys.

**Comment by rentalhost** [comment]
I think that arrays on PHP is misused. Array can represents two types of data: generic lists (like `['orange', 'banana', 'apple']`) or generic hashes map (like `´['orange' => 5, 'banana' => 2, 'apple' => 10]`, where we don't know "_which are each fruit_").

When you use an array as an object, you are misusing this, once that you know the possible keys. In this case, is important you replace it with an object container, like the `Fluent` on Laravel, for instance. Then you can annotate it with `@property` or even with `public $properties`. Then you can just check if it is not null, like `$object->foo !== null`. It will not fail in any case.

**Comment by kalessil** [comment]
I recently evaluated this case, unfortunately our tooling is not good enough -  the PHP arrays API is totally unfriendly to SCA...

**Comment by b1rdex** [comment]
Well actually I think my original issue was misunderstood.
I proposed to add inspection to find places where array accessed by key in variable but not to read code and find what keys are actually present (that's done by phpstorm partly, as it does complete known keys).
So `$foo['some key']` should not be reported but `$foo[$variableKey]` should.

But anyway issue is too wide so I'm ok that it's closed.

**Comment by b1rdex** [comment]
I'm actually not sure. Without ability to read code and get knowledge of array keys there will be too many false positives. Even code
```
$result = [];
foreach ($foo as $bar) {
    $result[] = $bar;
}
$result[0];
```
should be reported as we can't guarantee that key `0` is present.

**Comment by kalessil** [comment]
Understood. Yes, that would be plenty of false-positives (also PhpStorm array structures information is not available to us).
