### ISSUE TITLE
BadExceptionsProcessingInspection, ThrowRawExceptionInspection: enhancements needed

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#383]
- [x] an exception is thrown without arguments (ThrowRawExceptionInspection);
- [x] the catch block is not utilizing the caught exception (BadExceptionsProcessingInspection);

**Comment by Azaret** [comment]
Hi, would it be possible to split `RawException` from `NoArguments`?  
I use specific exception with normalized messages so I'm cool with not using `\Exception` but many times the normalized message from the exception is enough.  
So I would like to turn the `NoArguments` message off.  
Or please enlight me if I'm wrong about this.

**Comment by kalessil** [comment]
@Azaret : makes sense, I created a ticket for this - #390
