### ISSUE TITLE
ThrowRawExceptionInspection: add options

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#390]

**Comment by afoeder** [comment]
I have an addition BTW; what making this warning about a lacking exception message only when it's a "core" exception; IMO custom exceptions don't always need a message: `InvalidEmailAddressGivenException` for example. WDYT?

**Comment by kalessil** [comment]
@afoeder, I agree. The #405 is probably the case which is a criterion for reporting exceptions such as `InvalidEmailAddressGivenException`

**Comment by kalessil** [comment]
Fixed in 7f125722a4c8d4605928e0541c972771ea2a4c5e
