### ISSUE TITLE
Security advisories: option to manage dev-packages list

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#395]

**Comment by rentalhost** [comment]
Working on it and some plus.

**Comment by kalessil** [comment]
Great, since I'm at vacation next 2 weeks go ahead with merging this PR and test it drive in your environment. Other PRs have to wait when I'm back as probably we'll need to make 3.8.9.2

**Comment by rentalhost** [comment]
**Closing:** PR #446
Moving the milestone to this PR.
