### ISSUE TITLE
Invalid Suspicious Ternary Operator Warning

### ISSUE THREAD

**Issue by iakoder** [kalessil/phpinspectionsea#396]
`$x == 0 ? 0 : $x` reports "_Can be replaced with '0'_".  

Two things are wrong with the suggestion: 
1. if anything it would be replaced by $x; but 
2. with the weak comparison operator this is a reasonable way to convert falsey values to 0 so it shouldn't even be suggested in this case.

> PHP | Php Inspections (EA Extended) | Confusing constructs | Suspicious ternary operator

**Comment by funivan** [comment]
Why you are comparing $x with 0 i mean `$x==0` ?

**Comment by kalessil** [comment]
@iakoder, right the message should say offer using `$x`.

Regarding weak comparison, I'll make additional research.

**Comment by kalessil** [comment]
@funivan : this construct appears from time to time in projects - mostly around isolated legacy codebases with weak type control. Necessary evil...
