### ISSUE TITLE
\StdClass method implmentations

### ISSUE THREAD

**Issue by DarkMukke** [kalessil/phpinspectionsea#403]
The inspector gives an error when 
```
$obj = new \StdClass;
$bool = isset($obj->var);
```

Because it does not know the methods of \StdClass

Maybe it is best to suggest using `property_exists()` on \StdClass anyway
Although when combining `property_exists()` and `null !== $obj->var`,
`isset()` is probably cheaper

**Comment by kalessil** [comment]
Thanks for reporting @DarkMukke, what message is shown in this case?

**Comment by funivan** [comment]
@kalessil maby i can help. 
`\StdClass needs to implement __isset to properly work here.`
But when i change code:
```php
      $obj = new \stdClass;
      $bool = isset($obj->var);
```
message is gone.

**Comment by funivan** [comment]
probably the bug is here:

https://github.com/kalessil/phpinspectionsea/blob/1e5fa604b91976e0cc946405b7f02c6f322ad330/src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/semanticalAnalysis/classes/MissingIssetImplementationInspector.java#L33

**Comment by kalessil** [comment]
Oh I see, yep seems to be the case - will add class resolving then

**Comment by DarkMukke** [comment]
Great work, Will this fix solve all the case sentive issues on build in classes ?

**Comment by kalessil** [comment]
@DarkMukke : yep, cases-sensitivity is no longer a thing here.
