### ISSUE TITLE
Control flow: array initialization flaws

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#408]
```php
/* => $array = [...]; */
$array = [];
$array[] = ...;
```

**Comment by kalessil** [comment]
Oh, fuck it

**Comment by rentalhost** [comment]
Whats happened here? 
I don't understand what you want to get here.

**Comment by kalessil** [comment]
Idea was to have init-instruction instead of init+push. The last comment: just tired, and getting drunk =)

**Comment by rentalhost** [comment]
Haha, no problem!

It should works like (original code):

```php
$arr = [];
$arr[] = 1;
$arr[] = 2;
$arr[] = 3;
```

To: (?)

```php
$arr = [1, 2, 3];
```

If yes, it is a good idea. Maybe you can reopen it and move to milestone _2.3.+_ and back to it on future.
