### ISSUE TITLE
Unnecessary parentheses fixer, missing space (cosmetic issue)

### ISSUE THREAD

**Issue by bcremer** [kalessil/phpinspectionsea#410]
Given the following code snippet:

```php
<?php
$clone = clone($object);
```

The Code Style -> "Unnecessary parentheses" warning shows up (as excpected).

When using the "Remove the brackets" quickfix  the following output is generated:

```php
<?php
$clone = clone$object;
```

The following output would be preferred:

```php
<?php
$clone = clone $object;
```

This is perfectly valid code so it's just an cosmetic issue.

**Comment by kalessil** [comment]
Strange that PS doesn't re-format result expression.
I'll fix this on our side, thanks for reporting!

**Comment by kalessil** [comment]
Fixed, fresh binary pushed.

PS: just noticed Twitter notification, will answer today.tomorrow morning.
