### ISSUE TITLE
Warning when fopen binary mode is used wrong

### ISSUE THREAD

**Issue by zf2timo** [kalessil/phpinspectionsea#412]
Hello,

what do you think about an inspection for the `fopen` function, when the binary operator is used incorrectly.
I followed the Tip to add the binary operator, but used it wrong: `fopen($filename, 'bw+');` Of course, the binary flag has to be at the end. 
This is not checked by PHP Inspections EA and i received the Warning 
`PHP Warning:  fopen(basketList.csv): failed to open stream: Success in generate.php on line 34`

So it would be really nice, when PHP Inspections EA would show a warning, if the binary mode is used wrong.

**Comment by kalessil** [comment]
Thank you for reporting @zf2timo. Nice catch, we'll report this case =)

**Comment by kalessil** [comment]
Done, ETA for the next release is the end of the next week.

**Comment by zf2timo** [comment]
Wow, that's awesome how fast you implemented that feature.

Thank you.
