### ISSUE TITLE
Security advisories on package.json not working as expected

### ISSUE THREAD

**Issue by tarlepp** [kalessil/phpinspectionsea#414]
my `package.json` contains `roave/security-advisories` package, but still this telling me to add that.

![image](https://user-images.githubusercontent.com/595561/28500531-9aa1639e-6fd2-11e7-892d-c910dcaee465.png)

**Comment by kalessil** [comment]
Thank you for reporting @tarlepp, this has been fixed already: #398.
Next weekends we'll make a new release already =)
