### ISSUE TITLE
New pattern: one-time use variable [aggressive behaviour, also fors' inits definition]

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#415]
```php
$variable = <expression>;
while ($variable) { /* but not $variable comparison expression */
    ...
    $variable = <same expression>;
}
```
replace with
```php
while ($variable = <expression>) {
    ...
}
```

**Comment by bram123** [comment]
This does go against "PHP | Probable bugs | Assignment in condition".
Possible to active this pattern based on that inspection's setting?

**Comment by kalessil** [comment]
Nope, we'll need just to generate suppression then with our QF.

**Comment by davidmpaz** [comment]
What does it means:
>Nope, we'll need just to generate suppression then with our QF.

How will it works?

Point aside. My personal experience is that I found my self often braking apart very long (spaghetti like) conditions in those `while`, even if I repeat them inside the loop, just for the sake of readability.

From the point of view of performance I don't know whether we gain something though.

I would use it only for simple conditions, fitting in one line of code (~80 chars) for example.

**Comment by bestform** [comment]
I don't think it is a good idea to use an assignment in this condition. Depending on the expression, it will make the code harder to read. And every developer who is used to avoid assignments in condition will inevitably stumble upon this code and question it.

**Comment by kalessil** [comment]
@davidmpaz 

```php
/* @noinspection <Assignment-in-condition-inspection> */
while ($variable = <expression>) {
    ...
}
```

The inspection would be very questionable, Twitter poll is 50-50 pro and cons as well.
We gaining no performance, but dropping 2 lines of code and introducing assignment in a condition.

**Comment by kalessil** [comment]
@bestform: I agree and tempted at the same time. If my Twitter poll keeps being biased, we'll probably skip this.

**Comment by davidmpaz** [comment]
Ok got it. Voted already :)

**Comment by Ocramius** [comment]
Looks good to me 👍

**Comment by drealecs** [comment]
The only bad thing is when the variable has other assignments in the while loop.

**Comment by kalessil** [comment]
Right @drealecs, this noted down now ^_^

**Comment by rentalhost** [comment]
I prefer that it be done inside the own looping (maybe cost performance, but it more clear).

```php
while (true) {
    $variable = <expression>;

    if (!$variable) {
        break;
    }
}
```

**Comment by kalessil** [comment]
@rentalhost : this one is super-controversial =)

**Comment by kalessil** [comment]
So, we collected pretty much feedback and it's pretty controversial =)
We'll introduce a new setting: "Aggressive inlining (while, foreach)" disabled by default.

**Comment by rentalhost** [comment]
I know, but it avoid the _assignment-as-expression_ that sounds bad for me, and turn more hard identify a cause of a problem, once that you could confuses about `=` and `==`.

**Comment by kalessil** [comment]
@rentalhost, fully understandable =)

**Comment by kalessil** [comment]
Marking 2.3.10 to review twitter poll results.
