### ISSUE TITLE
New inspection: instanceof precedence

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#417]
It should warn about codes like `!$a instanceof B`.

It should be: `!($a instanceof B)`;
Quick-fix should help on that.

**Comment by kalessil** [comment]
The case with `!` and `instanceof` doesn't have any precedence issues, instanceof has higher priority so adding spaces/parenthesises makes no difference =)

**Comment by rentalhost** [comment]
Oh, you are right. It seems to be truth only for Java (that was my basis). :D

Then in this case, I could suggests that parentheses could be dropped.
