### ISSUE TITLE
Regex: new pattern

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#419]
`preg_match('/.../', strtolower|strtoupper(...))`
- use i-modifier (less memory allocations, less GCing and better overall performance)
- if i-modifier presented, we don't need any case manipulation
- if we have mb_str* then we should use iu modifier

**Comment by funivan** [comment]
if we have `mb_str*` then we should use `iu` modifier ;)

**Comment by kalessil** [comment]
Good idea =)
