### ISSUE TITLE
Missing inspection on overridden method return type

### ISSUE THREAD

**Issue by iakoder** [kalessil/phpinspectionsea#422]
Shouldn't there be some inspection somewhere that complains that the overridden FooBar::aMethod should return the same type as  Foo::aMethod?

class Foo {
    /**
      * @return Foo
      */
    protected  function aMethod() {
        return this;
    }
}

class FooBar extends Foo {
    /*
     * @return void
     */
    protected function aMethod() {
    }
}

**Comment by kalessil** [comment]
Than you you for proposal, @iakoder.

If return types being declared: aMethod(): Foo`` and `aMethod(): void` PS should report it. But annotations are not a reliable source for SCA, and I understand your idea correctly we can only speak about code style - PhpDoc defects (at least as I see this).

Do I understand correctly?

**Comment by iakoder** [comment]
I was only talking about defects in the PhpDoc.  As you say they're unreliable but the more checking we can do the more accurate they become.  If someone is happy with having bad PhpDoc then they don't need to inspect it.  If someone is trying to clean up their PhpDoc then having as many inspections as possible is a good thing.

Inspections on the declared return type would be good but wouldn't help us out right now because we're on a PHP 5.6 code base that is first trying to get our PhpDoc complete and accurate as a step on the path to PHP 7.1 compatibility.

**Comment by kalessil** [comment]
Getting back to this @iakoder, did you have real production issues with this or that's something that should support future migration to PHP7?

**Comment by iakoder** [comment]
We are in the process of cleaning up our codebase to move to PHP 7.1 in production.  We are looking for missing parameters to functions/methods and strings being used as arrays.  We are looking to PHPDoc to help us find them through static analysis rather than QA hunting them down one-by-one.  This example was pulled from our codebase.  If PhpStorm can't ensure that overridden methods don't return type-compatible values how can we ever know that calls to the returned methods are correct?

**Comment by kalessil** [comment]
Well, free of charge consulting tip: 
- use this https://github.com/dunglas/phpdoc-to-typehint and 
- inspect PS on the result - it'll spot incorrectly PhpDocs

And that's it + Php Inspections (EA Inspections) is more useful with type-hinted codebases.

**Comment by kalessil** [comment]
Since the goal is clear and can be archived with other OSS tools, closing the issue.

**Comment by iakoder** [comment]
Thanks.  Type-hinting is not an option until we can migrate to PHP 7, we're currently still at 5.6.  So we were hoping to be able to use PHPDoc instead of type hints to get us directly to 7.1.

**Comment by kalessil** [comment]
I see, what I suggested is to create a separate branch where the type hints will be applied, so PS can find parameters/return type hint issues and fix PhpDoc in Php 5.6 branch. Couple iterations and you are there.
