### ISSUE TITLE
ForgottenDebugOutputInspector: Laravel debug functions

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#423]
Hey guys, can you make me a favor and add laravel debug functions (I recall it was a `dd` function/method, but it's probably more of them).

**Comment by rentalhost** [comment]
Laravel have `dd()` (_dump and die_) and `dump()` (_just dump_). Both are used for debug. Do want a PR or just this info?

**Comment by kalessil** [comment]
Yes, please =)

**Comment by rentalhost** [comment]
Done at #427 for Laravel debug helpers. 

---

I have noted that it seems to supports some static methods like `\Codeception\Util\Debug::pause()`, but it seems not be working.

**Comment by kalessil** [comment]
Thanks @rentalhost !

It's not static methods - it's Fully Qualified Name notation, to register debug methods.
