### ISSUE TITLE
False/positive maybe ? elseif not needed with default return

### ISSUE THREAD

**Issue by DarkMukke** [kalessil/phpinspectionsea#426]
```php
<?php

namespace Testapp;

class Mock
{
    const FOO = 'foo';
    const BAR = 'bar';
    public static function stub($type)
    {
        if ($type === static::FOO) {
            return [
                1,
                2,
                3
            ];
        } elseif ($type === static::BAR) {
            return [
                4,
                5,
                6
            ];
        }
        return [];
    }
}
```

results in 
![image](https://user-images.githubusercontent.com/1083860/28715306-2ea12362-738f-11e7-8703-5b89b377fe87.png)

**Comment by kalessil** [comment]
@DarkMukke : that's correct - click Alt+Enter and apply the quick-fix to see what it suggests to do =)

**Comment by kalessil** [comment]
Or check this out: https://github.com/bitExpert/disco/pull/104/files#diff-4bbb70a090cf24b4220e053467ff9fe0

**Comment by kalessil** [comment]
I get used to closing tickets to keep focus, but discussions can be continued anyway - will be glad to support =)

**Comment by DarkMukke** [comment]
How is that correct ?

`Testapp\Mock::Stub( 'foo' )` should return `[1,2,3]`
`Testapp\Mock::Stub( 'bar' )` should return `[4,5,6]`
`Testapp\Mock::Stub( 'anythingELSE' )` should return `[]`

with an else that would be 

`Testapp\Mock::Stub( 'anythingELSE' )` returning `[4,5,6]`

**Comment by DarkMukke** [comment]
ok so it suggests

```php

    public static function stub($type)
    {
        if ($type === static::FOO) {
            return [
                1,
                2,
                3
            ];
        }

        if ($type === static::BAR) {
            return [
                4,
                5,
                6
            ];
        }

        return [];

    }
```

which is not cheaper, in fact it is more expensive without a return
So why would it suggest that in the first place
I've always know an elseif being the coding standard over multiple if's

**Comment by kalessil** [comment]
Proof: https://3v4l.org/5XV25

The point which makes difference is return (same for throw-statement) - it changes how the workflow behaves.

If return is not there, e.g.:
```php
class Mock
{
    const FOO = 'foo';
    const BAR = 'bar';

    public static function stub($type) {
        /** compact view, not a recommended code style */
        $result = [];
        if ($type === static::FOO) { $result = [1, 2, 3]; }
        if ($type === static::BAR) { $result = [4, 5, 6]; }
        return $result;
    }
}
```
then it'll be as you said - elseifs are makeng it's job.

**Comment by kalessil** [comment]
Here the 2nd snippet proof: https://3v4l.org/BMddt - results are the same

**Comment by DarkMukke** [comment]
You are right, my apologies

Adding in screenshots for the time differences and future reference
The suggested solution, multiple if
![image](https://user-images.githubusercontent.com/1083860/28716513-9cc710a8-7395-11e7-9374-f2381c23ca9c.png)

My original query, if elseif chain
![image](https://user-images.githubusercontent.com/1083860/28716524-b70ae700-7395-11e7-860b-37215b65a7b3.png)

**Comment by kalessil** [comment]
No worries =) Thanks for the reference!

BTW, what is the tool you used for measurements?

**Comment by DarkMukke** [comment]
https://3v4l.org/ but i have Dark Reader chrome plugin so it might look a bit different

**Comment by kalessil** [comment]
Oh, I recognize now. Thanks!

**Comment by DarkMukke** [comment]
Oh and a colleague also mentioned switch case https://3v4l.org/DWH8T/perf#output
```php
    public static function stub($type) {
        switch($type) {
            case static::FOO: return [1, 2, 3]; break;
            case static::BAR: return [4, 5, 6]; break;
            default: return [];
            
        }
    }
```
which result's sit in the middle between the 2, higher system time but lower user time and more memory
![image](https://user-images.githubusercontent.com/1083860/28717089-42b9d426-7398-11e7-8710-fd5afab2e4f3.png)

**Comment by kalessil** [comment]
This would the best solution, just one hint from me:
```php
public static function stub($type) {
        $result = [];
        switch($type) {
            case static::FOO: $result = [1, 2, 3]; break;
            case static::BAR:  $result = [4, 5, 6]; break;
            default: break;
        }
        return $result ;
    }
```
In this case better to use single return statement - clear intention regarding how mapping procedure.

**Comment by DarkMukke** [comment]
i agree, except that a default without a break is only cheaper in php 7
