### ISSUE TITLE
Internal: stop using WIP label

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#429]
Seems that the WIP label is misused here. 

I think that the concept of this label is mark the issue as "I am working on that right now" (_Work in progress_). But we currently have [6 issues](https://github.com/kalessil/phpinspectionsea/issues?q=is%3Aopen+is%3Aissue+label%3AWIP) with this label and two or three active collaborators, generally.

My suggestion is avoid this label once that it "block" the issue to a specific collaborator, but it not garantee that it is really in work - so any other collaborator can work on that. Personally I prefer tells that I am working on an issue by comment, because turn it more "personal" and make me apply more effort on it, and give a feedback if it was done or not, or if I need more time, for instance.

**Comment by kalessil** [comment]
Closing, the WIP label is dropped.
