### ISSUE TITLE
__construct is probably missing baseApp::__construct call

### ISSUE THREAD

**Issue by ArabCoders** [kalessil/phpinspectionsea#431]
```php
<?php

abstract class baseApp
{
    abstract public function __construct( array $opts );
}


class foo extends baseApp
{
    public function __construct( array $opts )
    {

    }
}
```

the example code trigger the inspect "__construct is probably missing baseApp::__construct call", in this case you cant really call parent __construct as it's abstract.

**Comment by kalessil** [comment]
Oops, thank you for reporting @ArabCoders, I'll take care of fixing this.

**Comment by ArabCoders** [comment]
@kalessil thank you for your fast reply xD
