### ISSUE TITLE
Strict comparison check suggestion: better messaging

### ISSUE THREAD

**Issue by Anyqax** [kalessil/phpinspectionsea#432]
When a variable is compared to an empty string

`$a != ''`

phpinspections suggests: 

> Safely use '!==' here.

which is wrong since e.g.

```
$a != '' // false
$a !== '' // true
```

for $a = null.

The suggestion should be analog to non strict number comparison instead:

> Please consider using more strict '!==' here (hidden types casting will not be applied anymore).

**Comment by kalessil** [comment]
Thank you for reporting @Anyqax, what does tooltip says if you click Ctrl and point to the variable with the mouse cursor?

**Comment by Anyqax** [comment]
it says "mixed", that's the phpdoc typehint from the originating function (a 3rd party library)

**Comment by kalessil** [comment]
From mixed we can not extract any useful type information, so let's try to improve message only.

**Comment by Anyqax** [comment]
The same is true when the variable is of type string.
In neither case is it safe to use strict comparison, yet a quickfix to do so is offered.
Imo the message should be changed and the quickfix removed.

**Comment by kalessil** [comment]
To stay safe people or suppressing such statements or using empty-statement, to avoid situations when bulk changes the code it shouldn't. 
I'd suggest following one of those options, we need this QF - it's used extremely often.

**Comment by kalessil** [comment]
Fixed, closing the issue.

**Comment by kalessil** [comment]
Newly fixed, this was a false-positive in fact =). See https://github.com/kalessil/phpinspectionsea/commit/99169c8f81232f28102d2aa6411b9f5a5c36f343 for details.
