### ISSUE TITLE
Broken "Use suggested refactoring" for `++`

### ISSUE THREAD

**Issue by matthiasnoback** [kalessil/phpinspectionsea#433]
The plugin suggests that

```php
$rsvpsPerAttendee[(string)$event->attendeeId()] += 1;
```

can be replaced by using `++` in front of the expression. The automatic refactoring doesn't work though, the result turns out to be:

```php
(string)$event->attendeeId();
```

The expected result should of course be:

```php
++$rsvpsPerAttendee[(string)$event->attendeeId()];
```
Even though I personally like this more:
```php
$rsvpsPerAttendee[(string)$event->attendeeId()]++;
```

**Comment by kalessil** [comment]
Oops, thank you for reporting @matthiasnoback , I'll take care of fixing the bug.

**Comment by kalessil** [comment]
@matthiasnoback: I'll probably introduce 2 separate QFes for prefix/suffix style fixing, hope it takes only minor efforts.

**Comment by matthiasnoback** [comment]
Great work!
No worries, it's not a big inconvenience ;)

**Comment by kalessil** [comment]
Fixed. I plan to release 2.3.10-preview release today including the fix + new option to configure which of prefix/suffix QFing style is preferred.
