### ISSUE TITLE
LowPerformanceArrayUniqueUsageInspection: drop

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#434]
Not relevant as in PHP 7.2 the array_unique got optimized.
See https://github.com/symfony/symfony/pull/23731 for more details.

We probably should suggest reverse refactoring for PHP 7.2+...

**Comment by kalessil** [comment]
//cc @dseguy, 
https://www.exakat.io/avoid-array_unique/: array_unique vs array_count_values seems to be not relevant since PHP 7.2. I dropping the inspection completely on my end.

**Comment by dseguy** [comment]
Hi Vladimir,

Thanks for the piece of news.
I don't know if I'm happy about this (This is definitely an improvement) or
sad (it's one of my favorite analysis, simple and obvious).

I tested it immediately, with a PHP 7.2 from July 27th, and I still have
significative different.

See it here :
https://3v4l.org/Ctfum

How did you check that on your side ?

Damien

**Comment by kalessil** [comment]
The change  (https://github.com/php/php-src/commit/6c2c7a023da4223e41fea0225c51a417fc8eb10d) is from yesterday, so it needs some time before it available on 3v4l.

I checked the commit, didn't do any proper benchmarking.

My reason to drop the inspection is the fix, which lowers benefits and not very positive feedback on using `array_count_value` instead of array_unique. And I tend to agree with the feedback.

**Comment by dseguy** [comment]
On Wed, Aug 2, 2017 at 12:14 PM, Vladimir Reznichenko <
notifications@github.com> wrote:

> The change (php/php-src@6c2c7a0
> <https://github.com/php/php-src/commit/6c2c7a023da4223e41fea0225c51a417fc8eb10d>)
> is from yesterday, so it needs some time before it available on 3v4l.
>
> I checked the commit, didn't do any proper benchmarking.
>
I see. I think I'll have to wait for thursday then. This is not in php-7.2
yet.


> My reason to drop the inspection is the fix, which lowers benefits and not
> very positive feedback on using array_count_value instead of
> array_unique. And I tend to agree with the feedback.
>
lower benefit?
I get feedback that is it ugly (indeed).

Damien.

**Comment by kalessil** [comment]
RIght, I'm pretty curious how good the optimization is =)

Lower - array_unique will be faster already, so gain in performance vs losses in readability is a thing.

**Comment by rentalhost** [comment]
If the performance difference on 7.2 could be not significant, maybe just set this inspection disabled by default, then user could choice it by heself.

**Comment by kalessil** [comment]
@rentalhost, can be an option., let's wait for benchmarking

**Comment by dseguy** [comment]
Hi all,

Compiled PHP-7.3 (aka master) :
The script I mentionned earlier now gives this (with $array of 1000) :

array_count_values : 20,473 ms

array_unique : 7,412 ms


I still don't see this on PHP 7.2-beta, but I may have compiled too early :
that will probably be included in PHP 7.2-beta next thursday (Tomorrow).

Glad to see this removed :)  Let's find another one!

Damien.

**Comment by kalessil** [comment]
I think this is in PHP 7.2-beta2. @dseguy : thanks for benchmarking!

**Comment by kalessil** [comment]
Dropped, now for PHP 7.2+ we suggesting the opposite cases (from using array_count_values to using array_unique).
