### ISSUE TITLE
Drop inspection MissingOrEmptyGroupStatementInspector

### ISSUE THREAD

**Issue by funivan** [kalessil/phpinspectionsea#435]
In the latest version of phpstorm core team implemented `Statement has empty body` inspection

https://blog.jetbrains.com/phpstorm/2017/07/new-inspections-in-phpstorm-2017-2/

Maybe we should drop our inspection.

**Comment by kalessil** [comment]
@funivan do you mean MissingOrEmptyGroupStatementInspector?
LoopWhichDoesNotLoopInspection does check other things?

I think we could exclude from MissingOrEmptyGroupStatementInspector what's covered by the inspection from PS team.

**Comment by funivan** [comment]
@kalessil yep. My bad. I mean `MissingOrEmptyGroupStatementInspector`

**Comment by kalessil** [comment]
No problems =) Yes, I think we can drop functionality covered by PS now - still something will remain I think.

**Comment by kalessil** [comment]
The match is not 1-1, we are not handling try/catch, switch blocks here. 
Hence I'm leaving the inspection, but updating warning texts to be in sync with PS.
