### ISSUE TITLE
Variable functions: dymamic vs static call (case forresearch)

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#438]
https://twitter.com/dkarlovi/status/892650051884941315

**Comment by dkarlovi** [comment]
So, to be more precise, it's suggesting to replace

```php
return \call_user_func([$class, 'build'], $params);
```

with

```php
$class->build($params);
```

but in this case `$class` is a string (a FQCN) which creates invalid PHP code.

**Comment by kalessil** [comment]
Fixed
