### ISSUE TITLE
[new] exceptions flow - @throws declaration for non-thrown exceptions

### ISSUE THREAD

**Issue by bram123** [kalessil/phpinspectionsea#44]
It would be useful to show a warning when a function/method has @throws in the docblock, but no actual Exceptions are (possibly) thrown.

This wouldn't be possible when the method is overloaded. Because a parent might want to document that a child can throw an exception.

**Comment by kalessil** [comment]
I'll pick it up for the next release.

**Comment by kalessil** [comment]
@bram123 , from your prospect, what is more important - this issue or #66 ?

**Comment by bram123** [comment]
@kalessil For us, this issue is more important.

Btw, thanks for the hard work; plugin is a great help :)

**Comment by kalessil** [comment]
@bram123 : would you please give a try to the new build (you'll need to activate the feature in the inspection settings)

You are welcome, it become very handy now as I noticed myself)

**Comment by bram123** [comment]
Just downloaded the latest version (2.2.2) from github. But I can't find the setting to enable this.

**Comment by kalessil** [comment]
That's here:
![ea-report-non-thrown](https://cloud.githubusercontent.com/assets/1577185/21256366/2959e4fc-c372-11e6-8091-d7b034489fa9.png)

**Comment by bram123** [comment]
Thanks, works great so far :)

**Comment by kalessil** [comment]
Great, have fun with new features)
