### ISSUE TITLE
Wrong inspection warning about in_array usage

### ISSUE THREAD

**Issue by Koc** [kalessil/phpinspectionsea#442]
Hi!

![default](https://user-images.githubusercontent.com/191082/28922665-c1326d8e-7863-11e7-87ae-3e22cdbb6808.png)

`array_search` result reused for `array_splice` call, so we cann't use `in_array` in this context.

**Comment by kalessil** [comment]
Thank you for reporting @Koc, I'll take care of fixing it.

**Comment by kalessil** [comment]
It seems like you discovered a priorities bug, the condition is processed as `$x = (array_search(...) !== false)`.
It's a new pattern for another inspection, but it should be like this i guess `($x = array_search('', [])) !== false`

**Comment by kalessil** [comment]
I created a follow-up ticket for reporting this pattern: #445
