### ISSUE TITLE
Provide fixers for some inspections

### ISSUE THREAD

**Issue by Koc** [kalessil/phpinspectionsea#443]
I'm hope that some warnings can be fixed automatically (`alt+enter`). But for now plugin forces us to fix code by hands. 

See https://github.com/Haehnchen/idea-php-symfony2-plugin/blob/master/src/fr/adrienbrault/idea/symfony2plugin/codeInspection/form/FormTypeAsClassConstantInspection.java for example implementation of autofixers.

**Comment by kalessil** [comment]
This is continuous work funded by on Indiegogo this year, current status is [here](https://github.com/kalessil/phpinspectionsea/blob/master/RULES.md) (QF column).

Can you list to 3 QF which could increase your team velocity please?

**Comment by kalessil** [comment]
I'm closing the issue, but looking forward for the list =)

**Comment by Koc** [comment]
1. mkdir race conditions
2. mkdir race conditions
3. mkdir race conditions
4. `is_null` -> `null === xxx`
5. castade `str_replace`

**Comment by kalessil** [comment]
xD, ok I'm back from vacation 21th August, will implement QF
- `mkdir` (100% paint point)
- cascade `str_replace`

`is_null -> null === xxx` is already fixed

**Comment by kalessil** [comment]
Reopening, so the final 2.3.10 coming with the promised fixers.

**Comment by kalessil** [comment]
Status update: cascade str_replace QF implemented (the thing was pretty complicated %) to implement), 
let see if race conditions fixes will be feasible.

**Comment by kalessil** [comment]
Note for myself: + for->foreach fixer

**Comment by kalessil** [comment]
SInce I started to work on `mkdir race conditions` fixer, closing the issue.
