### ISSUE TITLE
FP: elseif is not needed in switch

### ISSUE THREAD

**Issue by CZechBoY** [kalessil/phpinspectionsea#444]
Hi,
I have if+elseif in switch's case
```php
switch ($value)
{
    case 123:
       if ($abc === 1) {return 1234;}
       elseif ($abc === 2) {return 12345;} // error: elseif is not needed here (because of the last statement in if-branch)

       break;
}
```

but it is not true as everybody can see immediately.

**Comment by bram123** [comment]
I'm guessing the error means you can just use two IF statements instead of an IF and ELSEIF.

**Comment by kalessil** [comment]
Yep. @CZechBoY: if you put the mouse cursor on the `elseif` and press `Alt-Enter` it will be possible to apply a Quick-fix (true for the most of our inspections) and you'll see what is intended.

**Comment by kalessil** [comment]
@CZechBoY, think discussion in #426 can give some extra information about the topic, hope it helps.
