### ISSUE TITLE
Yoda style condition when fixing in_array misused

### ISSUE THREAD

**Issue by CZechBoY** [kalessil/phpinspectionsea#454]
Hi,
I have this code
```php
if (in_array($code, [1400], true)) { // error: '1400 === $code' should be used instead.
   return 'abc';
}
```
that's ok, it should be `$code === 1400`, but not in yoda style. Why not? Because there is another inspection on yoda style conditions...

**Comment by rentalhost** [comment]
Can't reproduce. 
What is your version of EA and PS?

**Comment by CZechBoY** [comment]
Newest stable PS - 2017.2.1

Dne 8. 8. 2017 7:02 odpoledne napsal uživatel "David Rodrigues" <
notifications@github.com>:

**Comment by rentalhost** [comment]
Oh, I understand it now. 
It is related to `Performance | 'in_array(...)' misused` inspection.

@kalessil Can we read a configuration of another inspection? It should be useful here, because we need check if Yoda/Regular style is in use to determine the best QF.

**Comment by kalessil** [comment]
Nope, but I'll introduce individual settings - one day we'll need to consolidate this, but easier to do it later.

**Comment by kalessil** [comment]
Added settings.

**Comment by rentalhost** [comment]
We can't use the current setting?

**Comment by kalessil** [comment]
Not yet, it should be plugin-wide settings, perhaps something can be taken from code style itself.
I didn't have time for a research how to make this setting shared.
