### ISSUE TITLE
Disable self class reference for recursive calls

### ISSUE THREAD

**Issue by SOF3** [kalessil/phpinspectionsea#455]
While some code styles avoid the use of `self`, it is reasonable to use it in recursive calls and/or private methods.

**Comment by funivan** [comment]
Hello. Can you give an example .

**Comment by SOF3** [comment]
For example, a static class method calling itself recursively or private static methods in its class can reasonably be `self` even for code styles that discourage use of `self`.
I'm therefore requesting an option to disable the `self` inspection for recursion and private static methods.

**Comment by b1rdex** [comment]
@SOF3 are you complain about 'replace `self::` calls with `static::`' inspection?

**Comment by SOF3** [comment]
@b1rdex No, I'm talking about the "Self class referencing" inspection with "Prefer class name referencing" enabled.

**Comment by kalessil** [comment]
ping @rentalhost

**Comment by rentalhost** [comment]
I don't know... The option "Prefer class name referencing" is exactly to turn clear that you prefer see the own class name on code instead of `self::class`. Can we think about it together? @funivan @kalessil @SOF3 @b1rdex

**Comment by b1rdex** [comment]
@SOF3 can you please show any OSS project with example of such code style? It looks not clear for me.

PS. https://github.com/FriendsOfPHP/PHP-CS-Fixer has AFAIK only one rule for replacing class referencing with `self` (as this plugin does): `self_accessor`.

**Comment by SOF3** [comment]
There is no large OSS projects out there using such code style, but I thought it would be reasonable to do so.

**Comment by funivan** [comment]
@SOF3 can you show some examples of your code. 
You can also suppress this inspection for specific cases. Just `Alt+Enter > Suppress inspection for statement`

p.s. Prefer to keep it as is

**Comment by SOF3** [comment]
Alright, this is probably quite personal.
