### ISSUE TITLE
FP: interface constant not found in self::MY_CONST

### ISSUE THREAD

**Issue by CZechBoY** [kalessil/phpinspectionsea#457]
Hi,
I have this code
```php
class MyClass implements IInterface
{
    public function abc()
    {
        echo self::MY_CONST;
    }
}

interface IInterface
{
    const MY_CONST = 9;
}
```
and I got this error: `Constant 'MY_CONST' not found in MyClass`

**Comment by funivan** [comment]
Hello. 
First of all this is standard inspection from PhpStorm (`Php -> Undefined -> Undefined Class constant`) ;) 
Second: can not reproduce. (Check exactly the same code)

**Comment by CZechBoY** [comment]
@funivan yes, you are right, I mislooked, it's from phpstorm. I will report to them. Thanks.
