### ISSUE TITLE
Internals: apply a default style to source code

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#458]
I like to apply a default code style to entire project source code. Basically is something that I do everytime before start to work on some inspection file, but now to all project. So we can reduce the inspection problems over project, for instance, by applying the `final` modifier where possible, normalizing the comparation style (to regular style), so on.

It will affects a lot of files (basically 99%), but should not affects the behaviour or code ordering (refactoring). The current object is just aesthetical, the next one (to future/new issue) is accept more inspection, but related to performance and some refactoring (that will be doing with new tests too).

I need some approval here to start, if you like that.

Code style/inspection profile: [settings.zip](https://github.com/kalessil/phpinspectionsea/files/1217789/settings.zip)

**Comment by funivan** [comment]
It would be better to store code style under the .git ;)

**Comment by kalessil** [comment]
+1 for sharing code style settings (but not global reformat). Now let see when I can get to this task =)

**Comment by rentalhost** [comment]
Great... I will share my current format. I have done a lot of tests to make it more clear than possible, without change too much current code style (the biggest problem is the code arrangement, but we can disable it for now). I'll push that soon.

**Comment by kalessil** [comment]
Re-evaluating. Ideally, Java has something like CS Fixer and it will not break merging into ultimate.

**Comment by ea-inspections-team** [comment]
Thanks for reporting @rentalhost and joining the discussion folks. We have to close this as this would totally break merging changes from OSS version into the Commercial one - codebases very diverged at this point.
