### ISSUE TITLE
[WIP] API from *Impl classes used

### ISSUE THREAD

**Issue by neuro159** [kalessil/phpinspectionsea#46]
Please get rid of *Impl method calls.
<img width="1396" alt="screenshot 2016-11-15 11 47 14" src="https://cloud.githubusercontent.com/assets/87308/20302934/646ad314-ab29-11e6-9106-0deddc583f35.png">

If you MISS something in corresponding interfaces, please contact us, we're actively working on improving our APIs

**Comment by kalessil** [comment]
Will do for BinaryExpressionImpl before the next release, thanks for pointing out. 

Can this be an inspection in Plugins SDK group: that would help much?

**Comment by neuro159** [comment]
Ideally we want devs to use stuff only from php-openapi.jar, but it's quite
incomplete yet. Moving stuff to public api, adding docs, publishing sources
is what I do ATM

**Comment by kalessil** [comment]
I see. 

I'll make a review for all uses of *Impl in my plugin (314 usages: imports, instanceof, tree search by *Impl and etc.) and come back to you here.

**Comment by kalessil** [comment]
@neuro159 : I worked out ~100 issues, the rest I'll work out next months (searching for a new job takes lots of time).

Would you please give me a list of priorities if something needs to be fixed ASAP?

**Comment by neuro159** [comment]
I'll try to keep binary compatibility for 2016.3 & minor updates.

2017.1 EAP starts in a month, I'll notify you of any incompatible changes.

**Comment by neuro159** [comment]
Have you ever considered working for us?) give me a Skype call)

**Comment by kalessil** [comment]
Didn't cross my mind yet and sounds interesting. Will tomorrow at 15:00 of German time work for you?

**Comment by neuro159** [comment]
Yep!

**Comment by kalessil** [comment]
Great, hear you tomorrow then.

**Comment by kalessil** [comment]
Closing, the upcoming 2.3.10 release drops allcom.jetbrains.php.lang.psi.elements.impl.* dependencies.
Thanks again for pointing out the issue.
