### ISSUE TITLE
Unnecessary doubles quotes severity don't change

### ISSUE THREAD

**Issue by nlhommet** [kalessil/phpinspectionsea#465]
When I change the severity of unnecessary doubles quotes, its stay in weak warning.
The change take effect in settings but not in code.
![issue](https://user-images.githubusercontent.com/15359336/29272541-c9ee0014-8100-11e7-995d-39aeb51baa30.png)

**Comment by funivan** [comment]
Thanks for the report. We will try to fix it.

**Comment by kalessil** [comment]
My bad, will fix this. Thank you for reporting @nlhommet !

**Comment by kalessil** [comment]
Fixed, closing the issue.

**Comment by rentalhost** [comment]
@kalessil By this fix, I think we should do it in all inspections, right? I mean, drop the `ProblemHighlightType.WEAK_ERROR` and similar.

**Comment by kalessil** [comment]
Nope =) There are inspections with multiple reporting levels - I doing needed fixes regularly when touching inspections code.

**Comment by funivan** [comment]
@kalessil maybe for all inspections that has one reporting level we can do this?

**Comment by kalessil** [comment]
Sure, I'll add corresponding checks to our CI pipeline.
