### ISSUE TITLE
[bug] foreach source/offset validity - ignore boolean in resolved types

### ISSUE THREAD

**Issue by harley84** [kalessil/phpinspectionsea#47]
There's a false positive in a following case:
We have a function that with this signature:

    /**
	 * executes a query in the system database
	 *
	 * @param string $query The SQL query to executes
	 * @param string $comment An optional comment explaining the query
	 *
	 * @return array|bool The result set on success, or false on error
	 */
	public static function runSingleQuery($query, $comment = '') {...}

Notice the array|bool return value.

Then when we execute the function:

        $result = SystemDatabaseManager::runSingleQuery(...);

        if ($result === false) {
            ...
            return $accountProfiles;
        } else {
            foreach ($result as $record) {
             ... 
             }
        }

In this case the inspection fires "Can't iterate bool (recheck type hints)" even though bool is not the only possible returned value type.

**Comment by kalessil** [comment]
Probably caused by https://youtrack.jetbrains.com/issue/WI-20196, but I'll just ignore booleans for in the inspections: no harm, less warnings, less support.

**Comment by kalessil** [comment]
@harley84 : I also pushed a fresh binary (in case if you;d want to give it a try).
