### ISSUE TITLE
Add `simplexml_load_file()` to the big list of PHP bullshittery that nobody should use

### ISSUE THREAD

**Issue by Ocramius** [kalessil/phpinspectionsea#471]
Ref: https://bugs.php.net/bug.php?id=62577
Ref: https://github.com/doctrine/doctrine2/issues/3788#issuecomment-323343537
Ref: https://github.com/doctrine/doctrine2/pull/6633

**Comment by kalessil** [comment]
Oh my, PHP is an endless source of fun.
Will implement this with corresponding QF.

**Comment by kalessil** [comment]
Implemented, closing the issue.
