### ISSUE TITLE
Integrate with sentry.io

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#476]
[Sentry.io](https://sentry.io/) is an exception handler that stores all exceptions cases online to be checked by the developer. It should works better than manual reporting, once that it is send automatically on exception.

I am using it with Laravel and works pretty. And the free tier is very flexible and full featured. I just don't know how we can capture all exception on Java. I hope that Jetbrains API have some kind of support to it, but I can't found on a fast research.

My suggestion is make it possible on next release.

**Comment by kalessil** [comment]
Hi again =)

We can only hook into reporting dialog, providing direct reporting to the sentry.
I didn't find how to hook into IDE exceptions handling, but sentry documentation gave me couple ideas to try.

**Comment by rentalhost** [comment]
Now back to activity? :D 

The reporting dialog should works fine. Could it be done automatically, without user press "send report"? It will be helpful.

**Comment by kalessil** [comment]
Yep, but in reduced mode - pretty much personal stuff is pending as well.

Hope so, question is when I have time for experiments xD

**Comment by kalessil** [comment]
Implemented, but on top of Google Analytics which we use already.

**Comment by kalessil** [comment]
Works nicely: 
![image](https://user-images.githubusercontent.com/1577185/30252332-d7a0e516-9670-11e7-8195-a80b459f03b9.png)
