### ISSUE TITLE
False positive: Exception with default message

### ISSUE THREAD

**Issue by Anyqax** [kalessil/phpinspectionsea#477]
```
class CustomException extends \Exception
{
    protected $message = 'CustomExceptionMessage';
}
```

Throwing this exception without a constructor argument, triggers the warning "This exception is thrown without a message. Consider adding one to help clarify or troubleshoot the exception.".

**Comment by kalessil** [comment]
Didn;t see this approach for some time already )
Thank you for reporting @Anyqax, I'll take care of fixing this.

**Comment by kalessil** [comment]
Fixed, closing this.
