### ISSUE TITLE
Unnecessary doubles quotes error message is not the correct one 

### ISSUE THREAD

**Issue by nlhommet** [kalessil/phpinspectionsea#483]
The error message is "Please consider using more strict '!==' here" instead of "Safely use single quotes instead."
![issue2](https://user-images.githubusercontent.com/15359336/29659520-e0981f78-88be-11e7-8216-ef22fdf0f4b6.png)

**Comment by kalessil** [comment]
Oh my, thank you for hands on @nlhommet .

**Comment by rentalhost** [comment]
Cross referencing: #432

**Comment by kalessil** [comment]
Right, thank you for cross-referencing @rentalhost
