### ISSUE TITLE
Architecture: single responsibility violation (Boolean parameters)

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#484]
Criteria: methods with 2+ parameters.

**Comment by rentalhost** [comment]
Seems that it is already implemented by Jetbrains:

- PHP | Code Smell | Too many parameters in function declaration

![image](https://user-images.githubusercontent.com/421851/65178020-44416d00-da2e-11e9-88b9-17001eebd4f5.png)
