### ISSUE TITLE
More options for Exceptions handling and annotating

### ISSUE THREAD

**Issue by GrandLTU** [kalessil/phpinspectionsea#485]
It would be very nice if this inspection had ability to ignore `\RuntimeException` and/or `\LogicException` and their descendants.

PhpStorm already has such configuration `Editor > Code Style > PHP > PhpDoc > @throws Tag Analysis` but the this inspection highlights only phpdoc section without hinting where or which exception is thrown

**Comment by kalessil** [comment]
Thank you for the proposal @GrandLTU, this should be covered by #354.
