### ISSUE TITLE
Field declared dynamically

### ISSUE THREAD

**Issue by SkLight** [kalessil/phpinspectionsea#486]
```php
trait CreatedAtTrait
{
    private $createdAt;
    ...
}
```
http://joxi.ru/82QYNX0fjz7pe2

**Comment by kalessil** [comment]
Thank you for the report @SkLight, unfortunately this is coming from the IDE itself.
Please report directly to JetBrains team: https://youtrack.jetbrains.com/issues/WI

**Comment by SkLight** [comment]
Oh... sorry. Did not notice when exactly the problem appeared. PhpStorm was updated a long time ago and it seemed to me that the problem appeared after the plug-in was updated.
Thank you)

**Comment by kalessil** [comment]
No problems, hopefully, PS update will solve the issue.
