### ISSUE TITLE
Single-quote <--> double-quote tipp show wrong hint

### ISSUE THREAD

**Issue by dpauli** [kalessil/phpinspectionsea#487]
If there is a hint to replace double quote with single quote there is the wrong hint shown. I see the hint:

**Please consider using '!==' more strict here**.

![wrong_error](https://user-images.githubusercontent.com/10072693/29716414-9ce9b578-89ab-11e7-82d3-0fbe2f7e9345.png)

**Comment by kalessil** [comment]
Hi @dpauli, thank you for reporting. We have fixed this already in #483 - the next release will contain the fix.
