### ISSUE TITLE
Patronage call to action: rework the text (+PayPal, more neutral wording)

### ISSUE THREAD

**Issue by michabbb** [kalessil/phpinspectionsea#488]
hi, i really like your project, and i am willing to donate you, but not every month, and the numbers of patrons tell me, i am not the only one with this. so if you add an option to donate your work, i am happy todo, but not with this patorn system, sorry.

GREAT WORK !!!
THANKS !!!!

**Comment by kalessil** [comment]
Hi @michabbb, thank you, hope the project makes you life easier =)

Fully understand your position, it's difficult to keep track on such things (BTW on Patreon you can specify for how long you want to stay a patron - months, half-year or year). 

We have a donation option via PayPal (https://www.paypal.me/VReznichenko), plus at Christmass time I share a wish list on Amazon.

BTW, what do you think about Supporter Licenses (just an idea ATM): https://twitter.com/kalessil/status/901377497123762176 ?

**Comment by kalessil** [comment]
And for sure, I'll rework the message to  be more neutral and to mention PayPal.

**Comment by michabbb** [comment]
@kalessil so how should this license look like? Maybe a fee for one year, because people are used to this time frames because of the phpstorm license... I cannot speak for others, but in my opinion I would say, that 40-50EUR by year would be extremely fair.

**Comment by michabbb** [comment]
Btw.. I made my donation 😁

**Comment by kalessil** [comment]
@michabbb : the donation has arrived, thank you!

The common idea for Supporter License is to give an easy way for Self-Employed People and Companies supporting the project. Payment page with Silver/Gold/Platinum license types + invoices, printable licenses are something I can image as of now.

**Comment by michabbb** [comment]
@kalessil maybe you can add sponsors at the popup inside phpstorm, like you do with your patron note. and a place inside your readme with a very short infos, what the sponsor is doing and howto contact him. i know, this has nothing todo with a licence, but maybe this is something you can run in parallel. anyway, an invoice is always welcome for people who are running a business, no question....

**Comment by kalessil** [comment]
@michabbb : we have already something like sponsors list (https://github.com/kalessil/phpinspectionsea#acknowledgments). 

And according to the poll, we have to go with Licensing (bills and so on, I think we can fit this year already).

PS: I update the update message, looks not so pushy now.
