### ISSUE TITLE
is_array($var) === false triggers expressions' type was not recognized

### ISSUE THREAD

**Issue by hansott** [kalessil/phpinspectionsea#496]
```php
final class SomeClass {
  protected function _processBatch($batch) {
    if (is_array($batch) === false) {
      return;
    }

    foreach ($batch as $event) {
      //    ^^^^^^^ expressions' type was not recognized, please check type-hints.
    }  
  }
}
```

`if (!is_array($batch)) { ... }` seems to works.

I guess `resolveExpressionType` does not resolve `=== false` expressions?

https://github.com/kalessil/phpinspectionsea/blob/66aaa8d479d16044c938fd75b83a9b60f0079b21/src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/forEach/ForeachSourceInspector.java#L57

Thanks for this awesome plugin! 🚀

**Comment by kalessil** [comment]
Thank you for reporting @hansott and you are welcome =)

The IDE types resolving relies on PhpDoc at first place, the message points to missing PhpDoc in fact.
Something like `@var Event[]|array $batch` will make the warning go.

**Comment by hansott** [comment]
Thanks for your answer, however, why does the warning go away when using `if (!is_array($batch)) { ... }`?

**Comment by kalessil** [comment]
IDE rarely analyzes code structure for types recognition (cpu expensive task), but PhpDoc and only in the limited amount of texts it respects is_* functions and instanceof expressions.

Shortly: specific of IDE types resolver.

**Comment by kalessil** [comment]
And the warning goes away because it's one of special context when is_* functions are taken into account.

**Comment by hansott** [comment]
https://github.com/kalessil/phpinspectionsea/issues/496#issuecomment-326283367

Isn't this than a valid improvement? `if (!is_array($batch))` vs `if (is_array($batch) === false)`?

Sorry for going on about it but I think it's a valid improvement.

Thanks for your hard work! 🤗

**Comment by kalessil** [comment]
Agree, the both forms should work. If you feel like it, you can create an issue in PhpStorm ticket system: https://youtrack.jetbrains.com/issues/WI

No worries, glad to help =)

**Comment by hansott** [comment]
Logged it! https://youtrack.jetbrains.com/issue/WI-37859

**Comment by kalessil** [comment]
Great, thank you =)
