### ISSUE TITLE
'null === ...' can be used, why not '... === null'?

### ISSUE THREAD

**Issue by kasperpeulen** [kalessil/phpinspectionsea#497]
I think that it is much more common to write`$value === null` then `null === $value`. 

IMO, this does read much easier. Would it be possible to autofix this the other way around. We got over 400 places where `is_null()` is used, I want to autofix them all, but would love if it could be done in a more standard way of checking for null values.

**Comment by kalessil** [comment]
I'll ping you back when you can install dev-build of the plugin with the option.

**Comment by kasperpeulen** [comment]
thanks 🙏

**Comment by kalessil** [comment]
Ready (fresh binary is pushed to the master as well), @kasperpeulen do you need support with installing the dev build?

**Comment by kasperpeulen** [comment]
Thanks!
