### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#5]

**Comment by kalessil** [comment]
@artspb : I need advisory here, perhaps can you could give me a hint or share how do you test inspections internally in JB?

**Comment by artspb** [comment]
There're many ways to do it. You can refer to [IntelliJ IDEA source code](https://github.com/JetBrains/intellij-community/tree/master/java/java-tests/testSrc/com/intellij/codeInspection) to find some examples. Here's one of the approaches:

```java
package com.jetbrains.php;

import com.intellij.testFramework.fixtures.CodeInsightFixtureTestCase;
import com.jetbrains.php.lang.inspections.PhpVariableVariableInspection;

public class DemoInspectionsTest extends CodeInsightFixtureTestCase {

  public void testSomeInspection() throws Exception {
    myFixture.configureByFiles("path/to/test.php");
    myFixture.enableInspections(PhpVariableVariableInspection.class);
    myFixture.testHighlighting(true, false, true);
  }
}
```

And here's `test.php` content:

```php
<?php
$var = "var";
echo <weak_warning descr="Usage of a variable variable">$$var</weak_warning>;
```

**Comment by kalessil** [comment]
Awesome, thank you!

**Comment by artspb** [comment]
You're welcome, feel free to ask :)

**Comment by kalessil** [comment]
Mostly worked, if I trying to run test in Idea CE, getting exception:
`ERROR: com.jetbrains.php.PhpFileTypeFactory has unsatisfied dependency: class com.intellij.ultimate.UltimateVerifier among unsatisfiable dependencies: [[class com.intellij.ultimate.UltimateVerifier]] where DefaultPicoContainer (root) was the leaf container being asked for dependencies.
`

Seems I need IdeaUltimate: applied for OSS license, let see if will get it.

**Comment by artspb** [comment]
You definitely should get it, let me know if you'll face any problems.

**Comment by kalessil** [comment]
First UT green, thanks a lot @artspb for your hints!
