### ISSUE TITLE
Senseless null parameter type

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#500]
See that code:

```php
function example(int $number = null) {
}
```

It is a `int` but the default value is `null`. So it should be `?int $number = null`, to ensure it is nullable.

Note: it is not a PHP error. On reality, by code `= null` make it be a nullable parameter by nature, but I belive that is better we put the `?` here.

**Comment by funivan** [comment]
Hello. Do not get it.  Why we should put `?`  to ensure it is nullable?
```php
 function test(int $number = null){
    var_dump($number);
  }
  test();
```
We get NULL.

**Comment by kalessil** [comment]
+1, why do we need to promote nullable scalars?

+100500 for promoting nullable objects, but nullable scalars is a mystery for myself since they got introduced. @rentalhost : can you elaboration about the use case, please?

**Comment by rentalhost** [comment]
Oh... The scalar was just an example. Anyway, I use a lot of nullable scalar to keep "null" as a "default keyword" (once that PHP not support this).

For instance:

```php
function example(?bool $multiply = null, ?bool $reduce = null) {
    $number = 2;
    if ($multiply !== false) $number *= 2;
    if ($reduce !== false) $number -= 1;
    return $number;
} 

example(null, false); // => 4
```

**Comment by funivan** [comment]
@rentalhost if you want to use null as a default keyword and `require` it every time then you should write 
```
function example(?bool $multiply, ?bool $reduce) {

} 
```

**Comment by rentalhost** [comment]
In this case have no sense be nullable, once it is required. On my example you could use just `example()`, for instance, and the function will determine the boolean values.

**Comment by funivan** [comment]
@rentalhost when you define parameter `?bool $multiply = null,` it is the same like `$multiply = null,`
I do not see any difference on the client side. It would be nice to see difference of usage in such cases.

**Comment by rentalhost** [comment]
`?bool $multiply = null` is the same like `bool $multiply = null`, but not like `$multiply = null`. The idea here is just normalize the code to put `?` on type everytime that it can be nullable (` = null`).

**Comment by funivan** [comment]
@rentalhost ok, I get it. Thanks for explanation.

**Comment by kalessil** [comment]
@rentalhost: is this idea still in demand?

**Comment by rentalhost** [comment]
Maybe. It is just to normalize the code style. Nothing critical.

**Comment by kalessil** [comment]
@rentalhost: let's skip for now. If it is relevant, we'll see similar reports (in fact this happened multiple times, your request are leaving tracks somewhere in my head) =)

**Comment by andreasschroth** [comment]
Actually I really like the idea and we keep it the same way.

If the default is `null`, of course it should also be possible to pass `null` as well.

Just see that example:

```php
function doSomething(int $number1 = null, int $number2 = null) {
}

// ok, number1 and number2 will be null
doSomething();
// also ok, number1 is passed and is 2, number2 will be null
doSomething(2);
// but what if I want to have number2 as 2 and number1 as null?
doSomething(null, 2); // fatal error, null cannot be explicitly be passed, thus it's never possible to only pass number2
```
Of course this example with a scalar number is kind of nonsense, but the same applies to arrays, objects, etc. as well. It's not about the scalar type here.
