### ISSUE TITLE
array_filter() can be used (crazy-crazy stuff)

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#507]
```php
        foreach ($source as $index => $value) {
            if (<treaky part: conditions>) {
                $container[] = $value;
            }
        }
```

**Comment by rentalhost** [comment]
Good ideia! 

1. Performance is acceptable? 
2. Could it be applied to filter by key too? (low priority, once that ia very uncommon)
3. Could it be applied for `array_map()` too? In this case conditions is optional.

```php
$dependency = 1;
foreach($items as &$item) {
    $item = expr($item, $dependency);
} 

// === 

$items = array_map(function ($item) use ($dependency) {
    return expr($item, $dependency);
} 
```

**Comment by kalessil** [comment]
Thanks =)

- Yes, the general pattern identification will cost almost nothing.
- Could be later enhancement, I'll leave it for community to request further enhacements.
- Yes, `array_map` can be identified as well

**Comment by rentalhost** [comment]
Oh, great... But the 1st I mean PHP performance, once that method calls are generally very slow if compared with constructors.

**Comment by kalessil** [comment]
Calling array_filter/array_map will cost something of course =)

**Comment by kalessil** [comment]
Something similar might come from PS itself: https://youtrack.jetbrains.com/issue/WI-38051. 
Pity, but let's close this ticket until the topic is popping up again.
