### ISSUE TITLE
Php Inspections (EA Extended) as a Service

### ISSUE THREAD

**Issue by vladyslavstartsev** [kalessil/phpinspectionsea#509]
I've found that you've forked the [phpstorm-inspect](https://github.com/kalessil/phpstorm-inspect) and one idea came into my mind. 
What if there was a service that will check the code with inspections before merging PR, I mean something like SensioLabsInsight/StyleCI/etc. But that's another project. 
Also the question is how JetBrains will react on it? I mean it will be build on top of PhpStorm.

Al least there can be an instruction on how to make cli inspections before commit

**Comment by kalessil** [comment]
We recently asked the community about the topic: https://twitter.com/kalessil/status/905340256102305793
JB will definitely escalate legal actions against PhpStorm based service, as it'll violate their licensing model.

I'm making research if we can use https://github.com/kalessil/consulo-php for running Php Inspections (EA Extended) in Idea CE - let see is this going to work.

**Comment by vladyslavstartsev** [comment]
@kalessil thank you for answer. I missed it somehow in my twitter.

**Comment by kalessil** [comment]
No worries =)
