### ISSUE TITLE
[bug] Wrong quick fix for PHP4 style type casting

### ISSUE THREAD

**Issue by LavaIsCool** [kalessil/phpinspectionsea#51]
I have some code similar to the following:
`$value = intval($number + ($continue ? ($number < 0 ? 1 : -1) : 1));`

When I use the quick-fix provided, it corrects it to:
`$value = (int)($number < 0 ? 1 : -1);`

Which is incorrect, as it's ignoring the $number + ($continue ...) part.

**Comment by kalessil** [comment]
Thanks for reporting @LavaIsCool , this fixed now. I'll release it withing next 48 hours.
