### ISSUE TITLE
Add inspection for parameter objects are wrongly returned after modfication

### ISSUE THREAD

**Issue by Haehnchen** [kalessil/phpinspectionsea#510]
I often notice the issue that objects are given into the function via parameter and returned after modfication. An inspection would help that objects are references.

```php
    private function foo(Request $request)
    {
        $request->request->add('foo');
        
        return $request;
    }
    
    public function indexAction(Request $request)
    {
        $request = $this->foo($request);

        return new Response();
    }
```

**Comment by rentalhost** [comment]
I think that Java inspection have something like that. I think that it too have a "scientific name" hehe. I just don't know if it will help or give us a headache - although it would be much more "profitable" to respect this rule. In IDEA I have disabled this inspection, anyway.

**Comment by kalessil** [comment]
Yep, appears from time to time in codebases, I'd report `return $request` as unnecessary.
Any recommendations regarding which visibility levels to inspect?
