### ISSUE TITLE
Failed to resolve object after instanceof === false

### ISSUE THREAD

**Issue by eigan** [kalessil/phpinspectionsea#511]
```php
<?php

interface Foo
{
	public function fooMethod();
}


class FooTest
{
	public function testInstanceOf($foo): void
	{
		if($foo instanceof Foo === false) {
			throw new InvalidArgumentException(); // or, return, exit
		}
		
		$foo->fooMethod();
	}
}
```

```
Method 'fooMethod()' not found in subject class
```

This works:
```php
if(!$foo instanceof Foo)
```

**Comment by kalessil** [comment]
Hi @eigan, so what exactly causes the issue: a Quick-Fix or that's a new pattern for our suspicious binary operations inspection?

**Comment by eigan** [comment]
Sorry, I am new to PHPStorm. I guess this is probably a bug in PHPStorm, not this plugin.

**Comment by kalessil** [comment]
Oh, ok. Looks like this: https://github.com/kalessil/phpinspectionsea/issues/496#issuecomment-326287539

**Comment by kalessil** [comment]
Or direct link: https://youtrack.jetbrains.com/issue/WI-37859

**Comment by eigan** [comment]
Thank you :)

**Comment by kalessil** [comment]
Happy to help =)
