### ISSUE TITLE
How to change the color of tag?

### ISSUE THREAD

**Issue by raoptimus** [kalessil/phpinspectionsea#514]
<img width="509" alt="screen shot 2017-09-14 at 22 55 14" src="https://user-images.githubusercontent.com/1120269/30452889-d81376f8-999f-11e7-8a0a-bc586c7f829b.png">

**Comment by kalessil** [comment]
Hm, unexpected =) I using standard themes, so can not share any experience in customizing themes.

**Comment by bazzik** [comment]
@raoptimus 
What "tag"?
Are you talking about that grey on light grey `contentType:` and `playliustId;` ?

If so:
- It's purely PhpStorm/IDE question and has nothing to do with this plugin.
- You are using custom color scheme .. which does not define color for this styling element hence the defaults from "Default" light scheme are used.
- You can change it at "Settings/Preferences | Editor | Color Scheme | Language Defaults --> Inline parameter hint".

**Comment by raoptimus** [comment]
> @bazzik You can change it at "Settings/Preferences | Editor | Color Scheme | Language Defaults --> Inline parameter hint".

Yes, it's it. Thank you very much
