### ISSUE TITLE
[FP] Array and string offset validity

### ISSUE THREAD

**Issue by iakoder** [kalessil/phpinspectionsea#515]
Cross-posted from https://youtrack.jetbrains.com/issue/WI-38063

Not sure how much is due to PhpStorm and how much from phpinspectionsea.

1) Red squiggle under the at-return annotation in the comment

2) Any way to get the inspection to know that the variant array|false is really an array without explicitly casting it?  Yea, it would take knowing that we're in a !==false branch which is probably out of the question but just thought I'd ask.

3) Why does disabling the Array and string offset validity inspection or casting the variable to an array affect the inspection on the return statement?

Php Inspections version: 2.13.10-preview

PhpStorm 2017.3 EAP
Build #PS-173.2290.12, built on September 13, 2017
PhpStorm EAP User
Expiration date: October 13, 2017
JRE: 1.8.0_152-release-915-b12 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

```
/**
 * @param string $objId
 *
 * @return string[][]|false
 */
function queryDatabase($objId) {
    return [ [ "20" ] ];
}

/**
 * @param int $objId
 *
 * In my codebase the at-return is red-squiggle-underlined with "return type does not match" because we're possibly returning
 * The int $objId parameter.  Even in this test the $objId on the return line is tagged as an int when you cmd-hover.
 * @return string  Final object id
 */
function usesDBQuery($objId) {

    $temp = queryDatabase($objId);
    if ($temp !== false) {
        // Flagged with "$temp may not support offset operations (EA Extended).  I'll ask them if there's a way to
        // get PhpStorm to know that at this point it's going to be an array?
        $objId = $temp[0][0];

        // If I cast $temp to an array then the offset inspection goes away and the return line is highlighted with 
        // "Return value is expected to be 'string', 'int' returned.  Is it an EA Extended problem that's preventing
        // the PhpStorm inspection on the return or a PhpStorm issue?
        // $objId = ((array)$temp)[0][0];
    }

    // In my codebase the return is not highlighted in any way even though the at-return is red-squiggle-underlined
    return $objId;

}

```

**Comment by kalessil** [comment]
What happens if instead of `$temp !== false` you place `is_array($temp)` - this should at flaf the array type properly. The question still is if the issues are going away or not.

**Comment by iakoder** [comment]
@kalessil changing temp !== false to is_array($temp) has no impact on the "$temp may not support offset..." inspection.  Even if it did, is_array appears to be about 5x slower than !==. 

As you say, it still doesn't explain why the "$temp may not support offset..." inspection is affecting the "Return value" inspection.

**Comment by kalessil** [comment]
- `$objId = $temp[0][0];`- since the is_array doesn't solve the warning, that's bug on my end.
- affecting the "Return value" inspection is unlikely - we only read types and tree information there, that's the EAP-specific IMO.

**Comment by b1rdex** [comment]
Mine example:
```
/**
 * @return array|false
 */
function read()
{
    return;
}
while (($row = read()) !== false) {
    $row['pid'] = (int)$row['pid'];
    $row['uid'] = (int)$row['uid'];
}
```
`while (is_array($row = read()))` is not fixes warning.

**Comment by mishavantol** [comment]
Don't know if it's related but with the following code I get an FP on '$foo[0]' while the return type for array_slice is 'array'.

```php
$foo = array_slice([1,2,3], 0, 2);    
$bar = $foo[0];
```

**Comment by b1rdex** [comment]
@mishavantol can't reproduce. Try invalidating phpstorm caches and restart, it looks like phpstorm glitch. Another thing — `array_slice` might be overriden somewhere in your project.

**Comment by mishavantol** [comment]
@b1rdex invalidating caches doesn't fix it. I've created a new project with just one .php file containing only the above code and I still get the error. I did had to turn the inspection on, don't know if it's off by default. I happens in both 2017.2.4 as 2017.3 EAP.

**Comment by kalessil** [comment]
@iakoder: the original cases is https://youtrack.jetbrains.com/issue/WI-38622 (btw. huge thanks for such a productive escalation :1st_place_medal:).

@mishavantol : I also was not able to reproduce, please file a separate issue with extended code fragment.

**Comment by iakoder** [comment]
It's not happening for me anymore in 

PhpStorm 2017.3 EAP
Build #PS-173.3415.21, built on October 25, 2017
PhpStorm EAP User
Expiration date: November 24, 2017
JRE: 1.8.0_152-release-1024-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

Php Inspections (EA Extended) 2.3.11.1

As I was pulling up this file (through find-in-files) PhpStorm reported an exception that I reported as 616.

**Comment by kalessil** [comment]
Ok, I'll check the exception.

**Comment by b1rdex** [comment]
It's still reproducible for me with code in https://github.com/kalessil/phpinspectionsea/issues/515#issuecomment-332732302

**Comment by kalessil** [comment]
@b1rdex : it's a case similar to https://youtrack.jetbrains.com/issue/WI-38622
