### ISSUE TITLE
Wrong `property usage` shown

### ISSUE THREAD

**Issue by vladyslavstartsev** [kalessil/phpinspectionsea#519]
By clicking Ctrl+right-click on property, I should get property usage and not `@tag` with the same name.
The example. I've clicked on the return property, but got all the methods that have `@return`

![image](https://user-images.githubusercontent.com/17382248/30502376-a5968baa-9a6e-11e7-8824-62c7d2ee48ef.png)

**Comment by kalessil** [comment]
That probably needs to be reported to PhpStorm team here: https://youtrack.jetbrains.com/issues/WI
