### ISSUE TITLE
[configuration] disconnected foreach instructions - suggest using clone option 

### ISSUE THREAD

**Issue by funivan** [kalessil/phpinspectionsea#52]
Can you add option for the `strProblemUseClone`?
```
Objects should be created outside of a loop and cloned instead
```
Fire example in our project we want to use `new` operator instead of the `clone`

**Comment by kalessil** [comment]
Sure, will do in the next release.

**Comment by kalessil** [comment]
This has been released, let me know if the solution working not as expected, please.

**Comment by funivan** [comment]
OK. I will check this feature. Thanks ;)
