### ISSUE TITLE
`heavy initialization` message fix

### ISSUE THREAD

**Issue by vladyslavstartsev** [kalessil/phpinspectionsea#520]
I got the app/lib that has min php version set to 5.4.*.When refactoring $variable, I've got a message that says
`This property initialization seems to be quite 'heavy', consider using static property or constant instead`, the part that says `constant instead` is wrong (if the variable is array) for php5.4 because `constant as array` was only [introduced in php5.6](http://php.net/manual/en/migration56.new-features.php)
The example.
![image](https://user-images.githubusercontent.com/17382248/30502772-4e0612a0-9a70-11e7-9126-30b94043c85d.png)

**Comment by kalessil** [comment]
Nice catch, I'll enhance message generation here.
