### ISSUE TITLE
foreach in a static array of strings

### ISSUE THREAD

**Issue by vladyslavstartsev** [kalessil/phpinspectionsea#524]
- when making `foreach` in a static array of strings that were not changed(for example we created a $variable, static array of strings, and `foreach`ed it right after creation), the $value is marked as mixed and not as a string. Also if we do `$key => $value` in this array, the $key type will be int|string but according to http://php.net/manual/en/language.types.array.php Example #4, it should be int only, as it didn't change. Not sure if it's EA or native PHPStorm.
The example (made with camera and not as screenshot because in Linux Mint you can't make screenshots and highlight at the same time)
```php
    protected static $relations = [
        'hasMany',
        'hasManyThrough',
        'belongsToMany',
        'hasOne',
        'belongsTo',
        'morphOne',
        'morphTo',
        'morphMany',
        'morphToMany'
    ];
```
$key typehint
![image](https://user-images.githubusercontent.com/17382248/30504670-d55b948e-9a78-11e7-9fa9-1214bd789440.png)

$value typehint
![image](https://user-images.githubusercontent.com/17382248/30504685-e330f0b8-9a78-11e7-918d-34301995bf37.png)

**Comment by kalessil** [comment]
Just regular type-hinting i needed:
```php
/* @var string[] */
protected static $relations = [];
```

**Comment by Xml-rpc-farfetched** [comment]
> Just regular type-hinting i needed:
> 
> /* @var string[] */
> protected static $relations = [];





https://bombshellreturning.github.io/talc/

**Comment by ea-inspections-team** [comment]
@Xml-rpc-farfetched : can you please elaborate on that link (is this something to correct @kalessil 's answer)?

**Comment by ea-inspections-team** [comment]
I see. Thank you for your comment @andrew-demb!
