### ISSUE TITLE
Sort static arrays in alphabetic order

### ISSUE THREAD

**Issue by vladyslavstartsev** [kalessil/phpinspectionsea#529]
It will help to refactor things `key duplicated but value is not the same` (when/if #528 will be implemented).

What I mean is I was editing translation files in Yii2/Laravel which use array for it. Sometimes if the array is huge (more then 100 LOC), it's kind of hard to find something in it. 
Implement thing to sort array in alphabetic order.
But make warning that it's risky, it might break things (there is situations when array order does meter).
Also it will look more neat and clean.

Also make option to rearrange whole array or whole array but with `code blocks` (what I mean is if there are empty lines after 2 (or more) keys, then sorting should be applied to block of keys/values, I mean for each of them)

I think it should work similar to `use` sorting.
As a workaround I use [Lines Sorter plugin](https://plugins.jetbrains.com/plugin/5919-lines-sorter) ([source code](https://github.com/syllant/idea-plugin-linessorter)) Install it, after it, select all the things that are in the array and after it click on `Sort Lines` action in `Edit` menu

**Comment by kalessil** [comment]
@funivan : this might be a new intention for your plugin, do you want to pick this up?

**Comment by funivan** [comment]
@vladyslavstartsev sort array by keys or by values ? 
Also try https://plugins.jetbrains.com/plugin/2162-string-manipulation

**Comment by funivan** [comment]
@vladyslavstartsev do you need some help here, or we can close the issue?

**Comment by vladyslavstartsev** [comment]
@funivan no help needed. Close I'll close it
