### ISSUE TITLE
Some key words MUST be in lowercase (PSR-2)

### ISSUE THREAD

**Issue by vladyslavstartsev** [kalessil/phpinspectionsea#531]
I've found that there is no highlight and suggestion to change (to lowercase) for words like  `true`, `false`, and `null`. They MUST be in lowercase because of [this](http://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull)

**Comment by kalessil** [comment]
We have big community part who are not following this specific recommendation, plus PHP CS Fixer has this rule `lowercase_keywords [@PSR2, @Symfony]`, which can be cleanup such mess.

I have to decline this FR.

**Comment by vladyslavstartsev** [comment]
Maybe it should be somewhere in the docs. Something like "If you would like to check for PSR-2 go get [PHP CS Fixer](http://cs.sensiolabs.org/)". I mean some section in the docs that say "This plugin does -blablabla. This plugin doesn't do things like (PSR-2 checking and etc.) because there are other tools (local and CD/CI) for that, for example, PHP CS Fixer, Sensiolabs Insight, StyleCI and etc."

**Comment by kalessil** [comment]
I think there is no need to anything here: PS supports PSR2 from the box.

![image](https://user-images.githubusercontent.com/1577185/30533186-53a89054-9c58-11e7-9406-2833ef615d74.png)

**Comment by vladyslavstartsev** [comment]
My bad. Sometimes I miss things or PS is just so huge that I can't find it.

**Comment by kalessil** [comment]
No problems =) It's really huge =)
