### ISSUE TITLE
Skip intermediate refactoring

### ISSUE THREAD

**Issue by vladyslavstartsev** [kalessil/phpinspectionsea#532]
Is there a way I can skip some intermediate refactoring, what I mean is, let's say I have something that looks like 
```php
if (($diff < $error) && ($diff >= $error * -1))
    return true;
else
    return false;
```
What I want is to directly change it to 
```php
return (($diff < $error) && ($diff >= $error * -1));
```
But right now I should do
1. add curly brackets 
```php
if (($diff < $error) && ($diff >= $error * -1)) {
    return true;
} else {
    return false;
}
```
2. split workflows
```php
if (($diff < $error) && ($diff >= $error * -1)) {
    return true;
}
return false;
```
3.Simplify to
```php
return (($diff < $error) && ($diff >= $error * -1));
```

**OR**

1. Simplify if to look like 
```php
return ($diff < $error) && ($diff >= $error * -1) ? true : false;
```
2.Simplify ternary operator
```php
return (($diff < $error) && ($diff >= $error * -1));
```

**Comment by funivan** [comment]
For me standard phpstorm intentions is enough. Just 2 times `Alt+Enter` and all is done =) Not so hard.

**Comment by kalessil** [comment]
So many options =) If seriously, I think we could support detecting pattern:
```php
if (....) {
    return true;
} else {
    return false;
}
```
and QFing it with a return statement, but the group statements are necessary - I know this is stupid, but that's what do we expect in all inspections.

**Comment by funivan** [comment]
@kalessil maybe we should report bug in https://youtrack.jetbrains.com/issues/WI ?
And core team can improve simplify if intention. What do you think?

**Comment by kalessil** [comment]
I don't know frankly - I implemented already support for the new patter, but if you think this should be an intention - go ahead =)
