### ISSUE TITLE
`Unnecessary fully qualified name` enhancement

### ISSUE THREAD

**Issue by vladyslavstartsev** [kalessil/phpinspectionsea#534]
Is there a way to make enhancement to `Unnecessary fully qualified name` so that it will import them all automatically?

**Comment by funivan** [comment]
We do not have quick fix for that. Users invoke standard (created by PS team) `Import class` intention.

**Comment by funivan** [comment]
This inspection goes from the PhpStorm team. Please create an issue in Youtrack https://youtrack.jetbrains.com/issues/WI

@vladyslavstartsev  Can we close this issue?

**Comment by rentalhost** [comment]
Except if it is related to some quick-fix from EA - in some cases it really use full qualified name.

**Comment by kalessil** [comment]
@vladyslavstartsev : is this related to or return type quick fixes, or it was something else?

**Comment by vladyslavstartsev** [comment]
@kalessil don't really remember :) think return type Quick fixes, but not 100% sure.
