### ISSUE TITLE
`'mkdir(...)' race condition` enhancement

### ISSUE THREAD

**Issue by vladyslavstartsev** [kalessil/phpinspectionsea#535]
The inspection is aimed at code like `mkdir($folder);`.
So right now it works like this
From
```php
mkdir($folder);
```
To
```php
if (!mkdir($folder) && !is_dir($folder)) {
    throw new RuntimeException(sprintf('Directory "%s" was not created', $folder));
}
```
**But** some people do things like ([real life example](https://github.com/adam2314/linet3/blob/815e238f3dfef3f333b38e0e008464094f29ba27/protected/models/Company.php#L78))
```php
if (!is_dir($folder)) {
    mkdir($folder);
}
```
which look like half-implemented suggestion. If you will implement (click on `Replace with conditional expression`) it will look like this
```php
if (!is_dir($folder)) {
    if (!mkdir($folder) && !is_dir($folder)) {
        throw new RuntimeException(sprintf('Directory "%s" was not created', $folder));
    }
}
```
this way `!is_dir($folder)` called 2 times which is not the best thing to have.
The expected behavior is 
From 
```php
if (!is_dir($folder)) {
    mkdir($folder);
}
```
To
```php
if (!mkdir($folder) && !is_dir($folder)) {
    throw new RuntimeException(sprintf('Directory "%s" was not created', $folder));
}
```

**Comment by kalessil** [comment]
The `!is_dir($folder) && !mkdir($folder) && !is_dir($folder) ` or its' or-invariant are something what should be used at the end, let me extnd our documentation so people don;t get confused.

**Comment by kalessil** [comment]
Docs updated.
