### ISSUE TITLE
`mkdir(...)' race condition` RuntimeException  class is not imported

### ISSUE THREAD

**Issue by vladyslavstartsev** [kalessil/phpinspectionsea#536]
When doing `Replace with conditional expression` it inserts code with `RuntimeException` **but** it doesn't import(`use` keyword) it in the class. Also the other way to do things is to put not `RuntimeException` but `\RuntimeException`.

**Comment by kalessil** [comment]
Oops, will be in 2.3.11

**Comment by kalessil** [comment]
Fixed =)
