### ISSUE TITLE
Any way to run your inspections on Jenkins?

### ISSUE THREAD

**Issue by vasily-kartashov** [kalessil/phpinspectionsea#538]
Is it a use case you cover, or will eventually cover?

**Comment by kalessil** [comment]
Yes: check this out https://github.com/kalessil/phpstorm-inspect please. Also, produces Jenkins-understood reporting formats.

2 restrictions though: only one instance of PS can be run at time, relatively slow - as the whole IDE, plugin load + indexing are taking place.
