### ISSUE TITLE
Symfony debug reported as forgotten debug statement

### ISSUE THREAD

**Issue by marcverney** [kalessil/phpinspectionsea#539]
![selection_102](https://user-images.githubusercontent.com/6585350/30532636-a3dc1422-9c55-11e7-981b-98c268f0702b.png)

IIUC, Symfony's Debug component calls should not be flagged as a forgotten debug statement.

PHPStorm 2017.1
Php Inspections EA Extended 2.3.10.3

**Comment by kalessil** [comment]
Thanks for the report @marcverney, I'll check the documentation out (or just send me a link with more details).

**Comment by kalessil** [comment]
@marcverney, it seems like we need to keep this reported, https://symfony.com/doc/current/components/debug.html says following

> You should never enable the debug tools in a production environment as they might disclose sensitive information to the user.

**Comment by marcverney** [comment]
Given that the `Debug::enable()` call on [Symfony's local development front controller](https://github.com/symfony/symfony-standard/blob/3.3/web/app_dev.php#L22) is there on purpose (not forgotten) and it makes no sense to remove it, I thought it was a bug that PHPIEA reports it as an error, sorry. I guess I'll have to live with it :-)

**Comment by kalessil** [comment]
Or you can remove it from the list, this is a valid option - do what's right for you and your teammates/clien =)

**Comment by glensc** [comment]
@marcverney never link to a branch, use git tag or commit instead (in github press `y` hotkey)

**Comment by marcverney** [comment]
@glensc oops, fixed.

**Comment by funivan** [comment]
@marcverney you can just suppress inspection in this specific case. 
More details https://www.jetbrains.com/help/phpstorm/suppressing-inspections.html

**Comment by marcverney** [comment]
@funivan this is what I do :-) Best solution for this case imo.
