### ISSUE TITLE
Add Inspection that finds superfluous @throws annotations

### ISSUE THREAD

**Issue by markwatney2016** [kalessil/phpinspectionsea#542]
After refactoring a method formerly valid @throws annotations can become superfluous. Would be nice to have an inspection that finds these now superfluous @throws annotations.

**Comment by kalessil** [comment]
Hi @markwatney2016, this is already available, just switch it on (as it deactivated by default):
![image](https://user-images.githubusercontent.com/1577185/30578472-6e96568c-9d14-11e7-9fc5-4d6944797235.png)
