### ISSUE TITLE
Probable Bugs => Null Reference should recognize PHPUnit's assertNotNull() (False positive)

### ISSUE THREAD

**Issue by AllenJB** [kalessil/phpinspectionsea#546]
Within (PHPUnit) unit tests, assertNotNull() can replace null checks (because the test will fail and proceed no further if the value is null). It would be great if this was recognized by the Null Reference inspection.

**Comment by kalessil** [comment]
Well, In general I'm agree, but still need a code sample to look at the use-case =) Can you share please?

**Comment by kalessil** [comment]
Done.
