### ISSUE TITLE
"Self Class Referencing" inspection appears to be returning false-positives in the most recent update

### ISSUE THREAD

**Issue by JackWH** [kalessil/phpinspectionsea#549]
I'm running the latest version of the plugin, and since updating, I've noticed the "Self class referencing" inspection seems to be returning false-positives.

Specifically, if a class named `MyClass` in the namespace `MyApp\MyNamespace` is referencing another class, also called `MyClass`, but in the namespace `MyApp\MyCompletelyDifferentNamespace`, the inspection is triggering and prompting to replace with `self`.

I'm pretty sure it wasn't doing this in previous releases. See screenshot below for an example:

<img width="1028" alt="screen shot 2017-09-21 at 13 02 09" src="https://user-images.githubusercontent.com/627533/30694801-a5853126-9ecd-11e7-8452-4e3ff91525a6.png">

**Comment by kalessil** [comment]
I see, which plugin version is it?

**Comment by JackWH** [comment]
@kalessil That would be v2.3.10.6, on PHPStorm v2017.2.4.

**Comment by kalessil** [comment]
Fixed, fresh binary pushed into master as well.
