### ISSUE TITLE
"Self class referencing" gets confused by namespace

### ISSUE THREAD

**Issue by 5lava** [kalessil/phpinspectionsea#555]
`\Admin\Page\News` is not `\Admin\View\Page\News`

<img width="434" alt="screen shot 2017-09-24 at 11 29 47" src="https://user-images.githubusercontent.com/63829/30784075-fa093f58-a11b-11e7-9404-19502d8faea2.png">

**Comment by kalessil** [comment]
Thank you for reporting @5lava, this has been fixed already in #549 and will be in the next release.
