### ISSUE TITLE
Self class referencing mismatching when two classes have the same name

### ISSUE THREAD

**Issue by insmod** [kalessil/phpinspectionsea#557]
I know this is not necessarily a good practice, but in my current project I have a Symfony form for a new Organisation with a class named OrganisationType. In that same form, I have a field 'type' (meaning the type of organisation) that points to an entity called... OrganisationType.

Even though I specifically reference the class \Something\SomethingBundle\Entity\OrganisationType::class (instead of \Something\SomethingBundle\Form\OrganisationType) in the form, your plugin still warns me that this could be replaced by '__CLASS__'.

This is not a major issue, but I thought it was worth pointing out as it could be an easy solve.

Feel free to ask for any details you need, I currently have the latest version of PhpStorm (2017.3 EAP, Build 173.2463.17) and Php Inspections (2.3.10.6) and I'm using Ubuntu 16.04

**Comment by kalessil** [comment]
Hi @insmod, thank you for reporting. It's a bug (fixed, #555). With the next release, it will go away.

**Comment by insmod** [comment]
Hey, no problem! Thank you for your work :)

**Comment by kalessil** [comment]
You are welcome, hope it helps =)
