### ISSUE TITLE
Forgotten debug statements: xdebug_break()

### ISSUE THREAD

**Issue by lurkie** [kalessil/phpinspectionsea#559]
I think the list of forgotten debug statements should contain xdebug_break by default, as it will result into errors when forgotten, and xdebug is not available on production systems

**Comment by kalessil** [comment]
Good ide @lurkie, probably we'll add more xdebug functions =)

**Comment by kalessil** [comment]
For volunteers: see com/kalessil/phpStorm/phpInspectionsEA/inspectors/apiUsage/debug/ForgottenDebugOutputInspector.java:129

**Comment by lurkie** [comment]
I'm willing to create a pull request, code seems logical enough :) But I'm not familiar with PHPStorm plugin development, so currently I'm not able to test it properly.

If that's OK with you, I suggest adding all functions mentioned in on https://xdebug.org/docs/all_functions, except for the code coverage functions as those are probably not forgotten in e.g. phpunit

**Comment by kalessil** [comment]
Let's start with a complete list then - I'll do QA anyway on major OSS projects and can exclude certain functions from the list.

@lurkie : just extend the list - it'll build a new binary and push it back so you can play with it before the official release. It'll be the simplest way IMO.
