### ISSUE TITLE
Double isset can not always be merged

### ISSUE THREAD

**Issue by BavoJanss** [kalessil/phpinspectionsea#565]
When you have a `isset($a) && isset($b)` the plugin suggests `isset($a , $b)`
But on a `isset($a['a']) && isset($a['a']['b'])` statements cannot be merged.

**Comment by kalessil** [comment]
Actually you can: https://3v4l.org/8RtGl

You can do even shortcut and just use `isset($a['a']['b'])` without checking `$a['a']`: 2.3.11 will bring the inspection for this short-cut =)

**Comment by kalessil** [comment]
@BavoJanss, I'd extend our docs a little bit to include this information - would this help somehow?
