### ISSUE TITLE
The default argument can be safely dropped for not the latest argument

### ISSUE THREAD

**Issue by zerkms** [kalessil/phpinspectionsea#576]
At the moment this code

```php
function f($a = null) {
    var_dump(func_get_arg(1));
}

f(null, 42);
```
triggers a weak warning, the `null` on call-side is greyed-out and is suggested for safe removal.

If one uses the built-in auto-fix it leads to

```php
f(, 42);
```

**Comment by kalessil** [comment]
It's defenetely a bug, thank you for reporting @zerkms
