### ISSUE TITLE
Class overrides a field of a parent: "enhance message for private fields"

### ISSUE THREAD

**Issue by kelunik** [kalessil/phpinspectionsea#577]
Private properties aren't visible to the extending class, so there's no reason to flag these on declaration.

```php
<?php

class A {
    private $foo = 42;
    
    public function getFooA() {
        return $this->foo;
    }
}

class B extends A {
    private $foo = 62;
    
    public function getFooB() {
        return $this->foo;
    }
}

var_dump((new B)->getFooA());
var_dump((new B)->getFooB());
```

**Comment by kalessil** [comment]
Why? Are properties identical or just names collision?

**Comment by kelunik** [comment]
They just have the same name. Real example: [`Driver`](https://github.com/amphp/amp/blob/7837d8ce08b0edada1fd10dc1b7eaf95d4655141/lib/Loop/Driver.php#L27) vs. [`UvDriver`](https://github.com/amphp/amp/blob/7837d8ce08b0edada1fd10dc1b7eaf95d4655141/lib/Loop/UvDriver.php#L18).

**Comment by kelunik** [comment]
In that case it should have another message though. Because the child property _doesn't_ override the parent's property, it's a separate property. I'm totally fine with a warning there, but the current warning makes it even weirder IMO. :-)

**Comment by kalessil** [comment]
Aaaaaa, that's a good idea to enhance the message.

**Comment by kelunik** [comment]
Maybe something like _"A parent class of this class uses the same name for a private property, which might be confusing for future readers."_
