### ISSUE TITLE
[false-positive] sscanf has the right arguments

### ISSUE THREAD

**Issue by coelhoricardo** [kalessil/phpinspectionsea#58]
Hi,

On this example, the "*printf/*scanf arguments count mismatches" inspection is triggered :
`list($hour, $minute) = sscanf($time, '%d:%d');`

I think it's a false positive.

Thanks for your plugin !

**Comment by kalessil** [comment]
Hi,

It is a false-positive, thank you for reporting.

You are welcome)

**Comment by kalessil** [comment]
This has been released, let me know if the solution working not as expected, please.

**Comment by coelhoricardo** [comment]
It works, thanks !
