### ISSUE TITLE
Feature request: replace if(isset($x) && $x) with if (!empty($x))

### ISSUE THREAD

**Issue by pascal-hofmann** [kalessil/phpinspectionsea#583]
I suggest adding an inspection that replaces if(isset($x) && $x) with if (!empty($x)).
This is equivalent but shorter. See http://php.net/manual/en/types.comparisons.php

**Comment by kalessil** [comment]
Hi @pascal-hofmann, thank you for the proposal - we'll implement this in one of next releases.

**Comment by kalessil** [comment]
Implemented.
