### ISSUE TITLE
[configuration] random API migration - add option for suggesting random_int

### ISSUE THREAD

**Issue by harley84** [kalessil/phpinspectionsea#59]
Hi
For code containing `mt_rand` references the Random API migration inspection fires that says "mt_rand has recommended replacement random_int, consider migrating".
Now, `mt_rand` is not cryptographically secure, but `random_int` is, but is it enough to justify such migration in all cases? In our case we use `mt_rand` a lot to generate random values for AB testing reasons, for example, and there is no need for cryptographically secure values. 
Extra randomness wouldn't hurt in our case, but I'd believe that there's also a performance penalty for using cryptographically secure generators, no?

**Comment by kalessil** [comment]
I gave a run for 100 000 generation cycles and come up with following numbers:

- random_int - php7.1 took 0.121, php7.0 took 0.098
- mt_rand -  php7.1 took 0.023, php7.0 took 0.018

For 100 000 it's even not noticeable.

**Comment by harley84** [comment]
I agree. It would be more optimal in my opinion if I as a programmer was in control and was able to have a setting in the inspection to not to offer to "upgrade" the cryptography strength. I'll do a pull request later if you're ok with that.

**Comment by kalessil** [comment]
Adding an option is a good idea. Thank you for your offer, but the inspection has no tests yet and I have to do it myself this time.

**Comment by kalessil** [comment]
This has been released, let me know if the solution working not as expected, please.

**Comment by harley84** [comment]
Works great, thanks
