### ISSUE TITLE
array casting replacement

### ISSUE THREAD

**Issue by DarkMukke** [kalessil/phpinspectionsea#591]
when having this code

    if (!is_array($fields)) {
            $fields = array($fields);
    }

and we press Alt+enter to replace the code, it becomes 

    $fields = (array)$fields

but it should be

    $fields = (array)$fields;

**Comment by kalessil** [comment]
Thank you for reporting @DarkMukke, will fix this.

**Comment by kalessil** [comment]
Fixed.
