### ISSUE TITLE
suggesting re-declaration with multiple types in PHPdoc

### ISSUE THREAD

**Issue by DarkMukke** [kalessil/phpinspectionsea#592]
Possible false positive.

Scenario 

    /**
     * @param boolean|array  $maybeArray
     *
     * @return mixed
     */
     public function func($maybeArray= [])
     {

The analyzer suggest that the function declaration be be re-written to 

     public function func(array $maybeArray = [])
     {

But this is not the case because it is the default to be an array. According to the PHPdoc, Booleans are also allowed.

Test case : https://3v4l.org/cbFEV

Inspection should check the PHPdoc for other allowed variables

**Comment by kalessil** [comment]
I don't have a strong opinion here.

I beg pardon for my curiosity, but as from PhpDoc I'd expect the parameter to be `array $maybeArray = false` - also the message is conflicting with the definition. Did I get the right impression?

**Comment by funivan** [comment]
I found only few cases when we can use mixed (or combined) types for single parameter. In other cases
`<type>` or `<type>|null` should be used.
Why you need `bool` value here?
for me it is very confusing phpdoc )

**Comment by DarkMukke** [comment]
I agree it is not perfect, and it is probably more the code (not my code i was just peer reviewing).
However maybe just lower the severity then ?
Or show a different warning when using mixed types on the same parameter ?

**Comment by funivan** [comment]
@DarkMukke in this case I just recommend you to suppress this inspection for this statement. 
https://www.jetbrains.com/help/phpstorm/suppressing-inspections.html

+ You can change severity manually for you current project.
