### ISSUE TITLE
Sometimes suggested solution is not part of the suggestions popup

### ISSUE THREAD

**Issue by iakoder** [kalessil/phpinspectionsea#596]
I ran the Missing or Empty conditionals inspection
Navigating through the results using Cmd+option+down
Popping up the suggestions with Option+return
Often, on the first inspection of a file (I haven't seen it on anything other than an if statement), the "add the group statement" is not in the popup and so I end up selecting "flip if-else".  When I notice the missing option and hit esc to close the popup and then option+return again the "add group statement" is reliably at the top of the popup.  Not sure if this is a PhpStorm issue or since it's one of your inspections if you're in the loop somehow.  I've watched the log while this happens and I don't see anything that corresponds to this happening.  Let me know if you think this is a PhpStorm issue and I'll post there.

PhpStorm 2017.3 EAP
Build #PS-173.3302.10, built on October 18, 2017
PhpStorm EAP User
Expiration date: November 17, 2017
JRE: 1.8.0_152-release-1024-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

Php Inspections (EA Extended) 2.3.11   (thanks for the recent EAP fix)

**Comment by kalessil** [comment]
Oh, it's not only me =)

It's because when you open the file on the reported place, the editor starts inspections there (running inspections bulk/by name results are not injected into the editor). And you are simply faster =)

Just use the fix button directly in results.

You are welcome. Regarding a ticket for PS team: makes sense - that's not a bug, but the usability issue.

**Comment by iakoder** [comment]
Huh, thanks.  There were a few times that I thought it might happen so waited 5-10 seconds before hitting option-return and even in those cases it wasn't long enough.  Maybe those were just exceptionally large files.

I'd started by using the button but dragging the mouse between the two sides of the panel or switching between the keyboard for select next and the mouse to insert the braces was too tedious.  After searching around and discovering the keyboard shortcut for the suggestions popup life was much better (most of the time ;)
