### ISSUE TITLE
PhpUnit: add option for BC, so all assert* reported again

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#6]

**Comment by 3DFace** [comment]
Seems like option does not works with current stable PhpUnit (6.0). Probably cause test cases does not extends expected \PHPUnit_Framework_... anymore?

**Comment by rentalhost** [comment]
@3DFace seems that you are right, but I guess that will be helpful if you could open a new issue about that.

**Comment by 3DFace** [comment]
Sure #141
