### ISSUE TITLE
@throws placement breaks doctype.

### ISSUE THREAD

**Issue by prdatur** [kalessil/phpinspectionsea#601]
My coding style docblock is

<pre>
    /**
     * Process normal messages.
     *
     * @param MstLib_Xmpp_Server_Connection $sender_connection
     *   The sender of this message.
     * @param array $message_array
     *   The incoming message.
     *
     * @return bool
     *   True if messages was consumed by the extension or false if not.
     */
</pre>

If I now throw an exception and fix the "Throws a non-annotated/unhandled exception: '\Mst_Tcp_Exception_SocketWrite'." error.

The `@throws` declaration is placed between return and return description like:

<pre>
    /**
     * Process normal messages.
     *
     * @param MstLib_Xmpp_Server_Connection $sender_connection
     *   The sender of this message.
     * @param array $message_array
     *   The incoming message.
     *
     * @return bool
     * @throws \Mst_Tcp_Exception_SocketWrite
     *   True if messages was consumed by the extension or false if not.
     */
</pre>

My suggestion would be changing the placement as following:

**@throws search**
Look for already existing `@throws` tags if found place it after (Already done) 
If not go to return tag check

Example:
**Before**
<pre>
    /**
     * Description ....
     * @return bool
     *   True if messages was consumed by the extension or false if not.
     * @throws ExistingException
     */
</pre>
**After**
<pre>
    /**
     * Description ....
     * @return bool
     *   True if messages was consumed by the extension or false if not.
     * @throws ExistingException
     * @throws NewException
     */
</pre>

**@return tag search**
Look for `@return` Tag. If found look for next `@` annotation and place the `@throws` tag before this next tag.

Example:
**Before**
<pre>
    /**
     * Description ....
     * @return bool
     *   True if messages was consumed by the extension or false if not.
     *   
     * @see some url
     */
</pre>
**After**
<pre>
    /**
     * Description ....
     * @return bool
     *   True if messages was consumed by the extension or false if not.
     *   
     * @throws NewException
     *   
     * @see some url
     */
</pre>
If not found place it before docblock end.

Example:
**Before**
<pre>
    /**
     * Description ....
     * @return bool
     *   True if messages was consumed by the extension or false if not.
     */
</pre>
**After**
<pre>
    /**
     * Description ....
     * @return bool
     *   True if messages was consumed by the extension or false if not.
     *   
     * @throws NewException
     */
</pre>

With the search for next valid tag or end of docblock, it should be not possible again to break any multiline tags

**Comment by prdatur** [comment]
Maybe also do the "before" placement for **@throws tag search**. It can also be that this has a multi line description.

**Comment by kalessil** [comment]
Thank you for reporting @prdatur.

We'll add multiline description support. Regarding `throws`/`return` tags search: let see, if the approach doesn't bring new complexity into QF, we probably can make it smarter.

**Comment by prdatur** [comment]
Thanks for the commit. Didn't have tested it yet.
Anyway, is there any "easy" way to keep/config the codestyle?
For example in my case. I normally have no new lines between same tags and one empty line between different tags.

<pre>
/**
 * @param ...
 *    Desc
 * @param ...
 *    Desc
 *
 * @return
 *    Desc
 */
</pre>

Currently and I think also the new fixed non-breaking modification also will add the **@throws** tag just below Desc.

Is there a way to get the user configuration "Blank linkes around parameter" and do a blank line if set? Or maybe an own option within the inspection configuration "Exception handling and annotations"?

Hope this makes not much work :) I could live with it that I need to scroll everytime up to correct the style. Would be a nice to have.

**Comment by kalessil** [comment]
@prdatur : the commit is not the fix yet =) 

I'm considering to add tags (simple, non-breaking):
- before the first existing throws tag
- as the last statement in doc-block

DocBlock formatting is what IDE itself addresses - once we modify code the IDE invokes auto-formatting. So perhaps PhpStorm team can give an idea how to deal with thedescribed formatting configuration.

**Comment by kalessil** [comment]
Fixed
