### ISSUE TITLE
UnqualifiedReferenceInspector: add option to only enable for special compiled PHP functions

### ISSUE THREAD

**Issue by jdreesen** [kalessil/phpinspectionsea#605]
Although there is one more step to do for unqualified function calls from inside namespaces [[1]](https://secure.php.net/manual/en/language.namespaces.faq.php#language.namespaces.faq.shortname2), there is some doubt that root-namespacing *every* native PHP function brings measurable perf improvements [[2]](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3048#issuecomment-330095150) [[3]](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3048#issuecomment-330097230) [[4]](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3054#issuecomment-330195999) (especially with enabled opcache [[5]](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3048#issuecomment-330137157)). 

But there are certainly *some special* functions that benefit from this. [[6]](https://github.com/phpspec/phpspec/pull/1152#issuecomment-328800844) [[7]](https://github.com/php/php-src/blob/f2db305fa4e9bd7d04d567822687ec714aedcdb5/Zend/zend_compile.c#L3872) [[8]](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3048#issuecomment-328810072) [[9]](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3048#issuecomment-332784692)

Thus I'd like to have an option to enable this inspection only for those special functions to reduce the visual noise created by the many `\`'s but still benefit from the perf improvements.

*Notice:*
Beware that some of the opcode optimizations seem to only get applied in some cases, see: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3048#issuecomment-328813367

**Comment by kalessil** [comment]
Thank you @jdreesen. 

That's are good points, so let's make reporting the functions default, with the option to report all of them. Then default configuration emits fewer warnings.

**Comment by kalessil** [comment]
Implemented, by default we'll report all constants + the referenced functions.
