### ISSUE TITLE
Composer: Do not suggest 

### ISSUE THREAD

**Issue by ScreamingDev** [kalessil/phpinspectionsea#615]
php EA suggest adding the package "roave/security-advisories:dev-master" to the require section.
Unfortunately the quality assurance via `composer validate` will fail as this package has no proper version.
As Ocramius does not put a version there (for good reasons) the inspection should no longer nag when the package is given in the require-dev part.
Within this part the `composer validate` does not nag about `dev-master`.

![image](https://user-images.githubusercontent.com/2559177/32276105-1766ee5a-bf0e-11e7-8ff2-21edabd6c26b.png)

- see https://github.com/kalessil/phpinspectionsea/blob/master/docs/security.md#security-advisories
- see https://github.com/Roave/SecurityAdvisories/blob/master/README.md#stability
- see https://twitter.com/Ocramius/status/925666318979883008

---

I know how to disable the inspection on this, but IMHO this is some kind of deadlock that php EA can solve best.
In addition I would not disable this inspection as it does more than just nagging about this one package.

**Comment by Ocramius** [comment]
The `dev-master` requirement is intentional and correct there: not sure what you're expecting from EA inspections. The `composer validate` is also correct, but this package is an exception to the rule, by design.

You simply need to drop that validation in your pipeline, introducing other risks instead.

**Comment by ScreamingDev** [comment]
Not sure what you mean.

If you mean dropping the `composer validate` from the CI, then: No, why would I bring in such risks?

If you mean dropping the inspection in EA, then: Nah, I wan't to be informed about the other things this single inspection gives me (here https://github.com/kalessil/phpinspectionsea/blob/master/docs/security.md#security-advisories)

I'm sure that PHP EA can enhance this in some way. Either as it's own inspection to disable it or be good with the package in the "require-dev" part. This would be the simplest solution I guess.

**Comment by kalessil** [comment]
@ScreamingDev: In general I agree with @Ocramius, the less of evils should be selected. 
But also you use-case I see from time to time and finally got an idea to try =)

Can you try using `"roave/security-advisories": "*"` with `composer validate --no-check-all`?
If this is acceptable, I'd simply extended the package version check =)

**Comment by kalessil** [comment]
@ScreamingDev @Ocramius : `composer validate --no-check-all` will allow using dev-master.
If there are no cons, I'm going to add a corresponding note to our docs.

**Comment by ScreamingDev** [comment]
Yee, I knew this would end like this which makes me sad.

Cons still is that I either have no assertion on bound version constraints (really don't wanna loose that)
or phpStorm is nagging about the missing package
or I disable the inspection forgetting about the package from time to time.

Guess I disable this inspection and write my own via simple `grep ` 

Fingers crossed that EA inspections allows this to be in the require-dev part some day which is the less of evils in my scenario.

**Comment by kalessil** [comment]
So, you are still not happy with solution - I guess =)
I'll add 2 options then to disable both parts of the inspection.

**Comment by ScreamingDev** [comment]
Nice! Now I need to come to some PHPUG (like Münster) and give you a hug or beer for this.
Wait for it. May take some weeks ^^

**Comment by kalessil** [comment]
No worries, sure thing looking forward!
