### ISSUE TITLE
Not an Issue: missing hint static public funtion get (?anInstance=[]) 

### ISSUE THREAD

**Issue by JProof** [kalessil/phpinspectionsea#620]
in an earlier release there was an hint such as 
static public funtion get (?anInstance=[])  "do we want to give null or instance"
Perhaps someone can tell me where i can find this.
Thanks

PhpStorm 2017.3 EAP
Build #PS-173.3531.17, built on November 2, 2017
PhpStorm EAP User
Expiration date: December 2, 2017
JRE: 1.8.0_152-release-1024-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by kalessil** [comment]
Look like `Null should be used as the default value (nullable types are the goal, right?)` emitted by `Non-null parameters default value`.
