### ISSUE TITLE
Wrong Null pointer exception (false positive)

### ISSUE THREAD

**Issue by alsii** [kalessil/phpinspectionsea#624]
This bug is similar to #545 one:

![grafik](https://user-images.githubusercontent.com/5807252/32436962-0ca059e4-c2e6-11e7-9ac9-cc35feffc800.png)

The type of $provision has been correctly identified by the IDE:

![grafik](https://user-images.githubusercontent.com/5807252/32436360-19be4228-c2e4-11e7-9492-25e9606157fa.png)

**PHP Extensions (EA Extended) Version: 2.3.11.1**

**PhpStorm 2017.2.4**
Build #PS-172.4155.41, built on September 15, 2017
Subscription is active until November 17, 2017
JRE: 1.8.0_131-8u131-b11-1~bpo8+1-b11 i386
JVM: OpenJDK Server VM by Oracle Corporation
Linux 3.16.0-4-686-pae

**Comment by kalessil** [comment]
Hi @alsii, thank you for reporting. That's a limitation of the inspection - is_* functions are not analyzed, we have documented this already: https://github.com/kalessil/phpinspectionsea/blob/master/docs/probable-bugs.md#null-pointer-exceptions-prevention

I'd suggest using direct null comparison instead (we have an inspection with Quick-fix which can assist you with `is_null` -> `null === `) migration.

**Comment by rentalhost** [comment]
Actually, I think that it is a PS issue, and not an EA. The "inside `if`" type of `$provision` variable should exclude `null` once that you have checked for `!is_null()` before.

Seems related to https://youtrack.jetbrains.com/issue/WI-38622

**Comment by Richard87** [comment]
Hi, I have the same error, and was told to report it here...

It seems to be a problemer everywhere there is multiple statements in if-sentences...

![image](https://user-images.githubusercontent.com/5749715/32596768-bf872628-c534-11e7-9c15-6da56fa23ee6.png)

https://intellij-support.jetbrains.com/hc/en-us/requests/1128403?flash_digest=796b4e5e3cebceb0e49559db1bc58f3483a8f99a

https://3v4l.org/hvDaC

I'm running PHP Inspections EA v.2.3.11.1
![image](https://user-images.githubusercontent.com/5749715/32596914-38a30ee6-c535-11e7-9835-8a455c80f3c0.png)

**Comment by kalessil** [comment]
@Richard87: you case has been fixed already (https://github.com/kalessil/phpinspectionsea/commit/1dd6cf44a6f60b5cdcdd6cb67bb495eb65a46488) in 2.3.12. I plan to release it on these weekends.
