### ISSUE TITLE
[false-positive] null-check should be used instead

### ISSUE THREAD

**Issue by zerkms** [kalessil/phpinspectionsea#625]
```php
function t()
{
    throw new \RuntimeException();
    return 42;
}

try {
    $a = t();
    $b = 7;
} finally {
    if (isset($a)) {}
    if (isset($b)) {}
}
```

for this code both `$a` and `$b` in the `isset` "calls" are marked as "null check should be used instead".

While in generally I prefer to never implement code that relies on existence of variables, in this case it simply demonstrates a convenient pattern for the after-the-failure cleanup:

```php
try {
    $resource1 = ...
    $resource2 = ...
} finally {
    // cleanup whatever had chance to initialise
}
```

While it's possible to pre-declare variables with `$resource1 = null; $resource2 = null;`, etc, this code would look odd in php.

**Comment by kalessil** [comment]
Fixed.
