### ISSUE TITLE
Make variable const

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#637]
It should identify if you have declared some variable statically and never override it. For instance:

```php
class MyClass {
    public function someMethod() {
        $startPos = 5;
        return $startPos;
    }
}
```

So it should suggests you convert `$startPos` to const `START_POS`.

**Comment by kalessil** [comment]
This could be a great intention for @funivan plugin =)

**Comment by rentalhost** [comment]
Hm... I don't mean like an intention, but as an inspection. Don't make sense `$startPos = 5`, if I could just `return 5`. So, if I need that `$startPos = 5`, it means that `5` is a magic value (that could be a string, maybe a boolean), so is important that it be part of a constant property.

The intention does exists, but as a "refactor/extract" on PS.

**Comment by funivan** [comment]
How would you detect this variables? Only when we have int/float or some strings too?

**Comment by funivan** [comment]
Can you show some examples from PHP Frameworks ;)

**Comment by rentalhost** [comment]
For instance (const vs inline). What does make more sense for you?

```php
return $minutes * static::MINUTES_IN_AN_HOUR; // vs.
return $minutes * 60;
```

Or then:

```php
abstract class Animal {
    const ANIMAL_REPRESENTED = null;

    public function isRepresented(array $animals) {
        return in_array(static::ANIMAL_REPRESENTED, $animals);
    }
}

class Dog extends Animal {
    const ANIMAL_REPRESENTED = 'dog';
}

class Cat extends Animal {
    const ANIMAL_REPRESENTED = 'cat';
}

(new Dog())->isRepresented($animals);

// vs.

abstract class Animal {
}

class Dog extends Animal {
    public function isRepresented(array $animals) {
        return in_array('dog', $animals);
    }
}

class Cat extends Animal {
    public function isRepresented(array $animals) {
        return in_array('cat', $animals);
    }
}
```

**Comment by funivan** [comment]
I do not think this is a good idea. For example, take a class and count number of constants that will be created (after implementing this inspection)

For example here is the code `new ConfirmedPaysFilter(new IntEq(0), new LastFewDays(60))` 
I do not want to extract `60` to the constant. 
When I implement some logic.
```
If user hasn't paid for last 10 days
 And he has more than 20 ads
 And he visited website for last 5 days 
then .... 
```
So all this numbers 10, 20, 5 should be converted to the constants. I think the code will be less maintainable. 

P.S. For me all examples are bad. Introduce method `getIndentifier` and implement it. Latest static binding has some drawbacks.

**Comment by rentalhost** [comment]
The last example that you give is same that #293 (magic numbers), but not is what I mean here. I am talking about values that I intentionally expects to extract after by pattern `$var = scalar`. But I am thinking now that it should be an "obscure" feature.

But you are right about the method `getIdentifier()`, it is more consistent than constants, and it could be done by PS by extracting value to method.
