### ISSUE TITLE
Performance issues reports

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#647]
https://twitter.com/mac_hour/status/931878228922372096

**Comment by funivan** [comment]
Performance optimization is good. But I think inspect file containing 29K LOC should be slow! 
P.S. Github can`t even render this file https://github.com/mpdf/mpdf/blob/development/src/Mpdf.php ))

**Comment by kalessil** [comment]
Done, profiling shows we are good.
