### ISSUE TITLE
FP: Throws a non-annotaded/unhandled exception

### ISSUE THREAD

**Issue by mishavantol** [kalessil/phpinspectionsea#652]
The @throws is added to the docblock, but the warning remains.

<img width="654" alt="screen shot 2017-11-22 at 09 44 46" src="https://user-images.githubusercontent.com/2063695/33117888-56c41534-cf6a-11e7-9389-ff9eb688f62d.png">

**Comment by kalessil** [comment]
Hm, looks weird =) I'll check what happens there, which IDE version is it?

**Comment by mishavantol** [comment]
PhpStorm 2017.3 EAP
Build #PS-173.3727.8, built on November 14, 2017
PhpStorm EAP User
Expiration date: December 14, 2017
JRE: 1.8.0_152-release-1024-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.1

**Comment by mishavantol** [comment]
When an @throws is passed from a called function it works as expected. 

<img width="461" alt="screen shot 2017-11-22 at 12 08 19" src="https://user-images.githubusercontent.com/2063695/33124623-ebd373e6-cf7d-11e7-9a97-0cfa4e03be59.png">

**Comment by kalessil** [comment]
Looks like the inspection is broken in the EAP completely, I have to wait for official release.

**Comment by kalessil** [comment]
For myself: annotations are not recognized in the EAP.

**Comment by 6ecuk** [comment]
Phpstorm official released today

**Comment by kalessil** [comment]
Fixed
