### ISSUE TITLE
[False Positive] Renaming class to self using anon. class

### ISSUE THREAD

**Issue by iltar** [kalessil/phpinspectionsea#653]
When you have an anonymous class, you're not allowed to extend/implement `self`or `static`:

![image](https://user-images.githubusercontent.com/1754678/33128087-6deb521a-cf8b-11e7-9be5-cac25521e49c.png)
![image](https://user-images.githubusercontent.com/1754678/33128094-78472978-cf8b-11e7-8284-22bd948c9f74.png)
![image](https://user-images.githubusercontent.com/1754678/33128104-807a4ce2-cf8b-11e7-9fa9-8227e6a2c532.png)

Output from PHP:
```
PHP Fatal error:  Cannot use 'self' as class name as it is reserved
```
Testcase:
```php
class SomeException extends \Exception
{
    public function test()
    {
        return new class() extends SomeException {};
    }
}
```

**Comment by kalessil** [comment]
Will fix, thank you for reporting!
