### ISSUE TITLE
[RFC] Smart checks based on php requirement in composer.json

### ISSUE THREAD

**Issue by iltar** [kalessil/phpinspectionsea#655]
Just now I had opened a project that supported php 5.4 (composer.json), but the inspection suggested me to replace a FQCN string to the `::class` variant. I'm not sure how easy this is to add for checks, but it would be really cool if the inspections could be "disabled" or tell me that it leads to incompatibility if I apply the check.

It could be done the other way around as well, tell me I should add a specific extension or php version to composer.json if I add a currently unsupported feature per configuration. This would probably increase compatibility and reduce the amount of bugs regarding dependencies.

**Comment by kalessil** [comment]
@iltar, are you aware of this feature: https://www.jetbrains.com/help/phpstorm/composer.html -> Synchronize IDE settings with composer.json?

Since PS default language level is 5.6, the inspection suggests using this feature.

**Comment by iltar** [comment]
That means I have to sync it for each project individually (200+ projects) and constantly have to update it if a version changes (which I won't be checking).

**Comment by kalessil** [comment]
Okay, this looks like root-cause already: the system should sync with composer.json.
I'm not sure if this should happen automatically or we just should emit a warning popup about language settings.

@artspb, is anything similar already in development by PS team (if so, which IDE version is targeted)?

**Comment by iltar** [comment]
I'm currently have to update the PHP version manually for each project I have, I do this when I notice that PhpStorm indicates a feature is only available in a later version than configured. If PhpStorm would automatically adjust the PHP version based on my minimum composer version, that would solve all issues, as this plugin can keep using just the PHP version.

**Comment by artspb** [comment]
@kalessil You've provided a proper link above. When synchronization is on PS (since 2017.2) will automatically set the proper language level. If you update `composer.json` manually (or via VCS), the language level will be updated accordingly without any additional action from your side. Did I answer the question?

**Comment by kalessil** [comment]
@artspb : yes.

The use case here need 2 things (can you discuss with the team if you want to pick this up):
- Finding composer.json in the root folder automatically (currently, I have to point onto it manually)
- Enabling synch with composer by default.

This helps to agencies where people have to switch over projects often.

**Comment by kalessil** [comment]
@artspb : if no, then I'd add this behavior to this project.

**Comment by artspb** [comment]
@kalessil We're going to implement both in the next version. Actually, it's already implemented and will be available in the first EAP, see [WI-38826](https://youtrack.jetbrains.com/v2/issue/WI-38826).

**Comment by kalessil** [comment]
@artspb : great, thank you!
@iltar : hold on, the solution will arrive soon.

**Comment by iltar** [comment]
Great news! Thanks both!
