### ISSUE TITLE
Accept "unused private property" if it is used as object

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#656]
If you declare some private property on constructor but never user it, then you receives this message "_property is used only in constructor, perhaps we are dealing with dead code here_".

It is right, but maybe we should ignore if this property is used as object (except for the direct assignment).

Currently:

```
$this->unusedProperty = new Object; // Warning
$this->unusedProperty->someMethod(); // Warning
$this->unusedProperty->someMethod(); // Warning
$this->unusedProperty->someMethod(); // Warning
```

Suggestion:

```
$this->unusedProperty = new Object; // Warning
$this->unusedProperty->someMethod(); // Ignore
$this->unusedProperty->someMethod(); // Ignore
$this->unusedProperty->someMethod(); // Ignore
```

It should avoid double warning for same reason.

![image](https://user-images.githubusercontent.com/421851/33181083-16cfec7c-d056-11e7-9837-2b2a8b559ddf.png)

**Comment by kalessil** [comment]
@rentalhost : agree, we should only report the assignment in this case.

**Comment by kalessil** [comment]
Fixed
