### ISSUE TITLE
[new] Child method is exactly the same

### ISSUE THREAD

**Issue by bram123** [kalessil/phpinspectionsea#66]
Would be useful to have an inspection telling us the child method is exactly the same as the parent's method.

**Comment by samdark** [comment]
Yes, that is indeed useful.

**Comment by kalessil** [comment]
Gladly will pick up the story after #44

**Comment by kalessil** [comment]
Picking this up for the next release.

**Comment by kalessil** [comment]
I pushed the 1st version of the inspection, does anyone want to give it a try?

**Comment by kalessil** [comment]
Hold on

**Comment by kalessil** [comment]
Now can be tested, looking for feedback on this: e.g. if we should add any options like reporting constructors, and etc. )

**Comment by kalessil** [comment]
Tested, looks good.
