### ISSUE TITLE
Detect assign and comparison operators in one statement 

### ISSUE THREAD

**Issue by funivan** [kalessil/phpinspectionsea#662]
Who loves this code ? 
```php
 } while (false !== $currentTheme = $currentTheme->getParent($context));
```
For me this is not readable. Maybe it can be nice candidate for the inspection.
Link to original code: https://github.com/symfony/symfony/blob/e69f9dbc25712b5ca902d5e54462979122b7a20f/src/Symfony/Bridge/Twig/Form/TwigRendererEngine.php#L185

**Comment by kalessil** [comment]
Ok, readability is not so good here. Would `false !== ($currentTheme = $currentTheme->getParent($context))` be more readable?

**Comment by funivan** [comment]
For me the best way is: 
```php
do{
...
 $currentTheme = $currentTheme->getParent($context)
} while (false !== $currentTheme);
```

**Comment by kalessil** [comment]
Ok, that's about structure. I need to think how to encourage end-users for the change.
I personally prefer the un-readable form, but I'll chat with people at UGs about the topic.

**Comment by funivan** [comment]
@kalessil this is just idea. If it is only me (or small amount of devs) then don`t waste the time ;)

**Comment by kalessil** [comment]
Removing "help wanted", ultimate version super-strictly moderated.
That's not a waste, such discussion often are very productive.

**Comment by funivan** [comment]
@kalessil if you do not have time i can implement this feature in my own plugin)

**Comment by kalessil** [comment]
@funivan , yes please!

**Comment by funivan** [comment]
In case if someone is interesting follow https://github.com/funivan/PhpClean/issues/81
