### ISSUE TITLE
Stale bot

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#665]
I do not know that Github had support to bots. Today I see the [**Stale Bot**](https://github.com/apps/stale) and is very useful. I guess that can works for us.

It check if we have some issue inative by more than 60 days (configurable), then advise that it have any update for a long time, then after 7 days (too configurable) it closes the issue.

**Comment by funivan** [comment]
Just awesome. I think it can be useful.

**Comment by kalessil** [comment]
Will add, it'll be like 2 years threshold =)

**Comment by kalessil** [comment]
Done!
