### ISSUE TITLE
NPE false positive

### ISSUE THREAD

**Issue by b1rdex** [kalessil/phpinspectionsea#669]
```php
class A
{
    /**
     * @var A|null
     */
    public static $field;

    public static function method()
    {
        return new self();
    }
}

$var = A::$field ?? A::method();

return $var->foo();
```

`$var->foo()` reported as possible NPE, but `$var` can't be null here.

**Comment by kalessil** [comment]
Probably same as #629 and https://youtrack.jetbrains.com/issue/WI-37013

**Comment by b1rdex** [comment]
Looks you are right, because `$var` type is reported as `A|null` in quick definition. I upvoted issue, ty.

**Comment by kalessil** [comment]
Duplicates #629
