### ISSUE TITLE
Disable `Unhandled Exception` inspection when in test

### ISSUE THREAD

**Issue by Jean85** [kalessil/phpinspectionsea#673]
The new inspection highlights calls that are marked with `@throws` annotation and are not caught nor re-annotated. This is useless and annoying while writing a PHPUnit test, where exceptions will cause test failure (which can be good) or even be expected.

Hence, this inspection should be disabled inside any class that extends `PHPUnit\Framework\TestCase`

**Comment by kalessil** [comment]
@Jean85 : can you post a message examples? PS 2017.3 brings similar inspections, so I want to be sure warnings are  from our plugin.

**Comment by Jean85** [comment]
Ops! I just updated to .3, I may have made this mistake indeed.

The message is the following:

> The inspection reports exceptions which are neither enclosed in a try-catch block nor documented using the '@throws' tag

**Comment by kalessil** [comment]
It's by PS, we are already aware of test classes specific.

**Comment by Jean85** [comment]
Ok thanks! I'll try to report i there!
