### ISSUE TITLE
"Unnecessary final modifier." for private methods in non-final classes?

### ISSUE THREAD

**Issue by donquixote** [kalessil/phpinspectionsea#678]
The "Unnecessary final modifier." warning occurs in two cases:
1. the method is final and the class is final.
2. the method is final and private.

https://github.com/kalessil/phpinspectionsea/blob/7aaf9e2f91434a7d52fd78ccfd421688e95d5898/src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/codeStyle/UnnecessaryFinalModifierInspector.java#L43

I think the second case is not justified. At least there should be a checkbox to disable it.

E.g. a `final private function __construct() {}` can be used to prevent child classes from being instantiated.

A `final private function foo() {}` prevents child classes from overshadowing this method. This is rather useless or exotic. But it is still different from the first case.

So maybe there should be even 3 cases with separate checkboxes:

1. the method is final and the class is final.
2. the method is final and private, and it is a constructor.
3. the method is final and private, and it is not a constructor.

**Comment by kalessil** [comment]
For myself: check if private final blocks overriding in child classes before making any changes.

**Comment by kalessil** [comment]
Thank you for reporting @donquixote

**Comment by kalessil** [comment]
I have checked: you are right, we shouldn't report the case with constructors (but regular methods will be reported - as you mentioned it's really useless).

**Comment by kalessil** [comment]
Fixed
