### ISSUE TITLE
Disable config

### ISSUE THREAD

**Issue by standus** [kalessil/phpinspectionsea#68]
Please help, how to disable some inspections?

**Comment by kalessil** [comment]
There are 2 ways:
- from inspections result (when inspected a folder/project): right lick on the inspection name, click disable inspection;
- Top menu: File -> Settings ->Editor -> Inspections -> Php -> Php Inspections (EA Extended)

**Comment by kalessil** [comment]
@standus : would you please close the issue once checked my hints?
