### ISSUE TITLE
UnqualifiedReferenceInspector incorrectly marks \define()

### ISSUE THREAD

**Issue by leofeyer** [kalessil/phpinspectionsea#681]
The UnqualifiedReferenceInspector incorrectly marks `\define()` as not optimized.

<img width="567" alt="" src="https://user-images.githubusercontent.com/1192057/33684808-da702f6a-dacf-11e7-9300-0d87723ace9b.png">

All other functions added in #605 are recognized correctly.

**Comment by kalessil** [comment]
Thank you for reporting @leofeyer, looks like a bug. Will check.

**Comment by kalessil** [comment]
Fixed

**Comment by leofeyer** [comment]
Thank you.

**Comment by kalessil** [comment]
You are welcome =)
