### ISSUE TITLE
Bug: Suppress for file didn't change a thing

### ISSUE THREAD

**Issue by ScreamingDev** [kalessil/phpinspectionsea#682]
Hi there :wave: 
Please look at the code below which correctly says that `object` is a very loose contract.
But in this class it is okay because the `$message` is allowed to be any kind of object
so I try to suppress this:

![image](https://user-images.githubusercontent.com/2559177/33803153-1b7b6144-dd89-11e7-896e-b7de641265b5.png)

Unfortunately nothing happens afterwards. The message is still there and the header doc-comment of the file did not change.

phpStorm 2017.3 

In addition I wrote `if ($x == 3) {}` where PHPEA wants to see triple equal signs. Again this can not be suppressed for the file.

Is there something I am doing wrong?

### The code

```
<?php
/**
 *
 */

namespace App\Entity;


class Event
{
    /**
     * @var string
     */
    private $event;
    private $message;

    /**
     * Event constructor.
     *
     * @param string $event
     * @param object $message
     */
    public function __construct(string $event, $message)
    {
        $this->event   = $event;
        $this->message = $message;
    }

    /**
     * @return string
     */
    public function getEvent(): string
    {
        return $this->event;
    }

    /**
     * @return object
     */
    public function getMessage(): object
    {
        return $this->message;
    }
}

```

**Comment by kalessil** [comment]
@ScreamingDev : this is something on IDE side, please vote for https://youtrack.jetbrains.com/issue/WI-5784
