### ISSUE TITLE
Not possible to suppress "Missing return statement" for method

### ISSUE THREAD

**Issue by brandonkelly** [kalessil/phpinspectionsea#685]
I think it used to be possible to suppress the "Missing return statement" inspection by placing this above a method:

```php
/** @noinspection PhpInconsistentReturnPointsInspection */
```

but that no longer has any effect. And the "Suppress for file" inspection option doesn't have any effect. Even if it did, that would be a little too heavy-handed. There are only a few _methods_ we would want to suppress that inspection. For Example:

```php
public function __toString()
{
    try {
        return (string)Craft::t('site', $this->name);
    } catch (\Throwable $e) {
        ErrorHandler::convertExceptionToError($e);
    }
}
```

(where `ErrorHandler::convertExceptionToError()` is going to throw a PHP error and end the PHP execution)

**Comment by kalessil** [comment]
@brandonkelly : PhpInconsistentReturnPointsInspection is coming from PhpStorm, not from the plugin this time.

File-level suppression seems to have issues: https://youtrack.jetbrains.com/issue/WI-5784 as well. 
Looks like a candidate for bug-report to JetBrains.

**Comment by brandonkelly** [comment]
Doh sorry :)

**Comment by kalessil** [comment]
No worries =)
