### ISSUE TITLE
Identify needless quotes

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#695]
```php
// Example 1:
echo "{$text}"; // ->
echo $text;

// Example 2:
echo "{$text1}{$text2}"; // ->
echo $text1 . $text2;
```

Quotes is needless here, except if `$text` is number, but in this case it should be `(string) $text` instead. But in general context, I think that a QF could only provies the removal of the quotes. Others inspections could help user to put a casting (_idk_).

**Comment by kalessil** [comment]
I think this should go into community edition =)

**Comment by rentalhost** [comment]
Oh, okay. I just not understand what should be Community or Ultimate for now. So next time I will keep it opened. :smiley:

**Comment by kalessil** [comment]
Probable bugs and security are coming to Ultimate, the rest - into Extended. Plus I'm not really want to go into code style too deep, so the Extended concept is migration support mainly. //cc @funivan

**Comment by funivan** [comment]
IMHO
Probable bugs, security and performance are coming to Ultimate

> I'm not really want to go into code style too deep 

+1 for that ;)

**Comment by kalessil** [comment]
I implemented `Example 1` case: `"$x"`/`"{$x}"` -> `(string) $x`. Some practices are promoting to go from concatenation to string with injected fragments, so I think we should not push in any direction there.

**Comment by rentalhost** [comment]
Hmm... I think that `(string)` should be put only if `$x` is not strictly a string.

**Comment by kalessil** [comment]
We have unnecessary type casting inspection, it will cover this.
