### ISSUE TITLE
Identify quoteable concatenation

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#696]
In a reverse side of #695, we could identify some possibles quoteable concatenations.

```php
// Simple example.
echo 'User: ' . $user; // ->
echo "User: {$user}";

// Multiline example: multine should be respected here.
echo 'User: ' . $user . "\n" . 
     'Age: ' . $age; // ->
echo "User: {$user}\n" . 
     "Age: {$age}";
```

**Comment by kalessil** [comment]
I think we could pick-up single-line case for ultimate (also opcode optimizations gets applied, what's cool IMO)

**Comment by rentalhost** [comment]
Hmm... you mean to turn the multiline into singleline? If yes, I think that is not a good option, because I personally split into multiline to make the code more readable in some cases.

**Comment by funivan** [comment]
@rentalhost I agree with @kalessil 
In the following case, we should fire a notice
```php
echo $name." test"; 
```
But we should skip multilines:
```php
echo "name : ".$name . "\n"
." id : " .$id."\n"
." created : ".$created."; 
```

**Comment by kalessil** [comment]
Re-scheduling for EA Extended, as EA Ultimate focus is very clear now.

**Comment by kalessil** [comment]
I'll skip this in order to not go into code style too much.
