### ISSUE TITLE
Limit comments on class

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#697]
Okay, I know. It will sound very much controversial. But now I'm working with as few comments as possible. And belive, it works a lot. I read in some place (_sorry, I don't remember where_) that if you have too much comments in your code, you don't know how name your methods and variables, and is possible that your class have more responsability than it should.

For instance:

```php
class Clock {
    public function getHours() { }
    public function getMinutes() { }
    public function getSeconds() { }
}
```

_Can you understand what this class does, without need additional comments. Right?_

So I think that we can implement an inspection that check if your class have more than a limit of comments (_should be customizable_):

* Over 2 methods commented (ignoring `@` attributes);
* Over 2 properties commented (ignoring `@` attributes);
* Over 0 variable on method commented (ignoring `@` attributes);
* Over 0 singleline comment outside method (on class body);
* Over 2 singleline comment on an unique method (inside);
* Over 0 multiline comment on an unique method (inside);

And okay... maybe you will question about documentable code sources. But how I told, if your property or method tells all that you need, why you need a description? It generally creates overcomplexed documentations, that hinders more than aid.

**Comment by kalessil** [comment]
I don't have any opinion on the topic, but people are working with information differently and this case should be covered on code review. For project it'll be better to leave this for humans =)

**Comment by funivan** [comment]
Agree with all. But making inspection can't cover if we need some comment or not. This responsibility goes to the reviewer.
