### ISSUE TITLE
Option to disable visibility check for const

### ISSUE THREAD

**Issue by donquixote** [kalessil/phpinspectionsea#699]
Follow-up to #501

Add a checkbox to disable "Access modifier shall be defined" inspection for const.

## Motivation

Until now, I did not care about adding a "public" keyword before "const".
I think I might start doing it sooner or later.
But until then, I think I would rather disable it the inspection for const.

Maybe others are in a similar situation. It might be generally useful but developers want to choose the time at which they start caring.

**Comment by kalessil** [comment]
Makes sense, I'll add the needed option.

**Comment by kalessil** [comment]
Done

**Comment by donquixote** [comment]
Thanks! You are a good maintainer who cares for his project!

**Comment by kalessil** [comment]
You are welcome =)

**Comment by kalessil** [comment]
BTW, if you have some resources free help is welcome:
- PRs to clean up my grammar or share expertise by extending docs (https://github.com/kalessil/phpinspectionsea/tree/master/docs);
- https://www.patreon.com/kalessil or https://plugins.jetbrains.com/plugin/10215-php-inspections-ea-ultimate- also an option;

**Comment by donquixote** [comment]
Hi, it looks like I ignored your last comment. But I did not!
I put a lot of free time into my own OSS projects, so I feel that my karma is in balance. I don't think any of those would be directly useful to you atm.. So I may consider to contribute anyway, if/when I have free resources.

**Comment by kalessil** [comment]
@donquixote : no worries =) Hope so (about some free resources) xD
