### ISSUE TITLE
"Return type hint can be used" -> Propose to "Refactor / change signature"

### ISSUE THREAD

**Issue by donquixote** [kalessil/phpinspectionsea#701]
If a "return type hint can be used" is found ina  method that implements or overrides a parent or interface method, propose to refactor the interface instead of just changing this one occurence.

**Comment by kalessil** [comment]
Good catch @donquixote, I obviously forgot to check this case.

**Comment by kalessil** [comment]
Fixed, now change signature is promoted for overridden/implemented methods.
