### ISSUE TITLE
Add inspection "parameter type hint can be used"

### ISSUE THREAD

**Issue by donquixote** [kalessil/phpinspectionsea#702]
Similar to "Return type hint can be used", add inspection "Parameter type hint can be used".

**Comment by funivan** [comment]
I think this is the same issue https://github.com/kalessil/phpinspectionsea/issues/834

**Comment by kalessil** [comment]
Not sure. Dropping into release, so I don;t forget to find it out.

**Comment by kalessil** [comment]
Duplicates #834
