### ISSUE TITLE
Detection of unhandled promises

### ISSUE THREAD

**Issue by kelunik** [kalessil/phpinspectionsea#707]
Promises are placeholders for the future result of an operation in asynchronous programming. ReactPHP and Amp both make use of them. Return values aren't returned directly, but wrapped in a promise, that might be resolved immediately or somewhere in the future. The same applies to exceptions, which might only occur after the function has already returned. These are said to fail the promise.

If a function returns a promise and the return value isn't used, a warning should be issued. This allows catching unhandled promises, which go otherwise unnoticed if an exception occurs, which can make debugging really hard.

This applies to the return types `Amp\Promise` and `React\Promise\PromiseInterface`.

**Comment by kalessil** [comment]
A sub-set of #1026
