### ISSUE TITLE
Exceptions vs class hierarchy

### ISSUE THREAD

**Issue by donquixote** [kalessil/phpinspectionsea#719]
Depending which exception philosophy one is using, a class method may only throw exceptions that are declared in the parent or interface method.

It would be nice if EA Extended would have an inspection to check verify this.

Example:

```php
interface I {
  /**
   * (throws nothing)
   */
  function foo();
}

interface J extends I {
  /**
   * @throws \Exception - here we should see an inspection warning.
   */
  function foo();
}
```

On the @throws \Exception in `J::foo()`, there should be an inspection warning "Exception not declared in parent method declaration."

The same covariance rules should apply here as they do for return types.
(native return types do not support covariance, but phpdoc @return does)

**Comment by kalessil** [comment]
Duplicates #14
