### ISSUE TITLE
Use named dataset on dataproviders

### ISSUE THREAD

**Issue by malukenho** [kalessil/phpinspectionsea#725]
It would be nice to have that as a rule/hint for phpunit `dataProviders` :)

**Comment by kalessil** [comment]
Makes sense, thank you for reporting @malukenho 

For myself:
- dataProvider: valid reference
- ensure referenced method returns an associative array

**Comment by kalessil** [comment]
Done, optional behaviour which needs to be enabled.

**Comment by kalessil** [comment]
Included in 2.3.15.1 which I just released, have fun =)

**Comment by malukenho** [comment]
Awesome! Thank you so much @kalessil 🎉

**Comment by kalessil** [comment]
You are welcome =) Hopefully it works as expected =)
