### ISSUE TITLE
Configurable one time use variable line length?

### ISSUE THREAD

**Issue by arcticlinux** [kalessil/phpinspectionsea#726]
Thoughts about making the 80 character limit on one time use variables a configurable option, on/off, # of characters?   We've been removing a number of these in our codebase and I saw an example in our code but the inspection wasn't thrown on it, so I dug into the code to find the character limit.  

At the very least I would add the 80 character limit into the description

https://github.com/kalessil/phpinspectionsea/blob/ef48c0c83378c0701b935e44c699e5d58ae7b7ca/src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/semanticalAnalysis/OneTimeUseVariablesInspector.java#L94

Reference
https://github.com/kalessil/phpinspectionsea/blob/2cf03442a82a4b3297c9734eaed3227e0214d7b1/src/main/resources/inspectionDescriptions/OneTimeUseVariablesInspection.html#L3

**Comment by kalessil** [comment]
@arcticlinux : sounds like something I've missed =) Will add settings for limit configuration.

**Comment by kalessil** [comment]
Done: new settings available. @arcticlinux : do you need a fresh build or waiting for the next release is ok?

**Comment by arcticlinux** [comment]
I'm not in a rush, just thought it was a good idea.

**Comment by kalessil** [comment]
=) It's a good idea for sure!
