### ISSUE TITLE
Allow to opt-out from sending crash report/statistics

### ISSUE THREAD

**Issue by ricardask** [kalessil/phpinspectionsea#728]
Hello, first of all thank you for a superb plugin.

Maybe it would be possible to implement a functionality to opt-out from sending crash reports and statistics.

**Comment by rentalhost** [comment]
From top of my mind, I think that you send crash report only if you want, and it is a very technical report (your code will be not send together).

**Comment by kalessil** [comment]
@rentalhost : crash-reports in the project are currently sent automatically without interacting with end-user.

@ricardask : I'll schedule the task for the next release, but most probably it'll happen within 2-3 releases (task is pretty big + bugs rate change can push it away from the release scope).
PS: you are welcome =)

**Comment by kalessil** [comment]
Done
