### ISSUE TITLE
False positive for "value is immediately overwritten"

### ISSUE THREAD

**Issue by DCoderLT** [kalessil/phpinspectionsea#729]
if (true) {
        $a = 1;
        echo $a;
    }
    $a = 2; // produces a false notice "$a is immediately overwritten"
    echo $a;

The value of `$a` is used inside the conditional, so the inspection is not correct in this case.

**Comment by kalessil** [comment]
Thank you for reporting @DCoderLT, I'll fix the case.

**Comment by kalessil** [comment]
I checked implementation, the inspection spots case correctly. I'd propose to rename the variable inside the if statement.
