### ISSUE TITLE
[new] Warn if default value is passed for last arguments

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#73]
This should checks if you are passing the default value of a method. But it should occur only if it's explicit. For instance:

```
function method($a = 0, $b = 0) {
}
```

Then:

```
method();     // Valid.
method(1);    // Valid.
method(0);    // Warn: you can omit the LAST argument (+fix).
method(1, 0); // Warn: you can omit the LAST argument (+fix).
method(0, 0); // Warn: you can omit the LASTS TWO arguments (+fix).
method(0, 1); // Valid.
```

Unfortunatelly PHP have no `default` keyword, then the last should be accept too. 😄

**Comment by funivan** [comment]
One important thing. If someone will change default argument.
```
// old code
function calculateDiscount($dealer, $days = 10) {
 // Calculate dealer discount depending on last 10 days activity
}

// new one. Change last argument value
function calculateDiscount($dealer, $days = 20) {
}
```
In this cases all calls `calculateDiscount($dealer, 20)` become invalid and we should fix it. 
This is really specific case.
