### ISSUE TITLE
Default parameter hint also on usage __CLASS__

### ISSUE THREAD

**Issue by dpauli** [kalessil/phpinspectionsea#733]
I found an exception for the hint

> The argument can be safely dropped, as it identical to the default value.

Look at the following code
```
class A {
}
class B extends A {
   function bar($className = __CLASS__) {
      ...
   }
}
```

Calling `A::bar()` will be an other result than `A::bar(__CLASS__)`. In first call the `$classname` is `B`, in second call its `A`.

Inspections says: you can drop this parameter value.

**Comment by kalessil** [comment]
Good catch @dpauli - I'll fix it.

**Comment by kalessil** [comment]
Fixed
