### ISSUE TITLE
[new] Warn if argument default value is not null

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#74]
It should be tell the coder how to improve code usability. Basically, when you accept only `null` as a default value for arguments, you could too use `null` to use it default value. For instance:

```
function badCalculateRadial($radius, $pi = M_PI, $multiplier = 1) {
    return $radius * $pi * $multiplier;
}
```

In this case, if you wants to modify the `$multipler`, but keeps the `$pi` value, you need to rewrite it. It's bad because you can broke your code if this code changes on future.

```
badCalculateRadial(5); // Ok.
badCalculateRadial(5, M_PI, 2.5); // Rewrite $pi?
```

Then, for stop this issue, we can just tells to user accepts only `null` as default value. If value is null, then the own method should set a default value for user then it is needly.

```
function goodCalculateRadial($radius, $pi = null, $multiplier = null) {
    return $radius * ( $pi ?? M_PI ) * ( $multiplier ?? 1 );
}
```

Then now you can do:

```
goodCalculateRadial(5); // Ok.
goodCalculateRadial(5, null, 2.5); // Ok, too.
```

Maaaybe you can not suggests the `null` usage for the last argument (because it can just be skipped). But I still guess that: or suggests for all, or suggests for none.

**Comment by kalessil** [comment]
- PHP7 and higher?
- Code style?

**Comment by rentalhost** [comment]
It could be compatible with any version. I guess that it is a code style, yes.

**Comment by kalessil** [comment]
And I also added a documentation chapter: https://github.com/kalessil/phpinspectionsea/blob/master/docs/code-style.md#non-null-parameters-default-value

A PR with the chapter extension and grammar fixes is welcome.
