### ISSUE TITLE
Enhancement: With "Type compatibility -> Foreach source to iterate over" let it work with is_iterable() same as is_array()

### ISSUE THREAD

**Issue by tfettig01** [kalessil/phpinspectionsea#743]
This works pretty great:
```php
/**
 * @param mixed $value
 *
 * @return bool
 */
function validateAsArray($value)
{
    if (is_array($value)) {
        $is_valid = true;
        foreach ($value as $sub_value) {
            $is_valid = $is_valid && validateAsArray($sub_value);
        }
        return $is_valid;
    }

    return false;
}
```
This is the same exact code except using is_iterable.  Notice that $value in the foreach() is highlighted as an error.
```php
/**
 * @param mixed $value
 *
 * @return bool
 */
function validateAsIterable($value)
{
    if (is_iterable($value)) {
        $is_valid = true;
        /* @varRemoveThisToSeeItWork array|\Traversable $value */
        foreach ($value as $sub_value) {
            $is_valid = $is_valid && validateAsIterable($sub_value);
        }
        return $is_valid;
    }

    return false;
}
```

Might be close to https://github.com/kalessil/phpinspectionsea/issues/441 but I don't think its the same.

**Comment by kalessil** [comment]
@tfettig01 : it's the same as #441 (or https://youtrack.jetbrains.com/issue/WI-15715). 
On my end I can introduce couple new settings:
- Request better specification for mixed (your case)
- Request missing types specification (when type is unknown at all)

Will this work for you?

**Comment by tfettig01** [comment]
@kalessil,

Well hopefully whoever pointed https://github.com/kalessil/phpinspectionsea/issues/441 over to https://youtrack.jetbrains.com/issue/WI-15715 was correct in their assessment.  I'm not too hopeful for a 6 year old issue to be resolved.

Anyway if there isn't anything that can be done because of JetBrains, whatever you can provide would be great.  

Thank you.

**Comment by kalessil** [comment]
Settings has been added
