### ISSUE TITLE
GetClassUsageInspector: miss and false positive

### ISSUE THREAD

**Issue by 5lava** [kalessil/phpinspectionsea#747]
![image](https://user-images.githubusercontent.com/63829/34954464-9193c66a-f9ee-11e7-819d-ea530695036c.png)

`foo3()`: miss
`foo5()`: false positive

**Comment by rentalhost** [comment]
I think that it could be fixed on EA, but is more related to a PS issue (I have opened [WI-39614](https://youtrack.jetbrains.com/issue/WI-39614) to help).

**Comment by kalessil** [comment]
Correct, in this case, type information is coming from IDE. It was multiple issues reported already to PhpStorm team.

On our end, I'll look into `foo3` case - looks like I can introduce a fix there.

**Comment by 5lava** [comment]
Can't thank you enough guys. You make the world a better place :)

**Comment by kalessil** [comment]
@rentalhost @5lava also please vote for https://youtrack.jetbrains.com/issue/WI-38622 - it looks very similar to the reported case.

**Comment by 5lava** [comment]
Voted for both.

**Comment by kalessil** [comment]
Fixed `foo3` case: it getting reported now.

**Comment by kalessil** [comment]
@5lava : remaining issues has been fixed in #784 (workaround for WI-38622)

**Comment by 5lava** [comment]
Thank you!
