### ISSUE TITLE
PhpMissingParentCallCommonInspection false alarm

### ISSUE THREAD

**Issue by 5lava** [kalessil/phpinspectionsea#749]
![image](https://user-images.githubusercontent.com/63829/34959352-28ca9ab2-fa04-11e7-881c-2a77e19db5e2.png)

**Comment by kalessil** [comment]
Thank you for reporting @5lava, I'll deal with the bug.

**Comment by kalessil** [comment]
I checked and looks like the issue needs to be reported at https://youtrack.jetbrains.com/issues/WI
Our messages look like '__construct is probably missing MissingParent::__construct call.', and this one probably from IDE bundled inspections.
