### ISSUE TITLE
Conflicting exception inspections.

### ISSUE THREAD

**Issue by DroneZzZko** [kalessil/phpinspectionsea#751]
I got very weird behavior for the exception inspection
```php
<?php

class NotFoundHttpException extends \Exception
{
}

class Entity
{
    public static function find(int $id)
    {
        return $id ? new self() : null;
    }
}

class ClassB
{
    /**
     * @param int $id
     *
     * @return Entity
     * @throws NotFoundHttpException
     */
    public function actionView(int $id): Entity
    {
        return (new ClassA($id))->getEntity();
    }
}

class ClassA
{
    private $entity;

    /**
     * @param int $entityId
     * @throws NotFoundHttpException
     */
    public function __construct(int $entityId)
    {
        $entity = Entity::find($entityId);
        if ($entity === null) {
            throw new NotFoundHttpException('Entity not found.');
        }
        $this->entity = $entity;
    }

    public function getEntity(): Entity
    {
        return $this->entity;
    }
}
```
There is only one the weak warning for the method ClassB::actionView():

> Exception 'NotFoundHttpException' is never thrown in the function

If remove this annotation we get another warning:

> Throws a non-annotated/unhandled exception: '\NotFoundHttpException

There is no way to fix this except to disable the exception inspections.

**PhpStorm 2017.3.2**

**Comment by kalessil** [comment]
@DroneZzZko, it's 2 options here:
- use PhpStorm EAP version, where https://youtrack.jetbrains.com/issue/WI-37946 has been fixed (the root cause here)
- disabling one of the inspections (PhpStorm bundled one or one from Php Inspections (EA Extended))

Hope this helps.
