### ISSUE TITLE
Idea: support beberlei/assert assertions

### ISSUE THREAD

**Issue by asgrim** [kalessil/phpinspectionsea#754]
Currently, I believe phpunit assertions work for helping determine types, e.g.:

```php
private function x(\stdClass $b)
{
}

/**
 * @return \stdClass|null
 */
private function g()
{
}

private function y()
{
    $g = $this->g();
//    \PHPUnit\Framework\Assert::assertNotNull($g);
//    \Assert\Assert::that($g)->notNull();
    $this->x($g);
}
```
If the PHPUnit assertion `assertNotNull($g)` is uncommented, the Null pointer exception goes away (awesome!)

However, the `beberlei/assert` assertion is not recognised... uncomment `\Assert\Assert::that($g)->notNull()`, but the null pointer exception remains (boo! hiss!)

Wonder if support for this great assertion library (to be clear: [beberlei/assert](https://packagist.org/packages/beberlei/assert)) could be added at all?

Example use case: I often use `beberlei/assert` in production, but `phpunit` assertions only in a `require-dev` dependency, so may not exist.

**Comment by kalessil** [comment]
Will do.
For myself: + `Assertion::notNull`

**Comment by kalessil** [comment]
Done

**Comment by asgrim** [comment]
wow, that was quick, thanks @kalessil :+1:

**Comment by kalessil** [comment]
You are welcome James =)
