### ISSUE TITLE
Null reference: follow up on #738

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#760]
https://github.com/kalessil/phpinspectionsea/issues/738#issuecomment-358711340

**Comment by dkushnikov** [comment]
I just checked 2017.3.3 non-EAP (yesterday was released). Bug still occurred.

**Comment by dkushnikov** [comment]
@kalessil can you confirm this issue? Or it's my env problem?

**Comment by kalessil** [comment]
@dkushnikov : just checked on PS 2017.3.3 - cannot reproduce.

Last check: for `'info' => $this->getInfo()->getValue()`, which types shown for `->getInfo()` when pointing the cursor and holding Ctrl?

**Comment by kalessil** [comment]
Weird. Types are ok and my implementation fires warnings only if null/void would present among the types. Is it the only case or you have multiple of them in your project?

**Comment by kalessil** [comment]
Ping @dkushnikov: does the issue still there?
I'll close issue, and will reopen when feedback is here =)
