### ISSUE TITLE
Introduce inspections.xml (replacement for pushing .idea folder)

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#762]
- Monitor changes and tweak IDE settings
- Support profiles, disabling, enabling and severity change
- Tweak php language inspections

**Comment by funivan** [comment]
Why is standard `.idea/inspectionProfiles/` now working for you? 
You can create multiple inspection profiles, change severity for different scopes, share it with all team members. Also configure PhpInspectionEA inspections, standard inspections, and custom in a single file.

**Comment by kalessil** [comment]
Meh, pushing .idea folder requires knowledge how IDE stores settings. The community is getting bigger, so we need an alternative - complaints appearing in JB bug-tracker as well.

**Comment by funivan** [comment]
So community members want to share inspection from "PhpInspectionsEA" but skip sharing standard inspections? 

p.s. anyway `.xml` is the best format for this task;)
