### ISSUE TITLE
Report overriding PHPUnit\Framework\TestCase::__construct without parent::__construct

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#766]

**Comment by tomzx** [comment]
Is there an inspection that already takes care of notifying the user he isn't calling the parent constructor, if said parent (or ancestors) constructor is not empty?

**Comment by kalessil** [comment]
Yes: check here com/kalessil/phpStorm/phpInspectionsEA/inspectors/magicMethods/MagicMethodsValidityInspector.java:67 for the implementation.

**Comment by kalessil** [comment]
Covered by an existing inspection already + we have plenty of work around PhpUnit ahead.
