### ISSUE TITLE
void type hint is not suggested when implementing interface

### ISSUE THREAD

**Issue by rdohms** [kalessil/phpinspectionsea#767]
Ok I managed to nail down after our twitter conversation.

This sample does not show the suggestion (note the interface)
```
<?php
declare(strict_types=1);

namespace Usabilla\FeedbackConsolidation;

use Behat\Behat\Context\Context;
use Behat\Behat\Tester\Exception\PendingException;

final class Dummy implements Context
{
    public function voidMethod()
    {
        throw new PendingException();
    }
}
```

but this one, does
```
<?php
declare(strict_types=1);

namespace Usabilla\FeedbackConsolidation;

use Behat\Behat\Context\Context;
use Behat\Behat\Tester\Exception\PendingException;

final class Dummy
{
    public function voidMethod()
    {
        throw new PendingException();
    }
}
```

the moment you add the interface, it stops suggesting the void typehint.

**Comment by kalessil** [comment]
Looks like a bug, will fix it. Thank you for investigation!

**Comment by kalessil** [comment]
@rdohms : fixed. I also pushed a fresh binary: https://github.com/kalessil/phpinspectionsea/raw/master/PhpInspectionsEA.jar (do you know how to install it?).

**Comment by rdohms** [comment]
Yep, installed, tried, confirm its working now. Thanks!

**Comment by kalessil** [comment]
You are welcome, have fun!
