### ISSUE TITLE
False positive: "cannot iterate null" with null-coalescing

### ISSUE THREAD

**Issue by afoeder** [kalessil/phpinspectionsea#774]
![image](https://user-images.githubusercontent.com/1125168/35503079-55fc526a-04df-11e8-9857-2a3da938e5e4.png)

Sorry for throwing it at you that way, have to speed-production-debug but stumpled upon this :)

**Comment by kalessil** [comment]
Looks familiar, I'll check what I can do here.

**Comment by kalessil** [comment]
Fixed

**Comment by kalessil** [comment]
Also fixes #629
