### ISSUE TITLE
NestedPositiveIfStatementsInspector::applyFix changes logic

### ISSUE THREAD

**Issue by pascal-hofmann** [kalessil/phpinspectionsea#776]
`NestedPositiveIfStatementsInspector::applyFix` should always use `&&` when merging if statements. Otherwise it will modify behaviour of the code.

https://github.com/kalessil/phpinspectionsea/blob/a6e7795a76dcee4190b36d5a863c3786d15c7990/src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/ifs/NestedPositiveIfStatementsInspector.java#L138

Edit: Caution: The existing conditions need to be put into brackets if they contain `||`)

**Comment by kalessil** [comment]
@pascal-hofmann, can you provide an example of the case please?

**Comment by pascal-hofmann** [comment]
Of course:
```
if ($a || $b) {
    if ($c || $d) {
        …
    }
}
```

will at the moment be changed to
```
if ($a || $b || $c || $d) {
    …
}
```
which is not logically equivalent.

**Comment by kalessil** [comment]
Fixed
