### ISSUE TITLE
Alias functions usage - false alarms when importing functions

### ISSUE THREAD

**Issue by amcsi** [kalessil/phpinspectionsea#78]
There's this library called iter where there's a namespaced function called `join()` https://github.com/nikic/iter/blob/master/src/iter.php

If I'm using that library and importing the function...

```php
use function iter\join;
```

Then using the `join()` function in that PHP file still crosses the use out saying that it's a deprecated function.

I believe if an alias function is overridden with an import, then it shouldn't cross the function call out saying that it's deprecated.

**Comment by kalessil** [comment]
Thank you for reporting @amcsi , the fix  will be available with next release.

**Comment by amcsi** [comment]
@kalessil I don't know if it matters, but I noticed that even if I don't import the functions, if I reference such a function name, it shows me a deprecation cross-out.

**Comment by kalessil** [comment]
This will be covered: Namespaces are taken into the account.

**Comment by amcsi** [comment]
@kalessil I have version `2.3.4` and aliased function names overriding deprecated global functions are still crossed out.

**Comment by rentalhost** [comment]
@amcsi Can you produce a reduced example based on this file that you have reported?

**Comment by kalessil** [comment]
@amcsi we have a problem in PS  EAP-version with function resolving (-> #170), so I wondering which PS version you are using and if we have the same problem here.

**Comment by amcsi** [comment]
@kalessil version 2016.3.3
The issue only happens if the function import is being done in a different file than the definition. If it's in the same file it's okay.

**Comment by kalessil** [comment]
@amcsi: I see. Will try to reproduce the case.

PS: @rentalhost, it was a good idea to request the code sample - that's a new case.

**Comment by rentalhost** [comment]
@kalessil Okay, I did and the issue really do exists.

**JoinNamespace.php:**

```php
namespace JoinNamespace {
    function join()
    {
    }
}
```

**JoinTest.php:**

```php
include_once __DIR__ . '/JoinNamespace.php';

use function JoinNamespace\join;

join();
```

Here, `join()` is the imported function, not the `\join()`.

**Comment by kalessil** [comment]
Fixed finally.
