### ISSUE TITLE
FP: may not support offset operation in string contexts

### ISSUE THREAD

**Issue by paveldvorak5** [kalessil/phpinspectionsea#780]
`
$str = \substr( $str, 2 );
if( $str[ 0 ] === '+' ) {
	$str = \substr( $str, 1 );
}
`
it says may not support offset operation
but it's impossible because there is and if before
if( ( strncmp( $str, '00', 2 ) === 0 ) ...

**Comment by kalessil** [comment]
What IDE shows when pointing the cursor onto `$str[ 0 ]` and clicking Ctrl (which types are there)?

**Comment by paveldvorak5** [comment]
pointing string|bool, clicking string
problem is, that all str function returns false on failure
but i usually have some if before, so it's false positive

**Comment by kalessil** [comment]
Got it. Has been fixed.
