### ISSUE TITLE
NPEs: a false-positive

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#781]
https://twitter.com/brandonkelly/status/956954255176351744

**Comment by brandonkelly** [comment]
To reproduce that one, run this:

    composer create-project -s RC craftcms/craft

I've seen it in a few places, but one of them will be:

vendor/craftcms/cms/src/migrations/Install.php - see the `createIndexes()` and `addForeignKeys()` methods.

**Comment by kalessil** [comment]
Ok, thank you =)

**Comment by rentalhost** [comment]
It's the same issue from #738

**Comment by kalessil** [comment]
@rentalhost : yes, it's quite the same.

**Comment by kalessil** [comment]
Fixed
