### ISSUE TITLE
Alias functions: new ones

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#792]
http://php.net/manual/en/migration71.incompatible.php#migration71.incompatible.rand-srand-aliases

**Comment by rentalhost** [comment]
I think that the ugly names should be part of this inspection as an additional option (disabled by default). It is really ugly, but anyway is an alias and some users could prefer avoid totally aliases without care about the "uglyness".

**Comment by kalessil** [comment]
@rentalhost : here the list:

odbc_field_precision — Alias of odbc_field_len()
mysqli_execute — Alias for mysqli_stmt_execute()
imap_header — Alias of imap_headerinfo()

I'd rather add them without settings if the origins are not so ugly as I think (you know, the plugin is very opinionated =))

**Comment by kalessil** [comment]
@rentalhost : added them

**Comment by rentalhost** [comment]
Oh, but in that case I prefer avoid uglies haha...

Forgets! I think that if the inspection was created to avoid aliases, so we should keeps the ugly ones, unfortunatelly. haha
