### ISSUE TITLE
Incorrect inspection error with foreach over iterable

### ISSUE THREAD

**Issue by cpriest** [kalessil/phpinspectionsea#793]
It's showing cannot iterate over bool|int|string on a branching type path.  I'm not sure where it's even getting bool or string from (perhaps from the __get() @return values).

In any case, the below short video demonstrates what's going on and what PhpStorm thinks of the various elements.

![inspection issue](https://user-images.githubusercontent.com/159323/36037490-96a4795e-0d82-11e8-9f5b-8b0e5a64c904.gif)

**Comment by cpriest** [comment]
Thank you for your contributions to OSS, I appreciate it.  I also work on some OSS projects of my own and I know the thanks can sometimes not be enough.  I also just became a patreon of the project as well.

**Comment by kalessil** [comment]
Thank you for your support @cpriest, it's appreciated =) I promise it'll be used for good (I'll also send you a Php Inspections (EA Ultimate) license at weekends already) =)

**Comment by kalessil** [comment]
Also, talking about OSS, is the code sample OSSed as well - the behaviour looks pretty strange and needs detailed investigation (is it the latest plugin version)?

**Comment by cpriest** [comment]
Unfortunately it's in my companies project which is not public code.

If you watch the video though you'll see the chain of classes that are 
involved.  Most of those are resolved via @property values.

**Comment by kalessil** [comment]
Oh, then for sure I need definitions of the objReferenceList and tblEmailListID **properties**, so I could build a similar test case. Will this work for you?

**Comment by cpriest** [comment]
Sure, I could post here a cut down version of the code I think that would reproduce it.  I've been out last week, but will try and get this to you next week.

**Comment by kalessil** [comment]
We dropped legacy type resolver, so the issue suppose to go away with the next update.
@cpriest : if next update doesn;t solve it, we'll reopen the issue.
