### ISSUE TITLE
Replace backtick to shell_exec()

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#797]
Backticks have the same effect as `shell_exec()`, but it could causes confusion because in some fonts you will see something like a quote.

**Todo:**
* **Inspection**: suggests replace backtick to `shell_exec()`;
* **Quick-fix**: escaped backticks inside backticks should be unescaped;
* **Quick-fix**: unescaped single quotes inside backticks should be escaped;

**References:**
* http://php.net/manual/en/language.operators.execution.php
* https://wiki.php.net/rfc/deprecate-backtick-operator

**Comment by kalessil** [comment]
Oh my, I wasn't even aware of this crap. Goes to language level migration (hopefully PS parser recognizes this construct at all)
