### ISSUE TITLE
Throwing an exception from a closure

### ISSUE THREAD

**Issue by 5lava** [kalessil/phpinspectionsea#806]
...~drives nu~ slightly confuses PHPIEA:

![image](https://user-images.githubusercontent.com/63829/36338763-8c826b58-1385-11e8-914b-c3f99fba4afb.png)

**Comment by tomzx** [comment]
What would be the behavior to expect? Given that the anonymous functions/closures do not actually throw the exception themselves, best I can see is to have the annotation just before it, such as

```php
	public function wellIdontThrowExceptionEither(): void {
		/**
		 * @throws \Exception
		 */
		$but_i_do = function() {
			throw new Exception();
		};
	}

	public function norAmIActually(): void {
		/**
		 * @throws \ErrorException
		 */
		$but_i_do = function() {
			throw new ErrorException();
		};
	}
```
and where such annotation would suppress the inspection.

Thoughts?


Code for reference.
```php
<?php
declare(strict_types=1);

class Foo {
	public function iDontThrowExceptions(): void {
		$but_i_do = function() {
			throw new Exception();
		};
	}

	public function wellIdontThrowExceptionEither(): void {
		$but_i_do = function() {
			throw new Exception();
		};
	}

	public function norAmIActually(): void {
		$but_i_do = function() {
			throw new ErrorException();
		};
	}
}
```

**Comment by 5lava** [comment]
Perhaps the issue can/should be broken down into two: one bug report and one feature request.

1. Inspection behaviour in cases 1 and 3 (`iDontThrowExceptions` and `norAmIActually`, correspondingly) is absolutely correct. Case 2 (`wellIDontThrowExceptionsEither`), although being somewhat similar to 3, is something that slipped the inspection. That would be a bug report.

2. Feature request: support `@throws` annotations on closures.

Btw, PHPStorm won't even let me easily annotate closure with `@throws` (but I'm guessing it has nothing to do with PHPIEA):

![image](https://user-images.githubusercontent.com/63829/36346059-fa18ce1c-1404-11e8-89e0-5f060bf6e261.png)

P.S. @tomzx Apologies for making you retype the whole thing from the screenshot, next time I'll paste the code.

**Comment by tomzx** [comment]
It's true that the autocompletion seems not to work properly, but if you start with `/**` and press enter, it will apparently generate the proper PHPDoc, at least on my side.

**Comment by 5lava** [comment]
> it will apparently generate the proper PHPDoc
Not on my side (EAP 181.3741.23). Works only on regular functions/methods, not closures.

**Comment by kalessil** [comment]
Looks similar to #686.

PhpStorm doesn't report exceptions in closures, but we do - hence this confusing case is taking place.
I'm in process of making decision how to be in #686

Autocompletion: worth reporting/checking JetBrain back-log as @tomzx suggested.
