### ISSUE TITLE
String offset: option to on/off complaining about `{}`

### ISSUE THREAD

**Issue by 5lava** [kalessil/phpinspectionsea#807]
![image](https://user-images.githubusercontent.com/63829/36357535-74e82192-14cd-11e8-8542-a1f764090d0d.png)

Please help me understand what's wrong with the latter one. I personally prefer using `{}` over `[]` on strings to visually distinguish strings from arrays, but maybe I'm missing something important that PHPIEA is trying to tell me.

**Comment by kalessil** [comment]
Partially because of this: https://stackoverflow.com/a/38415502 and partially because of best practices, when `{}` is used in following contexts `$object->{$propertyName}`, `"String with ${injected} fragment"`.

**Comment by 5lava** [comment]
> Partially because of this: https://stackoverflow.com/a/38415502

Well, that's hardly an argument. Using string interpolation without curly braces is moveton. No wonder it causes all kinds of confusion to newbies. One should never be taught that interpolation without `{}` is even possible. I strongly believe that braces must be enforced at the administrative level (and I'd love to have such inspection in PHPIEA). Or, even more fundamentally, at the language level, like in Ruby, JS, C#, Python, Swift...

> `{}` is used in following contexts only `$object->{$propertyName}`, `"String with ${injected} fragment"`.

Note that both contexts are **string** related, aren't they? And that's a good reason why using `{}` to access **string** offset makes even more sense. Let's `$keep[] = [$arrays[$alone]]`.

> `$string{0}` raises questions and pretty unusual style.

Generally yes. Most PHP developers, unfortunately, don't even know that strings can be accessed with `[]` or `{}`, so the "usual" style for them would be `substr()` (kudos goes to you for `SubStrUsedAsArrayAccessInspection`). But "no questions" thing can be misleading. When one sees `$var[0]` he almost certainly concludes `$var` is an array. So `$var{0}` raises questions, while `$var[0]` actually causes confusion. I'd rather prefer questions/eyebrows/hair raised once per developer than confusion being caused constantly. So `{}` is harmless, unlike `[]`. If my team will suddenly start using `[]` on strings, code review will immediately become harder, because every `$var[0]` must be paid attention to understand whether it's a string or an array, no assumptions can be made any longer.

**Comment by kalessil** [comment]
Well, I can introduce an option to switch on/off `{} -> []` promotion.
At the end who am I to complicate peoples life =)

**Comment by 5lava** [comment]
> who am I to complicate peoples life =)

Come on, you are not complicating anyone's life as long as there's a "Disable inspection" thing :)

But seriously, you're in a unique position as you're able to (positively) influence PHP community by choosing what inspections are enabled/disabled **by default**. So give it a good thought whether `[]` or `{}` should be PHPIEA's default suggestion. I encourage you to be open-minded and make the right call :)

**Comment by kalessil** [comment]
I dropped `{}` check completely - we are heading towards finding bugs and not code style =)

**Comment by 5lava** [comment]
Hmm. What about other 25 inspections currently present in category "Code Style"?

**Comment by kalessil** [comment]
They will remain for sure.
