### ISSUE TITLE
\shuffle investigation

### ISSUE THREAD

**Issue by funivan** [kalessil/phpinspectionsea#811]
Is shuffle secure or not for php >= 7.1
http://php.net/manual/en/function.shuffle.php#refsect1-function.shuffle-changelog
```
The internal randomization algorithm has been changed to use the » 
Mersenne Twister Random Number Generator instead of the libc rand function.
``

**Comment by kalessil** [comment]
For cryptography and in security-related components: no.
For randomizing things in other contexts: why not
