### ISSUE TITLE
Make a cli interface

### ISSUE THREAD

**Issue by sadovnik** [kalessil/phpinspectionsea#82]
Hello!

I want to use this code analyser as a linter in my CI flow. Is it possible to make a command line interface so it could be scripted and used from the terminal?

Also, I saw [this script](https://github.com/kalessil/phpinspectionsea/blob/master/cli/ps_inspect.sh) and it looks like it was used for some ad-hoc purpose. (Btw, I suggest to remove the hardcoded env vars.) 

What are your thoughts?

**Comment by funivan** [comment]
There are 3 lines of code. You can just create your own script to do that job  ;)

**Comment by sadovnik** [comment]
@funivan `ps_inspect.sh` uses PhpStorm to run this analyser. Is there any way to run it standalone?

**Comment by funivan** [comment]
@sadovnik You can run inspections only with phpstorm.

**Comment by sadovnik** [comment]
@funivan ok. Thanks for help. I close this issue for now.
