### ISSUE TITLE
auto fix for "Variables should not be self-assigned" 

### ISSUE THREAD

**Issue by summitpatil** [kalessil/phpinspectionsea#829]
Can we add auto fix for **"Variables should not be self-assigned"** 

Code Example
    $name = $name;
Solution
 remove such occurences

**Comment by kalessil** [comment]
@summitpatil : yes, I'll add in one of next releases.

**Comment by kalessil** [comment]
@summitpatil : this seems to be reported by "Silly assignment" inspection from IDE itself. Hence closing the issue (on our end we have no API for injecting custom QFes in 3rd party inspections.)

**Comment by funivan** [comment]
@summitpatil create an issue in phpstorm tracker. Maybe they can add a quick fix. It is not so hard. 

https://youtrack.jetbrains.com/issues/Wi
