### ISSUE TITLE
Suggest "roave/security-advisories" in "require-dev" section instead of "require" section of composer.json

### ISSUE THREAD

**Issue by jdreesen** [kalessil/phpinspectionsea#830]
See https://github.com/Roave/SecurityAdvisories/pull/41 & https://github.com/Roave/SecurityAdvisories/pull/43

**Comment by kalessil** [comment]
@Ocramius: we are targeting "require" section ATM, should we target "require-dev" instead (if I understood correctly we can now)?

**Comment by Ocramius** [comment]
Yeah, can be `require-dev`, as I verified that `composer update` *always* considers also the `require-dev` section.

**Comment by ktomk** [comment]
Please change. I don't want to disable that inspection ;-)

**Comment by Ocramius** [comment]
@ktomk why would you disable it?

**Comment by kalessil** [comment]
` Roave/SecurityAdvisories` is now considered as dev-package and promoted for require-dev packages group.

**Comment by ktomk** [comment]
@Ocramius: I don't want to, and seems with the changes I don't have to :+1: 

Thanks!

**Comment by Ocramius** [comment]
@ktomk the question was about why you'd want to remove it when it's in `require` instead of `require-dev` ;-)

**Comment by ktomk** [comment]
@Ocramius: Ah, well: I haven't had it in require, I just put it into require-dev as announced on the Homepage of it ;-). I don't do things wrongly only b/c the inspection tells me so ^^

**Comment by Ocramius** [comment]
To be clear: nothing wrong with using it in `require` ;-)

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by ktomk** [comment]
@Ocramius: Good to know! ^^

**Comment by craiglondon** [comment]
I have PHP Inspections v2.3.18 installed, I have added `"roave/security-advisories": "dev-master"` to my `require-dev` section, but the plugin is still saying it should go into the `require-dev` section.

**Comment by kalessil** [comment]
@craiglondon : we didn't release changes for this issue yet. An update is coming soon.

**Comment by craiglondon** [comment]
@kalessil Thank you for the response.  I will ignore it for now.
