### ISSUE TITLE
False positive?  with expression is not allowed as class constant value

### ISSUE THREAD

**Issue by craiglondon** [kalessil/phpinspectionsea#835]
`const ROUTE = parent::ROUTE . '/some-county';`
`const NO_RESULTS = ['NOTHING FOUND','NO PAYMENTS FOUND'];`

EA Inspections is saying this is an error.. 
with expression is not allowed as class constant value

**Comment by kalessil** [comment]
@craiglondon : reproduced the error message, but it triggered by IDE parser (as I understand).
PhpStrorm bug tracker is here: https://youtrack.jetbrains.com/issues/WI

Cheers, Vlad

**Comment by craiglondon** [comment]
@kalessil Thank you.

**Comment by kalessil** [comment]
You are welcome =)

**Comment by craiglondon** [comment]
For what it's worth, I didn't realize my project in PHP Storm was set to PHP 5.4.  Once I changed it to 5.6, this error went away.
