### ISSUE TITLE
Reduce highlighting level from aliases

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#837]
In case of aliases using (eg. `join()` instead of `implode()`), the aliases inspection will highlight both function name and it parameters, which causes a "visual noising". 

I think that it should be limited to only the function name and instead of strikeout uses the warning or weak-warning color.

**Currently:** 

![image](https://user-images.githubusercontent.com/421851/36912018-288772fc-1e24-11e8-9526-d1a9359dd976.png)

**Comment by kalessil** [comment]
Totally making sense, I'll make adjustments. If you notice something similar, please post here (I did similar fixes in the last release, but seems missed some cases).

**Comment by kalessil** [comment]
Fixed
