### ISSUE TITLE
What about `use function xxx` instead of `\xxx`?

### ISSUE THREAD

**Issue by tarlepp** [kalessil/phpinspectionsea#838]
Currently `Unqualified function/constant reference` fixes this like below:

Before:
```
$foo = array_map(...);
```

After:
```
$foo = \array_map(...);
```

What about if this was just handled via `use function array_map;` ?

**Comment by kalessil** [comment]
Can be done, but I can not say when this will happen.

**Comment by rentalhost** [comment]
Personally I don't like to use the`use function`, so when you implement that, could you make it an option (maybe disabled by default)? 😄

**Comment by kalessil** [comment]
@rentalhost : understood, will be optional behavior.

**Comment by funivan** [comment]
@kalessil is there any way to suggest two quick fixes? For example: import, add slash.

**Comment by kalessil** [comment]
@funivan : have no idea, I'll need to check.

**Comment by kalessil** [comment]
Looks like the plugin stable enough, hence the feature should land into the next release.

**Comment by kalessil** [comment]
Closing in favour of #1079 (duplicate)
