### ISSUE TITLE
Inspection "Suspicious Assignments" doesn't check 'continue' but only 'break' in switch statement

### ISSUE THREAD

**Issue by Denitz** [kalessil/phpinspectionsea#84]
Sample code:

```
switch ($rule)
{
    case 1:
        $result = null;
        continue 2;

    case 2:
        $result = false;
        break;
}
```

We will see inspection error for `$result = false;`  line.

**Comment by kalessil** [comment]
Thank you for reporting @Denitz , this is fixed now. Before the next release you can use the `.jar` file from the repository.
