### ISSUE TITLE
Unqualified function reference for function as string?

### ISSUE THREAD

**Issue by donquixote** [kalessil/phpinspectionsea#843]
On
```php
  array_filter($functions, 'function_exists');
```
the plugin suggests I use `'\function_exists'` instead.
Probably not a good idea :)

**Comment by kalessil** [comment]
Why =)

**Comment by jdreesen** [comment]
Why shouldn't this be a good idea? PHP's OPCode-Cache is able to optimize this if you use the root-namespaced version.

**Comment by donquixote** [comment]
ah, backslash in string is ok?

**Comment by rentalhost** [comment]
Actually it should works fine even for strings: https://ideone.com/xBfr7D

**Comment by donquixote** [comment]
You be right. I stand corrected. https://3v4l.org/JsnXA
