### ISSUE TITLE
Apply Quick-fix automatically on Reformat Code

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#845]
@kalessil Could it be done currently? Read the first comment from Anna Kozlova. It should be very important for inspections like `SenselessCommaInArrayDefinitionInspector`.

- See also: https://youtrack.jetbrains.com/issue/IDEA-187946

**Comment by kalessil** [comment]
Checked: it's different sort of functionality, we don't have API where possible to hook into.
A possible option is a custom intention, and I always ask if @funivan can include intentions into his plugn.

**Comment by rentalhost** [comment]
So you think that Anna reply is not related to the cause? I don't know if you understand my point here too, but is basically take advantage to yet-implemented quick-fix and run it automagically when you run Reformat Code.

**Comment by funivan** [comment]
Maybe @rentalhost is right. If it is possible to add chebox to the inspection and run QF automatically before reformat. It is strange that Jetbrains does not have this functionality built in. 
QF is very similar to intention. The main difference is creation process. QF is born from inspection (you need to find some errors), ok intention is born just from code analysis. 

How I think this can be done:
Check if some intentions can be invoked automatically before reformat.
If yes then:
A. We can extract some logic from QF to indentation
B. Maybe create similar intention in plugin that I created (refactoring plugin)

**Comment by kalessil** [comment]
@rentalhost: what's suggested there is a workaround - to create a macro which applies 2 quick fixes.

**Comment by rentalhost** [comment]
@kalessil I could not create a macro which applies quick fixes. I have tried to call one of your quick-fix, for instance, and I got that:

![image](https://user-images.githubusercontent.com/421851/37169961-4827497a-22e8-11e8-9c3f-957da924f05e.png)

**Comment by kalessil** [comment]
@funivan : I'd vote for "B" (com.jetbrains.php.lang.inspections.PhpTraditionalSyntaxArrayLiteralInspection.PhpConvertToShortArrayQuickFix#PhpConvertToShortArrayQuickFix can be extracted into an intenton and modified to drop tha last comma)

**Comment by kalessil** [comment]
@rentalhost : got it, seems it's fewer options now.
