### ISSUE TITLE
In which file are settings persisted?

### ISSUE THREAD

**Issue by jcrben** [kalessil/phpinspectionsea#846]
I reset some of the Probable Bugs to warnings instead of errors. I expected these to show up in my settings - either in the `.idea` directory (`.idea/inspectionProfiles/Project_Default`?) or my overall install settings (maybe in `inspection/` or `/options/ea_xtended`?) - but I'm not seeing the changes I'd expect.

I've also scoured the docs in https://github.com/kalessil/phpinspectionsea/tree/master/docs and couldn't find anything.

**Comment by kalessil** [comment]
@jcrben : those settings tweaks are normally landing in `.idea/inspectionProfiles/*` files. If after restart settings are not reset, then 100% they are in that directory.

Are inspections with modified error levels colored by blue color?

**Comment by jcrben** [comment]
Ah, I'm seeing the file updated now. Perhaps it required a restart, or maybe I was scatterbrained while searching around for where they should be.
![image](https://user-images.githubusercontent.com/5614134/37171191-eae5958a-22c1-11e8-8425-585a7090191d.png)

**Comment by kalessil** [comment]
Oh, .idea on several directory levels is well-known fun =)
