### ISSUE TITLE
Proposal: check set_exception_handler() in PHP 7

### ISSUE THREAD

**Issue by rk** [kalessil/phpinspectionsea#847]
Hello,

A project had a critical bug recently, caused by `display_errors` being off and this:

```php
set_exception_handler(function (\Exception $e) {
  // Log exception
});
```

In PHP 5.6 that code is perfect working code. But in PHP 7 that code will break error handling when an `Error` is thrown by PHP.

The alternatives are simple:

```php
// Don't type it at all...
set_exception_handler(function ($e) {
  // Log exception
});

// Or type it to Throwable
set_exception_handler(function (\Throwable $e) {
  // Log exception
});
```

I have caught this a couple of times since I switched to PHP 7, but currently it doesn't stand out (with any inspections) in my PHP 7+ projects. What's puzzling is, this is a known breaking change since 7.0 and not even PHPStorm has an inspection for it.

It's not a super-high priority one, I admit. But for cron, or daemon, processes it could be critical to finding out what happened to cause a bug.

**Comment by kalessil** [comment]
Thank you for the proposal @rk, I'll schedule for the next release but most probably it'll be shifted.

**Comment by kalessil** [comment]
For myself: enhance CallableMethodValidityInspector

**Comment by kalessil** [comment]
Implemented
