### ISSUE TITLE
Modified Severity of Addition operator used on arrays not recognized in inspection report

### ISSUE THREAD

**Issue by jcrben** [kalessil/phpinspectionsea#848]
Running Intellij Ultimate 2017.3.4 and EA EA Inspections 2.3.18

![image](https://user-images.githubusercontent.com/5614134/37246271-669410d6-245b-11e8-8264-e581bca2dca7.png)
from this line of code
![image](https://user-images.githubusercontent.com/5614134/37246272-69dc5320-245b-11e8-8cea-ffb3a537e2a2.png)

still registers as an error in the scrollbar and Analyze->Inspect Code report and gets the red squiqqly line

Code is proprietary so I can't share it all...

**Comment by kalessil** [comment]
Fixed
