### ISSUE TITLE
Bug: Nullpointer exception on variable setting

### ISSUE THREAD

**Issue by dpauli** [kalessil/phpinspectionsea#849]
Hi there,

following code does not work correctly:
```
public function bar()
{
    $foo = null;
    ...
    $foo['bar'] = 'bar';
}
```

On setting values on `$foo` there is the information, that a null pointer may occur. This is not correct, because I write (and not read) from `$foo`.

**Comment by kalessil** [comment]
Hi David,

It seems that $foo has an object type: means that ArrayAccess is implemented and hence null reference gets reported. When $foo has only scalar types, the message should go away.

Taking this context into account, do we need to address more contexts?

**Comment by dpauli** [comment]
Hey,

perhaps I understand it wrong, but `$foo` has only scalar value types, not objects, in this case.

**Comment by kalessil** [comment]
Fixed!
