### ISSUE TITLE
Use array access: wrong suggestion if substr() is using negative values

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#85]
Example of inspected code:
substr($string, -1, 1)
Obviously this cannot be changed to $string[-1] as the inspection suggests. We should check this.

Author @Jean85
Original link: https://bitbucket.org/kalessil/phpinspectionsea/issues/307/use-array-access-wrong-suggestion-if

**Comment by bram123** [comment]
PHP 7.1 and up does allow $string[-1];
https://3v4l.org/PVuvE

**Comment by kalessil** [comment]
Yep, negative offsets are suported, but semantics of `substr($string, -1, 1)` is rather `$string[strlen($string) - 1]`. 
I'll need to correct suggested replacement with negative offsets.
