### ISSUE TITLE
False positive: Suspicious assignment  - Last array element accessed via count() is treated as same index

### ISSUE THREAD

**Issue by WiXSL** [kalessil/phpinspectionsea#853]
$values = array();
$values[count($values)] = 1;
$values[count($values)] = 2; // $values[count($values)] is immediately overridden, please check...

**Comment by kalessil** [comment]
Thank you for reporting @WiXSL. Will be fixed in the next release.

**Comment by kalessil** [comment]
@WiXSL , apart from the false-positive, isn't it the same as `$values[] = ...`?

**Comment by kalessil** [comment]
Fixed
