### ISSUE TITLE
Inspection of composer.json, blank entries under Annotator

### ISSUE THREAD

**Issue by craiglondon** [kalessil/phpinspectionsea#854]
PHP Inspections v2.3.18 installed.
PhpStorm 2017.3.6
Build #PS-173.4674.46, built on March 15, 2018
JRE: 1.8.0_152-release-1024-b15 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

I ran an inspection of my composer.json.  Below is the screenshot

![composer-blank-annotator](https://user-images.githubusercontent.com/3833140/37671810-f0a9b192-2c42-11e8-8c53-86588c2f2975.jpg)

**Comment by kalessil** [comment]
Hi @craiglondon: doesn't look like something from us. Do you have composer.json plugin installed? Perhaps the inspection belongs to it (I guess).

**Comment by rentalhost** [comment]
I think the same. I have installed it soon and I see the same issue. So I think that it is related to the [composer plugin](https://github.com/psliwa/idea-composer-plugin).

**Comment by kalessil** [comment]
Duplicates https://github.com/psliwa/idea-composer-plugin/issues/57

**Comment by craiglondon** [comment]
Thank you.  I do have this plugin installed as well `PHP composer.json support v 1.0.25` and when I disabled it, those messages related to annotator went away.

**Comment by kalessil** [comment]
@craiglondon : you are welcome. I think it should be also possible to disable inspection which causes the issue and keep the plugin enabled - it helps pretty much.
