### ISSUE TITLE
False positive: Suspicious assignment

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#857]
Hi,

Thanks for this awesome plugin!

Here's a false positive I had on a project and I could reproduce:
![false positive](https://user-images.githubusercontent.com/9605520/37728534-cb0ac6f8-2d3a-11e8-8a6e-7ae710222d8f.PNG)

When a variable is reassigned with a string composed with itself via the syntax {$foo}, it detects it as "immediately overriden".

Thanks

**Comment by kalessil** [comment]
You are welcome =) Confirmed, will be in the next release.

**Comment by orklah** [comment]
Thanks for the super fast answer!

**Comment by kalessil** [comment]
Fixed
