### ISSUE TITLE
Nested ifs: option to avoid complex ifs

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#858]
There some cases where I prefer keep nested ifs, even when I could just merge it to avoid complexity. 

For instance:

```php
if ($a || $b) {
    if ($c) {
    }
}
```

Currently it turns to:

```php
if (($a || $b) && $c) {
}
```

It is right, but I think more complex read codes like that.

Before:

![image](https://user-images.githubusercontent.com/421851/37734926-58fc1d8c-2d2b-11e8-8a6a-e500d099de86.png)

After:

![image](https://user-images.githubusercontent.com/421851/37734946-66392e22-2d2b-11e8-8704-3101cd289899.png)

**Comment by kalessil** [comment]
Will adding a new line do the trick (so we tweak formatting) or you want the option to skip merging cases when `||` and `&&` are mixed up?

**Comment by rentalhost** [comment]
Second option.

**Comment by kalessil** [comment]
Done, as default behaviour, no settings.
