### ISSUE TITLE
isset(...) helper

### ISSUE THREAD

**Issue by mambax7** [kalessil/phpinspectionsea#863]
Would it be possible to replace automatically "isset(" to "null !==" ? 

I have this: 

```php
if (isset($abc)
```

and the plugin suggests:

```php
null !== $abc construction should be used instead.
``` 
but I have to do it manually. 

Being able to right-click and convert it automatically would save a lot of time :) 

Thank you,

**Comment by kalessil** [comment]
Hi @mambax7 : should be easy to implement - I'll schedule for the next release.

**Comment by kalessil** [comment]
@mambax7 : this should be part of Ultimate v2.0.1. I'll update the ticket with correct milestone later.

**Comment by mambax7** [comment]
Awesome!!! Thank you!!!
