### ISSUE TITLE
"Exception handling and annotating" doesn't respect severity type

### ISSUE THREAD

**Issue by MMauro94** [kalessil/phpinspectionsea#866]
As the title states, the mentioned inspection doesn't respect the assigned severity type: it always stays on "weak warning" with the grey squiggly underline.

**Comment by funivan** [comment]
@kalessil why you control severity type from the java code and not from the XML ;)

**Comment by kalessil** [comment]
That's what called "learning curve" =) I also imagined that I know better than users what severity should be.
Anyway, I'll make a fix.

**Comment by funivan** [comment]
Maybe we can fix all similar cases?

**Comment by kalessil** [comment]
Cleaning up periodically =)

**Comment by kalessil** [comment]
Fixed
