### ISSUE TITLE
Suggest removal of silly evaluation of functions return value.

### ISSUE THREAD

**Issue by WiXSL** [kalessil/phpinspectionsea#869]
```
function getMyValue(){
    $X = 'ANY VALUE OF ANY TYPE';

    $returnValue = getSomeValue();

    // This if is unnecessary:
    if ($returnValue == $X) {
        return $returnValue;
    }

    return $returnValue;
}
```

Notice that the if comparison could be used with any comparison operator (==, ===, !=, !==, ??, <=>, etc)

**Comment by kalessil** [comment]
Thank you for a proposal @WiXSL - I'll schedule for the next Extended release.

**Comment by WiXSL** [comment]
Another example:

```
if ($returnValue == $X) {
    return $X;
}
else {
    return $returnValue;
}
```

**Comment by kalessil** [comment]
Implemented: goes into ultimate according to this announcement https://kalessil.github.io/page-blog-post-about-ea-ultimate.html from January.
