### ISSUE TITLE
How to resolve transitive dependencies with Laravel

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#871]
I am receiving a lot of warnings about transitive dependencies because of the usage of Laravel [`Illuminate`](https://github.com/laravel/framework/blob/5.6/composer.json#L94) classes. I am not understanding the reason of this warnings, once that I am requiring the `laravel/framework` (that implements this classes).

**Comment by rentalhost** [comment]
For some reason too, some classes are not being affected:

![image](https://user-images.githubusercontent.com/421851/38210520-0c5a299e-368e-11e8-8ef5-464b6fbb6c57.png)

That is my `composer.json`:

![image](https://user-images.githubusercontent.com/421851/38210534-1dcb9d98-368e-11e8-8cbe-5fc140ee15c7.png)

**Comment by kalessil** [comment]
The marked classes are not coming from laravel/framework, but e.g. from illuminate/auth, illuminate/cache and etc.

Adding them implicitly would be the way to go - the implicit declaration of dependencies.
Might be redundant, but why not.

**Comment by kalessil** [comment]
I'll check if I can fix this

**Comment by rentalhost** [comment]
Hmm... Maybe it should consider the [`replace`](https://getcomposer.org/doc/04-schema.md#replace) key from composer? Because the Laravel replace have [a lot of instructions about that](https://github.com/laravel/framework/blob/5.6/composer.json#L42). I believe that it works like an "alias" to the package. So `illuminate/auth` refers to the own `laravel/framework` that I have set on my `composer.json`. If I am right, I guess that this warning is a false-positive.

**Comment by kalessil** [comment]
@rentalhost : all correct - that's a false-positive and we need to lookup the replace section in some cases.

**Comment by kalessil** [comment]
Solved in #890. I'll be possible to add 'laravel/*' into ignored packages.

**Comment by rentalhost** [comment]
Do you not prefer make this option configurable via options list?

**Comment by rentalhost** [comment]
Oh, you did it. :D

**Comment by aand18** [comment]
Hello, 
it still doesn't work with `laravel/*`
I'm using `illuminate/*` as a workaround.


![image](https://user-images.githubusercontent.com/36073609/49279932-12ecb600-f489-11e8-89fa-218e7cfacd29.png)

**Comment by kalessil** [comment]
Hey @aand18: probably ignoring 'illuminate/*' was intended. But Laravel case has been addressed and will be in the next release (ETA next week).
