### ISSUE TITLE
'false !== strpos($httpCode, "200")' can be used instead <- suggestion is bad for readability

### ISSUE THREAD

**Issue by neorganic** [kalessil/phpinspectionsea#875]
I would argue that preg_match('/200/', $httpCode) has a much better readability .

And a little prehistory of this issue is that I've had a bug after refactoring to strpos and it wasn't clear for some time what's wrong due to bad readability.

The problem is that ``strpos()`` doesn't return true at any time and the ``false !== strpos();`` is a hack....

I think this suggestion should be removed.

**Comment by kalessil** [comment]
`false !== strpos(...)` is faster (and generally used) alternative, so removal is unlikely.

But `I've had a bug after refactoring to strpos` sounds like an acting challenge, can you provide a code sample with explanations, please?

**Comment by kalessil** [comment]
Closing, as no feedback was provided. 
@neorganic : I'll re-open the issues when the requested code sample provided.
