### ISSUE TITLE
assertTrue(in_array) -> assertContains

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#878]

**Comment by michabbb** [comment]
@kalessil from today's point of view, the plugins suggest to use "assertContains" but phpstorm gives me the hint: 

![image](https://user-images.githubusercontent.com/3524595/76619820-0f6d2900-652c-11ea-8322-1a50fc6d9ca8.png)

so when it comes to phpunit 9, the plugin shouldn´t recommend "assertContains" any longer, in case of  checking if an array contains a string.  or ? 😏

**Comment by kalessil** [comment]
@michabbb, thank you for reporting. Please file a new issue, as this was closed in 2018.

**Comment by michabbb** [comment]
@kalessil DONE
