### ISSUE TITLE
New value type (float) is not in annotated types.

### ISSUE THREAD

**Issue by mambax7** [kalessil/phpinspectionsea#879]
I have in some old code this defined:
```php
 * @param  int    $time
```
and then I'm getting the float type notice for this line:
```php
$time = time() + 3600 * 24 * 365;
```
while this is still an integer

**Comment by kalessil** [comment]
Will check, thank you for reporting Michael!

**Comment by kalessil** [comment]
Fixed

**Comment by mambax7** [comment]
Thank you so much!!!  :)
