### ISSUE TITLE
array_filter: unnecessary callback closure

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#883]
- `array_filter/array_map([], function(...) { return function(...); })`

**Comment by kalessil** [comment]
Closing, stupid idea.

**Comment by rentalhost** [comment]
Do you mean something like the following?

```php
array_filter($array, function ($item) {
    return is_int($item);
});

// Could be optimized to:
array_filter($array, 'is_int');
```

**Comment by kalessil** [comment]
Yes

**Comment by rentalhost** [comment]
It seems very useful, but probably complex to implement, and rare to occur.

**Comment by kalessil** [comment]
It staged a little bit, but there is something about what I don't like.

**Comment by rentalhost** [comment]
You still like to implement that your you think better do not?

**Comment by kalessil** [comment]
Will implement simplified version

**Comment by kalessil** [comment]
Implemented
