### ISSUE TITLE
Illusion of Choice: how it works?

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#887]
Just to clearify. I don't understand well what is the meaning of this inspection.

![image](https://user-images.githubusercontent.com/421851/39006687-332b9a40-43da-11e8-9a04-7282de399daf.png)

The suggested fix is:

![image](https://user-images.githubusercontent.com/421851/39006693-3bd42a0e-43da-11e8-9a58-4a63cb5d458f.png)

And it could break my code if `$content` is not extracted to this view. Maybe it could be an issue? I am using it on Blade.

**Comment by kalessil** [comment]
` ($context = null) ?? null` = null
` ($context = '...') ?? null` = '...'

The statement is always evaluated to $context - but as you pointd out not in global context =)

**Comment by funivan** [comment]
@kalessil I just catched new case with null coalescing operator(

**Comment by kalessil** [comment]
Report here =)

**Comment by kalessil** [comment]
Fixed
