### ISSUE TITLE
"False positive" for in_array check if types are known

### ISSUE THREAD

**Issue by iltar** [kalessil/phpinspectionsea#89]
![image](https://cloud.githubusercontent.com/assets/1754678/21588714/00e0ad14-d0ea-11e6-8db7-b42f43d27b1e.png)

Given:
 - the haystack is always an int
 - the argument is always an int

Then the check so not be telling me to add a `strict=true`, because it can't ever be another type. This check is still valid for objects though, just not for scalar types.

**Comment by kalessil** [comment]
Thank you for reporting @iltar, I'll check this.

**Comment by kalessil** [comment]
Hi @iltar, is the fix working for you with a new release of the plugin?

**Comment by iltar** [comment]
@kalessil it seems to work indeed! Thanks for the fix!

**Comment by kalessil** [comment]
@iltar : thanks for spotting the issue ;)
