### ISSUE TITLE
Idea for discussion: exclude some things from transitive dependency inspection

### ISSUE THREAD

**Issue by asgrim** [kalessil/phpinspectionsea#890]
Just an idea here: some discussion about pros/cons of doing this is of course welcome!

Whilst I like that transitive dependencies are checked, I think perhaps some exclusions for common ones that generally we might not care about may be useful.

Ones I've noticed on my current project:

 - `psr/container` - one could argue that this should be in `composer.json`, so I'm split on this one at least
 - `container-interop/container-interop` - when stuck with some legacy nonsense - same as above tho
 - `phpunit/phpunit-mock-objects` - when using `PHPUnit\Framework\MockObject\MockObject` to annotate types returned by `$this->createMock` for example

I can't think of any else off my head, but certainly the `MockObject` one I get a lot, and don't necessarily want to add `phpunit/phpunit-mock-objects` into Composer.

**Comment by asgrim** [comment]
With the `psr/container` / `container-interop` ones, perhaps if they `provide` the `psr/container-implementation` then exclude it (e.g. this project depends on `zendframework/zend-servicemanager` which `provide`s `psr/container-implementation`)? Wonder if that's a bit complex to handle? Kinda similar in concept to the #871 issue for `replaces` in meta-packages?

**Comment by kalessil** [comment]
For UTs: got it, test scope should not be reported IMO. So, I'll exclude test scope.

Exclusions are needed: to keep it simple, let's 'vendor/package', 'vendor/*' patterns will be supported.

**Comment by kalessil** [comment]
Done. Test scope gets ignored, settings added.
