### ISSUE TITLE
[FR] Add option to ignore non-annotated/unhandled exceptions in private methods

### ISSUE THREAD

**Issue by jeromegamez** [kalessil/phpinspectionsea#900]
I don't know if it makes sense, but for me it would be great to have an additional option in `Control Flow -> Exceptions handling and annotating` to control whether non-annotated/unhandled exceptions *in private methods* should be reported and/or alternatively (if possible) perform a check if the exception has been annotated/handled in one of the calling/parent methods.

<img width="835" alt="example" src="https://user-images.githubusercontent.com/67554/39311445-3e5db2fc-496d-11e8-891c-5bf3094ccd42.png">

That way, it would not be necessary to suppress the inspection in all private methods throwing exceptions that might be handled in the public methods that call them.

:octocat: 

PS: Don't mind the code itself 😅

**Comment by kalessil** [comment]
We recently dropped the inspection completely, hence closing.
