### ISSUE TITLE
Callable parameter usage violates definition should not check interfaces

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#902]
I don't know if it could be generalized, but certainly it should be skipped for `\assert()`. The following code will fails, but is a valid check.

```php
interface MyInterface
{
}

class MyClass implements MyInterface
{
    public function check(MyClass $myClass)
    {
        \assert($myClass instanceof MyInterface);
    }
}
```

**Comment by funivan** [comment]
I think this case is similar to : 
```php
 function check(string $a) {
       if(is_string($a)){
      }
}
```
But I can be wrong.

**Comment by kalessil** [comment]
Re-visiting the ticket after a while. The check has found the dead code (probably existing before introducing parameter types), hence closing the issue.

@rentalhost, with a fresh look - isn't it the dead code.
