### ISSUE TITLE
[FR] Missing False Detection for \DateTime::createFromFormat()

### ISSUE THREAD

**Issue by kiler129** [kalessil/phpinspectionsea#911]
The following code will crash, since attempt to call `format()` on `false` was made:

```php
<?php

\DateTime::createFromFormat('Y', 'boo')->format('d');
```

I know the plugin detects such attempts where call on null is executed, but maybe it should also protect against such cases?

**Comment by kalessil** [comment]
@funivan @rentalhost : please advice

**Comment by funivan** [comment]
It would be nice to have this check. Maybe the case can be following:
If we call property/method/constant on the type of boolean or null then we should check it.

You already handle null check, maybe it is possible to handle boolean and maybe resource or array types.

We have the similar case in our project. Resolved it once and do not any have problems. 

Other case is to collect feedback. If more then 3 users will have similar problem - then think about implementation.

**Comment by kalessil** [comment]
Ok, adding to backlog.

**Comment by kalessil** [comment]
I was digging into the inspection codebase yesterday. Unfortunately, I can not implement false handling.
