### ISSUE TITLE
Why "Class needs to implement __isset to properly work here"?

### ISSUE THREAD

**Issue by Revisor** [kalessil/phpinspectionsea#912]
Hello,
I haven't found anything about this inspection in the docs or in the issues.

Can you please explain, why

```
if (isset($object->property))
```
shows the following error?
> Class needs to implement __isset to properly work here

Why does the $object's class need to implement `__isset()`?

**Comment by kiler129** [comment]
If the property doesn’t exists in the class and it’s accessed via magic getter the only way for interpreter to know if the property exists is to call __isset.

**Comment by kalessil** [comment]
As @kiler129 says, if a property does not exists or the property is private/property the `__isset` is needed. 

It's also possible that the codebase creating properties dynamically, like e.g. stdClass used as DTO (Data Transfer objects). Here we can not really fix this and just recommending using less dynamics and write regular DTO instead (the have all fields declared implicitely).

**Comment by Revisor** [comment]
So if I understand correctly, the condition
```
if (isset($object->property))
```
is a problem if

1. The class implements `__get()` but not `__isset()`
2. Or the property is private.

On the other hand it is not a problem if the property is public (or undeclared) and the class doesn't implement `__get()`.

Is that correct?

**Comment by kalessil** [comment]
- `The class implements __get() but not __isset()`: Correct
- `Or the property is private`: Correct (same applies to protected properties)

- `Or the property is private`: correct

- ` class doesn't implement __get()`: correct, but in general if you are using any of `__get/__set/__isset` , you are expected to have all 3 of them (one of our inspections suppose to complain if something is missing).

**Comment by Revisor** [comment]
Thank you for the explanation, now I understand the inspection and the problem it points to.

**Comment by kalessil** [comment]
You are welcome. I'll reopen the issue in order to cover the topic in our documentation as well.

**Comment by kalessil** [comment]
Done: https://github.com/kalessil/phpinspectionsea/blob/master/docs/probable-bugs.md#emptyisset-results-correctness

@Revisor @kiler129 : feedback on the added docs is appreciated.
