### ISSUE TITLE
Reuse variable

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#917]
I don't know if it does sense, but I found some code with something like that:

```php
$a = 123;
$b = $a;

echo $b;
```

`$a` is just initialized or overrided before `$b` copy that, and `$b` is never modified after that, so basically have the same content as `$a`. So, `$b` here could be dropped and  `$a` be used instead.

Exception could occur if `$b` is a reference-variable, then it could be valid in some contexts (like `function x(&$b)`), for static codes, I think that it could be just replaced by original source (`$a`).

**Comment by kalessil** [comment]
Looks like a new pattern for one-time use variables.

**Comment by kalessil** [comment]
Implemented
