### ISSUE TITLE
[FP] IllusionOfChoiceInspection

### ISSUE THREAD

**Issue by funivan** [kalessil/phpinspectionsea#919]
```php
if ($input->hasArgument('test')) {
 $name = $input->getOption('n');
  if ($name === null) {
   throw new \Exception('Invalid name');
  }
}
echo $name ?? null; // <-- error goes here. 
```
I can alsow run quick fix. But the code will get invalid:
` echo $name;`
Yep. This code is old and need to be rewriten. At least i add `$name = null` to the top. But i think Illusion of choise does not work correctly.

**Comment by kalessil** [comment]
Agree. Note for myself: only `??` is affected.

**Comment by kalessil** [comment]
Fixed
