### ISSUE TITLE
Incorrect hints and quick-fix for intval(), floatval() etc.

### ISSUE THREAD

**Issue by DroneZzZko** [kalessil/phpinspectionsea#920]
The inspection show wrong hints for this construction:
```php
return intval(true ? 1.1 : 2.1);
```

> '(int) true ? 1.1 : 2.1' would be more performant here (up to 6x times faster).

But this hint gives a different result:
```php
var_dump((int)true ? 1.1 : 2.1);
float(1.1)
```
```php
var_dump(intval(true ? 1.1 : 2.1));
int(1)
```

**Comment by kalessil** [comment]
Fixed
