### ISSUE TITLE
Disable ArrayTypeOfParameterByDefaultValueInspection if param can be non-array

### ISSUE THREAD

**Issue by Denitz** [kalessil/phpinspectionsea#923]
Can the inspection be not checked if PHPDoc defines any additional non-array param type?
```
    /**
     * @param array|string $options
     */
    public function test($options= [])
    {

    }
```

**Comment by funivan** [comment]
Hello @Denitz do you write such code very often? You can suppress inspection in 1-2 places if needed.
Mixed types is bad practice IMHO.

**Comment by Denitz** [comment]
Agree, but flexibility is also counted.

**Comment by kalessil** [comment]
Fixed. I tend to agree with @funivan, but we'll get a new inspection anyway for parameters types.
