### ISSUE TITLE
Default settings in PhpStorm

### ISSUE THREAD

**Issue by MaSergiu** [kalessil/phpinspectionsea#924]
Let's say, in PhpStorm, I made some adjustments to the inspections rules (from Settings -> Editor -> Inspections -> PHP -> PHP Inspections (EA Extended)) and now I want them back to defaults. How can I achieve that? 
Thank you.

P.S. Excuse me for opening an issue, didn't find the answer in documentation or other closed issues..

**Comment by rentalhost** [comment]
On inspections panel, you will see some blue items. That items are modified from default value. So you could basically toggle the checkbox to turn it black, that representes the default value implemented by the inspection.

**Comment by MaSergiu** [comment]
Thank you for such a fast reply. 
What's the probability that in PhpStorm Settings -> Other Settings -> Php Inspections (EA Extended) you would add a button for this purpose?

**Comment by rentalhost** [comment]
I don't think that it should be done by this plugin. But let wait for @kalessil here.

**Comment by kalessil** [comment]
Hi @MaSergiu : here we go with a solution - https://plugins.jetbrains.com/plugin/7622-php-inspections-ea-extended-#comment=27384

**Comment by MaSergiu** [comment]
Thank you very much. 
Since there is no other option to reset to defaults just the PhpInspections plugin, suggested workaround worked for me.
Good luck in further development and maintenance of such a good tool.
