### ISSUE TITLE
Bug: if else shortcut giving wrong construction

### ISSUE THREAD

**Issue by duncan-qabana** [kalessil/phpinspectionsea#927]
`$var = isset($x['key']) ?: $x['key_2']  !== null `

results in an feedback popup that says:

`'$var = isset($x['key']) ?: $x['key_2']  !== null !== null' construction should be used instead.`

**Comment by kalessil** [comment]
Looks weird. I'll check.

**Comment by kalessil** [comment]
@duncan-qabana: I'm unable to reproduce, unfortunately. Would you please provide a screenshot and IDE/plugin versions?

**Comment by funivan** [comment]
Unable to reproduce too. EA Ultimate 2.0.4

**Comment by duncan-qabana** [comment]
I am using PHPstorm 2018.1.4PhpStorm 2018.1.4 - Build #PS-181.5087.24 with EA extended 3.0.2.1.
When trying to recreate it, I cleared the cache and now it just says: Unnecessary parentheses.
Sorry to bother you, yesterday all the shortcuts had the same error :/

**Comment by kalessil** [comment]
Ok, thank you for re-checking @duncan-qabana
