### ISSUE TITLE
Optimize array_slice(array_values($x), $n)

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#929]
The code `array_slice(array_values($x), $n)` is slower than `array_values(array_slice($x, $n))`, so it could be optimized. It could be observed to both `array_values()` and `array_keys()` with some kind of filter wrapper like `array_filter()` or `array_slice()`, once this methods will work with less amount of data.

**Comment by kalessil** [comment]
Good catch @rentalhost, thank you for reporting =)

**Comment by kalessil** [comment]
Done
