### ISSUE TITLE
if(strpos()) could causes issues

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#930]
Some functions on PHP will returns an integer that is zero-based. Zero could be returned even for true results, but if you do `if(substr())`, in case where zero is returned, it will considered as falsy and will not work like expected, causing wrong behavior on code.

The example below is a big example:

```php
function test() {
	$haystack = 'abcdef';
	$needle   = 'abc';

	if (substr($haystack, $needle)) {
	    return 'Found!';
	}

	return 'Not found.';
}

echo test();
```

The code above will print "not found" instead of "found", because `strpos()` will returns `0` that is, actually, the real positon of `abc` in `abcdef`.

**Possible solution:** `strpos()` should not be `if()`'ed directly without an additional comparision operator (like in previous example). To fix it should be `strpos() !== false` or `strpos() >= 0`.

There are another functions that will have the same behavior, like `strrpos()`, and I don't know if any fits here.

**Comment by funivan** [comment]
If function return different types (for example `int|boolean` )  then we should check it with strict comparison.

**Comment by kalessil** [comment]
Good finding @rentalhost =) Sometimes I wondering how do you find all that stuff.

**Comment by rentalhost** [comment]
Generally after a lot of headache. haha

**Comment by kalessil** [comment]
For myself: array_search, strpos, stripos, strrpos, strripos, strstr, stristr + mb-invariants

**Comment by kalessil** [comment]
Ready!
