### ISSUE TITLE
False positive of UnnecessaryCastingInspection

### ISSUE THREAD

**Issue by apapsch** [kalessil/phpinspectionsea#935]
Consider the following statement:

    $quantity = (int)($item["quantity"] ?? 0);

This will yield a UnnecessaryCastingInspection warning. The offender seems to be `?? 0` because if I remove it, the warning goes away. This statement in question I could refactor to omit the explicit default value, by ensuring that the quantity field is guaranteed to exist. But there still is the underlying issue in the UnnecessaryCastingInspection, which is confused if a statement may yield several types, one of them the casting type.

**Comment by kalessil** [comment]
Hm, looks familiar. Which plugin and version is this?

**Comment by apapsch** [comment]
Oh well, after upgrade from 3.0.0 to 3.0.3 the false positive is gone. Closing this issue.
