### ISSUE TITLE
Merge for "Cascading 'str_replace(...)' calls" uses new and old array syntax

### ISSUE THREAD

**Issue by antiphp** [kalessil/phpinspectionsea#942]
Code:

    $value = str_replace('|', '-', $value);
    $value = str_replace('"', "'", $value);

After _Merge_ done by _Cascading 'str_replace(...)' calls_:

    $value = str_replace(['|', '"'], array('-', "'"), $value);

Notice new array syntax for 1st paramter and old array syntax for 2nd parameter.
Git diff screenshot here: https://ibb.co/kWKXpd

**Comment by kalessil** [comment]
Confirmed, thank you for reporting @antiphp

**Comment by kalessil** [comment]
Fixed

**Comment by Koopzington** [comment]
I'm on 3.0.6 and this issue still seems to exist.

**Comment by kalessil** [comment]
Snap, re-opening than. Thank you for reporting, @Koopzington.

**Comment by kalessil** [comment]
Second attempt to fix the un-reproducible behaviour. I have no more ideas how to reproduce/test the issue.

**Comment by Koopzington** [comment]
ah... i didn't see that the inspection had an option to explicitly use short array syntax.
The box was unchecked on my side but i configured PhpStorm to enfore short syntax (Editor > Code Style > PHP > Code Conversion) resulting in the replacement being mixed like in the initial issue.
It's kind of confusing though that the second array doesn't get automatically converted to the short syntax too.

**Comment by kalessil** [comment]
Uh, thank you for clarifying!

**Comment by kalessil** [comment]
So, i was able finally to reproduce the issue, will be covered in #1200 (at least I hope so).
