### ISSUE TITLE
[FR] Merge ob_get_contents+ob_end_clean into ob_get_clean

### ISSUE THREAD

**Issue by dryabov** [kalessil/phpinspectionsea#947]
A kind of micro-optimization: find a sequence of assignment and function call
```php
        $content = ob_get_contents();
        ob_end_clean();
```
and suggest to replace it with a single call
```php
        $content = ob_get_clean();
```

**Comment by kalessil** [comment]
Looks good, will implement it.

**Comment by kalessil** [comment]
Implemented!

**Comment by kalessil** [comment]
@dryabov, by the way: you've helped me a lot on early project phase, so I would gladly give you a free perpetual Php Inspections (EA Ultimate) license. Any interest?

**Comment by dryabov** [comment]
@kalessil Sure :-)

**Comment by kalessil** [comment]
@dryabov can you ping me via email please (kalessil at gmail dot com, licenses are bound to emails)?
