### ISSUE TITLE
Variable is redundant

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#950]
The following code will mark `$notRedundant` as redudant.

```php
$notRedundant = new stdClass;

$a = $notRedundant->value;
$b = $notRedundant->value;
```

**Comment by funivan** [comment]
Can not reproduce even this code:
 ```php
    public function getId(): int {
      $id = 123;
      return $id;
    }
``` 
What is the name of the inspection, cant find )) 
P.S. Enable `OneTimeUseVariable` but no luck

**Comment by rentalhost** [comment]
@kalessil I am running on EAU 2.0.5 and PS 2018.2 EAP (182.3341.34).

**Note:** the code will fail only if it is scoped on root. 

```php
$notRedundant = new stdClass;

$a = $notRedundant->value;
$b = $notRedundant->value;
```

The following code will not fail:

```php
function example()
{
    $notRedundant = new stdClass;

    $a = $notRedundant->value;
    $b = $notRedundant->value;
}
```

The inspection is "_PHP | Php Inspections (EA Ultimate) | Control Flow | One-time use variables_".

**Comment by funivan** [comment]
**Plugin** EAU 2.0.5 
**PhpStorm** 2018.2 EAP #PS-182.3341.34

Can not reproduce on the global scope.

**Comment by funivan** [comment]
@rentalhost try to create new dummy project and test it

**Comment by rentalhost** [comment]
@funivan I have tried on a new clear project, and it keeps happening. haha Very strange!

Anyway, I will put some files attached here and my current PS settings. Maybe is some kind of custom setup.

[test.zip](https://github.com/kalessil/phpinspectionsea/files/2125258/test.zip)
[settings.zip](https://github.com/kalessil/phpinspectionsea/files/2125260/settings.zip)

**Comment by funivan** [comment]
@rentalhost  `test.php` is empty )

**Comment by rentalhost** [comment]
I am sending again, with the .idea directory too.
[test.zip](https://github.com/kalessil/phpinspectionsea/files/2128135/test.zip)

**Comment by funivan** [comment]
Still can`t reproduce.

**Comment by funivan** [comment]
Try to create the new instance of the phpstorm. And use new project with fresh configs.

**Comment by GaryJones** [comment]
![screenshot 2018-06-29 12 54 19](https://user-images.githubusercontent.com/88371/42091044-a38f671e-7b9b-11e8-84da-6b58f9458f12.png)

I had to enable the inspection's `Allow long statements` setting for it to appear. After disabling that option, the violation reporting persisted.

Ultimate 2.0.6 (trial)
PhpStorm 2018.1.6

**Comment by kalessil** [comment]
Oh, thank you @GaryJones !

**Comment by kalessil** [comment]
Fixed!
