### ISSUE TITLE
Non-Optimal If Conditions

### ISSUE THREAD

**Issue by iakoder** [kalessil/phpinspectionsea#951]
Are there any heuristics applied using the complexity of the body of the conditional when considering the non-optimal, duplicate if conditions inspection?  I'm not sure if there's a better way to write the following pattern:

```php
<?php

$b = $_REQUEST['blah'];

function f1() {
}

function f2() {
}

function f3() {
}

if ( $b === 0 || $b === 1 ) {
    f1();
    // Flagged with duplicate condition
    if ( $b === 0 ) {
        echo 'Is it 0';
        f3();
    }
    echo 'It is 0 or 1';
    f2();
} else {
    echo 'It is different than 0 or 1';
}
```

**Comment by funivan** [comment]
How `f1` function can change the value of the variable `$b`?
Do you use `global` keyword?

**Comment by kalessil** [comment]
@iakoder : nope, the inspection is straight-forward one. I'd give a try to this approach (a local variable for repeated condition)

```php
if ( $isZero = $b === 0 || $b === 1 ) {
    f1();
    if ( $isZero ) {
        echo 'Is it 0';
        f3();
    }
    echo 'It is 0 or 1';
    f2();
} else {
    echo 'It is different than 0 or 1';
}

**Comment by kalessil** [comment]
@funivan : nope - `$b === 0 || $b === 1` is a branch for handling 2 workflows inside if' body.

**Comment by kalessil** [comment]
I can not imagine a solution here, hence closing.
