### ISSUE TITLE
Implement Yoda/Regular switch for "'substr(...)' could be replaced with 'strpos(...)'" inspection

### ISSUE THREAD

**Issue by Koopzington** [kalessil/phpinspectionsea#955]
I saw that some of the Inspections have the option to choose between Regular and Yoda style.
I'd love to see that same setting for the Control Flow > "'substr(...)' could be replaced with 'strpos(...)'" inspection since the replacement uses Yoda conditions by default.

**Comment by kalessil** [comment]
Will add =)

**Comment by kalessil** [comment]
Added

**Comment by rentalhost** [comment]
I guess that is the time to think in a more generic way to do that (use the Yoda setting directly)... I will try do that tomorrow.
