### ISSUE TITLE
Merge isset can change expression semantics

### ISSUE THREAD

**Issue by msarris** [kalessil/phpinspectionsea#956]
If you have the following expression:

```php
$a = isset($b) && isset($c) && ($d || $e);
```

This plugin (if I'm correct) will allow you to automatically merge the isset calls via the "Merge isset constructs" option.

This will result in the following code:

```php
$a = isset($b, $c) && $d || $e;
```

The expected code however is:

```php
$a = isset($b, $c) && ($d || $e);
```

Because the resulting code is equal to:

```php
$a = (isset($b, $c) && $d) || $e;
```

which is semantically different from the original expression.

**Comment by kalessil** [comment]
Oops, thank you for reporting @msarris

**Comment by kalessil** [comment]
Fixed!
