### ISSUE TITLE
NPE false positive

### ISSUE THREAD

**Issue by b1rdex** [kalessil/phpinspectionsea#959]
```
$a = Users::model()->findByUid($uid);
echo $a->foo ?? 123;
```
`findByUid` has `@return Users|null` phpdoc.

If I simplify example code to
```
$a = null;
echo $a->foo ?? 123;
```
Then issue is not reproduced.

**Comment by kalessil** [comment]
Duplicates #952

**Comment by kalessil** [comment]
Re-evaluated with a fresh build: fixed. I'll make a new release ~ in a week.
