### ISSUE TITLE
substr + strlen => problem

### ISSUE THREAD

**Issue by voku** [kalessil/phpinspectionsea#961]
Hi, the substr + strlen replacement didn't work as expected.

```php
substr($var, 1, strlen($var) -2) !== substr($var, 1, -2)
```

Version: 3.0.4

Demo: [https://3v4l.org/RQ9X3](https://3v4l.org/RQ9X3)

![phpeaerror](https://user-images.githubusercontent.com/264695/41994399-8aae5064-7a4e-11e8-92dc-5a1706719fd8.png)

**Comment by kalessil** [comment]
Hi Lars, I'll take care of the issue. Thank you for reporting.

**Comment by kalessil** [comment]
Fixed!
