### ISSUE TITLE
Function renaming should respects backslash option

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#976]
Some inspections like [`ArraySearchUsedAsInArrayInspector`](https://github.com/kalessil/phpinspectionsea/blob/89287702f97775db4c49733de3a675950308f88b/src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/apiUsage/arrays/ArraySearchUsedAsInArrayInspector.java#L104) will create `in_array()` with the autofix, but it doesn't respects the backslash option if enabled, which causes a _inspection-after-inspection_ in such cases. I like to implement it in form that it will apply backslash if this option is enabled.

It will consider the inspection `Unqualified function/constant reference` functions and if it is enabled or not (but I still don't know how I will check if this inspection is enabled or not, but is a problem in a part hehe).

Another thing to do is allow add custom functions to this list via `OptionsComponent.addList()`.

I just don't know how much inspections do that, so I should use the current `UnqualifiedReferenceInspector` function list and search on code where this functions are generated, replacing with a solution that should rename with/without the backslash.

**Comment by kalessil** [comment]
I'm going to decline this one - inspections must remain decoupled from each other. 
IMO after QF, the missing '\' will be reported and can be QFed as well (Linux approach).

**Comment by rentalhost** [comment]
This is exactly the problem. If we have an inspection that will highlight the missing backslash as a "code inconsistency", why others inspections will create inconsistence codes? In practice, we will have the double work of performing two fixes (one generated by the user, and another by the own inspection). A good example is the Yoda inspection that now is global to avoid two fixes: you setup it like you want, and the generated code by other inspections will respect it to avoid a new warning. Make sense for you?

**Comment by kalessil** [comment]
I understand your point and agree that it's little bit extra work. But we have #838 which can not be easily integrated ATM globally, at least not now yet.
