### ISSUE TITLE
Incorrect null pointer exception inspection when in a while loop

### ISSUE THREAD

**Issue by thexpand** [kalessil/phpinspectionsea#977]
![screenshot from 2018-07-16 12-28-12](https://user-images.githubusercontent.com/14979167/42751538-c6288700-88f3-11e8-8232-881b2457ccd2.png)

**Comment by kalessil** [comment]
Thank you for reporting @thexpand, I'll take care about the bug.

**Comment by kalessil** [comment]
Thank you @thexpand, with this input I reproduced the issue. Fixed!
