### ISSUE TITLE
Is it possible to define access with property in php class annotation?

### ISSUE THREAD

**Issue by wwulfric** [kalessil/phpinspectionsea#978]
```php
/**
 * Class MyClass
 * @property int id
 */
class MyClass{
    private $id;
}
$obj = new MyClass();
echo $obj->id;
```

I used `@property int id` to declare a property `id` in MyClass. Then I could automatically generate getter and setter with correct type hint(int). But ea would do nothing in `$obj->id`. It thought that's right because of `@property int id`, even though it was a private field.

```php
/**
 * Class MyClass
 * @property int @access protected id
 */
class MyClass{
    private $id;
}
$obj = new MyClass();
echo $obj->id;
```

I then changed to `@property int @access protected id`. But getter and setter wouldn't generate correct type hint(mixed instead). What's the solution?

**Comment by funivan** [comment]
Ive implemented the following logic in my custom plugin: 
Add annotations `@internal` and `@deprecated` to the description.
`internal` - allows usages of virtual property inside the class. And fire warning if Im using in other places
`deprecated` - fire warning when we use property in any place. 
Maybe this logic can be applied here. 

How it`s look like:
```
/**
 * @property int $id @internal
 */
```

**Comment by kalessil** [comment]
Looks like the question was answered, closing the issue.
