### ISSUE TITLE
Check if class implements methods from interfaces

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#98]
It could sounds like an exotic implementation: currently if you _implements_ some interface in your class, phpstorm will check if you have defined the methods required from this _interface_. But the reverse way is not true.

**I guess that an implementation like that will help in two ways:**

1. Help you to identify that your class is an _interface compatible_;
2. Help you to identify if some method collection could be confused with an interface (_if it's not your intention_);

For instance: the interface `Countable` requires the definition of a `int count()` method only. Then if you defines a method on your class like the example below, is too much probably that you wants to make it `Countable` too:

```php
// Info: YourClass should be compatible with Countable interface (autofix).
class YourClass {
    public function count(): int {
        return count($array);
    }
}
```

It should be more useful for more complex cases, where the analysis could check if a collection of methods is compatbile with an interface, and you forget to _implements_ that. The example below should remember you to implements the `ArrayAccess`:

```php
// Info: YourClass should be compatible with ArrayAccess interface (autofix).
class YourClass {
    public boolean offsetExists($offset) { ... }
    public mixed offsetGet($offset) { ... }
    public void offsetSet($offset , $value) { ... }
    public void offsetUnset($offset) { ... }
}
```

Of course that it should generate some false-positive. For instance: if I implements `count()` to not acts like a _Countable_. But within this reasoning, I really do not see what I should do something like that (_a count method to a not countable object?_).

---

To implements that (_programatically_), I guess that the first step is analyses all existent interfaces (I hope that phpstorm make it easy) then check if user class implements some interfaceable method.

1. Get all YourClass methods;
2. Get all interfaces methods (_referenced_);
3. Check each YourClass methods exists on interface methods;
4. Check if compatible interfaces was not declared;
5. Generate an "info" warning to YourClass (with autofix, _plx_);

**Comment by funivan** [comment]
If `YourClass` does not implement `Countable` Why you should care about `count` method signature?

**Comment by rentalhost** [comment]
@funivan Hm... I'm following the same logic of magic methods. If I declare `__call()` I do expects that my object have support to have magic methods (`$object->hello()`). If is not my intention do that, so I could not declare the `__call()` method.

If I do the same for _"same signatured"_ as interfaces, then I should expects that my class be supported to implements an interface. If I do implements methods like `start()`, `stop()`, `pause()` and `resume()`, maybe my class should implements the `Player` interface (or could be treated for it).

**Comment by funivan** [comment]
> too much probably that you wants to make it Countable too

This phrase is interesting to me. For example I have class with count but I do not want to use countable interface. Then I will get warning.

**Comment by rentalhost** [comment]
@funivan Right, but what is the sense that you have a `count()` method implemented but it is not a real countable? (_just to help with false-positives_)

**Comment by funivan** [comment]
@rentalhost in some cases strict types =)

**Comment by rentalhost** [comment]
@funivan Yeah, but I think that it is not a case for a warning, but a code suggestion (_info_). Could you elaborate an example of a real world case where you don't wants to implements a full compatible interface?

**Comment by funivan** [comment]
@rentalhost You are right. I cant find real example.
But for the countable i find standard inspection: `Invocation parameter types are not compatible with declared.`

If you are planing to use object as `Countable` PhpStorm will give you an information about that. Probably quick fix would be very helpful. 
```php
$a = new \stdClass();
echo count($a);
```

**Comment by rentalhost** [comment]
@funivan I guess that this inspection is when you make a class `Countable` but declare the method like `int count($param)` where it should be `int count()` only (_wrong signature_).

**Comment by funivan** [comment]
Here is simple example:
![07 52 41](https://cloud.githubusercontent.com/assets/425208/21837230/f7a7616c-d7d2-11e6-92c9-4583c11461d4.png)

I thinks this feature request is solver in partial. If author would like to implement that logic than ok =)
