### ISSUE TITLE
Symfony: lowercase letters for service and parameter

### ISSUE THREAD

**Issue by garak** [kalessil/phpinspectionsea#988]
Such rule should be deleted or at least adapted to allow keys like `env(FOO)`
Symfony allows [uppercase letters when using env vars](https://symfony.com/blog/new-in-symfony-3-2-runtime-environment-variables) in parameters since version 3.2

**Comment by kalessil** [comment]
Hi @garak, wondering about the context as we don't have any specific frameworks support in this project. Any insights, what is this about?

**Comment by jdreesen** [comment]
Maybe the inspection comes from this plugin: https://github.com/Haehnchen/idea-php-symfony2-plugin ?

**Comment by garak** [comment]
@jdreesen just found that myself too.
Sorry for confusion
