### ISSUE TITLE
Simplify quotes

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#991]
| Subject    | Details                                                  |
| :--------- | :------------------------------------------------------- |
| Issue type |  Feature request     |
| IDE        | PS-182.3684.42                          |
| Plugin     | 2.0.7 U |

Suggests simplification of quotes when it could optimizes string visualization. 

```
// Suggests simplification:
from 'he\'llo' to "he'llo"
from "he\"llo" to 'he"llo"

// Dont suggest simplification:
from "he\"{$llo}"
```

**Comment by kalessil** [comment]
Reopening
