### ISSUE TITLE
Redundant variables

### ISSUE THREAD

**Issue by JProof** [kalessil/phpinspectionsea#997]
In earlier Versions i remember, that the redundant var initialization was an ea-inspection. 
Currently i can not find the inspection.

Perhaps someone has an idea.

```php
declare(strict_types=1);

/**
 * @return bool
 */
function myMethod(): bool
{
	$tmpl = 'myDummyTemplateString';
	// should mark the "$tmpl" var as redundant
	echo $tmpl;
	
	return true;
}

```

IDE:
PhpStorm 2018.2.2 EAP 
Build #PS-182.4129.18, built on August 15, 2018
Licensed to somewhereovertherainbow
Subscription is active until November 29, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Plugin:Php Inspections Ultimate  2.0.7
Issue Type: Support Request

thx..

**Comment by kalessil** [comment]
@JProof : that's a new pattern, implemented
